terraform/environments/analytical-platform-management/providers.tf
terraform/environments/bench/providers.tf
terraform/environments/bichard7/providers.tf
terraform/environments/cooker/providers.tf
terraform/environments/heater/providers.tf
terraform/environments/justice-on-the-web/providers.tf
terraform/environments/ops-engineering/providers.tf
terraform/environments/performance-hub/providers.tf
terraform/environments/remote-supervision/providers.tf
terraform/environments/sprinkler/providers.tf

We have updated our templates to not give this repo access to the shared
services provider, and only use a dns role specific to the account
business unit, so that they cannot amend dns entries of another business
unit.  This change updates the files that have already been created so
that they are in line with the new template.

Update providers to restrict access

---

.github/workflows/bench.yml
.github/workflows/heater.yml
.github/workflows/ops-engineering.yml
.github/workflows/performance-hub.yml
.github/workflows/sprinkler.yml

These workflow files are generated from the template for our current
environments, environments that are managing their own accounts have not
been included.

Add workflow files for existing envs

---

.github/workflows/run-opa-tests.yml

As we've made this a required test, it has to always run otherwise the
PR cannot be merged

Change workflow so tests always run

---

terraform/environments/analytical-platform-management/providers.tf
terraform/environments/bench/providers.tf
terraform/environments/bichard7/providers.tf
terraform/environments/cooker/providers.tf
terraform/environments/heater/providers.tf
terraform/environments/justice-on-the-web/providers.tf
terraform/environments/ops-engineering/providers.tf
terraform/environments/performance-hub/main.tf
terraform/environments/performance-hub/providers.tf
terraform/environments/remote-supervision/providers.tf
terraform/environments/sprinkler/providers.tf

Now that we have the new role for accessing core vpc data, switching
providers to use it.

Update providers to use new role

---

.github/workflows/terraform-static-analysis.yml

The terraform static analysis repo is now in the moj repo, switching
over to using this one.  Also removing AWS credentials as the tf init
part of the action has been removed over security concerns of these
scripts having access to the creds.

Switch Terraform Static analysis to MoJ repo

---

terraform/environments/performance-hub/main.tf
terraform/environments/performance-hub/templates/task_definition.json

I'd updated `secrets.tf` a while ago, but the secret wasn't visible in the container. I think I also needed to update `task_definition.json` and `main.tf`...(?)
Basically trying to get `GOVUK_NOTIFY_API_KEY` to appear as an env var in the container.

Added secret definition for govuk_notify_api_key

---

.github/workflows/terraform-static-analysis.yml
.gitignore
terraform/environments/nomis/bastion_linux.tf
terraform/environments/performance-hub/bastion_linux.tf
terraform/environments/sprinkler/bastion_linux.tf

- Use the terraform bastion linux module from separate repository and pinned to a release: github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux?ref=v1.0.0
- Add IntelliJ files to .gitignore

Use the bastion linux terraform module from separate repository and pinned to a release

---

terraform/environments/nomis/packer.tf
terraform/environments/nomis/packer_cicd_user.tf

This provides a number of resources required to run packer:
Role that can be assumed by the packer cicd user providing the minimum permissions required by Packer
Policy definition and attachment to Role
Policy definition and attachment to packer user group allowing members to assume Role
Instance profile to be attached to the Packer build instances to allow connection with Session Manager (SSM)
Security group for Packer to attach to its build instance.

add resources, role and policy required for packer

---

terraform/environments/nomis/weblogic.tf

PR to open access from jumpserver to weblogic server for forms/reports endpoint (port 7777)

Add weblogic sg rule (forms/reports)

---

terraform/environments/analytical-platform-data/providers.tf
terraform/environments/analytical-platform-management/providers.tf
terraform/environments/bichard7/providers.tf
terraform/environments/cooker/providers.tf
terraform/environments/mi-platform/providers.tf
terraform/environments/nomis/providers.tf
terraform/environments/performance-hub/providers.tf
terraform/environments/remote-supervision/providers.tf
terraform/environments/sprinkler/providers.tf
terraform/environments/tariff/providers.tf
terraform/environments/testing/providers.tf
terraform/environments/xhibit-portal/providers.tf

After enabling security hub alarms for the modernisation platform core
account, there were a lot of unauthorized api alarms -
```
Sum unauthorised-api-calls GreaterThanOrEqualToThreshold 1.0
```
Tracking down the alarm reason in cloudtrail shows that the unauthorised
call was to DescribeAccountAttributes from the member-ci user.
This is because calls from the member-ci user assume a role normally,
and the only thing the ci user has direct permissions for is to access
the state. When the Terraform AWS provider first starts it checks the
supported EC2 platforms which uses the above permission.  We don't need
it to do this for the non member accounts that the member-ci has access
to, as it will only ever create EC2 resources in the member account
(which has this permission as it assumes the …

Update non member account providers

---

terraform/environments/xhibit-portal/app-server.tf

MS DTC seems to need lots of random open ports bidirectionally. 
Opening up ports to test whether the app starts when the ports are open. We'll have to figure out a way to lock these ports and just open the required ones later.

allow all traffic back from db

---

terraform/environments/nomis/packer.tf

Give packer-build role permission to retrieve AWS "parameter store" parameters

Give packer-build role permission to retrieve AWS parameters

---

terraform/environments/sprinkler/kms.tf

Adding a kms key that can be used for the sprinkler account to encrypt
ebs volumes, this will be used in the ami builds for this account

Feat: adding kms for sprinkler

---

.github/workflows/dex-ta.yml
terraform/environments/sprinkler/kms.tf

Adds some extra KMS permissions as detailed here:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/key-policy-requirements-EBS-encryption.html#policy-example-cmk-cross-account-access
These are required for access to the KMS key across accounts.

External KMS access for EC2 Image Builder from core-shared-services

---

terraform/environments/performance-hub/templates/task_definition.json

Changed the CPU units to 1536 to enable placement on a t3.medium instance.

Changed the CPU units to 1536 to enable placement on a t3.medium

---

terraform/environments/analytical-platform-data/versions.tf
terraform/environments/analytical-platform-management/versions.tf
terraform/environments/bichard7/versions.tf
terraform/environments/cooker/versions.tf
terraform/environments/dex-ta/versions.tf
terraform/environments/mi-platform/versions.tf
terraform/environments/nomis/versions.tf
terraform/environments/performance-hub/versions.tf
terraform/environments/ppud/versions.tf
terraform/environments/remote-supervision/versions.tf
terraform/environments/sprinkler/versions.tf
terraform/environments/tariff/versions.tf
terraform/environments/testing/versions.tf
terraform/environments/xhibit-portal/versions.tf

Currently our versioning is as follows:
version = ">= 3.47.0"
This means that the pipelines will always get the latest version (this doesn’t happen locally as you have to run an init upgrade if you’ve run init previously), this is causing issues now when we move to version 4 where there are breaking changes.
If we change the way we version to only allow patch and minor changes, but not major version changes:
version = ">= 3.47.0, < 4.0.0"
This will still allow minor upgrades to happen automatically, but any breaking changes won’t.
Then we can go through each tf and upgrade and make the changes required manually.

Prevent auto upgrade to AWS provider 4.0.0

---

.github/workflows/performance-hub.yml

Trigger preproduction plan and deployment upon merge to the main branch. Otherwise, if configured to be triggered through a feature branch we would get the error: Branch is not allowed to deploy to performance-hub-preproduction due to environment protection rules.

Trigger preproduction plan and deployment upon merge to the main branch

---

terraform/environments/xhibit-portal/lambda.tf

Lambda is failing because timeout config was reverted t0 3 seconds.

Fixes lambda timeout error.

---

terraform/environments/performance-hub/application_variables.json

Update the ECS cluster AMI to the new Windows_Server-2019-English-Full-ECS_Optimized AMI.
aws ssm get-parameters --names /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-ECS_Optimized --profile performance-hub-preproduction
{
"Parameters": [
{
"Name": "/aws/service/ami-windows-latest/Windows_Server-2019-English-Full-ECS_Optimized",
"Type": "String",
"Value": "{\"image_name\":\"Windows_Server-2019-English-Full-ECS_Optimized-2022.02.10\",\"image_id\":\"ami-035b1d60ffc27a71d\",\"ecs_runtime_version\":\"Docker version 20.10.9\",\"ecs_agent_version\":\"1.59.0\"}",
"Version": 37,
"LastModifiedDate": "2022-02-14T23:41:21.534000+00:00",
"ARN": "arn:aws:ssm:eu-west-2::parameter/aws/service/ami-windows-latest/Windows_Server-2019-English-Full-ECS_Optimized",
"DataType": "text"
}
], …

Update the ECS cluster AMI for performance hub preproduction

---

terraform/environments/nomis/ec2-common.tf
terraform/environments/nomis/loadbalancer.tf
terraform/environments/nomis/modules/weblogic/main.tf

Keeping the database on an hour longer to accommodate weblogic instances being created for the warm pool during the evening scale in event.  Also changed autoscaling schedule to power down weblogics at the weekend.

Adjust evening power off times

---

terraform/environments/nomis/application_variables.json
terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/modules/database/main.tf
terraform/environments/nomis/modules/database/user-data/user-data.sh
terraform/environments/nomis/modules/database/variables.tf
terraform/environments/nomis/versions.tf

Set out to correct the memlock settings required for oracle based on instance size but during testing uncovered an issue where the ebs volumes are slow to attach during instance creation, causing disk operations in the user-data script to fail.  Added a wait condition to user-data and made the user-data script dependent on the volume ids of the ebs volumes, thus all ebs volumes will be created before the instance itself (but not attached yet).  Also added audit database.

updating database user-data script to fix memlock settings

---

terraform/environments/ppud/ppud_data_transfer_instance.tf

This shamelessly rips off the IAM config from the bastion module - this
should in theory allow me to use SSM to log into the EC2 instance
(rather than having to open up SSH access).

PPUD transfer allow SSM access

---

terraform/environments/nomis/ec2-weblogic.tf

Need this security group rule to allow the Cloud Platform prometheus server to scrape metrics

Rule to allow access to CP prometheus server

---

terraform/environments/ppud/ppud_data_transfer_instance.tf

Now we've imported the current PPUD snapshot, spin everything down so
that we're not incurring unnecessary costs.

Remove/Disable the `ppud-data-transfer` EC2 instance.

---

terraform/environments/equip/securitygroup.tf

This PR explicitly adds rules for inter-DC traffic, to ensure that all documented ports requested are permitted explicitly between domain controller hosts

added declarative rules for DC to DC traffic

---

terraform/environments/performance-hub/monitoring.tf

- Create an alarm from the AWS Shield Advanced DDoSDetected metric.
- Create a high priority SNS topic where we can push the alarm to.
- Subscribe to the topic the pagerduty cloudwatch endpoints:
low-priority service for non prod, high-priority service for production.
This will allow us to be notified if any DDoS attacks are detected on
performance hub in the #modernisation-platform-high-priority-alarms
channel.

Add DDoS alarm to Performance Hub

---

terraform/environments/equip/alb.tf
terraform/environments/equip/dlm-snapshot/data.tf
terraform/environments/equip/dlm-snapshot/main.tf
terraform/environments/equip/dlm-snapshot/variables.tf
terraform/environments/equip/dlm-snapshot/versions.tf
terraform/environments/equip/dlm.tf
terraform/environments/equip/ec2-instance-module/main.tf
terraform/environments/equip/ec2-instance-module/outputs.tf
terraform/environments/equip/instance_role.tf
terraform/environments/equip/s3-ukcloud-replica.tf

* Clean up linting through use of `terraform fmt`
* Employ and invoke a module to make use of AWS Data Lifecycle Manager to make EBS Snapshots of EC2 instances in development environment

Take EBS snapshots via DLM policy

---

terraform/environments/equip/ec2-instance-module/main.tf

* Prevent changes to EBS volume from setting off a cycle of spurious rebuilds
* EG, replacing a volume from a snapshot will trigger the deletion and recreation of an instance

Equip EBS volume lifecycle statement

---

terraform/environments/nomis/application_variables.tf
terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/modules/database/main.tf
terraform/environments/nomis/modules/database/variables.tf

This is an empty DB in prod env, it will be used for syncing with the PDPDL00038 Prod Audit DB.

Creating an audit database in Production

---

terraform/environments/equip/dns.tf

* Change conditional in DNS records so that production, not development, creates them
* Gateway still pointing at development until go-ahead from team given

Point Equip DNS records at production load balancer

---

.github/workflows/nuke-redeploy.yml

- Do not recreate testing-test after it's being automatically nuked. The -development suffix is the naming convention used in the terraform-apply-after-nuke.sh script.
- Note that the secret nuke_account_ids in the Modernisation Platform account now also includes two additional environments: "EXAMPLE_DEVELOPMENT_ACCID":"083957762049","TESTING_TEST_DEVELOPMENT_ACCID":"836052629367"

Do not recreate testing-test after it's being automatically nuked

---

scripts/nuke.sh
scripts/terraform-apply-after-nuke.sh

Fix a bug in auto-nuke not reporting correct number of failed environments

auto-nuke not reporting correct number of failed envs

---

terraform/environments/equip/alb.tf
terraform/environments/equip/dns.tf

* Point `gateway.equip.service.justice.gov.uk` record at production
* Create `HTTP_301` redirects for legacy addresses

Equip redirects

---

.github/workflows/example.yml
.github/workflows/nuke-redeploy.yml
.github/workflows/nuke.yml
.github/workflows/ppud.yml
.github/workflows/sprinkler.yml
.github/workflows/tariff.yml
.github/workflows/threat-and-vulnerability-mgmt.yml
terraform/environments/cooker/versions.tf
terraform/environments/example/versions.tf
terraform/environments/ppud/versions.tf
terraform/environments/sprinkler/versions.tf
terraform/environments/tariff/versions.tf
terraform/environments/threat-and-vulnerability-mgmt/versions.tf

We also want to ensure we can automatically update for minor version
changes.
Note the difference in versioning specification.
The Terraform action requires the syntax "~1"
The Terraform version block requires "~1.0"
Also added `terraform --version` line so that we can see easily what
version the action is running with.
Tested as follows to prove -
Terraform version(which checks the version of TF complies):
```
required_version = "~> 0"
using terraform 1.0.1
Plan completes!
```
And obviously...
```
required_version = "~> 1"
using terraform 1.0.1
Plan completes!
```
So to follow up...
```
required_version = "~> 2"
using terraform 1.0.1
Plan fails
```
So for the terraform action version which impacts the installed version of terraform, I tried:
`terraform_version: "~0"`
And that got TF …

Update Terraform version in MP controlled TF

---

terraform/environments/nomis/application_variables.tf
terraform/environments/nomis/modules/weblogic/main.tf
terraform/environments/nomis/r53-oracle-manager-dns.tf

In order to avoid changing /etc/hosts file on the VM itself, the IP address for the OMS should be retrieved from a private hosting zone.

DSOS-1350: Adding DNS record for Oracle Manager

---

terraform/environments/xhibit-portal/importrole.tf

The existing reference to the VM import module referenced a specific MOJ version, however we don't have all the permissions required.

Remove reference to a specfic version of the vm import module

---

terraform/environments/xhibit-portal/importmachine.tf

The AWS instance configuration for the import machine ignored any changes made to the root block device. We increased the size of the disk in a previous PR but because this setting was there, nothing ever happened.
Fixing this issue.
Outcome in Dev - increasing the disk to 70GB leaves us with 10GB of unallocated space - as expected. Needs user to manually extend the partition.

Remove ignore changes to root block device to increase drive size in the import server

---

terraform/environments/nomis/application_variables.tf

I'm increasing Oracle ASM disk capacity for both data and flash disks in order to test the procedure described in Confluence: https://dsdmoj.atlassian.net/wiki/spaces/DSTT/pages/3958145072/Increasing+Oracle+ASM+Disk+Group+Capacity

Increase data & flash disk capacity for testing

---

terraform/environments/sprinkler/bastion_linux.tf

────────────────────────────────────────────────────────────────────────────────
github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket?ref=v6.1.1/main.tf:151-156
via s3.tf:4-67 (module.s3-bucket)
────────────────────────────────────────────────────────────────────────────────
151    resource "aws_s3_bucket_versioning" "default" {
152      bucket = aws_s3_bucket.default.id
153      versioning_configuration {
154        status = (var.versioning_enabled != true) ? "Suspended" : "Enabled"
155      }
156    }
────────────────────────────────────────────────────────────────────────────────
ID aws-s3-enable-versioning
Impact Deleted or modified data would not be recoverable
Resolution Enable versioning to protect against accidental/malicious removal or modification
More …

Result #11 MEDIUM Bucket does not have versioning enabled

---

terraform/environments/example/bastion_linux.tf
terraform/environments/nomis/bastion_linux.tf
terraform/environments/performance-hub/bastion_linux.tf
terraform/environments/xhibit-portal/bastion_linux.tf

Adding the tfsec exclusions to all the bastion module definitions
Result #11 MEDIUM Bucket does not have versioning enabled
────────────────────────────────────────────────────────────────────────────────
github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket?ref=v6.1.1/main.tf:151-156
via s3.tf:4-67 (module.s3-bucket)
────────────────────────────────────────────────────────────────────────────────
151    resource "aws_s3_bucket_versioning" "default" {
152      bucket = aws_s3_bucket.default.id
153      versioning_configuration {
154        status = (var.versioning_enabled != true) ? "Suspended" : "Enabled"
155      }
156    }
────────────────────────────────────────────────────────────────────────────────
ID aws-s3-enable-versioning
Impact Deleted or modified data would …

Adding the tfsec exclusions to all the bastion module definitions

---

terraform/environments/nomis/application_variables.tf

The database needs to be completely destroyed first as a simple change of the AMI parameter won't recreate the EBS volumes attached to it (due to an imposed lifecycle policy) ⭐

Removing the NOMIS db to recreate it with a new AMI

---

terraform/environments/nomis/application_variables.tf

The database needs to be completely destroyed first as a simple change of the AMI parameter won't recreate the EBS volumes attached to it (due to an imposed lifecycle policy)

Removing the NOMIS db to recreate it with a new AMI later

---

terraform/environments/xhibit-portal/lambda.tf
terraform/environments/xhibit-portal/lambda/delete_old_ami.py
terraform/environments/xhibit-portal/lambda/index.py

We create backups of just the root disk for our disaster recovery process, via a timed lambda.
The issue with this is it is not managed by AWS backup, and will just sit in the environment, costing us more and more.
By adding this script, it should delete anything over 122 days (it won't yet as I've enabled the dry_run flag) and remove those resources we no longer need.

New Script to remove non-AWS Backup managed items

---

terraform/environments/xhibit-portal/lambda.tf

I missed off the DescribeInstances permission for the Delete old AMI's Lambda. Adding in now.

Add missing permission "DescribeInstances" for the delete old ami Lambda

---

terraform/environments/nomis/application_variables.tf

As per PR description - need to destroy to recreate it correctly

Destroying CNOMT1TEST as it's been created without oracle_sid parameter

---

terraform/environments/nomis/application_variables.tf

Rebuilding CNOMT1TEST instance - this time with `oracle_sids` set to CNOMT1

Recreating CNOMT1TEST instance

---

terraform/environments/nomis/application_variables.tf

Spin up a new database for preprod audit.
Note this doesn't follow the proposed naming conventions yet as this isn't in the scope of the ticket.

nomis DSOS-1443: preprod audit db

---

terraform/environments/xhibit-portal/lambda/delete_old_ami.py

After a successful run - remove the dry run variable to actually remove the old snapshots/ami's

Remove dry run after successful run

---

terraform/environments/xhibit-portal/lambda.tf
terraform/environments/xhibit-portal/lambda/delete_old_ami.py

The lambda was timing out when attempting to iterate over the snapshots - this way we'll at least process some of the snapshots before reaching our timeout value.
Also increased the timeout value due to the amount of data being returned

Add Pagination for the Snapshot deletion process

---

terraform/environments/nomis/packer.tf

Adding S3 PutObject and EC2 DescribeInstances permissions to packer for running ansible via SSM.

Adding permissions  to packer for running ansible via SSM

---

terraform/environments/xhibit-portal/lambda.tf

There's been issues running the lambda, possibly due to the large amount of snapshots we have (We need to iterate over them to clear up any orphaned snaps)

Increase the amount of memory associated with the Lambda

---

terraform/environments/nomis/application_variables.tf

I'm rebuilding RHEL7TEST base_instance with a new ami with updated set of packages - I'll be using it for testing node_exporter ansible role.

Recreating RHEL7TEST base_instance with a fresh AMI

---

terraform/environments/nomis/ansible/README.md
terraform/environments/nomis/ansible/group_vars/aws_ec2.yml
terraform/environments/nomis/ansible/group_vars/environment_name_nomis_test.yml
terraform/environments/nomis/ansible/group_vars/server_type_base.yml
terraform/environments/nomis/ansible/inventory_aws_ec2.yml
terraform/environments/nomis/ansible/roles/get-ec2-facts/README.md
terraform/environments/nomis/ansible/roles/get-ec2-facts/tasks/main.yml
terraform/environments/nomis/ansible/site.yml
terraform/environments/nomis/application_variables.tf
terraform/environments/nomis/ec2-test_instance.tf
terraform/environments/nomis/modules/test_instance_asg/main.tf
terraform/environments/nomis/modules/test_instance_asg/user_data/ansible.sh.tftpl
terraform/environments/nomis/modules/test_instance_asg/variables.tf

Since we don't have a separate ansible repo (yet), and Julia has added ansible into environments repo for now, this PR builds on that work:
- add README, generic site.yml from the strategy ticket (copied across from AMI repo)
- update test-instance-asg module to use environments repo as default repo and allow any path
- add a new ASG for testing base 7.9 image (will be used to validate naming stuff for test audit DB)

nomis: DSOS-1439: setup ansible framework

---

.github/CODEOWNERS

Removing interventions-reporting-discovery group

---

terraform/environments/nomis/ec2-common.tf

ssm documents that need to pull values from Parameter Store require the ssm:GetParameters role
In this case it's so that the AWS-ApplyAnsiblePlaybooks doc can pull a Github PAT out of the Parameter Store via the tokenInfo parameter but supplying any parameter to a playbook is going to need this permission
also put the roles back into alphabetical order

add ssm:GetParameters to pull secrets from Parameter Store

---

terraform/environments/performance-hub/locals.tf

The attribute "body" is deprecated. Refer to the provider documentation for
details.

Missed replacing body with request_body.

---

terraform/environments/nomis/bastion_linux.tf
terraform/environments/nomis/templates/bastion-user-data.sh.tftpl

Add the mod platform internal zone as an additional dns zone to search.  This way, EC2 short names, e.g. t1-db-audit can be accessed directly without the FQDN, t1-db-audit.nomis.hmpps-test.modernisation-platform.internal

Nomis: DSOS-1439: update bastion search zones

---

terraform/environments/nomis/application_variables.tf
terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/modules/ec2_instance/variables.tf

Rebuild of T1 and preprod Audit database.
- Use latest image
- Zap the old T1/preprod databases
- Standup t1 and preprod instances.

Nomis: DSOS-1507: T1 and preprod audit db

---

terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/modules/ec2_instance/README.md
terraform/environments/nomis/modules/ec2_instance/data.tf
terraform/environments/nomis/modules/ec2_instance/locals.tf
terraform/environments/nomis/modules/ec2_instance/main.tf
terraform/environments/nomis/modules/ec2_instance/variables.tf

Minor tweaks/fixes to ec2_instance module
- fix swap disk size (4 Gb -> 16 Gb on the new audit DBs).  This can be applied dynamically
- remove the database specific stuff and replace with variable
- cloning ansible with a branch is now an opt-in feature per ec2 instance.  This avoids unwanted user-data plan changes.
- adding an extra label to disk names (e.g. app/data) is optional.  Added README about this.

Nomis: DSOS-1507: audit db swap fix

---

terraform/environments/nomis/nomis-production.tf
terraform/environments/nomis/nomis-test.tf
terraform/environments/nomis/templates/ansible.sh.tftpl

Deleting unused databases and ASGs.  The databases need to be rebuilt using the new naming.
Since t1-nomis-db-2 accidentally zapped, updating the AMI it uses.
Minor fix to ansible template file to suppress warnings.

nomis: resource tidyup

---

terraform/environments/nomis/ec2-database.tf

role defined in ec2-database.tf to PUT items in 'nomis-db-backup-bucket* expanded to allow retrieval of database backups from here as well

add ListObject and GetObject permissions to get db backups from s3

---

terraform/environments/nomis/nomis-test.tf

Sandhya has migrated the T1 audit database to the new t1-nomis-db-2 host.  Zapping the old one

nomis: remove unused test EC2

---

terraform/environments/nomis/nomis-test.tf

Discussed with Sandhya and she advises we leave the audit database up 24/7 - so excluding this from the mod platform power down automation.

nomis: disable automation scheduling for T1 nomis DB

---

terraform/environments/nomis/nomis-development.tf
terraform/environments/nomis/templates/ansible-ec2provision.sh.tftpl

Update ansible template to work on RHEL6 (no set -u option)
Use optional metadata tokens on RHEL6 test instances
Add ami tag on ec2-test instances for testing ansible patching with AMI repo.

nomis: DSOS-1558: rhel 6 10 fixes

---

terraform/environments/nomis/modules/ec2_instance/locals.tf
terraform/environments/nomis/modules/ec2_instance/main.tf
terraform/environments/nomis/nomis-development.tf
terraform/environments/nomis/nomis-production.tf
terraform/environments/nomis/nomis-test.tf

Removing snapshot_id, which is an optional parameter, from the ebs_volume terraform.  Snapshots can't be accessed if the AMI is sitting in another account such as core-shared-services-production.  This removes the need to copy DB AMIs across to other accounts.
It's safe to remove the snapshot_id since all of the volume settings are known anyway from the data.aws_ami resource.  However, I spotted a bug where the disk settings weren't been set properly.  I've updated the variable files to make sure there's no plan changes, but we need to adjust some of the disk settings in a follow up PR.

DSOS-1561: db ami snapshot fix

---

terraform/environments/nomis/ec2-test.tf

For NDH testing since the instances need to talk to each other.

nomis: DSOS-1543: allow traffic between test ec2s

---

terraform/environments/nomis/modules/ec2_instance/README.md

Describe adding a fixngo-connection-target tag to nomis-db instances 
This uses the mod-platform-configuration-management repo to create a script-exporter job which will provide metrics for prometheus to scrape to alert whether the nomis-db instance with this tag has lost connection to a target within the azure fixngo environment

describe fixngo-connection-target tag in nomis ec2-instance readme

---

terraform/environments/mlra/lz-conn-test.tf

Re-adding EC2 instance used for network connectivity testing, which was temporarily removed due to VC conflicts

Re-Add Test Instance

---

.github/workflows/format-code.yml
.github/workflows/generate-dependabot-file.yml
.github/workflows/go-tests.yml
.github/workflows/nuke.yml
.github/workflows/run-opa-tests.yml
.github/workflows/terraform-static-analysis.yml

Following github best practices, restricting the top level permissions to read only and allowing write in the jobs where required.

Restrict default permissons to read only

---

.github/workflows/apex.yml
.github/workflows/ccms-ebs.yml
.github/workflows/data-and-insights-wepi.yml
.github/workflows/delius-iaps.yml
.github/workflows/digital-prison-reporting.yml
.github/workflows/equip.yml
.github/workflows/example.yml
.github/workflows/format-code.yml
.github/workflows/generate-dependabot-file.yml
.github/workflows/go-tests.yml
.github/workflows/maatdb.yml
.github/workflows/mlra.yml
.github/workflows/nomis.yml
.github/workflows/nuke-redeploy.yml
.github/workflows/nuke.yml
.github/workflows/oasys.yml
.github/workflows/performance-hub.yml
.github/workflows/ppud.yml
.github/workflows/refer-monitor.yml
.github/workflows/run-opa-tests.yml
.github/workflows/sprinkler.yml
.github/workflows/tariff.yml
.github/workflows/terraform-static-analysis.yml
.github/workflows/threat-and-vulnerability-mgmt.yml
.github/workflows/xhibit-portal.yml

Following github security hardending guidance for actions here - https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Pin github actions to specific commit hash

---

terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/loadbalancer.tf

I've created new load balancer **jbtest-lb** in **nomis-test** and moved the listeners from existing load balancer **lb-internal-nomis** to **jbtest-lb**. The code changes have already been deployed into **nomis-test** so the Terraform plan should be clear. I've tested connectivity to **jbtest-lb** using the Windows jump server in **nomis-test**. Expect a follow-up PR in the coming days to align the load balancer with our naming standards.

Moving listeners to new load balancer

---

terraform/environments/nomis/ec2-common.tf
terraform/environments/nomis/s3.tf

Allow EC2s to access imagebuilder S3 bucket within the same account.  This is for weblogic patch testing

DSOS-1570: allow ec2s to access imagebuilder s3 bucket

---

terraform/environments/mlra/ecs.tf

Pinning the MP ECS module version.
Using the latest version `v.2.1.2` . This version has been tested and it currently works with our configuration.

Pinning the MP ECS module version

---

terraform/environments/nomis/ec2-weblogic.tf

Removed security group. This is a pre-requisite to avoid a dependency error included in a follow-up change.

Commented out security group

---

terraform/environments/nomis/ec2-weblogic.tf

Now that the old load balancer and other related resources, including a security group, have been destroyed and rebuilt, I can add this back in.

Adding security group back in

---

terraform/environments/nomis/ec2-common.tf

Back this out as EC2s are unable to access SSM parameters

DSOS-1586: backout checkov policy fixes as they don't work

---

.github/workflows/awsnuke.yml

Relevant Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2400
Removing the debug version of the matrix variable and adding in the generated version instead.
Related PR: https://github.com/ministryofjustice/modernisation-platform-environments/pull/1153

Replacing debug value for matrix with dynamically generated matrix value

---

terraform/environments/example/bastion_linux.tf

Version 3.0.6 of the bastion repo uses templatefile terraform function for templates. This is to replace the discontinued hashicorp/template provider.
Linked issue: https://github.com/ministryofjustice/modernisation-platform/issues/2506
Tested  locally with plan/apply.

Updating bastion version in example-development account

---

terraform/environments/mlra/cloudwatch.tf
terraform/environments/mlra/locals.tf

To make things more uniform it was decided to move two variables to the locals.tf instead of having them in the cloudwatch.tf
This Pr corrects this issue.

Moved sns vars to locals

---

terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-jumpserver.tf
terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/modules/ec2_autoscaling_group/locals.tf
terraform/environments/nomis/modules/ec2_autoscaling_group/variables.tf
terraform/environments/nomis/modules/ec2_instance/locals.tf
terraform/environments/nomis/modules/ec2_instance/variables.tf
terraform/environments/nomis/nomis-development.tf

Add option to ignore EBS volumes in AMI images and set this for jumpserver.
This is to get rid of the unwanted EBS ephemeral devices in the jumpserver images which is causing terraform problems.

Nomis: jumpserver bodges

---

terraform/environments/apex/providers.tf
terraform/environments/ccms-ebs/providers.tf
terraform/environments/data-and-insights-wepi/providers.tf
terraform/environments/delius-iaps/providers.tf
terraform/environments/delius-jitbit/providers.tf
terraform/environments/digital-prison-reporting/providers.tf
terraform/environments/equip/providers.tf
terraform/environments/maatdb/providers.tf
terraform/environments/mlra/providers.tf
terraform/environments/nomis/providers.tf
terraform/environments/oasys/providers.tf
terraform/environments/performance-hub/providers.tf
terraform/environments/ppud/providers.tf
terraform/environments/refer-monitor/providers.tf
terraform/environments/tariff/providers.tf
terraform/environments/threat-and-vulnerability-mgmt/providers.tf
terraform/environments/xhibit-portal/providers.tf
terraform/environments/xhibit-portal/providers.tf.gh
terraform/environments/xhibit-portal/providers.tf.local

```
Warning: Argument is deprecated
with provider["registry.terraform.io/hashicorp/aws"].modernisation-platform,
on providers.tf line 19, in provider "aws":
19:   skip_get_ec2_platforms = true
With the retirement of EC2-Classic the skip_get_ec2_platforms attribute has
been deprecated and will be removed in a future version.
```
Resolves the above warning.

Remove deprecated provider attribute from apps

---

terraform/environments/nomis/cidrs.tf
terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-jumpserver.tf
terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/nomis-development.tf
terraform/environments/nomis/nomis-preproduction.tf
terraform/environments/nomis/nomis-production.tf
terraform/environments/nomis/nomis-test.tf

Add access for analytical platform and the AKS clusters.
Aligned the rules while I was at it:
- consistent access for ssh / rdp / prometheus across all groups
- consistent naming
- rules are in port order in the terraform

nomis: DSOS-1522: revise security groups

---

.github/CODEOWNERS
terraform/modules/README.md

Following a user request, creating a shared module folder in the environments repo, this is to enable teams to create modules that they can use across multiple applications, and for users of other teams to use, with a view that if the module is successful we can then move it out to its own repo and add tests, version it etc.
Effectively this will allow users to contribute and write shared modules when they need them.

Add shared modules folder

---

terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/nomis-test.tf

Update t1-nomis-web to use the newer, shinier, and hopefully working version of weblogic
Aligned ec2-test ASG with the weblogic one by adding "offpeak_desired_capacity" option.
Also added Tony's NDH ASGs which were applied via a branch but forgot to make its way into main

DSOS-1611: migrate weblogic ami to ansible

---

.github/workflows/generate-dependabot-file.yml
.github/workflows/terraform-static-analysis.yml

Also remove notification of SCA failure from environments repo, we do not need to know this in this repo as it will often failing as we don't enforce it here.

Replace slack notification with official action

---

terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis/templates/ansible-ec2provisiondata.sh.tftpl
terraform/environments/nomis/templates/install-ssm-agent.sh.tftpl

Some minor improvements for testing images:
- allow testing directly on base RedHat image  (added ssm-agent cloud-init script to support)
- ansible component bails out if aws cli or git not installed
- use new base AMI images in the ASG

Nomis: DSOS-1613: test new base amis

---

terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/modules/ec2_instance/main.tf

Updated weblogic AMI to the latest version which has the stig hardening included.
Update ec2-module public IP to EIP so IP persists between rebuild

DSOS-1571: use stig weblogic and ec2_module tweak

---

terraform/environments/delius-iaps/ec2-iaps-server.tf
terraform/environments/nomis/data.tf
terraform/environments/nomis/ec2-jumpserver.tf
terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/loadbalancer.tf
terraform/modules/ec2_autoscaling_group/data.tf
terraform/modules/ec2_autoscaling_group/main.tf
terraform/modules/ec2_autoscaling_group/variables.tf

Work item nit-476: Changes to the local ASG module to receive a set of subnet_ids that are then applied to the ASG. It allows module consumes to be in charge of which subnets that want the ASG to operate over (and therefore adding AZ redundancy)

Nit476 allow asg module to support multi az

---

terraform/environments/mlra/modules/albvars/main.tf

tfsec ignore comments and checkov ignore comments added to file .../mlra/modules/albvars/main.tf - this will ignore the load balancer not using HTTPS protocol

LAWS-2949: added tfsec and checkov ignore comments

---

terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/lb-listeners.tf
terraform/environments/nomis/locals-lb-listeners.tf
terraform/environments/nomis/locals-lbs.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/modules/weblogic/outputs.tf
terraform/modules/ec2_instance/outputs.tf
terraform/modules/lb_listener/README.md
terraform/modules/lb_listener/data.tf
terraform/modules/lb_listener/locals.tf
terraform/modules/lb_listener/main.tf
terraform/modules/lb_listener/outputs.tf
terraform/modules/lb_listener/variables.tf
terraform/modules/lb_listener/versions.tf

Allow addition of multiple loadbalancer listeners and rules for T1, T3 etc.
- moved legacy weblogic locals (soon to be deleted) outside of main locals-test to avoid circular dependency
- added load balancer security groups to the ec2 security groups where necessary
- added a lb-listener module for ease of adding listeners
- added 3 endpoints for T1 nomis for ASG (t1-nomis-web.nomis), standalone instance (t1-nomis-web-instance.nomis), and the legacy EC2 (weblogic-cnomt1.nomis).  The latter 2 will be removed following some testing
- increased the ASG count for weblogic servers while we test

Nomis: DSOS-1628: add loadbalancer listeners

---

terraform/environments/nomis/locals-lb-listeners.tf
terraform/environments/nomis/locals-test.tf

Was temporarily used for testing weblogic from FixNGo.  No longer needed, we can use the main load balancer now.

DSOS-1620: remove standalone weblogic load balancer

---

terraform/environments/example/loadbalancer.tf
terraform/environments/example/loadbalancer_using_module.tf
terraform/environments/example/s3.tf

Whilst trouble shooting a failed plan on a dependabot PR in example, it became clear that you cannot easily destroy example without a lot of manual work.
These changes mean you can build and destroy the example account easily.

Make example destroyable

---

terraform/environments/nomis/locals-test.tf

These were enabled just to test prometheus.  Disabling again now we can see monitoring is working.

DSOS-1645: stop monitoring couple of EC2s in nomis-test

---

terraform/environments/nomis/locals-development.tf

A Windows 2019 jumpserver for **nomis-development**.

Adding an ASG for the Windows 2019 jumpserver

---

.github/workflows/ccms-ebs.yml

When the test environment fails it prevents dev deployment from running.
Turning off fail-fast to run the deployment workflows even if the plans fail.

Fix failing action when test fails

---

terraform/environments/nomis/monitoring-alerts.tf
terraform/modules/ec2_instance/README.md

Adds basic alerts for linux EC2 instances based off metrics and AWS instance status info. 
There are tickets in the backlog for other alerts and changes to the local cloudwatch agent install process which will take into account Windows servers, custom scripts and endpoint checking. See [DSOS-1657](https://dsdmoj.atlassian.net/browse/DSOS-1657) for what's been implemented so far versus existing Prometheus based monitoring in FixNGo and Mod Platform (which will be superseded by this soon).
[DSOS-1657]: https://dsdmoj.atlassian.net/browse/DSOS-1657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Nomis/dsos 1657/metric alerts nomis

---

terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-jumpserver.tf
terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/security-groups.tf

Now everything has switched over to the new groups, should be possible to zap the old ones

nomis: DSOS-1647: Remove unused security groups

---

terraform/environments/nomis/locals-test.tf

additional log group for weblogic logs for nomis-test environment only (at the moment) 
assuming this works I'll replicate it to the other nomis environments or revert this if it doesn't

add cwagent log stream for weblogic logs in nomis

---

scripts/tests/validate/opa.sh
scripts/tests/validate/run-opa-tests.sh

A bit of a dirty fix, as it would be better if we checked for the whole file name, but the changes needed for https://github.com/ministryofjustice/modernisation-platform/issues/2521 will be rolled out in batches, so this can be fixed properly after all of the accounts have the changes.

Temp fix for opa tests

---

terraform/environments/nomis/ec2-common.tf
terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/templates/cloud_watch_windows.json
terraform/environments/nomis/templates/jumpserver-user-data.yaml

Since it's quite challenging to have ansible (running from the modernisation-platform-configuration-management repo) install cloudwatch-agent and config etc. onto Windows machines, for the sake of expediency this is being done in the windows init script.
This (currently) also only applies to the Jumpserver instances as these are our only Windows machines. Possibly the way forward is to use the ansible aws_ssm provider instead but for the moment this is the most straight-forward way of getting Windows logs/metrics into Cloudwatch.
This PR is basically to test the init changes. Assuming windows events start appearing in Cloudwatch I'll extend some of the alerts to include the Jumpservers as well.
NOTE: Open-policy-agent checks associated with adding backends and adding providers have been …

add cloud_watch_config_windows to parameter store and install/start cloudwatch using the windows init script

---

terraform/environments/nomis/cmk.tf
terraform/environments/nomis/ec2-common.tf
terraform/environments/nomis/ec2-image-builder-iam.tf
terraform/environments/nomis/s3.tf

Remove old nomis CMK (we now use hmpps key from core-shared-services-production instead)
Set default S3 bucket encryption keys to hmpps general.  This will make sharing between accounts easier - particularly relevant for image builder / db backup buckets.

Nomis: DSOS-1587: more cmk changes

---

terraform/environments/nomis/ec2-common.tf

Add KMS Grant for autoscaling policy.  This gives access to the shared HMPPS EBS key.  Without this, ASG instances using this key will fail to start

Nomis: DSOS-1587: fix asg shared kms key access

---

terraform/environments/nomis/ec2-common.tf
terraform/environments/nomis/ec2-image-builder-iam.tf
terraform/environments/nomis/s3.tf

Fix S3 KMS keys:
- add access to keys for EC2 and scaling groups
- corrected default key (use ARN instead of ID)

Nomis: DSOS-1587: fix s3 shared kms key access

---

terraform/environments/nomis/locals-security-groups.tf

Allow direct access to individual weblogic server from Azure JumpServers.  This will be required while we figure out how best to provide access to the AWS JumpServers

DSOS-1704: allow access to weblogic servers from Azure 

---

terraform/environments/nomis/monitoring-alerts.tf

picks up things moving into 'unhealthy' status after 3 minutes

load balancer target alerts

---

terraform/environments/nomis/monitoring-alerts.tf

Although AWS Certificate manager should absolutely auto-renew these it'd be useful to get a heads up when things are on their way to expiry. We can always delete or change these alerts later if they turn out to be irrelevant.

certificate expiry alerts

---

terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/locals-alerts-linux.tf
terraform/environments/nomis/locals-alerts-windows.tf
terraform/environments/nomis/monitoring-alerts.tf
terraform/modules/ec2_autoscaling_group/main.tf
terraform/modules/ec2_instance/main.tf

alarm names by instance-name-alarm-name
ec2_instances will have their own alerts on the metrics we're interested in
asg's will have alerts by asg group so this should be fairly sane now!

Nomis/dsos 1716/fix alarm names

---

terraform/environments/nomis/ec2-database.tf

remove this alarm 'cause it will trigger whenever a test db instance is created and is not particularly useful
the metric exists for debugging purposes so that's fine - it should be incorporated into a "db dashboard" later but having this as an alert is too shouty

remove file_error alert

---

terraform/environments/nomis/monitoring-setup.tf

Since adding and then referring immediately to an alert_sns_topic resource seems to have some issues - add this first and THEN apply the changes/linking to the pagerduty/slack integration in a separate PR so it can get this from the state

create an additional sns topic for non-prod alerting

---

terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-jumpserver.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-alerts-linux.tf
terraform/environments/nomis/locals-alerts-windows.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/monitoring-alerts.tf
terraform/environments/nomis/monitoring-setup.tf

Introduces a non-production alerts channel into slack for everything to send notifications to `#dso_alerts_devtest_modernisation_platform` unless specifically over-ridden
You can over-ride this and send alarms to #dso_alerts_modernisation_platform by adding the `sns_topic = aws_sns_topic.nomis_alarms.arn` to the instance config in locals-production.tf (for example) 
Further config options to come but at this point we will be able to differentiate between 'production' and everything else
- changed alarm names to appear as instance-name-alarm-name
- database, jumpserver and weblogic instances can send alarms to 'prod' channel
- alarms go to non-prod channel by default
- existing pagerduty subscription is being re-created as its module call has been renamed

Nomis/dsos 1755/nomis nonprod alarm

---

terraform/environments/oasys/main.tf

This is required to create a load balancer target group.

Adding missing vpc_id argument

---

.github/workflows/apex.yml
.github/workflows/ccms-ebs.yml
.github/workflows/data-and-insights-wepi.yml
.github/workflows/delius-iaps.yml
.github/workflows/delius-jitbit.yml
.github/workflows/digital-prison-reporting.yml
.github/workflows/equip.yml
.github/workflows/example.yml
.github/workflows/laa-oem.yml
.github/workflows/long-term-storage.yml
.github/workflows/maatdb.yml
.github/workflows/mlra.yml
.github/workflows/nomis-combined-reporting.yml
.github/workflows/oas.yml
.github/workflows/performance-hub.yml
.github/workflows/ppud.yml
.github/workflows/refer-monitor.yml
.github/workflows/sprinkler.yml
.github/workflows/tariff.yml
.github/workflows/tipstaff.yml
.github/workflows/xhibit-portal.yml

Expands on the work completed in https://github.com/ministryofjustice/modernisation-platform-environments/pull/1465
`nomis` and `oas` workflows have been exluded from this as they show significant customisation from our default workflow file.

Allow users ability to destroy development / test environments

---

terraform/environments/nomis/ec2-database.tf

These metrics come in as 0 (okay) and 1 (batch is failing) if the db monitor has posted the associated strings into a file.
This isn't guaranteed so change the alarm settings so that 'missing' data doesn't render the metric into an "insufficient data" state once it's been set up

means that 'missing' values appear as green in the AWS UI

---

terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-alerts-linux.tf
terraform/environments/nomis/locals-alerts-windows.tf

Introduces a number of new alarms which will trigger on non-running key services
- ssm agent
- cloudwatch agent
- chronyd
- sshd
- oracle-ohasd and oracleasm for db machines
- weblogic-node-manager for web instances
Adds a missing CPUUtilization alarm for windows hosts
Changes the cpu-iowait threshold to bring it in line with settings in dso-monitoring for this metric

Nomis/dsos 1778/linux service alarms

---

terraform/environments/example/s3.tf

After a version bump of the S3 bucket module, a deprecated attribute was not removed. This removes that attribute, allowing example to successfully execute a `terraform plan`.

removed deprecated bucket option for example

---

terraform/environments/delius-iaps/templates/iaps-EC2LaunchV2.yaml.tftpl

IAPS Domain Users require local admin rights, as some of the legacy applications they use rely on them. Additionally each IAPS Domain only covers the environment it is in. (AD is hopefully a temporary workaround, and the auth method should change in the future)

IAPS - Use AD to manage access

---

terraform/environments/oas/ec2.tf

This PR looks at adding in an ingress route in the security group with port 1389 that is needed to integrate with applications in the Dev Landing Zone.
It also adds egress routes in the security group with port 1521 so that it can integrate with databases in the Dev Landing Zone.

LAW-3033 OAS LZ Integration

---

terraform/environments/performance-hub/application_variables.json
terraform/environments/performance-hub/locals.tf
terraform/environments/performance-hub/route53.tf

A recent deployment failed because the certificate in production was expired.  This is an ACM certificate, but because it isn't being used (production uses an imported Gandi certificate), Amazon doesn't renew unused certificates, and the expired certificate caused the apply to fail as the state was unexpected.
This PR adds a count in so that the ACM certificate and the validation records are not created in production.
Also during this change the AMI version was updated so updating here in the same PR to avoid 2 PRs which would implement changes and cause redeployments.  We should see a clean plan with this PR as these changes have been implemented via terraform locally.

Remove certificate from production

---

.github/workflows/nomis-combined-reporting.yml
.github/workflows/nomis-data-hub.yml
.github/workflows/nomis.yml
.github/workflows/reusable_terraform_plan_apply.yml

Retrofitted the new mod platform destroy functionality to the re-usable pipelines, since I need it for NDH.
Tested both destroy and deploy modes in the NDH pipelines

nomis: DSOS-1796: add destroy to nomis pipelines

---

.github/workflows/reusable_terraform_plan_apply.yml

Due to various issues with 1.4.0, setting the default terraform version to 1.3.9 for the time being.

fix terraform version to 1.3.9

---

.github/workflows/apex.yml
.github/workflows/ccms-ebs.yml
.github/workflows/data-and-insights-wepi.yml
.github/workflows/delius-core.yml
.github/workflows/delius-iaps.yml
.github/workflows/delius-jitbit.yml
.github/workflows/digital-prison-reporting.yml
.github/workflows/equip.yml
.github/workflows/example.yml
.github/workflows/laa-oem.yml
.github/workflows/long-term-storage.yml
.github/workflows/maatdb.yml
.github/workflows/mlra.yml
.github/workflows/nuke-redeploy.yml
.github/workflows/oas.yml
.github/workflows/oasys.yml
.github/workflows/performance-hub.yml
.github/workflows/portal.yml
.github/workflows/ppud.yml
.github/workflows/refer-monitor.yml
.github/workflows/sprinkler.yml
.github/workflows/tariff.yml
.github/workflows/tipstaff.yml
.github/workflows/xhibit-portal.yml
terraform/environments/mlra/platform_versions.tf
terraform/environments/oas/platform_versions.tf
terraform/environments/tipstaff/platform_versions.tf

In line with this Terraform issue - https://github.com/hashicorp/terraform/issues/32810 - this PR temporarily sets the Terraform version used in customer pipelines to `1.3.x`.
Also adds some missing provider references.

set floor terraform version to 1.3.x

---

terraform/environments/delius-iaps/ec2-iaps-server.tf
terraform/modules/ec2_autoscaling_group/main.tf
terraform/modules/ec2_autoscaling_group/variables.tf

Remove windows feature volume from IAPs AMI as it was only required during AMI build to enable windows features without going over the internet

NIT-531: Remove Windows installation media from AMI

---

.github/workflows/laa-oem.yml

Because of how the `laa-oem` team are using volume snapshots, and because they don't have any snapshots in their `test` environment, `continue-on-fail` is needed for changes to be made to the development environment

allow laa-oem to continue on fail

---

terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-jumpserver.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-development.tf

- example in nomis-development for setting up an alarm on a single instance
- includes use of fixngo-connection-target tag to set up metric with amazon-cloudwatch-agent role is run on it
- allows web, jumpservers and database instances to set up their own unique alarms if included in the instance configs

Nomis/dsos 1650/fixngo connectivity alarm

---

.github/workflows/laa-oem.yml

Add `continue-on-error` to terraform destroy jobs to accommodate failure to build test preventing deletion of development

allow laa-oem destroy plans to continue on fail

---

terraform/environments/delius-iaps/application_variables.json
terraform/environments/delius-iaps/ec2-iaps-server.tf

NIT-546 -  Specify version for IAPS server AMI.
Time stamp information already included in the name, so we can use that.
Set the version as an application variable per environment. If it's not specified, then use the latest using _*

Nit 546 - IAPS Server image specify version

---

terraform/environments/nomis-combined-reporting/baseline.tf
terraform/environments/nomis-combined-reporting/baseline_presets.tf
terraform/environments/nomis-data-hub/baseline.tf
terraform/environments/nomis-data-hub/baseline_presets.tf
terraform/environments/nomis/baseline.tf
terraform/environments/nomis/baseline_presets.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/oasys/main.tf
terraform/modules/baseline/outputs.tf
terraform/modules/baseline/route53.tf
terraform/modules/baseline/security_groups.tf
terraform/modules/baseline/variables.tf
terraform/modules/baseline_presets/outputs.tf
terraform/modules/baseline_presets/route53.tf
terraform/modules/baseline_presets/variables.tf
terraform/modules/ip_addresses/azure_fixngo.tf
terraform/modules/ip_addresses/outputs.tf

Added configuration to forward DNS requests for Azure hosts to Azure domain controllers via baseline module.
- added FixNGo domain controller details into ip_addresses module
- baseline presets now takes ip_addresses module output as a parameter, so it can use common IPs
- added route53 forwarding configuration to baseline
- added FixNGo route53 forwarding config into baseline_presets
- enable for nomis account only at the moment, but likely to be needed for other accounts.

Nomis: DSOS-1816: fixngo dns forwarding

---

terraform/environments/nomis/locals-production.tf

add alarm specifically to prod-nomis-db-2 that it's connectivity to the azure environment has died

add fixngo connected metric alarm to prod-nomis-db-2

---

terraform/environments/nomis/baseline.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/locals.tf
terraform/environments/nomis/outputs.tf
terraform/modules/baseline/lb.tf
terraform/modules/baseline/outputs.tf
terraform/modules/baseline/route53.tf
terraform/modules/baseline/variables.tf
terraform/modules/environment/outputs.tf
terraform/modules/lb_listener/main.tf

Add ability to create route53 zones via baseline module and added additional zones for nomis for Mojo device testing:
- environment module route53 zones output now includes the provider to use for each zone
- baseline module can now create route53 zones and associated records 
- create new domains under "az.justice.gov.uk" so URLs work with Mojo devices without any changes

Nomis: DSOS-1831: create az zones

---

terraform/environments/nomis/baseline_presets.tf

We don't need the standard wildcard cert now we have the new one which includes the nomis.az domains.  So get rid.

nomis: DSOS-1831: remove old wildcard cert

---

terraform/environments/example/environment.tf
terraform/environments/nomis-combined-reporting/environment.tf
terraform/environments/nomis-data-hub/environment.tf
terraform/environments/nomis/environment.tf
terraform/environments/nomis/monitoring-setup.tf
terraform/environments/oasys/main.tf
terraform/modules/environment/README.md
terraform/modules/environment/data.tf
terraform/modules/environment/outputs.tf
terraform/modules/environment/versions.tf

Preparation for moving nomis monitoring stuff into baseline module for re-use by oasys/ndh and combined reporting.
Add the pagerduty integration keys into environment module and updated nomis code to use this.  This requires adding modernisation-platform provider so updated all the other places the module is used.

Nomis: DSOS-1834: add pagerduty data to environment module

---

.github/workflows/format-code.yml

Following configuration guidance here - https://github.com/marketplace/actions/megalinter#quick-start
Setting the report folder to none 
> REPORT_OUTPUT_FOLDER | ${GITHUB_WORKSPACE}/megalinter-reports | Directory for generating report files. Set to none to not generate reports

Disable megalinter reports

---

.github/labeler.yml

Currently we can't exclude the environments repo from our PR notifications on slack.  By adding a label we can exclude based on label.

Add a env repo label to everything

---

terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf

Add ACM/LB alarms plus updated existing alarms:
- statistic changes to take into account there could be multiple instances being checked
- updated naming to allow for different variants of same alarm, high-cpu-5mins, high-cpu-15mins etc.
- removed windows CPU alarm as duplicate of the EC2 one
- increased some of the time thresholds

nomis: DSOS-1834: update cloudwatch alarms

---

.github/workflows/nomis-combined-reporting.yml
.github/workflows/nomis-data-hub.yml
.github/workflows/nomis.yml
.github/workflows/oasys.yml
.github/workflows/reusable_terraform_strategy.yml

This PR is part of the https://github.com/ministryofjustice/modernisation-platform/issues/3452 ticket.
The original reusable terraform strategy pipeline only accepts standard four accounts, which is no good, if a team has a random number of environments (e.g. only development and production and not test and preproduction).
This change is to dynamically generate the strategy matrix by reading an application's [json environment file](https://github.com/ministryofjustice/modernisation-platform/tree/main/environments) and generating the matrix based on the environments found in that file.
Updating the workflows that already use the reusable terraform pipelines.

Generating strategy matrix using environment files and updating relevant pipelines

---

terraform/environments/sprinkler/data.tf
terraform/environments/sprinkler/main.tf
terraform/environments/sprinkler/outputs.tf
terraform/environments/sprinkler/platform_providers.tf

Adding an ACM resource in US east 1, locally the sso or collaborator role is assumed, but when run on the pipeline the
MemberInfrastructureAccessUSEast role.

Testing dynamic provider for us-east-1

---

terraform/environments/apex/platform_providers.tf
terraform/environments/ccms-ebs/platform_providers.tf
terraform/environments/data-and-insights-wepi/platform_providers.tf
terraform/environments/data-platform/platform_providers.tf
terraform/environments/delius-core/platform_providers.tf
terraform/environments/delius-iaps/platform_providers.tf
terraform/environments/delius-jitbit/platform_providers.tf
terraform/environments/digital-prison-reporting/platform_providers.tf
terraform/environments/equip/platform_providers.tf
terraform/environments/example/platform_providers.tf
terraform/environments/laa-ccms-infra-azure-ad-sso/platform_providers.tf
terraform/environments/laa-oem/platform_providers.tf
terraform/environments/long-term-storage/platform_providers.tf
terraform/environments/maatdb/platform_providers.tf
terraform/environments/mojfin/platform_providers.tf
terraform/environments/nomis-combined-reporting/platform_providers.tf
terraform/environments/nomis-data-hub/platform_providers.tf
terraform/environments/nomis/platform_providers.tf
terraform/environments/oas/platform_providers.tf
terraform/environments/oasys/platform_providers.tf
terraform/environments/performance-hub/platform_providers.tf
terraform/environments/portal/platform_providers.tf
terraform/environments/ppud/platform_providers.tf
terraform/environments/refer-monitor/platform_providers.tf
terraform/environments/tariff/platform_providers.tf
terraform/environments/tipstaff/platform_providers.tf
terraform/environments/tribunals/platform_providers.tf
terraform/environments/xhibit-portal/platform_providers.tf

The local user doesn't have permission to assume the MemberInfrastructureAccessUsEast1 role. When running locally using the original session which has readonly access.

Add us-east-1 dynamic provider for local plans

---

terraform/environments/nomis/baseline.tf
terraform/environments/nomis/baseline_presets.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-test.tf
terraform/modules/baseline/ec2_autoscaling_group.tf
terraform/modules/baseline/variables.tf
terraform/modules/ec2_autoscaling_group/main.tf
terraform/modules/ec2_autoscaling_group/variables.tf

Use baseline module to create new T1 ASG in prep for preprod/prod changes:
- autoscaling group module supports specific availability zone
- fixed tags for baseline module for ASGS
- add a t1-nomis-web-a autoscaling group (idea is for green/blue deployments swapping between -a and -b availability zones)

Nomis: DSOS-1843: new weblogic asgs

---

terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf

Tweak the DNS naming strategy:
- ensure there is a name matching the ASG in both mod platform domain and .az domain (latter for Mojo testing)
- use "c" for the endpoint we give out to people to be consistent with current naming, or c-t1 when we have stacked environments, e.g.
c.production.az.nomis.justice.gov.uk
c.preproduction.az.nomis.justice.gov.uk
c-t1.test.az.nomis.justice.gov.uk

nomis: DSOS-1843: tweak DNS entries for nomis

---

terraform/modules/baseline/lb.tf
terraform/modules/baseline/variables.tf
terraform/modules/lb_listener/README.md
terraform/modules/lb_listener/locals.tf
terraform/modules/lb_listener/main.tf
terraform/modules/lb_listener/outputs.tf
terraform/modules/lb_listener/variables.tf
terraform/modules/lb_listener/versions.tf

Try and simplify lb-listener a bit:
- remove support for target groups being created within the module (this is done within ASG)
- remove support for adding route53 entries (this can be done via baseline module)
- remove the replace logic (it's too confusing)
Should be zero plan changes as these features are not currently in use.

Nomis: DSOS-1847: simplify lb listener module

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/main.tf

I've also applied an alphabetical sort for the Baseline Module arguments which is why the diff looks a bit of a mess.

Adding resource_explorer Baseline Module argument for OASys environments

---

terraform/environments/nomis-combined-reporting/baseline_presets.tf
terraform/environments/nomis-data-hub/baseline_presets.tf
terraform/environments/oasys/main.tf
terraform/modules/baseline_presets/ec2_instance.tf
terraform/modules/baseline_presets/iam_policies.tf
terraform/modules/baseline_presets/variables.tf

Add S3 policies that allow access to image builder software S3 buckets cross-account.  
Made the default EC2 policy list a little more flexible.

nomis: DSOS-1847: add image builder S3 policies for EC2 instances

---

terraform/environments/delius-jitbit/monitoring_app.tf
terraform/environments/delius-jitbit/monitoring_ecs.tf

- Create new log group for application logs
- Log metric filter to filter error logs "Error in Helpdesk"
- Create alarm hooked into PagerDuty integration for alerting when error count in the last 5 minutes exceeds the threshold of 10 (these examples are PoC and are subject to adjustment)
- Add widget to jitbit dashboard with error count

Jitbit: Alerting for high volume of application error logs

---

terraform/environments/data-platform/src/code_extractor/main.py

The json parsing presumed the syntax of an S3 notification - I have changed it to read an eventbridge event correctly.

Corrected json parsing

---

terraform/environments/equip/monitoring.tf
terraform/environments/performance-hub/monitoring.tf
terraform/environments/sprinkler/monitoring.tf

These subscriptions are used for DDOS alarms only, any other alarms should be created separately.

Rename sns subscriptions to ddos alarms

---

terraform/environments/delius-iaps/application_variables.json
terraform/environments/delius-iaps/files/ndelius_interface_ssm_params.yml
terraform/environments/delius-iaps/ssm.tf
terraform/environments/delius-iaps/templates/iaps-EC2LaunchV2.yaml.tftpl

We are choosing to use a find+replace method to configure the interface. Previous method of editing the XML file using PowerShell does not allow us to write certain characters without escaping them. The application does not conform to XML specication and expects some URI characters like & to remain unescaped
Additionally, some parameters we previously set are not required

NIT-621 change how nd interface is configured

---

terraform/environments/nomis/baseline_presets.tf
terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/locals.tf
terraform/modules/baseline/sns.tf
terraform/modules/baseline/variables.tf
terraform/modules/baseline_presets/iam_policies.tf
terraform/modules/baseline_presets/outputs.tf
terraform/modules/baseline_presets/s3.tf
terraform/modules/baseline_presets/sns_topics.tf
terraform/modules/baseline_presets/variables.tf

Re-enable cloudwatch alarms via baseline:
- support email SNS topics for DBAs
- also some terraform fmt
Tested both email + pagerduty in nomis-test.  Although email is disabled for time being.

nomis: DSOS-1847: migrate sns part2

---

terraform/environments/data-platform/glue_script/glue_transform_script.py
terraform/environments/data-platform/lambda_for_data.tf
terraform/environments/data-platform/src/data_extractor/main.py

permissions were attached to the role for code extraction
Have also used this PR to fix minor issues with:
- the lambda and glue job script alignment with regard to s3 path names
- logging in the data lambda python code
- missing glue read permissions to data lambda role so it can get the job status

attach iam policy perms to data role

---

terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf

All weblogic servers have been rebuilt so we can get remove these remaining security references in preparation for deleting the old groups

nomis: DSOS-1847: remove references to old security groups

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_security_groups.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

More T1 migration prep:
- setup green deploying with combined reporting fix (new SHA for config management repo)
- added http 7777 support for T1 (since this is how it is accessed in Azure)
- setup auto redirect from http to https if port 80 used

Nomis: DSOS-1874: reporting fix

---

.github/CODEOWNERS

Related to this PR - https://github.com/ministryofjustice/modernisation-platform/pull/3759

Changing codeowners laa-ccms-devs to laa-ccms-webops

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/modules/baseline/sns.tf
terraform/modules/baseline_presets/sns_topics.tf

Add DBA alarms with associated pager duty integration.  Tested all variants.  Added high level docs in confluence.
- make use of the 3 new DBA pagerduty integrations (prod callout, prod, devtest)
- setup initial set of alarms for database.  I expect this will be tweaked a bit following further testing.
- added tags and encryption to SNS topics in baseline

Nomis: DSOS-1849: dba alarms

---

terraform/environments/laa-oem/member_certificates.tf

LAA-OEM: Shorter domain_name in aws_acm_certificate.

LAA-OEM: Shorter domain_name in aws_acm_certificate.

---

terraform/environments/data-platform/glue_job_spark.tf
terraform/environments/data-platform/route53.tf

Once merged, this zone will be delegated out via Cloud Platform https://github.com/ministryofjustice/cloud-platform-environments/pull/12907
Also, replacing `etag` with `source_hash` on `aws_s3_object.object`, see https://stackoverflow.com/a/68886287

Add Data Platform development Route 53 zone

---

terraform/environments/delius-iaps/application_variables.json
terraform/environments/delius-iaps/ec2-iaps-server.tf

access to port 1433 is removed as we don’t talk to MSSQL dbs directly
access to port 1521 is locked to VPC only

NIT-655 IAPS Security Group updates

---

terraform/environments/equip/application_variables.json

As part of https://github.com/ministryofjustice/modernisation-platform/issues/3339, this PR adds a common outbound access rule to all hosts, allowing them to send traffic to their 3rd party monitoring solution over the agent check-in port.

Allow Equip hosts to send traffic to 3rd party monitoring solution

---

terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/templates/post-ec2provision.sh.tftpl
terraform/environments/oasys/locals.tf
terraform/modules/baseline_presets/ec2_autoscaling_group.tf

Enable warm pools for NOMIS since weblogic takes forever to build
- add a number of different autoscaling configurations to baseline presets
- update oasys to use the default one 
- update nomis to use the warm pool one

nomis: DSOS-1893: enable warm pools

---

terraform/environments/mlra/alb.tf
terraform/environments/mlra/modules/alb/data.tf
terraform/environments/mlra/modules/alb/main.tf
terraform/environments/mlra/modules/alb/variables.tf

New code that replaces the existing functionality for the above resource types. The source of which was the module: https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/modules/acm_certificate

MLRA - New Terraform for Certificate, Route53 & Domain Name Validation Resources.

---

terraform/environments/nomis/locals_test.tf

name the asg to match the environments it's in

rename jumpserver asg to to test-jumpserver-2022 in nomis-test environment

---

terraform/environments/nomis/locals_test.tf

part of extending the monitoring to multiple sids on a given host
all the changes will be in re-applying the collectd role from modernisation-platform-configuration-management
this should be the only PR in this repo associated with this

add missing SIDs to t1-nomis-db-1-b

---

terraform/environments/digital-prison-reporting/main.tf
terraform/environments/digital-prison-reporting/modules/glue_registry/outputs.tf

* added new `dpr.contract.registryName` parameter to the DataHubJob so that the contract registry name can be passed to the job.

DPR-498 add contract registry name parameter to DataHubJob

---

terraform/environments/nomis/ec2_common.tf

Linux cloudwatch config is managed by ansible.
Moving the windows param into baseline.  Removing it here first.

nomis: DSOS-1918: removing unused SSM param

---

terraform/environments/nomis-combined-reporting/baseline.tf
terraform/environments/nomis-data-hub/main.tf
terraform/environments/nomis/main.tf
terraform/environments/oasys/main.tf
terraform/modules/baseline/iam_policies.tf
terraform/modules/baseline/route53.tf
terraform/modules/baseline/versions.tf

Mod platform have done their bit so we can merge this now
- add us-east-1 provider so we can create loggroup in correct place
- enable force_destroy on route53 zones to avoid dangling resources (i.e. what happened in oasys)
- automatically setup route53 query logging for all zones created via baseline

nomis: DSOS-1866: add route53 query logging

---

terraform/environments/data-platform/glue_script/glue_spark_transform_script.py
terraform/environments/data-platform/lambda_for_code.tf
terraform/environments/data-platform/lambda_for_data.tf
terraform/environments/data-platform/lambda_for_presigned_url.tf
terraform/environments/data-platform/src/presigned_url/main.py

* Presigned URL should now write to the `raw_data` directory
* The glue job has been changed to follow ISO datetime standards eg `20230609T133114Z` rather than with no T and Z as before eg `20230609133114`
* Added new trigger events for cloudwatch to cover multi part data and code uploads

Data platform 396 end to end data upload

---

terraform/environments/data-platform/lambda_for_athena_load.tf

lambda code for this function is to be contained within an ecr image.
It's triggered by the same event bridge notification as the spark glue job trigger lambda [lambda_for_data.tf](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/data-platform/lambda_for_data.tf) and performs the same task other than there is no transformation of data other than an extraction_timestamp being added to use as a partition
[#data-platform476](https://github.com/ministryofjustice/data-platform/issues/476)
Now not using the modernisation platform lambda module to a) be consistent with approach of other lambdas in data-platform env, and b) bypass the issue had with terraform plan caused by unknown arn until terraform apply in policy json.

infra for athena load lambda

---

terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

- switch lb rules to point at the newer nomis-web-a instances in nomis-test
- turn monitoring on for the nomis-web-a instances and OFF for the nomis-web-b instances

Nomis/dsos 1934/switch to new web a nomis test instances

---

terraform/modules/baseline_presets/s3.tf

If you want to upload to S3 from an EC2 instance, you need this permission. and probably Put as well (if using the ansible module)

nomis: DSOS-1935: allow GetObjectTagging permissions

---

terraform/environments/example/ec2.tf

This PR is part of the https://github.com/ministryofjustice/modernisation-platform/issues/3822 ticket.
This is to enable latency testing between CP nettest namespace and an EC2 in the MP example-development environment. 
Tested with the following:
```[nettest@nettest-57bb9b554-rz2zs /]$ ping 10.26.16.46
PING 10.26.16.46 (10.26.16.46) 56(84) bytes of data.
64 bytes from 10.26.16.46: icmp_seq=1 ttl=58 time=3.82 ms
64 bytes from 10.26.16.46: icmp_seq=2 ttl=58 time=2.11 ms
64 bytes from 10.26.16.46: icmp_seq=3 ttl=58 time=2.20 ms
64 bytes from 10.26.16.46: icmp_seq=4 ttl=58 time=2.21 ms
64 bytes from 10.26.16.46: icmp_seq=5 ttl=58 time=2.06 ms
64 bytes from 10.26.16.46: icmp_seq=6 ttl=58 time=2.15 ms
64 bytes from 10.26.16.46: icmp_seq=7 ttl=58 time=2.10 ms
64 bytes from 10.26.16.46: …
```

Enable ICMP from CP to example

---

terraform/environments/nomis/locals_database.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms_lists.tf

turn off mem_used_percent alarms as per [DSOS-1956](https://dsdmoj.atlassian.net/browse/DSOS-1956)
[DSOS-1956]: https://dsdmoj.atlassian.net/browse/DSOS-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

turn off high-memory-usage-15mins alarm ref: DSOS-1956

---

terraform/environments/nomis/locals_database.tf

Enable EC2 backups for databases in nomis-test.  Remove unused monitored tag.

nomis: enable EC2 backup for DBs in nomis-test

---

terraform/environments/nomis/locals_test.tf

For consistency with other T1 databases + since we are rebuilding the server

nomis: add t1 audit DB DNS entries

---

terraform/environments/data-platform/lambda_for_glue_metadata.tf
terraform/environments/data-platform/src/get_glue_metadata/main.py

Adds a simple Lambda function that retrieves a Glue catalog metadata via an API Gateway request.
The database and table are passed via the request body in this format:
```
{
"database": "<glue_database_name>",
"table": "<glue_table_name>"
}
```
For the moment the function retrieves all the available metadata from a specific table in a specific database. The funciton will need further refinement to suit our needs, this could be treated as an initial working POC.

add lambda function and api gateway to retrieve glue catalog metadata

---

terraform/environments/nomis/locals_security_groups.tf
terraform/environments/nomis/locals_test.tf

Create additional DNS records for users that are connecting directly to single database.
Allow other HMPPS accounts (both dev and test) access to T3 database.

nomis: T3 fixes

---

terraform/environments/nomis/locals_test.tf

To workaround T3 migration mistake

nomis: DSOS-1965: dns bodge

---

terraform/environments/nomis/locals_test.tf

Now that migration is complete, add missing cloudwatch alarms to T2 and T3 databases in nomis

enable alarms on T2 and T3 db instances in nomis-test

---

terraform/environments/data-platform/src/docs/swagger.json

The response is not yet documented as it currently returns all the available metadata, the format can be found [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue/client/get_table.html)
This will need to be refined to return only that metadata which is of interest to us.

add docs for the get_glue_metadata API endpoint

---

terraform/environments/data-platform/lambda_for_athena_load.tf

Assign bucket owner full control over query results by setting `acl_configuration` in athena `data_product_workgroup`
In accordance with policy set on the data bucket

add acl_configuration to workgroup

---

terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/templates/new-jumpserver-user-data.yaml

start building the jumpserver config on top of a blank windows server
- contains the java installer only so we can at least start testing the connectivity to t1/2/3 environments without having to guess what's broken

change the asg in nomis-development to test new jumpserver setup fixes

---

terraform/environments/nomis/locals_test.tf

this will add these missing oracle-sid values as tags to the relevant db instance
the tag is used by the 'oracle db connection check' metric which is created by re-running the monitoring ansible roles from the modernisation-platform-configuration-management repo at these targets

add missing oracle SIDS to t1, t2 configs for monitoring

---

terraform/environments/digital-prison-reporting/modules/compute_node/scripts/domain-builder.sh

* revised bootstrap to
* ensure ssm-user is able to write anywhere in their home directory
* write a domain-builder wrapper script into /usr/bin that also sets the api URL using the aws client to fetch the URL from the apigatewayv2 configuration

DPR-356 ensure ssm-user can write to their home directory and introduce domain builder launch script

---

terraform/environments/example/certificates.tf

After reviewing the Modernisation Platform DNS configuration, this should bring the certificate code in the example environment more into line with our intended uses.

Tidy up Example certificate code

---

terraform/environments/digital-prison-reporting/modules/compute_node/scripts/domain-builder.sh

* create the `ssm-user` with defaults if not already present
* use a hardcoded fallback until we can fetch the actual url from the api-gateway configuration

DPR-356 create ssm-user if required and default domain builder url

---

terraform/environments/hmpps-oem/locals_security_groups.tf
terraform/environments/nomis/locals_test.tf

Allow nomis DB to connect to OEM server.  Hardcoding IP for now as it's just a temporary test server sitting in an ASG

nomis: DSOS-1936: oem networking

---

terraform/environments/nomis/templates/new-jumpserver-user-data.yaml

- Set user-data script to fail on error
- Comment out Cloudwatch-Agent Config/Setup temporarily (let's fix one thing at a time!)
- Set IE Compatibility mode for sites
- Allow only certain domains under IE Enhanced Security Mode 
- Add desktop shortcuts for user to T1-T3
- If we can move this user-data/setup from ssm documents we might be able to add the shortcuts for the environment the jumpserver is deployed in

add IE Enhanced Security exceptions list to Jumpserver

---

terraform/environments/example/certificates.tf

Because the zone name in `core-vpc` for the platforms business unit exceeds 64 characters, the certificate domain name for `example` uses `modernisation-platform.service.gov.uk`.
Because the domain name is `modernisation-platform.service.gov.uk`, the provider for the validation records needs to be `aws.core-network-services`.
Because the domain name is `modernisation-platform.services.gov.uk` and the provider is `aws.core-network-services`, the route53 zone needs to be the `data.aws_route53_zone.network-services.zone_id`

Revert "Tidy up Example certificate code"

---

terraform/environments/nomis/templates/new-jumpserver-user-data.yaml

- comment aws cloudwatch agent setup back in
- add domains list to HKLM and HKCU Domains list (Trusted Domains)
- uses https values only as http is blocked entirely
Previously added these to EscDomains which are domains that ARE affected by IE ESC restrictions.

comment aws cloudwatch agent setup back in

---

terraform/environments/data-platform/s3.tf

passing the extra policy json to module rather than attaching here. This ensures our additional policies are appended to he default ones for the module.

fix policy for bucket

---

terraform/environments/digital-prison-reporting/main.tf

This change:
- enables autoscaling of the glue DPR jobs
- Sets the maximum number of workers to 4

DPR-586: Enable glue autoscaling and set max workers to 3

---

terraform/environments/nomis/locals_database.tf
terraform/modules/baseline/ec2_instance.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms_lists.tf

- set cpu alarm params to not trigger on db instances under normal load
- re-add memory alarm now that root cause is understood
- basically a miss-configuring the cloudwatch-agent log collector by using a wildcard for the log files is a bad idea!

address cpu alarm triggering on nomis-db instances and re-add mem alarm

---

terraform/environments/nomis/locals_test.tf

Following T2 DB failover.  Update DNS and SIDs.

nomis: DSOS-1938: update oracle SIDs and T2 DB DNS

---

terraform/environments/nomis/locals_test.tf

We've migrated to the shinier -a servers which have a number of fixes in. Get rid of the old servers.  For DB connection point of view, point both primary and standby DNS entries at the -a server.

nomis: DSOS-1938: remove old nomis DBs

---

terraform/environments/nomis/locals_test.tf

now that these are both live turn on alarms for these
will follow up by running the mod-platform-config-management roles to set up collectd and the cloudwatch-agent settings on all nomis-test instances after this

enable alarms for t2-nomis-db-1-a and t3-nomis-db-1

---

terraform/environments/digital-prison-reporting/main.tf

This change speeds up the DataHubJob by setting the `batchDurationSeconds` to 60 seconds.
Also, the Spark history logs is turned off for cost reasons.

DPR-586: Optimize DataHubJob

---

terraform/environments/long-term-storage/platform_versions.tf
terraform/environments/long-term-storage/remote-supervision.tf

The will hold the remaining remote supervision data and enable the closure of the remote supervision AWS account.

Create S3 bucket for remote supervision storage

---

terraform/environments/nomis/locals_security_groups.tf

Move to a 10/8 for https traffic to reduce number of SG rules.  This is what we allow on Azure and there's a whole bunch of IPs that we haven't included in the current rule set.

noms: DSOS-2001: reduce number of SG rules

---

terraform/environments/digital-prison-reporting/modules/compute_node/scripts/domain-builder.sh

* revised the domain-builder launch script on the ssm host to support batch and interactive modes
* if no args are passed to the script, interactive mode is assumed, otherwise any args are passed to the domain builder in batch mode
* also added in a TODO around the api key which also needs to be passed here - covered in later work

DPR-603 support domain-builder batch invocation on the ssm host

---

.github/workflows/reusable_terraform_plan_apply.yml

In line with the syntax [here](https://github.com/hashicorp/setup-terraform#:~:text=CLI%20configuration%20file.-,terraform_version,-%2D%20(optional)%20The%20version), this PR bumps the minimum version of Terraform used to `1.5.0`.
Teams can still override this in their workflows by supplying `"${{ inputs.terraform_version }}"`.

Raise default terraform version used by workflows

---

terraform/environments/nomis/ec2_common.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_test.tf

- creates rman backup failure and success metric filters on cwagent-var-log-messages log stream 
- alarm for failure
- alarm for success not within last 36 hours (backup is missing basically)
- runs off of logs in cloudwatch log stream to /var/log/messages in the each environment if rman_database_backups is defined in locals
- sns topics are not yet enabled for this but alarms will appear in the cloudwatch alarms list for each db in nomis-test

create per-environment alarm for rman backup failures

---

terraform/environments/nomis/ec2_common.tf

max period allowed is 24h so setting this alarm to that
if we need to look back further then we'll have to use a custom metric/log line in /var/log/messages for this instead

set period to 24h max allowed

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/main.tf
terraform/modules/baseline/backups.tf
terraform/modules/baseline/ec2_autoscaling_group.tf
terraform/modules/baseline/ec2_instance.tf
terraform/modules/baseline/outputs.tf
terraform/modules/baseline/variables.tf
terraform/modules/baseline_presets/backups.tf
terraform/modules/baseline_presets/outputs.tf
terraform/modules/baseline_presets/variables.tf

Add a custom backup policy as the default one is way more than we need.
- create new daily/weekly policy (daily backups kept for 7 days, weekly backups for 4 weeks) in line with Azure config via baseline
- remove existing mod platform backups (remove backup tag, rename is-production: true).  NB, there is a ticket raised with mod-platform to improve this.
- use new EC2/ASG modules which allows separate tagging on ec2 instance and ebs resources
- add new backup-plan tag to the databases EC2 instances only.  No need for separate backup of EBS resources, nor backup of anything that we have fully in code, i.e. ASGs.

Nomis: DSOS-1987: custom backup policies

---

terraform/environments/mojfin/rds.tf

Added the multi_az attribute to mojfin RDS instance, now that the apply_immediately setting has been set to 'false' (in previous change); so that this change is implemented during the next maintenance window (July 24, 2023 02:15 - 07:00 UTC+1 (next Monday morning)

LAWS-3328: enable multi-az in mojfin during next maintenance window

---

terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_xtag.tf

Get NDH EMS hostname from tag instead of hardcoded in ansible defaults.

nomis: DSOS-2000: xtag fix

---

terraform/environments/ccms-ebs/ccms-ec2-clamav.tf
terraform/environments/ccms-ebs/ccms-ec2-ftp.tf
terraform/environments/ccms-ebs/ccms-ec2-oracle_accessgate.tf
terraform/environments/ccms-ebs/ccms-ec2-oracle_ebs.tf
terraform/environments/ccms-ebs/ccms-ec2-oracle_ebs_apps.tf
terraform/environments/ccms-ebs/ccms-ec2-oracle_webgate.tf
terraform/environments/ccms-ebs/templates/ec2_user_data_accessgate.sh
terraform/environments/ccms-ebs/templates/ec2_user_data_clamav.sh
terraform/environments/ccms-ebs/templates/ec2_user_data_ebs.sh
terraform/environments/ccms-ebs/templates/ec2_user_data_ebs_apps.sh
terraform/environments/ccms-ebs/templates/ec2_user_data_ftp.sh
terraform/environments/ccms-ebs/templates/ec2_user_data_webgate.sh

CC-1993: Templated user_data.

---

terraform/environments/nomis/locals_xtag.tf

- puts nomis-xtag instances at the latest config management rep commit from yesterday
- includes collectd metrics for xtag services

fix typo & pull latest config-management user-data for xtag

---

terraform/environments/delius-iaps/cloudwatch-alarms.tf

When in alarm due to missing data, this could be an indication of the instance being down.

IAPS: CPU alarm treat missing data as in alarm.

---

terraform/environments/delius-jitbit/ssm.tf

to be pulled down by the jitbit app terraform and passed as an environment parameter to the ECS task

Jitbit: Store app url environment variable in SSM parameter 

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/locals_xtag.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf

- collectd metrics which were previously common, split by dimension, now have named metrics making things way easier
- weblogic-healthcheck alarm will appear per asg, not some vague collectd-exec-value alarm saying 'something broke'
- alarms will appear with their metric names in slack so they're way easier to react to
- nomis-db alarms are as previous but pending re-write of how the metrics are collected in DSOS-2092
- fixngo connection alarm also pending re-write of how this status is collected in DSOS-2093

alarm metric changes

---

terraform/environments/nomis/locals_production.tf

Using "c.nomis.service.justice.gov.uk" instead of "c.production.nomis.service.justice.gov.uk" for production endpoint to align with what's been configured on Mojo devices.

nomis: production DNS entry tweaks

---

terraform/environments/nomis/locals_production.tf

Shouldn't have deleted this in last PR.  It's temporarily needed for the CNAME from Azure.

nomis: prod DNS records attempt 2

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_test.tf

These are bigger instances and have the new nomis deployment role configured (rather than manual deployment on the -a servers).

DSOS-2108: switch to weblogic-b servers for T3 and preprod

---

terraform/environments/corporate-staff-rostering/locals_security_groups.tf
terraform/environments/corporate-staff-rostering/locals_test.tf
terraform/environments/corporate-staff-rostering/templates/app-server-user-data.yaml

- all AD related rules are in the `migration-app-sg` security group
- took a step out of the user-data script as this fails on Windows Server 2012 R2

Csr/dsos 2076/ingress rules

---

terraform/environments/hmpps-oem/locals_test.tf

This tag is required for an Ansible condition.

Add 'oracle-sids' tag to hmpps-oem-test auto-scaling group

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_test.tf

We've switched over to later version on T3 and preprod so removing these servers.

nomis: remove unused weblogic-a servers

---

terraform/environments/corporate-staff-rostering/locals_development.tf

server 2012 r2 ami seems to have issues with ssm launching properly
if it's an asg you can't actually reboot it without it failing
turn it into an ec2 instance so that it's easier to reboot

move test server to ec2 instance to debug ssm launch issues

---

terraform/environments/corporate-staff-rostering/locals_development.tf

can't duplicate the server name that the asg has

rename server instance

---

terraform/modules/baseline/variables.tf

Set alarm actions as an optional variable with default value of [].  Fixes an issue with attempting to iterate through a null list.

nomis: baseline code fix for alarm_actions

---

terraform/environments/corporate-staff-rostering/locals_development.tf
terraform/environments/corporate-staff-rostering/locals_security_groups.tf

137, 138 UDP and 139 TCP for NetBios
9389 TCP Active Directory Web Services
389 UDP for LDAP Server

add ports for AD inbound to security groups

---

terraform/environments/data-platform/lambda.tf

PR coming after this to reinstate the correct lambda policies, once the resources they depend on to form are created. The problem as far as I can tell was that the policies weren't passing their dependencies (eg the athena workgroup arn) to the lambda module (as the lambda module takes in raw json rather than terraform resource names in HCL where dependencies can be mapped), so the lambda module was trying to resolve a policy with an uncreated arn and failing

Deploy infra with policies not dependent on other resources

---

terraform/environments/corporate-staff-rostering/locals_security_groups.tf

applied to test and development already
- extended rdp rules to include fixngo jumpserver and rd gateway
- need to comment out ldap and netbios rules for now and apply to prod/pre-prod

add dev jumpservers to rdp port allow range, fix ldap and netbios rules

---

terraform/environments/nomis/locals_development.tf
terraform/modules/baseline/ec2_autoscaling_group.tf
terraform/modules/baseline/ec2_instance.tf
terraform/modules/baseline/outputs.tf
terraform/modules/baseline/variables.tf

Updated baseline module to allow placeholder SSM parameters in EC2/ASG module.  Part of the SSM param simplification requested by DBAs.  Also prep for applying KMS Key ID for all params but will do this in subsequent PR.  Also added missing output for SecretsManager.
This will trigger a plan change in all EC2/ASG policies as I rename a policy from  "ASM" to "SSM".  But is not impacting anything

DSOS-2124: allow placeholder ssm params

---

terraform/modules/baseline/backups.tf
terraform/modules/baseline/bastion_linux.tf
terraform/modules/baseline/ec2_autoscaling_group.tf
terraform/modules/baseline/ec2_instance.tf
terraform/modules/baseline/lb.tf
terraform/modules/baseline/route53.tf
terraform/modules/baseline/s3_bucket.tf
terraform/modules/baseline/secretsmanager.tf
terraform/modules/baseline/ssm.tf
terraform/modules/baseline/variables.tf
terraform/modules/baseline/versions.tf

Best practice - use customer managed KMS Key for encrypted SSM params.
Setting default key to the "general" business unit key.  This won't touch the value of existing parameters (I have double-checked this)
Plus fixed some checkov/lint warnings

DSOS-2011: use business unit kms keys for ssm params

---

terraform/environments/data-platform/infra_route53.tf

I forgot this in the original migration 😬

❇️ Add Data Platform documentation CNAME

---

terraform/environments/corporate-staff-rostering/templates/ansible-ec2provision.sh.tftpl
terraform/environments/hmpps-domain-services/templates/ansible-ec2provision.sh.tftpl
terraform/environments/hmpps-oem/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis-combined-reporting/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis-data-hub/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/templates/ansible-ec2provision.sh.tftpl
terraform/environments/oasys/templates/ansible-ec2provision.sh.tftpl
terraform/environments/planetfm/templates/ansible-ec2provision.sh.tftpl

Pass in ec2_name, application and aws_environment as extra variables in the ansible user-data script.  This corresponds to changes made to dynamic inventory in the config management repo.
Note I've aligned the oasys script with all the other applications because I'm lazy.  But there shouldn't be any material difference now as the AMIs are in a good place and there's no need to install python/aws cli.

DSOS-2090: pass in additional ansible vars in user-data

---

terraform/environments/data-and-insights-wepi/network.tf
terraform/environments/data-and-insights-wepi/redshift.tf

Attempting to associate a security group with the load balancer and allow connection via redshift security group.

Network Load Balancer Security Group

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/main.tf
terraform/environments/hmpps-domain-services/locals.tf
terraform/environments/hmpps-domain-services/main.tf
terraform/environments/hmpps-oem/locals.tf
terraform/environments/hmpps-oem/main.tf
terraform/environments/nomis-combined-reporting/locals.tf
terraform/environments/nomis-combined-reporting/main.tf
terraform/environments/nomis-data-hub/locals.tf
terraform/environments/nomis-data-hub/main.tf
terraform/environments/nomis/ec2_common.tf
terraform/environments/nomis/locals.tf
terraform/environments/nomis/main.tf
terraform/environments/oasys/main.tf
terraform/environments/planetfm/locals.tf
terraform/environments/planetfm/main.tf
terraform/modules/baseline_presets/README.md
terraform/modules/baseline_presets/key_pairs.tf
terraform/modules/baseline_presets/outputs.tf
terraform/modules/baseline_presets/ssm.tf
terraform/modules/baseline_presets/variables.tf

First of several PRs improving secret management.
This ensures ec2-user_pem and cloud watch agent windows SSM parameters are in code.  The former is just a placeholder which is updated outside of terraform.
For nomis, I'm removing the CI/CD secret and associated SSM doc since there is a new solution from mod platform that we need to migrate to

DSOS-2189: Add ec2-user and cloud-watch-agent-windows ssm params

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

This re-adds the config that was removed in #3427.

re-add initial config for pre-pd web server 7

---

terraform/environments/hmpps-oem/locals.tf
terraform/modules/baseline_presets/ec2_instance.tf
terraform/modules/baseline_presets/iam_policies.tf
terraform/modules/baseline_presets/variables.tf

The default policy allows any EC2 to access any SSM param.  Given that we are storing passwords in SSM params this is a bit excessive.  Create a reduced policy for testing in hmpps-oem account

DSOS-2190: Add option to use reduced scope for SSM params

---

terraform/environments/corporate-staff-rostering/locals_development.tf
terraform/environments/corporate-staff-rostering/locals_test.tf
terraform/environments/hmpps-oem/locals.tf
terraform/environments/hmpps-oem/locals_oem.tf
terraform/environments/hmpps-oem/locals_test.tf
terraform/environments/nomis-combined-reporting/locals_database.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/oasys/locals.tf
terraform/modules/baseline_presets/ec2_instance.tf
terraform/modules/baseline_presets/iam_roles.tf

Simplify SSM params:
- Replace individual user/password parameters with a single password parameter which will be JSON and managed by ansible. This way, DBAs can rotate passwords, add new users etc without touching terraform.
- Moved all EC2 scoped parameters under /ec2 prefix.  All shared /oracle stuff under /oracle.
I'll update the parameters as necessary after terraform runs.

DSOS-2151: asm password new code

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/modules/baseline_presets/s3.tf

Add policy to database backups to enable read-only access from paired accounts (e.g. dev and test, preprod and prod)
Add policy to allow preprod EC2 databases to access production backups
Add policy for all other databases to scope access to environment specific SSM parameters
Comment out the new DR databases as accidentally created in wrong availability zone (sorry, should be a separate PR really but noticed it was wrong when doing this)

Nomis: DSOS-2205: policies for DB SSM params

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_jumpserver.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_weblogic.tf

Restore is-production flag back to true now that Mod Platform have updated their code.
Set backup tag to false to prevent automated mod platform backup and use our own instead

DSOS-2195: fix backup tags

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf
terraform/environments/corporate-staff-rostering/locals_test.tf
terraform/environments/hmpps-oem/locals_oem.tf
terraform/environments/nomis-combined-reporting/locals.tf
terraform/environments/nomis-combined-reporting/locals_bip.tf
terraform/environments/nomis-data-hub/locals_test.tf
terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/main.tf
terraform/environments/planetfm/locals.tf

Align backups across DSO accounts:
- enable daily backup (7 day retention) + weekly backup (4 week retention) plan
- opt out of mod platform plan (30 day backup + backs up EBS volumes twice)
Enable backup on EC2 instances across our estate
- CSR migrated servers
- Combined Reporting standalone EC2 instances
- NDH test EC2 instances
- OASys databases and BIP

DSOS-2195: update backup plans

---

terraform/environments/performance-hub/database.tf

Unfortunately we need the app running for overnight jobs (automated data imports, de-activating unused user accounts ...)
EC2 is part of an ASG, so no tag needed

Disable RDS instance scheduling for overnight jobs to run

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

didn't include the $ for the ouPath variable in the if ( )

fix ouPath syntax error

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

- handles the fact that there's no default OU for azure.noms.root domain
- splat Add-Computer parameters so 'optional' ones aren't buried in if statements
- add optional 'restart' parameter, defaults to true

splat arguments for Add-Computer to aid readability

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/lambda.tf

This brings the register data-product endpoint in line with [our API specs](https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4511991882/Initial+APIs)

Add data-product endpoint and rename data product register components

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

- add and move do not seem to be allowed in the same operation on our hmpp DC
- remove OUPath option from code for now, returns SSM Document to a working state
- removed the -NOT logic from conditionals as it's hard to read

remove oupath option

---

terraform/environments/digital-prison-reporting/application_variables.json

During the release, the initial job run took over a day before it was manually terminated. The performance degradation is due to the incremental domain refresh trying to load records and apply them to the domain. This was made worse because the CDC events were processed before the load events were completed thereby creating multiple errors.
This PR increases the number of workers to 6 thereby decreasing the run duration to 11 hours (down from over 2 days).

DPR2-146: Increase max workers in prod

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

- rename included as prior step, doesn't require a restart
- add-computer uses rename value if it's been changed, without needing a prior restart

rework rename computer code

---

terraform/environments/nomis/locals_preproduction.tf

This should allow s3 sync to work with the backup bucket in prod account.

DSOS-2198: nomis: fix s3 permission so aws s3 sync works

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

- rename and reboot if newName != $env:COMPUTERNAME
- if/when this has changed, run Add-Computer

add rename-computer and reboot

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

Create additional SSM parameter for MIS load configuration
Temporarily drop monitoring from new nomis DBs until they are fully configured

nomis: add misload ssm param

---

terraform/environments/data-platform/infra_route53.tf

data-platform.service.justice.gov.uk points to GitHub Pages

🌐 Add Data Platform front door CNAME

---

terraform/environments/nomis/iam.tf

specify the resource by the full arn and not the key_id

DSOS-2209: use arn not key_id

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_security_groups.tf
terraform/modules/ip_addresses/azure_fixngo.tf

- web, app, domain, load-balancer, database, jumpserver security groups
- imported (many) cidr ranges to help access fixngo more cleanly
- tidied up new security groups so they work outside of dev/test environment

Csr/dsos 2175/security groups

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/lambda.tf

This PR seeks to do the following:
Defines "/data-product/{data-product-name}"
Defines "/data-product/{data-product-name}/table"
Defines "/data-product/{data-product-name}/table/{table-name}"
Defines "/data-product/{data-product-name}/table/{table-name}/upload"
Removes /upload_data"
Defines "/data-product/{data-product-name}/table/{table-name}/upload" POST and makes {data-product-name} & {table-name} path variables available.
Removes "upload_data" and removes former querystring parameters.
Defines "/data-product/{data-product-name}/table/{table-name}/upload" POST
Removes "upload_data_to_lambda"

:sparkles: Create upload for data product components

---

terraform/environments/planetfm/locals.tf
terraform/environments/planetfm/locals_development.tf
terraform/environments/planetfm/locals_security_groups.tf

- loadbalancer, web, app, domain and jumpserver sg's ready for new instances
- further work will be needed once we add 'external access' but this is a good enough initial framework
- remove duplicate/un-used data-db SG before it's attached to things in anger

Pfm/dsos 2216/security groups

---

terraform/modules/baseline_presets/s3.tf

We've got lifecycle rules to put stuff into glacier storage but no permissions to restore.  Adding restore permissions to anything that has write access.

DSOS-2241: Add restore object permissions to S3 policies

---

terraform/environments/nomis/locals.tf

Reduce scope of EC2 SSM access.  Previously EC2s could access all secrets, now they can only access secrets that they need.

DSOS-2190: Reduce EC2 SSM permissions

---

terraform/environments/delius-core/modules/environment_all_components/db_ec2.tf
terraform/environments/delius-core/modules/environment_all_components/db_iam.tf
terraform/environments/delius-core/modules/environment_all_components/db_s3.tf

- Added IAM policy document that was previously created manually to test permissions
- Added SG to EC2 DB to allow inbound traffic from ECS frontend service on Oracle port

Nit 858 Connection with EC2 based DB 

---

terraform/environments/data-platform/iam-roles.tf

Allows us to build a policy in the Data Platform Apps and Tools account without looking up the role in Data Platform first because it currently is suffixed with a random string

♻️ Remove random suffix from Open Metadata target role

---

terraform/environments/delius-core/modules/environment_all_components/db_ec2.tf

delius-core-dev/JDBC_URL in parameter store has been updated to point to EC2 based Oracle DB R53 DNS record. Frontend app is coming up fine without any errors

Nit 890 delius db create dns record

---

.gitattributes
terraform/environments/nomis/templates/jumpserver-user-data.yaml.tftpl

To prevent accidental shutdown
https://dsdmoj.atlassian.net/browse/DSOS-2143
.gitattributes config was added to attempt to force github to display this particular file as a YAML file - this is to make it more readable as currently when viewing the file on github it is being viewed as text with no syntax highlighting.

Hide shutdown / restart buttons in start menu

---

terraform/environments/corporate-staff-rostering/ec2_common.tf

re-adding the resource to build the ssm doc for ami builds
checked doc manually in AWS CSR Dev account and it deploys

re-adding the ssm doc resource

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/application_variables.auto.tfvars.json
terraform/environments/data-platform/iam.tf
terraform/environments/data-platform/lambda.tf
terraform/environments/data-platform/locals.tf
terraform/environments/data-platform/variables.tf

https://github.com/ministryofjustice/data-platform/issues/1657
This deploys the changes from
https://github.com/ministryofjustice/data-platform/pull/2020
and https://github.com/ministryofjustice/data-platform/pull/2079

Roll out update metadata API and new version of create_schema

---

terraform/environments/corporate-staff-rostering/locals_test.tf

- remove the T3 db instance, has been confirmed by the app-owner that all this data can be deleted
- it's been un-used since 2017 
- remove r53 rule for the T3 db instance
- remove asg's as they're now old/irrelevant
- kept s3 buckets for now

remove ec2 test instances

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/iam.tf

This is taken from @LavMatt's draft PR https://github.com/ministryofjustice/modernisation-platform-environments/pull/3481/commits/cd40e9d471a0d8eb8d98901c25a07e977033ffa7
I took out the x-ray part as I don't think we need that at the moment (can always add it back later)
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html
This adds access logs under the `data_platform_api` group and execution logs available under the `API-Gateway-Execution-Logs_hsolkci589/development` group. The former is a group managed by us, so we can change the name if anyone has a better suggestion. The latter is managed by AWS, we've just enabled it for all requests.
Example access logs:
```
2023-10-27T14:40:57.744+01:00
{
"caller": "-",
"ip": "51.14.4.225",
"method": "POST",
"path": …
```

Add API gateway logging to cloudwatch

---

terraform/modules/baseline/route53.tf

Spotted this when preparing to move nomis zone. NS records not set correctly when using ns_records option.  Only affects nomis.

DSOS-2194: fix bug when NS records automatically added from parent zone

---

terraform/environments/data-platform/api.tf

To enable logging to cloudwatch in API gateway, a role needs to be set on the API gateway account resource.
It seems like terraform gets confused the first time this is run, as it tries to apply default_stage before the role is set on the account.
Hopefully adding this depends_on will prevent this from recurring in the future.

Add explicit depends on

---

terraform/environments/planetfm/locals_preproduction.tf
terraform/environments/planetfm/locals_web.tf

- create web_locals.tf for common planetfm web instance config
- existing web instance in preproduction seems to want to redeploy based on newer ami version

create common config for planetfm web instances

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

load balancer seems to be working at first glance.  Update the R3 preprod DNS entry so it can be properly tested.

csr: DSOS-2327: update R3 preprod DNS entry

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- add pp-csr-w-2-b as webserver for r4
- awaiting config of this and pp-csr-a-14-b
- test with http://r3.pp.csr.service.justice.gov.uk/isps/index.html?2057 from prod-jumpserver(s) to ensure LB works

add r4 instance as pp-csr-w-2-b to LB

---

terraform/modules/baseline/lb.tf

Ticket: https://dsdmoj.atlassian.net/browse/DSOS-2309
Latest lb module = https://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer/releases/tag/v3.3.0

DSOS-2309 | Reference latest load balancer module

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/application_variables.auto.tfvars.json
terraform/environments/data-platform/iam.tf
terraform/environments/data-platform/lambda.tf
terraform/environments/data-platform/locals.tf
terraform/environments/data-platform/variables.tf

adds api gateway infra for the PUT method for `/data-product/{data-product-name}/table/{table-name}/schema` which is used to update a table schema
Also adds lambda function to be invoked and variables for image.
Also updated docs version.

infra and vars for update schema endpoint

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/application_variables.auto.tfvars.json
terraform/environments/data-platform/iam.tf
terraform/environments/data-platform/lambda.tf
terraform/environments/data-platform/locals.tf
terraform/environments/data-platform/variables.tf

As a user, I want to confirm the successful creation of my data product. This feature eliminates the need for users to possess AWS accounts or tools in order to access and view the data.
This will create infrastructure for query api

Dp 1843 query apiendpoint

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- add pre-prod web rules to LB for latest servers
- training instances for pre-prod are not included yet
- extends @GlennBarber handy diagram so should be correct! Suggest referring to this when reviewing

add all pre-prod web instance rules to LB

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/application_variables.auto.tfvars.json
terraform/environments/data-platform/lambda.tf
terraform/environments/data-platform/secrets.tf

Adds a place in secrets manager to store openemetadata jwt to use for api auth.
Also fixes an error that crept through with preview api integration and renames a lambda and ecr repo for it

Dpl add openmetadata token secret

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

Configure the existing Azure domain for R3 Preprod csrppr3.az.justice.gov.uk on the AWS load balancer.  This will allow us to temporarily use this URL for testing R3 preprod on a Mojo device.

CSR: allow azure csrpp3 azure hostname through the load balancer

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf

- traina and trainb pp.csr.service.justice.gov.uk load balancer entries
- traina and trainb .csr.service.justice.gov.uk redirect to pre-prod loadbalancer

add traina and trainb to loadbalancer in preprod plus prod redirect

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

Simplified and fixed S3 permissions.  Allows preprod servers read access to the prod audit S3 bucket.
Only test and production need bucket policies set to allow sharing into development/preproduction respectively.  Otherwise default permissions are good enough.

DSOS-2358: correct S3 permissions for audit and backup

---

terraform/environments/data-platform/application_variables.auto.tfvars.json
terraform/environments/data-platform/iam.tf
terraform/environments/data-platform/lambda.tf
terraform/environments/data-platform/locals.tf
terraform/environments/data-platform/secrets.tf
terraform/environments/data-platform/variables.tf

This PR adds a new lambda container function that is triggered by the create/update metadata/schema lambdas. It has permissions to get the secret api token from secrets manager in a new policy
Removed secret versions as we'll be manually rotating secrets for openmetadata.
Added two env vars to locals for openmetadata:
`OPENMETADTA_JWT_SECRET_ARN` the arn of the secret in secrets manager holding the jwt
`OPENMETADATA_DEV_API_URL` the url for api calls to our dev openmetadata

Data Platform - new lambda infra for push-to-catalogue

---

terraform/environments/apex/application_variables.json
terraform/environments/apex/ecs.tf
terraform/environments/apex/locals.tf
terraform/environments/apex/modules/codebuild/main.tf
terraform/environments/apex/modules/ecs/README.md
terraform/environments/apex/modules/ecs/main.tf
terraform/environments/apex/modules/ecs/outputs.tf
terraform/environments/apex/modules/ecs/variables.tf
terraform/environments/apex/modules/ecs/versions.tf
terraform/environments/apex/task_definition.json
terraform/environments/apex/user_data.sh

JIRA ticket: https://dsdmoj.atlassian.net/browse/LAWS-3487

Setting up Apex ECS resources 

---

terraform/environments/data-platform/cloudtrail.tf
terraform/environments/data-platform/iam.tf

These PutObject events are quite useful as they tell us when an upload has reached each "zone" (landing -> raw -> curated)
The events are currently queryable via athena but not via cloudwatch.
If the data is available in cloudwatch I'll be able to visualise them in grafana.
(https://github.com/ministryofjustice/data-platform/issues/2016)

Send cloudtrail events to cloudwatch

---

terraform/environments/oasys/locals_test.tf

Update naming for consistency, this is part of the T2 environment so should be named as such.

oasys: rename test BIP ASG to t2

---

terraform/environments/data-platform/application_variables.auto.tfvars.json
terraform/environments/data-platform/tests/run_smoke_tests.py

The previous approach of deleting the glue table didn't work becuase it left the files in s3, and in this scenario, athena load thinks there is something wrong, and we need to reload the data product.
Ideally, the test should register the data product itself and delete everything when done, so that this won't get stuck in a broken state again if something goes wrong with a previous test run.
However, I found that the delete data product endpoint is a bit unreliable at the moment, so we can't include this at the moment. I've left this commented out for now so we can enable it later.
1. If the glue table is missing, delete data product doesn't work. This happened before because the tests used to delete the glue table itself, but it could happen again if we manually delete glue tables for …

Fix smoketest

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

Temporarily remove alarms.  Need to re-run ansible on the servers which will change some of the metrics slightly.  Will re-add them back in after this.
Also remove unused preprod audit DB which has been moved into preproduction account

DSOS-2359: temporarily remove alarms

---

terraform/environments/data-platform/application_variables.auto.tfvars.json
terraform/environments/data-platform/tests/run_smoke_tests.py

This updates all the lambdas to pick up recent changes to the base image, including logging changes and renaming glue databases to include version numbers.
As a side effect of this, we can no longer look up the glue table in the smoketest, so I've replaced it with a call to the preview endpoint.

Update all the things

---

terraform/modules/baseline_presets/s3.tf

Add additional permission required for Oracle Secure Backup to our default policies.
Remove the DeleteObjectVersion permission from DevTest role. This should not be included for security reasons.

Nomis: DSOS-2358: oracle secure backup fix

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

Create a network load balancer for preprod 5 and 6.  Note 100% sure if the HTTP healthchecks will work, only one way of finding out.

csr: DSOS-2387: network LB test for preprod 5 and 6

---

terraform/environments/planetfm/locals_security_groups.tf

- add TCP access to db security group for SQL on port 1433, mimics what's in Azure
- add UDP access to db security group for SQL on port 1434, mimics what's in Azure
- add cafm licensing port access for TCP 7071 and 7073 for db security group, mimics what's in Azure
- temporarily delete RDP access to db instances
-  these rules will be put back in a subsequent PR with the correct name

add missing sql db access from enduser client cidr

---

.github/workflows/reusable_terraform_plan_apply.yml
scripts/terraform-plan-evaluator.sh

Fixes https://github.com/ministryofjustice/modernisation-platform-environments/pull/4048

🚑 Exclude `read` from plan evaluator

---

terraform/environments/corporate-staff-rostering/locals_database.tf
terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- NLB r34 added
- in use for r3.pp.csr.service.justice.gov.uk and r4.pp.csr.service.justice.gov.uk
- equates to EC2 instances pp-csr-w-5-a and pp-csr-w-6-b
- requires separate IIS config changes that aren't in code

change r3 and r4 targets to use NLB r34 instead

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf
terraform/environments/nomis-combined-reporting/locals.tf
terraform/environments/nomis-combined-reporting/locals_development.tf
terraform/environments/nomis-combined-reporting/locals_preproduction.tf
terraform/environments/nomis-combined-reporting/locals_production.tf
terraform/environments/nomis-combined-reporting/locals_test.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/oasys/locals_preproduction.tf

Changes to support cross-account DB refresh, e.g. preprod refresh from backup in production account
- Add S3 bucket policy to allow prod DB backup S3 buckets to be accessed read-only from preprod, and test S3 buckets to be accessed read-only from Dev
- Add required IAM policy to preprod DBs

DSOS-2358: permission changes to DB backup buckets for cross-account access

---

terraform/environments/corporate-staff-rostering/locals_test.tf

Looks like there is a DB backup in CSR test even though rest of the account is empty.  Restore the bucket for the time being.

DSOS-2358: restore csr db-backup bucket

---

terraform/environments/oasys/locals_test.tf

oasys db skip instance scheduling
need the db up before web and bip, no time control in instance-scheduling so need db up all the time

oasys db skip instance scheduling

---

terraform/environments/nomis/locals_development.tf
terraform/environments/oasys/locals_development.tf

Comment out DBs in nomis and oasys development accounts as they are not currently used. There's likely to be a requirement in future hence why they are commented out and not deleted.

DSOS-2359: remove unused dbs

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/locals_xtag.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf

Re-enable nomis cloudwatch alarms based on the new style collectd metrics.  Make more use of dimensions so no need to have a separate alarm configured for each service or database.

DSOS-2359: re-enable nomis cloudwatch alarms

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- return c-s-r-preprod apply to a 'good' state by removing apply NLB access_logs feature which doesn't work

remove lb logs collection

---

terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

Following discussion with Sandhya, increased memory alarm threshold for DR DB to >= 99%.  The current level is OK while it is in DR mode

Nomis: DSOS-2359: alarm fix v2

---

terraform/environments/data-platform/cloudtrail.tf

We want to have a record of all writes into our s3 buckets. This allows us to monitor flow of data through the conformance zones.
Currently we log PutObject, but in the landing-to-raw lambda we copy files from landing to the data bucket, using a raw/ or fail/ prefix. This goes via boto's copy method, rather than put_object. It will use either the copy api or the multipart upload api.
So in order to get raw and fail events logged, we need to include the corresponding events.
[This explains why both figures are missing recent data in the grafana dashboard.](https://g-e937f84aea.grafana-workspace.eu-west-2.amazonaws.com/d/H-9kBpVSk/ingestion-overview?orgId=1)
However, it doesn't explain why cloudwatch returns a count of 330 for both when the time span is set to the last year.

Include object copies in our custom cloudtrail for s3

---

terraform/environments/delius-core/modules/environment_all_components/db_s3.tf

During this phase of development we only have access to the delius-mis-dev legacy account backups.

Access is only to the Dev backups for now

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- add r12 network load-balancer
- add trainab network load-balancer
- add missing cross-zone redirect allow setting to r34
- change r34 healthcheck settings
the next PR will re-assign servers to the 2 new nlb's
the final PR will delete the existing 'private' LB

Csr/dsos 2388/add missing pre prod nlb settings

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_test.tf

CPU can peak for long time on DB restore.  Extend threshold. Plus terraform fmt

Nomis: tweak alarm thresholds

---

terraform/environments/mlra/modules/codebuild/main.tf
terraform/environments/mlra/modules/ecs/main.tf

I've updated the terraform file for MLRA to include the metrics_granularity property which should switch on the autoscale group metrics

Added ASG metrics collection to MLRA terraform

---

terraform/modules/baseline/outputs.tf
terraform/modules/baseline/secretsmanager.tf
terraform/modules/baseline/variables.tf

Revert secrets recovery_window_in_days back to 30 days (default) to ensure secrets are not accidentally deleted.
For placeholder secrets (those whose values are managed outside of terraform), don't both creating a secret_version.  This keeps things consistent with EC2 instance and ASG modules.  I've tested this in nomis to make sure we are not losing any secret values

DSOS-2406: tweak baseline secrets

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml
terraform/environments/hmpps-domain-services/ssm-documents/windows-domain-join.yaml
terraform/environments/planetfm/ssm-documents/windows-domain-join.yaml

The SSM document cannot handle taking in password with quotes

Updated description for domain join ssm document password requirement

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf
terraform/environments/nomis-combined-reporting/locals_test.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/scripts/get-secretsmanager-secrets.sh
terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_test.tf

Add permissions to access secrets across nomis, oasys, CSR and NCR

DSOS-2406: update policies to use secrets instead of ssm

---

terraform/environments/planetfm/locals_preproduction.tf

- webx ALB for planetfm web portal servers
- listens on Port 443 and redirects to 80
- certificate sits on the ALB

Planetfm/dsos 2398/preprod lb

---

terraform/environments/planetfm/locals_preproduction.tf

- certificate_names_or_arns is the only var defined in baseline, not certificate_arn_lookup

change variable to look up cert name

---

terraform/environments/observability-platform/managed-grafana.tf

- Enables Enterprise functionality in Grafana
- Enables Grafana Unified Alerting
- Removes `data-platform-labs` from Editor permissions
EDIT 2:
AWS Marketplace _things_ don't play nicely with IaC, so we've (@ASTRobinson and @dms1981 thanks ❤️) clickopsed the licenses in the console. Development has gone in fine, but Production might need importing.
EDIT:
Currently blocked...
```
╷
│ Error: creating Grafana License Association: AccessDeniedException: Access denied when trying to get marketplace agreements
│ 
│   with module.managed_grafana.aws_grafana_license_association.this[0],
│   on .terraform/modules/managed_grafana/main.tf line 378, in resource "aws_grafana_license_association" "this":
│  378: resource "aws_grafana_license_association" "this" {
│ 
╵
```
```json
{ …
```

🔎 Upgrade Observability Platform AMG

---

terraform/environments/planetfm/locals_security_groups.tf

- add port 80 in allow for web instances
- comment out 443 traffic allow

allow port 80 from loadbalancer for web instances

---

terraform/environments/ccms-ebs-upgrade/application_variables.json
terraform/environments/ccms-ebs-upgrade/ec2-oracle_ebs_db.tf

Added a swap volume to EBS DB in the Upgrade environment.

CC-2254: Added a swap volume to EBS DB in the Upgrade environment.

---

terraform/environments/nomis-data-hub/locals.tf
terraform/environments/nomis-data-hub/locals_test.tf
terraform/environments/nomis-data-hub/main.tf

Add NDH secrets for future T1, T2 setup plus existing test.
Added ndh-environment tag to EC2s.  To be used in ansible.

ndh: DSOS-2421: add secrets

---

terraform/environments/cdpt-chaps/ecs.tf
terraform/environments/cdpt-chaps/loadbalancer.tf

Also extends acceptable status codes for healthcheck

Add ECS logging

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_weblogic.tf

Add preprod-nomis-db-1-a in prep for moving preprod DBs
Updated weblogic healthchecks to speed up time of detecting unhealthy hosts from 2mins 30 to under 30 seconds

Nomis: preprod db build

---

terraform/environments/nomis/locals_test.tf

Up the memory alarm threshold for T1 weblogic.  The environment isn't used much and is still performing OK despite occasionally exceeding 95% memory usage.

tweak alarm threshold for t1 weblogic

---

terraform/environments/nomis/locals_preproduction.tf

DB is now migrated, add first batch of alarms.

DSOS-2466: add monitoring for preprod-nomis-db-1-a

---

terraform/environments/data-platform-apps-and-tools/cloudwatch-log-groups.tf
terraform/environments/data-platform-apps-and-tools/observability-platform.tf

- Bumps `terraform-aws-modules/cloudwatch/aws` to `~> 5.0`
- Bumps `ministryofjustice/observability-platform-tenant/aws` to `0.1.0`

📌 Bump module versions

---

terraform/environments/corporate-staff-rostering/templates/ansible-ec2provision.sh.tftpl
terraform/environments/hmpps-domain-services/templates/ansible-ec2provision.sh.tftpl
terraform/environments/hmpps-oem/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis-combined-reporting/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis-data-hub/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis/templates/ansible-ec2provision.sh.tftpl
terraform/environments/oasys/templates/ansible-ec2provision.sh.tftpl
terraform/environments/planetfm/templates/ansible-ec2provision.sh.tftpl

Request from Delius DBAs. Use application tag rather than environment-name. Not sure why I didn't do this in the first place but I've tested this and works fine. The application tag is defined across all resources, and in some cases, like delius, cannot be derived from the environment-name.
Update this across all DSO ansible user-data scripts to keep in step with ansible repo. Tested in nomis and seems to work fine.

DSO apps: update ansible script to use application tag

---

terraform/environments/data-platform-apps-and-tools/rds.tf

This pull request adds `apply_method = "pending-reboot"` (the default) to `rds.force_ssl` to fix the perpetual diff we were seeing

🚑 Fix RDS perpetual update

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/main.tf

Misload metrics are being populated correctly and it ran successfully yesterday.  Adding in the corresponding alarms.
Also made sure preprod account doesn't alert to the Sheffield High Priority pagerduty service

nomis: DSOS-2466: add misload alarms for preprod-nomis-db-2-a

---

terraform/environments/nomis/locals_preproduction.tf

HA DB now commissioned on preprod-nomis-db-1-b, updating DNS entries to reflect this.

nomis: Update DNS entry for Preprod HA DB

---

terraform/environments/nomis/locals_test.tf

The EC2 size is at the limit for T2 but should still be OK - increase alarm threshold for memory so it only alarms when totally maxed out

Increase T2 nomis weblogic memory alarm threshold

---

terraform/environments/hmpps-oem/locals_oem.tf

I think the oasys role was briefly deleted and this is now causing some problems with the terraform.  Temporarily removing oasys from the policy. Will re-add in a subsequent PR.

DSOS: hmpps-oem: fix issue with Oasys principal in secrets policy

---

terraform/environments/hmpps-domain-services/locals.tf
terraform/environments/hmpps-domain-services/locals_security_groups.tf
terraform/environments/hmpps-domain-services/locals_test.tf
terraform/modules/baseline/variables.tf

Miscellaneous fixes to support remote desktop in hmpps-domain-services account:
- Created a public load balancer and revamped the associated security groups
- Created 3 standalone EC2 instances for RDS testing
- Fixed the target groups and DNS entries for the load balancer

DSOS-2476: RemoteDesktop spike

---

terraform/environments/planetfm/locals_preproduction.tf
terraform/modules/baseline/s3_bucket.tf

- remove un-needed coalesce from s3_bucket module ref in baseline
- uncovered as part of the loadbalancer module changes

remove un-needed coalesce from s3 module in baseline

---

terraform/environments/planetfm/locals_preproduction.tf

this resource defaults to 'application' load balancer type but that's why this typo wasn't picked up earlier

load_balancer_type variable spelt incorrectly

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_test.tf

Following discussion with DBAs, re-configure XTAG as a standalone EC2. 
I've applied in nomis-test already and it works and is resilient to reboots.

Nomis: DSOS-2467: move xtag from ASG to instance

---

terraform/environments/nomis/locals_test.tf
terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_development.tf
terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_production.tf
terraform/environments/oasys/locals_test.tf
terraform/environments/oasys/main.tf
terraform/modules/baseline_presets/iam_roles.tf
terraform/modules/baseline_presets/variables.tf

- Option to enable observability platform monitoring
- IAM role to be created for observability-platform created in baseline_presets module (has to be named specifically as per [https://registry.terraform.io/modules/ministryofjustice/observability-platform-tenant/aws/latest?tab=inputs]
- nomis-test and oasys-test to enable observability platform monitoring only

Dsos 2432 observability platform integration

---

terraform/modules/baseline/lb.tf

- deletes the glue crawler resources
- implements aws_glue_catalog_table resources for network and application loadbalancers
- should fix a bunch of issues around flipping access_logs from `false` to `true` after deployment

change baseline lb module release hash

---

.github/workflows/reusable_terraform_plan_apply_test.yml
terraform/environments/data-platform/application_variables.auto.tfvars.json

Deploys https://github.com/ministryofjustice/data-platform/pull/2821
to change `extraction_timestamp` to `load_timestamp` in athena tables

Bump version

---

terraform/environments/sprinkler/directory-service.tf

A recent pipeline run for creating MMAD in sprinkler failed with a message around secret deletion.
This PR sets the recovery window to 0 days to allow immediate secret deletion / recreation

set recovery window for sprinkler mmad secret to 0

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf

- remove logging from csr network load balancers 
network loadbalancers only tls traffic but in this case we're only using http listeners so nothing is going to be logged anyway

CSR network lb only accepts http requests so logging isn't useful

---

terraform/modules/baseline/lb.tf

- MoJ repos use version tags so set this to v4.0.0 as this was released now

set lb module version tag as per convention elsewhere

---

terraform/environments/observability-platform/data.tf
terraform/environments/observability-platform/managed-grafana.tf
terraform/environments/observability-platform/providers.tf
terraform/environments/observability-platform/secrets.tf

Part of https://github.com/ministryofjustice/observability-platform/issues/16
- Adds Secrets Manager secret for housing Grafana's API key

🔐 Add Grafana API key secret

---

terraform/environments/data-platform-apps-and-tools/environment-configuration.tf
terraform/environments/data-platform-apps-and-tools/powerbi-gateway-iam.tf
terraform/environments/data-platform-apps-and-tools/powerbi-gateway-secret.tf
terraform/environments/data-platform-apps-and-tools/powerbi-gateway-server.tf

https://github.com/ministryofjustice/data-platform/issues/2452
Bumping the AMI to full base install so as not to manage configuration purely in powershell.

DPAT: Updating PowerBI Gateway AMI

---

terraform/environments/data-platform-apps-and-tools/environment-configuration.tf
terraform/environments/data-platform-apps-and-tools/helm-charts-applications.tf
terraform/environments/data-platform-apps-and-tools/helm-charts-system.tf

- Resolves https://github.com/ministryofjustice/data-platform/issues/2905
- Upgrades EKS AMI release to `1.17.0-53f322c2`
- Upgrades EKS add-ons
- coredns
- kube-proxy
- vpc-cni
- ebs-csi
- efs-csi
- Upgrades system Helm charts
- cluster-autoscaler
- external-dns
- cert-manager
- ingress-nginx
- velero
- external-secrets
- policy-controller
- aws-for-fluent-bit
- prometheus

📌 DPAT EKS upgrade

---

terraform/environments/data-platform-apps-and-tools/jml_lambda_execution_roles.tf
terraform/environments/data-platform-apps-and-tools/secrets.tf

We are working on a JML (Joiners, Movers, and Leavers) project. We have created a lambda function on the data platform, which queries logs from 'data-platform-apps-and-tools-production' and sends emails to specific users using the 'gov-notify' service. We are using these roles and secrets for that lambda function. If needed more information here is the [ticket](https://github.com/orgs/ministryofjustice/projects/27/views/18?pane=issue&itemId=40142613#:~:text=%E2%9A%99%20Automate%20generating%20and%20sending%20JML%20extracts%20monthly%231719)

JML lambda execution role and secrets manager

---

terraform/environments/hmpps-domain-services/locals_development.tf
terraform/environments/hmpps-domain-services/locals_preproduction.tf
terraform/environments/hmpps-domain-services/locals_production.tf
terraform/environments/hmpps-domain-services/locals_test.tf

Create load balancer cert and set NS records for the new zones

DSOS-2537: Add load balancer certificate for hmpps-domain-services

---

scripts/terraform-plan-evaluator.sh

This relates to https://github.com/ministryofjustice/modernisation-platform/pull/5975 which is granting the `member-access`role the ability to create and delete ec2 vpc endpoints as listed as min pre reqs in creation of aws transfer servers [here](https://docs.aws.amazon.com/transfer/latest/userguide/getting-started.html)
This PR should ensure that the MP team must review any vpc endpoint related resources being managed by members.
I've added a check for both `"aws_transfer_server` and  `"aws_vpc_endpoint"` as in the case of the aws transfer server it is creating a vpc endpoint by proxy as part of that resource. This makes me wonder whether any other resources in aws create vpc endpoints when they are created and do we need to add more to this list?

check for vpc endpoint or transfer server resources

---

terraform/environments/equip/main.tf

after a meeting with the equip team it was decided that EQ06 is not required and can be removed this pr removed this ec2 instance

Remove EC2 instance that is not required

---

terraform/environments/hmpps-domain-services/locals.tf
terraform/environments/hmpps-domain-services/locals_development.tf
terraform/environments/hmpps-domain-services/locals_rds.tf

Some tidy up:
- move to new security group on ASG
- remove old default cert
- enable backup on EC2s

DSOS-2537: remove old hmpps domain cert and enable backup

---

terraform/environments/data-platform/iam.tf

- This follows a bugfix which moves data to the new data product created upon deletion of a table in a data product
- permissions to move data via athena are needed for the lambda now (data wasn't being moved before)

Added Athena permissions for delete table lambda

---

terraform/environments/hmpps-oem/locals.tf
terraform/environments/hmpps-oem/locals_development.tf
terraform/environments/hmpps-oem/locals_preproduction.tf
terraform/environments/hmpps-oem/locals_production.tf
terraform/environments/hmpps-oem/locals_test.tf
terraform/environments/hmpps-oem/main.tf
terraform/modules/baseline_presets/iam_policies.tf
terraform/modules/baseline_presets/iam_policy_statements_ec2.tf
terraform/modules/baseline_presets/iam_roles.tf
terraform/modules/baseline_presets/variables.tf
terraform/modules/environment/outputs.tf

Primarily, adding new role to allow sharing of AD secrets. But also tightened up the policies on the existing OEM sharing role as these were too permissive:
- rejig baseline presets in hmpps-oem to align with nomis (allows different settings per environment)
- added delius sharing policy in hmpps-oem-development only (for delius DBAs)
- added option to create new role and policy for sharing AD secrets
Applied in nomis-test and hmpps-oem-test and all works.

hmpps: DSOS-2542: add AD secret sharing role

---

terraform/environments/observability-platform/observability-platform.tf

- Deployes the module `ministryofjustice/observability-platform-tenant`

👀 Deploy Observability Platform module into Obersvability Platform

---

terraform/environments/cdpt-chaps/database.tf

This enables a final snapshot to be taken of the existing prod RDS, so that it can be replaced in a subsequent apply with a restored RDS.

add final snapshot

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/planetfm/locals.tf
terraform/modules/baseline_presets/iam_policies.tf

Enable role which allows HMPPS secrets access for CSR and PlanetFM

DSOS-2542: enable rds secrets role

---

terraform/environments/electronic-monitoring-data/server_access_capita.tf
terraform/environments/electronic-monitoring-data/server_access_test.tf
terraform/environments/electronic-monitoring-data/transfer_server_capita.tf

Finishes off implementing the AWS transfer workflow for 
1. copy file once it's put into landing bucket to the data store bucket (in a directory named `capita` in this instance
2. delete the original file in the landing bucket once the above has finished
Tested using the test user account and all works as expected.
I've left permissions for the transfer workflow to also allow adding tags to the files also, but couldn't think of appropriate tags atm.
Also done some reorganisation of the files to pull the access permissions into their own file so they're easier to find and review.

ELM-1312 Add AWS transfer workflow

---

terraform/environments/corporate-staff-rostering/locals_development.tf

- don't have alarms set on dev-tst asg in corporate-staff-rostering-development as this will send the initial start-up alarm into the slack channel 👎 
- alarms aren't really needed if this is just a testing server in the dev environment

quick pr to turn off alarms on dev-tst asg as not necessary

---

terraform/environments/digital-prison-reporting/data_ingestion_pipeline.tf
terraform/environments/digital-prison-reporting/main.tf
terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/pipeline.tf
terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf
terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/variables.tf
terraform/environments/digital-prison-reporting/modules/step_function/variables.tf

This PR:
- creates a reload step functions pipeline
- creates a glue job `glue_stop_glue_instance_job` to stop a running instance of the CDC job
- creates a `s3_temp_reload_bucket` for temporarily holding the curated data to avoid downtime during the data reload
- creates a glue job `glue_switch_prisons_hive_data_location_job` which switches the prisons hive table to a s3 location according to the given args
- creates a glue job `glue_s3_data_deletion_job` to delete data from s3 bucket(s)
- defaults the `dms_task_time_out` to 24 hours

DPR2-46: Add reload pipeline and associated glue jobs

---

terraform/environments/electronic-monitoring-data/s3.tf
terraform/environments/electronic-monitoring-data/server_access_capita.tf
terraform/environments/electronic-monitoring-data/server_access_civica.tf
terraform/environments/electronic-monitoring-data/server_access_g4s.tf
terraform/environments/electronic-monitoring-data/server_access_test.tf
terraform/environments/electronic-monitoring-data/transfer_server_capita.tf
terraform/environments/electronic-monitoring-data/transfer_server_civica.tf
terraform/environments/electronic-monitoring-data/transfer_server_g4s.tf

Done a few things here, if the files changed tab is a lot, maybe page through the individual commits as they were atomic.
So I've done:
* add transfer server and user account for civica (left access details blank for now)
* add transfer server and user account for G4S (left access details blank for now)
* moved the transfer user terraform code to `server_access_<supplier>.tf` 
* renamed a load of the resources to have simpler names (as I realise now how verbose I was being)
Done a local `terraform plan` and everything looks happy, will get an MP team review and do the deployment after it's had an EM review.

ELM-1310 & ELM-1311 Create transfer servers for civica and g4s

---

terraform/environments/nomis-data-hub/locals_ndh.tf

Default size is too small, needs 16GB RAM.

ndh: DSOS: Resize NDH EC2 size

---

terraform/environments/electronic-monitoring-data/data.tf
terraform/environments/electronic-monitoring-data/server_access_capita.tf
terraform/environments/electronic-monitoring-data/server_access_civica.tf
terraform/environments/electronic-monitoring-data/server_access_g4s.tf
terraform/environments/electronic-monitoring-data/server_access_test.tf
terraform/environments/electronic-monitoring-data/transfer_server_capita.tf
terraform/environments/electronic-monitoring-data/transfer_server_civica.tf
terraform/environments/electronic-monitoring-data/transfer_server_g4s.tf

Set to use unique iam role for transfer server logging - noticed it was using the test user iam policy which also gives landing bucket access.

ELM-1393 set unique iam for transfer server logging

---

terraform/environments/corporate-staff-rostering/iam.tf

Member infrastructure code moved from mp repo to corporate-staff-rostering environment

Moved corporate-staff-rostering member infrastructure from mp repo

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml
terraform/environments/planetfm/ec2-common.tf
terraform/environments/planetfm/ssm-documents/windows-domain-leave.yaml

Each SSM domain join and domain leave/unjoin script has removed the requirement to type in a domain username and password instead calls upon the hmpps-domain-secrets account and fetched them from there and is able to distinguish between environments
Script was tested through an ec2 windows machine in dev to join AZURE.NOMS.ROOT both in the machine and through ssm

Csr/dsos 2565/ssm doc updates

---

terraform/environments/hmpps-domain-services/locals_preproduction.tf
terraform/environments/hmpps-domain-services/locals_rds.tf

Since some ASG instances are created in 2c region.

DSOS-2560: add eu-west-2c to LB config 

---

terraform/environments/data-platform-apps-and-tools/lambda-functions.tf

Added start, stop and getquereyexection

JML- added-actions-to-poicy-statements

---

terraform/environments/hmpps-domain-services/locals_development.tf
terraform/environments/hmpps-domain-services/templates/user-data-call-ssm-example.yaml
terraform/environments/hmpps-domain-services/templates/user-data-test.yaml

* add a user-data example that calls the windows-domain-join ssm document
* add a user-data step which always runs and gets the EC2 instance information
* sadly getting EC2 info from one script step doesn't survive into the next one

Planetfm/dsos 2576/call ssm docs with reboots from user data

---

terraform/environments/data-platform-apps-and-tools/lambda-functions.tf

Generated dataframes are over the 128MB default memory limit. This bumps us to half a gig.

Up memory limit to account for filesize

---

terraform/environments/data-platform-apps-and-tools/lambda-functions.tf

Lambdas default to 3(!) seconds before timeout. The query will take at least 3 times that, so bumping to 2 minutes.

Increase JML Lambda Timeout

---

terraform/environments/hmpps-domain-services/locals_rds.tf
terraform/environments/nomis-combined-reporting/locals_tomcat_admin.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/oasys/locals.tf
terraform/modules/baseline/ec2_autoscaling_group.tf
terraform/modules/baseline/variables.tf

Current version of ASG module doesn't allow HTTPS protocol on healthcheck.
Also removing unused variable and explicitly putting protocol in healthcheck to reduce cut-and-paste issues.

DSOS-2560: new version of ASG module fixing target group healthcheck

---

terraform/environments/hmpps-domain-services/lambda.tf
terraform/environments/hmpps-domain-services/locals.tf
terraform/environments/hmpps-domain-services/locals_production.tf
terraform/environments/hmpps-domain-services/locals_security_groups.tf
terraform/environments/hmpps-domain-services/templates/user-data-domain-join.yaml

- replace pd-rds-1-b with pd-rds-1-a and move it to eu-west-2a
IMPORTANT 
- this instance will run the user-data-domain-join script and add itself to the domain automatically 🥇 
- don't start changing it's config till it's definitely reachable via rdp using it's name, at least 1 reboot happens during this
THEN:
- need to remove pd-rds-1-b from the domain controller when it's been killed
- check nslookup (domain name) and nslookup (ip) to make sure the new one is in the correct place!
- move to GPO_BLOCKED manually and start configuring it again (lovely)

burn down pd-rds-1-b, apply domain join automatically and move fwd

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf

- add loadbalancer alarms for csr production servers
- add loadbalancer alarms for csr training servers
- no alarms required for pre-production but included one just to see it fail, will be deleted shortly

add alarms for production lb and training servers in preprod

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf

- create a network lb specific alarm as this exists in a different namespace from the application loadbalancer one
- redeploy across csr-prod and csr-preprod for training servers
- one network lb host health alarm WILL fail (on purpose) so will remove this in the next PR after a positive test

create alarms for network lb host health

---

terraform/environments/corporate-staff-rostering/ec2_common.tf

Changes from #4845 are now applied.

csr: remove `moved` blocks

---

terraform/environments/nomis/locals_database.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf

On DBAs request since there is now OEM pagerduty integration

nomis: disable pagerduty alerts for disconnected Oracle DBs

---

terraform/environments/planetfm/locals_defaults.tf
terraform/environments/planetfm/locals_preproduction.tf
terraform/environments/planetfm/locals_production.tf

- make it more obvious what to do if you need to delete an instance
- had issues where this was set in the defaults and got into a tf state problem trying to delete un-deletable instances

move disable_api_termination and other commands

---

terraform/environments/electronic-monitoring-data/modules/landing_zone/main.tf

Add additional sub-directory for copied files based on the user name of account that transferred the file.
gone from 
```
cp file /<supplier/
```
to 
```
cp file /<supplier>/<username>/
```
We will provide usernames for each system being sent over, so doing this means we can organise the directory structure to easier find different systems.

ELM-1490 Update transfer workflow copy destination

---

terraform/environments/electronic-monitoring-data/modules/s3_log_bucket/main.tf
terraform/environments/electronic-monitoring-data/s3.tf

See [here](https://dsdmoj.atlassian.net/wiki/spaces/EM1/pages/4700111402/Risk+4+-+S3+Bucket+Configuration+Weaknesses) for details on the missing bucket configs.
In this PR TLS is added to the additional buckets.

ELM-1496 Add TLS to data store and log buckets

---

terraform/environments/electronic-monitoring-data/locals.tf
terraform/environments/electronic-monitoring-data/main.tf

Adding access for G4S ahead of them testing the connection to the SFTP server for them to deposit data.
This will add a new (well renamed from just `g4s`) user account `g4s_test` to the existing G4S sftp server.

ELM-1499 Add access credentials for G4S to their server

---

terraform/environments/electronic-monitoring-data/modules/landing_zone/server_security_group/main.tf

This change makes it so terraform creates the new resource before deleting the old one. Without
terraform cannot delete the original group as it's associated to a resource.

invert security group deletion-creation

---

terraform/environments/electronic-monitoring-data/modules/landing_zone/main.tf

As outlined in the [pen test results](https://dsdmoj.atlassian.net/wiki/spaces/EM1/pages/4700111381/Risk+3+-+Lack+of+Customer+Master+Key+Rotation) these keys should have rotation enabled.

ELM-1498 enable key rotation on KMS key

---

terraform/environments/corporate-staff-rostering/locals_defaults.tf
terraform/environments/corporate-staff-rostering/locals_production.tf

- remove the oracle rman backup status alarms till CSR Prod DB has been deployed

don't create oracle backup alarms in prod yet

---

terraform/environments/electronic-monitoring-data/locals.tf

G4S provided their internal rather than external IP address.

Update G4S allow listed IP

---

terraform/environments/planetfm/locals_security_groups.tf

- missing some security group rules for planetfm database instances
- these already exist in azure, could see RPC ones being blocked in the VPC flow logs

add missing rules for planetfm db sg

---

terraform/environments/electronic-monitoring-data/locals.tf
terraform/environments/electronic-monitoring-data/main.tf

To allow better storage of data migrated to MoJ use usernames of accounts for each system. This means we will have the structure `/supplier/system/upload_date/*`

ELM-1519 Add accounts for each system to be migrated

---

terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf
terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/variables.tf

This PR recreates the Hive tables during the reload pipeline.
This addresses the scenario where a new table is onboarded to a domain that is already in use.

DPR2-46: Recreate Hive tables during the reload

---

terraform/environments/corporate-staff-rostering/locals_defaults.tf

- only applies to pre-prod at the moment 
- will ensure that refresh db activity doesn't trigger an alarm un-necessarily

change alarms for db instances to cope with refresh duration

---

terraform/environments/electronic-monitoring-data/calculate_checksum_lambda.py
terraform/environments/electronic-monitoring-data/data_store.tf

Done two things:
1. updated the lambda python code to read files in chunks so we're not trying to dump a multi GB file into memory and crashing out
2. Updated the s3 event notification to all object types as large files come in via multiPartUpload (and unclear if via `put` or `copy`

ELM Change checksum lambda to work with large files

---

terraform/environments/hmpps-domain-services/locals_domain.tf

New roles have been created in core-shared-services-production for domain controllers - grant relevant permissions.

DSOS-2615: give secret access to DCs

---

terraform/environments/planetfm/locals_defaults.tf

- need to know sooner when instances are stopped
- alarm now checks every 10 seconds back over 30 and will trigger if 1 metric is missing
- might be a bit too shouty but we can work back up

increase alarm sensitivity

---

terraform/environments/corporate-staff-rostering/locals_defaults.tf

- will check every 10 seconds whether there's been a breach in the last 30 seconds
- if this is too sensitive we can always ramp it back

increase instance stopped alarm sensitivity

---

terraform/environments/corporate-staff-rostering/.ssh/.gitignore
terraform/environments/corporate-staff-rostering/iam.tf
terraform/environments/corporate-staff-rostering/lambda.tf
terraform/environments/corporate-staff-rostering/lambda/ad-clean-up/lambda_function.py

This PR will add a CW eventbridge rule, lambda target, and lambda IAM policies to allow for invocation by CW event bridge.
Commented resources to be added on a second apply (requires the lambda arn to exist).
Deploying to CSR only for now for end-to-end testing, to then be deployed to Planet FM and domain services accounts.
Python black used to format python code.

Lambda CW eventbridge rule and corresponding IAM policies

---

terraform/environments/electronic-monitoring-data/locals.tf
terraform/environments/electronic-monitoring-data/main.tf

G4S want to start with cap_dw system so adding in their account.

Add G4S account for cap data warehouse

---

terraform/environments/nomis/locals_test.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf

Create cloudwatch alarms for EBS volume disk iops limits and EBS throughput limits for nomis-test.

EBS iops and throughput cloudwatch alarms for nomis-test

---

terraform/environments/delius-mis/application_variables.json
terraform/environments/delius-mis/bcs.tf
terraform/environments/delius-mis/secrets.tf
terraform/environments/delius-mis/templates/EC2LaunchV2.yaml.tftpl

this is only required during initial stages of the migration process

NIT-1042 join new vms to legacy domain

---

terraform/environments/corporate-staff-rostering/app_log_metrics.tf

When applying this Terraform, the AWS API was returning `InvalidParameterException: Invalid character(s) in term`.
After trying to backslash escape the parentheses, it still wasn't having it.
Upon reviewing the AWS docs for filter patterns, it explicitly suggests using ASCII hexadecimal codes to specify the disallowed character[^1][^2].
`\x28` and `\x29` denote `(` and `)` respectively.
[^1]: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html
[^2]: https://web.archive.org/web/20240221165209/https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html

csr: escape parentheses in metric filter regex via hex codes

---

terraform/environments/corporate-staff-rostering/locals_defaults.tf

The alarms are only applied to web servers. It also aligns it with the naming of the `app` map.

csr: rename `windows` metric alarm map to `web`

---

terraform/environments/electronic-monitoring-data/locals.tf
terraform/environments/electronic-monitoring-data/main.tf

Need a new sftp username for the mailbox transfer. We can only have 5 active at a time, so removing the dev account.
Also set the test account credentials to capita rather than ddc.

ELM Add capita details for new mailbox account

---

terraform/environments/electronic-monitoring-data/server_backups.tf

The classic tale of Matt vs IAM. The instance needs to be able to list the bucket also in order to do the database restoration.

ELM Update RDS instance S3 permissions

---

terraform/environments/electronic-monitoring-data/server_backups.tf

1TB was not enough to restore a 30GB backup, so going for a doubling approach to 2TB

ELM update rds allocated storage

---

terraform/environments/electronic-monitoring-data/server_backups.tf

Without this flag, changes are applied during a maintenance window instead (see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance)

ELM Immediately update RDS instance of changes

---

terraform/environments/electronic-monitoring-data/server_backups.tf

Not sitting in the MadeTech office anymore.

Remove unnecessary allowed IP for RDS instance

---

terraform/environments/corporate-staff-rostering/locals_defaults.tf
terraform/environments/corporate-staff-rostering/locals_production.tf

- set alarms for pd-csr-db-a now that it's been deployed
- this changes some params specifically for databases

set alarms for pd-csr-db-a now it's deployed

---

terraform/environments/corporate-staff-rostering/app_log_metrics.tf

Change missing data in application log alarms from `ignore` to `notBreaching`.

csr: change missing data to not breaching

---

terraform/environments/corporate-staff-rostering/locals_security_groups.tf
terraform/environments/planetfm/locals_security_groups.tf

We've hit the maximum SG Rule limit so will need to remove the Azure IPs before adding the new AWS IPs.  Rolling back

DSOS-2635: Roll back production domain controller IPs for CSR and Planet

---

terraform/modules/baseline_presets/route53.tf
terraform/modules/ip_addresses/modernisation_platform.tf
terraform/modules/ip_addresses/outputs.tf

Update resolver rules for azure.noms.root domain.  A couple of azure IPs are gone, replaced with AWS ones.

DSOS-2635: update azure noms root dns forward

---

terraform/environments/hmpps-oem/locals_preproduction.tf
terraform/environments/hmpps-oem/locals_production.tf

Add tags used by cloudwatch monitoring for preprod and prod OEM.

hmpp-oem: DSOS-2671: add tags for OEM monitoring

---

terraform/environments/equip/alb.tf

Andy has requested we point `analytics.equip` to EQP-04 so the new server / software can be tested.

Update target group for analytics to point at EQP04 for testing

---

terraform/environments/observability-platform/environment-configurations.tf

- Adds Analytical Platform's Ingestion accounts to Observability Platform

🔭 Adds Analytical Platform's Ingestion accounts to Observability Platform

---

terraform/environments/corporate-staff-rostering/locals_defaults.tf
terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf

- remove cloudwatch_metric_alarms from default as it's not applicable anywhere anymore
- declare cloudwatch_metric_alarms in each database server (prod and preprod) where it's needed
- apply special backup_database locals config which doesn't include the rman backup alarms to -pd-csr-db-b in production as this is the backup server where rman backup doesn't run

exclude rman backup alarms from the backup database deployment

---

scripts/terraform-plan-evaluator.sh

- Extends `scripts/terraform-plan-evaluator.sh` to include resources that are part of creating a VPC

➕ Extend plan evaluator resources

---

terraform/environments/hmpps-oem/locals_test.tf
terraform/environments/hmpps-oem/modules/cloudwatch_dashboard/cross_account_alarms.tf

Shows cross-account alarms in hmpps-oem-test from nomis-test and oasys-test.
Hardcoded values will be removed as part of this ticket - https://dsdmoj.atlassian.net/browse/DSOS-2638

Dsos 2661 cross account alarms

---

terraform/environments/cdpt-chaps/monitoring.tf

Adds Cloudwatch alarm, SNS topic, and PagerDuty integration to alert on detection of a DDOS attack.

DDOS alarms for cdpt-chaps

---

terraform/environments/analytical-platform-ingestion/environment-configuration.tf

This is required after a new release to the ingestion-transfer lambda container image. 
New release here:
https://github.com/ministryofjustice/analytical-platform-ingestion-transfer/releases

Ingestion Transfer Lambda: v0.0.1 -> v0.0.2

---

.github/workflows/reusable_terraform_plan_apply.yml
.github/workflows/reusable_terraform_plan_apply_test.yml

To resolve occasion customer issues with S3 bucket rewind failures, and to ensure that by default we're using the most recent version of terraform, this PR sets the floor to `~1` for terraform.
Customers can still override this as they see fit.

Remove minor version pin from reusable terraform version

---

terraform/environments/corporate-staff-rostering/locals_production.tf

- request from db's to make flash disks on pd-csr-db-a and -b 250G each as they're running out of space
- increase 'flash' size in db code to 500 so it's split

increase prod DB flash disk sizes

---

terraform/environments/equip/alb.tf

This PR updates the target groups for Equip changing it from `COR-A-EQP01 `to `COR-A-EQP04`
I have also updated the health checks as these are currently failing due to the re-direct on the homepage.

Equip Cutover: Upgrade from EQP01 to EQP04

---

.devcontainer/devcontainer-lock.json
terraform/environments/observability-platform/secrets.tf

- Adds a new secret to consume @moj-observability-platform-bot's GitHub token
- Adds a new secret to consume Observability Platform's Slack token
- Updates `ghcr.io/ministryofjustice/devcontainer-feature/terraform` to `0.0.4`

🤐 Add GitHub and Slack secrets

---

terraform/environments/analytical-platform-ingestion/cloudwatch-log-groups.tf
terraform/environments/analytical-platform-ingestion/eips.tf
terraform/environments/analytical-platform-ingestion/environment-configuration.tf
terraform/environments/analytical-platform-ingestion/iam-policies.tf
terraform/environments/analytical-platform-ingestion/iam-roles.tf
terraform/environments/analytical-platform-ingestion/kms-keys.tf
terraform/environments/analytical-platform-ingestion/transfer-servers.tf
terraform/environments/analytical-platform-ingestion/transfer-user.tf

- Adds KMS key for structured transfer logs
- Adds CloudWatch Log Group for structured logs
- Switches to `module.vpc.public_subnets` for calculating EIP count
- Moves SFTP users into environment configuration
- Adds IAM policy and role for transfer logging
- Enables structured logging on transfer server

⚙️ Update Analytical Platform Ingestion

---

terraform/environments/nomis/locals_development.tf

Forgot the DNS entries for the syscon build server

DSOS-2700: add missing nomis syscon DNS records

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_development.tf
terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf
terraform/environments/corporate-staff-rostering/locals_test.tf
terraform/environments/corporate-staff-rostering/main.tf
terraform/environments/corporate-staff-rostering/platform_base_variables.tf
terraform/environments/corporate-staff-rostering/variables.tf
terraform/environments/planetfm/locals.tf
terraform/environments/planetfm/locals_development.tf
terraform/environments/planetfm/locals_preproduction.tf
terraform/environments/planetfm/locals_production.tf
terraform/environments/planetfm/locals_test.tf
terraform/environments/planetfm/main.tf

Enabling metric sharing from planet fm prod to csr prod.
No preset dashboard built alongside - leaves option for App Support team to build their own, as required.

Adding cross-account monitoring from planet to csr

---

terraform/modules/baseline_presets/iam_policies.tf
terraform/modules/baseline_presets/iam_policy_statements_ec2.tf
terraform/modules/baseline_presets/s3.tf

On request from Delius DBAs
Allow dev and test DB EC2 instances to access db backup buckets in dev and test.

hmpps-oem: DSOS: update db backup sharing permissions

---

terraform/environments/observability-platform/secrets.tf

- Adds a secret we can populate for PagerDuty integration keys

🔐 Add PagerDuty integration key secret

---

terraform/environments/observability-platform/environment-configurations.tf
terraform/environments/observability-platform/locals.tf
terraform/environments/observability-platform/managed-grafana.tf
terraform/environments/observability-platform/modules/grafana/contact-point/pagerduty/main.tf
terraform/environments/observability-platform/modules/grafana/contact-point/pagerduty/providers.tf
terraform/environments/observability-platform/modules/grafana/contact-point/pagerduty/variables.tf
terraform/environments/observability-platform/modules/grafana/contact-point/slack/main.tf

- Introduces `pagerduty_services` to `tenant_configuration`
- Creates a Grafana contact point
- Mutates the root notification policy to create labels for routing to PagerDuty

📟 Observability Platform PagerDuty alerting

---

terraform/environments/analytical-platform-ingestion/cloudwatch-log-groups.tf
terraform/environments/analytical-platform-ingestion/data.tf
terraform/environments/analytical-platform-ingestion/environment-configuration.tf
terraform/environments/analytical-platform-ingestion/kms-keys.tf
terraform/environments/analytical-platform-ingestion/lambda-functions.tf
terraform/environments/analytical-platform-ingestion/modules/transfer-family/user-with-egress/main.tf
terraform/environments/analytical-platform-ingestion/modules/transfer-family/user-with-egress/variables.tf
terraform/environments/analytical-platform-ingestion/modules/transfer-family/user/main.tf
terraform/environments/analytical-platform-ingestion/observability-platform.tf
terraform/environments/analytical-platform-ingestion/s3-notifications.tf
terraform/environments/analytical-platform-ingestion/s3.tf
terraform/environments/analytical-platform-ingestion/secrets.tf
terraform/environments/analytical-platform-ingestion/transfer-servers.tf
terraform/environments/analytical-platform-ingestion/transfer-user.tf
terraform/environments/analytical-platform-ingestion/vpc.tf

- Adds a new module which introduces egress functionality

🚚 Add egress functionality to Analytical Platform Ingestion

---

terraform/environments/analytical-platform-ingestion/s3.tf

This locks down the quarantine S3 bucket in Analytical Platform Ingestion.

🔧  Add Deny Policy for Quarantine S3 bucket

---

terraform/environments/oasys-national-reporting/locals_development.tf

- rhel 6 doesn't support use as an asg ami
- create a rhel 6 stand-alone instance instead
- create a web asg for testing as well

create a web asg and an ec2 boe instance instead

---

terraform/environments/analytical-platform-ingestion/data.tf
terraform/environments/analytical-platform-ingestion/environment-configuration.tf
terraform/environments/analytical-platform-ingestion/lambda-functions.tf
terraform/environments/analytical-platform-ingestion/security-groups.tf
terraform/environments/analytical-platform-ingestion/vpc-endpoints.tf

- Moves Lambda functions into VPC
- Creates and attaches security groups to Lambda functions
- Allows access to S3 gateway
- Adds a VPC interface for Secrets Manager

:wrench: Move Lambda to VPC

---

terraform/environments/ccms-ebs-upgrade/r53.tf

`ccms-ebs-app-X-upgrade` → `ccms-ebs-appX-upgrade`

CC-2488: ccms-ebs-app-X-upgrade -> ccms-ebs-appX-upgrade

---

terraform/environments/oasys-national-reporting/locals_defaults.tf

- set to optional for Rhel 6 defaults

set https token requirements to optional

---

terraform/environments/maat/maat-param.tf
terraform/environments/maat/maat-task-definition.json
terraform/environments/mlra/locals.tf
terraform/environments/mlra/task_definition.json

Update MLRA Google Analytics 4 property name to `APP_MLRA_GOOGLE_ANALYTICS_4_TAG_ID` to include `APP` prefix and also confirm to the same pattern as the MAAT application `APP_MAAT_GOOGLE_ANALYTICS_4_TAG_ID`.
Also update the MAAT Google Analytics 4 property name to follow the same structure `APP_MAAT_GOOGLE_ANALYTICS_4_TAG_ID`
This will also address the "Invalid parameters" issue with MLRA

LASB-2974 Update MLRA property name to include APP prefix

---

terraform/environments/cica-data-extraction/platform_providers.tf

This provider will allow the `cica-data-extract` application to make use of AWS Bedrock resources in `eu-central-1`.

Add bedrock provider for cica-data-extraction

---

terraform/environments/hmpps-domain-services/patch.tf
terraform/modules/patch_manager/ExtractAndUploadPatches.yaml
terraform/modules/patch_manager/README.md
terraform/modules/patch_manager/patch-manager.tf
terraform/modules/patch_manager/s3.tf
terraform/modules/patch_manager/variables.tf

- Remove hard coded account Ids and updated the module to accept a list of instance roles instead.
- Set  windows patch schedules for test and dev environments
- Split bucket so only dev gets a cross account bucket whereas all environments get a patch logging bucket

Patching refactor to remove accountIds and set schedules

---

terraform/environments/nomis-data-hub/locals.tf

NDH doesn't need a certificate and it's causing an issue with the terraform. Remove

ndh: DSOS: remove unused ACM cert

---

terraform/environments/cdpt-chaps/ecs.tf

From what I could see, setting `$Latest` for the `launch_template {}` in `aws_autoscaling_group.cluster-scaling-group` was not resulting in updates to the launch template in use - the default (`1`) was being used in all cases.
Shifting this to dynamically refer to the latest launch template version appears to work.

Update autoscaling group to retrieve latest version of launch template

---

terraform/environments/oasys/locals_security_groups.tf

Following conversation from Data Engineering, they just need stage -> preprod and prod -> prod.  Limit access to prevent accidents.

DSOS-2736: add dataengineering access to preprod oasys and restrict prod

---

terraform/environments/nomis/locals_preproduction.tf

AWS refusing to start the latest AMI, trying an older one to see if it works

nomis: DSOS-2719: align AMI with other existing deployment

---

terraform/environments/electronic-monitoring-data/server_backups.tf

open all ingress and egress ports for the rds database so we can run a glue crawler

Glue open ports for RDS security group EM

---

terraform/environments/oasys-national-reporting/locals_test.tf

`.config` shouldn't be there. It should merge on the parent, in order to include any maps that aren't explicitly declared.

onr(test): fix reference to ec2 defaults local

---

terraform/environments/nomis/locals_preproduction.tf
terraform/modules/baseline_presets/ec2_autoscaling_group.tf

Better to use the default for this so it matches up with the maximum capacity, e.g. in nomis-preprod where we have max capacity of 2 this isn't really working.

Nomis: DSOS-2719: warm pool fix

---

terraform/modules/baseline/secretsmanager.tf
terraform/modules/baseline/variables.tf

Allow individual tagging on secrets - for fine-grained iam policy access

DSOS-2692: allow tagging on secrets

---

terraform/environments/oasys-national-reporting/locals.tf
terraform/environments/oasys-national-reporting/locals_defaults.tf
terraform/environments/oasys-national-reporting/locals_test.tf
terraform/environments/oasys-national-reporting/main.tf

- db instance in oasys-national-reporting-test is commented out for now
- pending additions to config management repo
- note, not all disks exist/are required for testing
- adds secrets for testing ONR db install/config automation
- changes some defaults

Onr/dsos 2682/add test db instance

---

terraform/environments/nomis/locals_preproduction.tf

Drop the inactive deployment back to defaults following successful test of autoscaling schedules. Leaving the comments in so we can add back in once agreed by DBAs.

nomis: DSOS-2719: ASG change

---

terraform/environments/oasys-national-reporting/locals_test.tf

It allows the Ansible to source the name from the default environment tags, which use "test" by default.

onr: change secret name from t1 to test

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_jumpserver.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/locals_xtag.tf

This will restrict access when people use the instance-access role.  Jump server is fully accessible but only SSH/Port forwarding allowed on the other instances

nomis: DSOS-2720: add instance-access-policy tag

---

terraform/environments/oasys-national-reporting/locals_test.tf

This allows instances to access values in the specified secrets. Required for the Ansible to work.

onr: add IAM policy for secret access by instances

---

terraform/modules/baseline/variables.tf

Needs a default, otherwise other environments will break

DSOS-2749: fix baseline efs bug

---

terraform/environments/nomis-combined-reporting/locals.tf
terraform/environments/nomis-combined-reporting/locals_preproduction.tf
terraform/environments/nomis-combined-reporting/main.tf
terraform/environments/nomis-combined-reporting/outputs.tf

The BIP application servers require a file share.  Creating EFS for that purpose

DSOS-2749: Add file share for preprod nomis combined reporting

---

terraform/environments/hmpps-oem/locals.tf
terraform/environments/hmpps-oem/locals_test.tf
terraform/environments/hmpps-oem/main.tf
terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/main.tf
terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_test.tf
terraform/environments/oasys/main.tf
terraform/modules/cross_account_cloudwatch/monitoring_account.tf
terraform/modules/cross_account_cloudwatch/outputs.tf
terraform/modules/cross_account_cloudwatch/variables.tf

- Removed hardcoded values for hmpps-oem-test, oasys-test and nomis-test account IDs in cross_account_cloudwatch module
- monitoring_account_id and source_account_ids can now be defined in locals_<environment>.tf files
- Output for monitoring_account_sink_identifier to remove hardcoded value

Dsos 2735 cloudwatch dashboard account names

---

terraform/environments/mlra/ecs.tf
terraform/environments/mlra/locals.tf
terraform/environments/mlra/modules/ecs/main.tf
terraform/environments/mlra/modules/ecs/variables.tf

For MLRA, rename `ga_4_tag_id_secret_name` to `ga_4_tag_id_secret_name2` to force a refresh of the AWS Parameter Store value for `APP_MLRA_GOOGLE_ANALYTICS_4_TAG_ID`
Jira: https://dsdmoj.atlassian.net/browse/LASB-3001

LASB-3001 MLRA Refresh Google Analytics AWS Parameter Store value

---

terraform/environments/example/certificates.tf
terraform/environments/example/ec2.tf
terraform/environments/example/ec2_autoscaling_group.tf
terraform/environments/example/ec2_complete.tf
terraform/environments/example/ecs.tf
terraform/environments/example/loadbalancer.tf
terraform/environments/example/loadbalancer_module.tf
terraform/environments/example/platform_providers.tf

As a possible example for https://github.com/ministryofjustice/modernisation-platform/issues/1519, this PR implements the use of `default_tags` as configured in version 5.0 and above of the Terraform AWS Provider, using the common values in `local.tags`:
```
provider "aws" {
default_tags { tags = local.tags }
}
```

Use `default_tags` in AWS Provider statements

---

terraform/environments/analytical-platform-compute/data.tf
terraform/environments/analytical-platform-compute/environment-configuration.tf
terraform/environments/analytical-platform-compute/secrets.tf
terraform/environments/analytical-platform-compute/vpc.tf

Part of https://github.com/ministryofjustice/data-platform/issues/3555
- Removes the VPC and VPC endpoints that are provided as part of the isolated networking option, I need to resize the subnets but they are blocked by the existence of VPC endpoints, so instead of doing it bit-by-bit, I'll just blow it all away and start again, which as a lesson learned from Analytical Platform Ingestion

🔥 Remove Analytical Platform Compute VPC

---

terraform/environments/analytical-platform-ingestion/modules/transfer-family/user-with-egress/main.tf
terraform/environments/analytical-platform-ingestion/modules/transfer-family/user-with-egress/versions.tf
terraform/environments/analytical-platform-ingestion/modules/transfer-family/user/main.tf
terraform/environments/analytical-platform-ingestion/modules/transfer-family/user/versions.tf
terraform/environments/analytical-platform-ingestion/s3.tf
terraform/environments/analytical-platform-ingestion/secrets.tf
terraform/environments/analytical-platform-ingestion/security-groups.tf
terraform/environments/analytical-platform-ingestion/sns.tf

Add a lifecycle rule to the `mojap-ingestion-${local.environment}-quarantine` bucket which deletes files 90 days after they were last modified or created. Files should only be created in this context.

Delete Quarantined files after 90 days

---

terraform/environments/corporate-staff-rostering/main.tf
terraform/environments/hmpps-domain-services/main.tf
terraform/environments/hmpps-oem/main.tf
terraform/environments/nomis-combined-reporting/main.tf
terraform/environments/nomis-data-hub/main.tf
terraform/environments/oasys-national-reporting/main.tf
terraform/environments/oasys/main.tf
terraform/environments/planetfm/locals.tf
terraform/environments/planetfm/main.tf

Moving ec2-user private key secret into SecretsManager to ensure EC2s can't access it.  Via baseline module.

DSO-2691:  add ec2-user secret to DSO apps

---

terraform/environments/oasys/locals_secrets.tf
terraform/environments/oasys/locals_test.tf

- add T2BOSYS and T2BOAUD to `t2-oasys-db-a` for BOE XI 3.1 silent installer testing
- DB for new install needs to exist IN ADVANCE of filling in the response.ini file for the silent installer
- @Sandhya1874 creating these new tables so testing doesn't impact anything that already exists
This will allow the following items to be completed in the `modernisation-platform-configuration-management` repo
- fill in oracle-tns-names role variables for onr-boe role and test it works
- pull the db-names and passwords etc. into ansible from the AWS Secrets Manager 
- add these secrets to the response file

add T2 oracle-sids

---

terraform/environments/nomis/locals_production.tf

Create prod-nomis-db-1-a  and prod-nomis-db-2-a 
Increase data disk sizes on prod-nomis-db-2-b to 6000

nomis: DSOS-2759: add main production nomis DBs

---

terraform/environments/analytical-platform-compute/environment-configuration.tf

- Is part of https://github.com/ministryofjustice/data-platform/issues/3555
- Corrects Production subnets, I've spent too long looking at these now.

🚑 Correct Analytical Platform Compute Production VPC subnetting

---

terraform/environments/oasys/locals_secrets.tf
terraform/environments/oasys/locals_test.tf

- reduced size so it's in line with other t2 environments
- will run `server_type_onr_db` group-vars from `modernisation-platform-configuration-management` with -ec2provision tag
- oracle-sids values for monitoring are commented out
- removes un-necessary secrets definition from locals

Onr/dso 2726/setup oasys onr t2 db instance

---

terraform/environments/oasys/locals_test.tf

- ansible automation failed due to a package missing/unavailable error
- destroy t2-onr-db-a instance
Will deploy it from a branch and make sure all the config-management runs BEFORE doing a PR for this

destroy instance

---

terraform/environments/oasys/locals.tf

- make it clearer why the base ami image is used here and what else needs to be set for this to work properly

add comment to onr db defaults in locals

---

terraform/environments/oasys-national-reporting/locals.tf
terraform/environments/oasys-national-reporting/locals_jumpserver.tf
terraform/environments/oasys-national-reporting/locals_security_groups.tf
terraform/environments/oasys-national-reporting/locals_test.tf

- create locals for jumpserver asg
- add a security-group just for this
We might not end up using/keeping this in this particular environment BUT it's just a dev platform at this point
Should probably have a better description TBH, we're not 'developing' the nart client software. This asg is just a dev instance to automate how the nart client software gets installed on Windows Server 2102 r2 automatically :P

create jumpserver asg for nart client software development

---

terraform/environments/electronic-monitoring-data/locals.tf
terraform/environments/electronic-monitoring-data/main.tf

Create the final transfer family SFTP account needed for transferring G4S data.

Add account for G4S x drive data

---

terraform/environments/electronic-monitoring-data/main.tf

Now that data migration has been completed for these suppliers the servers can be removed (saving $$$). 
There is likely to be an additional transfer in a few months time so not removing the code yet.

Deactivate the landing zones for capita and civica

---

scripts/terraform-plan-evaluator.sh

Relates to https://github.com/ministryofjustice/analytical-platform/issues/3555
- Adds `aws_iam_openid_connect_provider` to `scripts/terraform-plan-evaluator.sh`
- source: https://mojdt.slack.com/archives/C01A7QK5VM1/p1715690493676859?thread_ts=1715600755.670579&cid=C01A7QK5VM1 

🛂 Add `aws_iam_openid_connect_provider` to plan evaluator

---

terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf

Changed duration till alarm triggers from 1 hour to 15 minutes so alarms trigger faster when disk and memory threshold  is reached.

change datapoints to alarm to 15 for free-disk-space-low

---

terraform/modules/baseline/ssm.tf
terraform/modules/baseline/variables.tf
terraform/modules/lb_listener/main.tf

Suppose might be useful elsewhere so adding this feature into baseline, but primarily this is for offloc implementation

DSOS-2779: allow ssm parameter value to be looked up from s3 bucket name

---

terraform/environments/oasys-national-reporting/locals_defaults.tf
terraform/environments/oasys-national-reporting/locals_jumpserver.tf
terraform/environments/oasys-national-reporting/locals_preproduction.tf
terraform/environments/oasys-national-reporting/locals_production.tf
terraform/environments/oasys-national-reporting/locals_test.tf

- revised instance size/types work with underlying OS ✅ 
- add instance types/sizes for preproduction and production as comments for later
- delete test-boe-asg ahead of turning this into a non-asg instance
- comment out onr_db default as we don't seem to need this here
@keirwilliams I have not changed the development environment instance type/sizes 👍

check instance type and size changes, check jumpserver ami changes

---

terraform/environments/example/ec2.tf
terraform/environments/example/ec2_autoscaling_group.tf
terraform/environments/example/ec2_bastion_linux.tf
terraform/environments/example/ec2_complete.tf
terraform/environments/example/ecs.tf
terraform/environments/example/loadbalancer.tf
terraform/environments/example/loadbalancer_module.tf
terraform/environments/example/platform_versions.tf
terraform/environments/example/rds.tf
terraform/environments/example/s3.tf

I think there's some value in revisiting / rewriting the code we have in `example` as it's gotten a bit disorganised, and doesn't represent consistent practice that we'd always want customers to crib from.
However, this PR add some randomisation to names where there were previous clashes, updates to the most recent version of the ECS module, gets the RDS instance created, switches out the remote refs for modules to commit values, and puts in place some checkov skips where appropriate.

Get `example` successfully completing terraform runs

---

terraform/environments/oasys-national-reporting/locals_test.tf

- add t2 onr boe instance not as an asg, but commented out for now
- re-enable an onr boe asg instance with revised name for making sure all the ansible runs okay!
Basically want to test all the ansible first before I finally switch to a non-asg instance

add boe instance

---

terraform/modules/rds_instance/versions.tf

Reverts ministryofjustice/modernisation-platform-environments#5021

Revert "Update hashicorp/cloudinit requirement from ~> 2.2.0 to ~> 2.3.3 in /terraform/environments/hmpps-domain-services"

---

terraform/environments/cooker/main.tf
terraform/environments/example/loadbalancer.tf
terraform/environments/sprinkler/main.tf

I noted that a number of MP-provided environments in this repository are not using secure TLS policies. This PR updates the configuration to use secure listeners. From some investigation, it appears that when a policy is not specified in Terraform, it defaults to using `ELBSecurityPolicy-2016-08` as discussed [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html#describe-ssl-policies).

Updated SSL policy used in listeners to use secure TLS protocols

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

Remove unused secrets
Reverted high-memory alarm to default for prod-nomis-db-1-b
Reverted maintenance message to a more generic message

Nomis: DSOS-2792: post migration tidy up

---

terraform/environments/equip/alb.tf

As part of https://github.com/ministryofjustice/modernisation-platform-security/issues/4, it was identified that the Equip ALB listener is not using the recommended TLS policy.
This PR amends the `ssl_policy` value, adding compatibility with TLS 1.3 and removing compatibility with some older cipher suites.

upgrade Equip SSL policy to support modern TLS versions

---

terraform/environments/dacp/load_balancer.tf
terraform/environments/ncas/load_balancer.tf
terraform/environments/pra-register/load_balancer.tf
terraform/environments/tipstaff/load_balancer.tf

update LB to recommended tls security policy on DTS Legacy apps (dacp, ncas, pra, tipstaff)

update dts-legacy .net services elb policy

---

terraform/environments/hmpps-oem/locals.tf
terraform/environments/hmpps-oem/main.tf
terraform/environments/nomis/locals.tf
terraform/environments/nomis/main.tf
terraform/modules/baseline/oam.tf
terraform/modules/baseline/outputs.tf
terraform/modules/baseline/variables.tf
terraform/modules/baseline_presets/iam_roles.tf
terraform/modules/baseline_presets/oam.tf
terraform/modules/baseline_presets/outputs.tf
terraform/modules/baseline_presets/s3.tf
terraform/modules/baseline_presets/ssm.tf
terraform/modules/baseline_presets/variables.tf

Add cloudwatch OAM into baseline so can be easily applied across all accounts.

DSOS-2797: cloudwatch metric sharing into baseline

---

terraform/environments/example/data.tf
terraform/environments/example/ec2_complete.tf
terraform/environments/example/macie.tf

This fixes two issues identified when rebuilding example:
- job_status is a required parameter that is incorrectly stated as optional in the documentation. See bug https://github.com/hashicorp/terraform-provider-aws/issues/20726.
- Amends two of the data items that reference s3 bucket names to use terraform logical names.
Note that that the apply error for an existing ec2 security group occurs which relates to a fixed bug which likely was amended prior to this rebuild. This will require fixing in a separate ticket.
Error: [WARN] A duplicate Security Group rule was found on (sg-02e8df8703e730ebf). This may be
│ a side effect of a now-fixed Terraform issue causing two security groups with
│ identical attributes but different source_security_group_ids to overwrite each
│ other in the state. …

Amends MACIE s3 bucket name references and adds missing job_status flag.

---

terraform/environments/digital-prison-reporting/athena_federated_queries.tf
terraform/environments/digital-prison-reporting/data.tf
terraform/environments/digital-prison-reporting/locals.tf
terraform/environments/digital-prison-reporting/main.tf
terraform/environments/digital-prison-reporting/modules/athena_federated_query_connectors/oracle/iam.tf
terraform/environments/digital-prison-reporting/modules/athena_federated_query_connectors/oracle/variables.tf
terraform/environments/digital-prison-reporting/secrets.tf

- Switch from using SID to using service name in NOMIS connection string for Athena federated queries
- Simplify secrets by using a single pre-existing secret rather than a second secret
- Allow oracle connector module to be given access to multiple secrets when using multiple connection strings

DPR2-720 switch from sid to service name

---

terraform/environments/analytical-platform-compute/environment-configuration.tf

- Upgrades EKS to 1.30
- https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-eks-distro-kubernetes-version-1-30/
- https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/
Notes:
- `apply` fails because no version is returned from AWS API when requesting versions for `aws-guardduty-agent` for EKS `1.30`, I have raised this with enterprise support. It doesn't affect clusters upgrading, but **would** affect new clusters

📌 Upgrade Analytical Platform Compute EKS to 1.30

---

terraform/environments/nomis/locals_production.tf

Remove prod-nomis-db-2 and prod-nomis-db-3, they are no longer in use

DSOS-2796: remove unused prod DBs

---

terraform/environments/hmpps-domain-services/locals_development.tf

- There is no hmpps_rhel_8_5 in group_vars

Update ami tag for testing new role

---

terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

One of the servers has been taken down, use Domain Controller instead.
Also, the test is only in nomis-production.  Update nomis-test dashboard to reflect this.

Nomis: connectivity test fix

---

terraform/environments/analytical-platform-compute/kubernetes-annotations.tf
terraform/environments/analytical-platform-compute/kubernetes-storageclasses.tf

- Adds a new storage class for `gp3` and makes it the default
- Annotates `gp2` to unset it as default
Note:
I have rolled the Prometheus Proxy deployment to pick up the new storage class
```
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                              STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-86f303de-ee95-4cc1-b508-9145d4eb83f8   2Gi        RWO            Delete           Bound    aws-observability/storage-amazon-prometheus-proxy-alertmanager-0   gp3            <unset>                          3m52s
pvc-ed8e583f-428d-4e13-bab1-30afa16a03bd   8Gi        RWO            Delete           Bound …
```

💼 Add `gp3` storage class

---

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
terraform/environments/analytical-platform-compute/secrets.tf
terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/create-a-derived-table/values.yml.tftpl

- Adds CaDeT's Actions Runner Helm release to production
- Renames the secret module

⚓ Add CaDeT Actions Runner Helm release

---

terraform/environments/oasys-national-reporting/locals_test.tf

- missed off flag needed for Rhel 6 instances to actually start

add rhel 6 cloud-init fix
