terraform/environments/analytical-platform-management/providers.tf
terraform/environments/bench/providers.tf
terraform/environments/bichard7/providers.tf
terraform/environments/cooker/providers.tf
terraform/environments/heater/providers.tf
terraform/environments/justice-on-the-web/providers.tf
terraform/environments/ops-engineering/providers.tf
terraform/environments/performance-hub/providers.tf
terraform/environments/remote-supervision/providers.tf
terraform/environments/sprinkler/providers.tf

New provider for network services to enable certificate validation dns
entries to be created.

Update providers to include network services

---

terraform/environments/sprinkler/providers.tf

I changed this for the demo and missed changing it back

Fix missed provider update

---

.github/CODEOWNERS
terraform/environments/analytical-platform-management/providers.tf
terraform/environments/bench/providers.tf
terraform/environments/bichard7/providers.tf
terraform/environments/cooker/providers.tf
terraform/environments/heater/providers.tf
terraform/environments/justice-on-the-web/providers.tf
terraform/environments/ops-engineering/providers.tf
terraform/environments/performance-hub/providers.tf
terraform/environments/remote-supervision/providers.tf
terraform/environments/sprinkler/providers.tf

Now that we have a restricted member role we need to update the
providers to use it.

Update providers to use new member role

---

terraform/environments/performance-hub/secrets.tf

Adding secret defintions for secrets which don't exist yet

Adding secret definitions for API keys and persistent storage

---

.github/workflows/terraform-static-analysis.yml

This action will run TFSEC and Checkov on changed terraform folders. There is a workflow dispatch option to run a full scan on all our terraform.

Add terraform static analysis to repo

---

terraform/environments/nomis/database.tf

Initial version of DB instance code for https://github.com/ministryofjustice/modernisation-platform/issues/956.

#956 create db instance

---

terraform/environments/performance-hub/application_variables.json
terraform/environments/performance-hub/main.tf
terraform/environments/performance-hub/templates/task_definition.json

Adding env vars for environment name, system upload account and Ordnance Survey API key

Adding env vars for environment name, system upload account and OS key

---

terraform/environments/bench/app_variables.json
terraform/environments/cooker/app_variables.json
terraform/environments/heater/app_variables.json
terraform/environments/nomis/bastion_linux.tf
terraform/environments/performance-hub/bastion_linux.tf
terraform/environments/sprinkler/app_variables.json
terraform/environments/sprinkler/bastion_linux.tf

And update rds postgresql version from 12.5 to 12.7

Update all consumers to bastion v1.0.3

---

terraform/environments/xhibit-portal/application_variables.json

update ami with gcairns and achopra accounts

---

terraform/environments/xhibit-portal/domain-controllers.tf

Dont understand where this suprious volume is coming from. the volume and machine are totally gone. Lets see what happens this time. grrrrr

re-add machine and volume. 

---

terraform/environments/nomis/application_variables.json
terraform/environments/nomis/modules/nomis_stack/ec2_database.tf
terraform/environments/nomis/modules/nomis_stack/ec2_weblogic.tf
terraform/environments/nomis/modules/nomis_stack/user_data/weblogic_init.sh
terraform/environments/nomis/modules/nomis_stack/variables.tf

In this PR:
- Pass database endpoint to Weblogic-init script. 🥇

Fix weblogic dependencies

---

terraform/environments/xhibit-portal/database-server.tf

This reverts commit 7a13f3e25b61d57d971a1e4375559afaa6111dbf.

Revert "locking down ICMP and UDP for db ingress"

---

terraform/environments/xhibit-portal/database-server.tf

This reverts commit bd7f201b7c669774246ec521260179de737be3e1.

Revert "Locking down SQL egress ports only"

---

terraform/environments/xhibit-portal/providers.tf

Set providers back to its original state

Fix providers.tf to add original settings

---

terraform/environments/cooker/versions.tf
terraform/environments/nomis/bastion_linux.tf
terraform/environments/nomis/loadbalancer.tf
terraform/environments/nomis/modules/database/versions.tf
terraform/environments/nomis/modules/nomis_stack/networking.tf
terraform/environments/nomis/modules/nomis_stack/versions.tf
terraform/environments/nomis/s3.tf
terraform/environments/nomis/versions.tf

* Update deprecated data calls
* Update references to downstream modules
* Update version constraint to `~> 4.0`

Nomis AWS Provider V4 changes

---

terraform/environments/equip/data.tf
terraform/environments/equip/locals.tf

As per #1545, fixing the templated files

Fix data and locals

---

terraform/environments/equip/alb.tf
terraform/environments/equip/application_variables.json
terraform/environments/equip/dns.tf
terraform/environments/equip/locals.tf

Creates certificates and conducts validation for equip

rewrote creation of certificates for load balancer

---

terraform/environments/equip/alb.tf
terraform/environments/equip/dns.tf
terraform/environments/equip/securitygroup.tf

Adds a resolver rule that will direct DNS requests for equip.local at the private IP addresses of the DCs

added resolver rule to send DNS requests for equip.local to DCs

---

.github/workflows/nuke-redeploy.yml
.github/workflows/nuke.yml
scripts/nuke-config-template.txt
scripts/nuke.sh
scripts/terraform-apply-after-nuke.sh

Relevant documentation can be found in: https://github.com/ministryofjustice/modernisation-platform/pull/1699

Auto-nuke and redeploy development environments on weekly basis

---

terraform/environments/equip/securitygroup.tf

* Trim the amount of traffic permitted to ingress the DCs from `all_internal_groups` to only traffic required to join the domain

Trim security groups

---

.github/workflows/nuke-redeploy.yml
.github/workflows/nuke.yml
terraform/environments/sprinkler/app_variables.json

The env variables NUKE_SKIP_ENVIRONMENTS and NUKE_DO_NOT_RECREATE_ENVIRONMENTS are non secret. Therefore, defining them within the job YAML.

Non secret env variables

---

terraform/environments/equip/s3-awslogs.tf

Cleaning up the un-necessary data and variables

Cleanup of Project

---

terraform/environments/equip/application_variables.json
terraform/environments/equip/securitygroup.tf

* Adds application-specific values for security group rules into json
* Adds `security_group_rule` resources for CTX-to-CTX host traffic

added security group rules for CTX host internal traffic

---

terraform/environments/equip/securitygroup.tf

* Amend references for CTX internal traffic to correct security group IDs

changed reference for ctx security groups

---

terraform/environments/sprinkler/monitoring.tf

Switching sprinkler over to test the new high priority alarm channel.

Switch to high priority alarm

---

terraform/environments/xhibit-portal/waf-load-balancer.tf

Waf Updates to ensure access to portal if from GB ONLY
OUT of Hours ONLY

Update the WAF to block none-GB users - Out of Hours ONLY

---

terraform/environments/nomis/ec2-common.tf
terraform/environments/nomis/ssm-documents/node-exporter-windows.json

Resource definition for NodeExporterWindows ssm doc association

Add ssm association for NodeExporterWindows

---

.github/workflows/nuke-redeploy.yml
.github/workflows/nuke.yml
scripts/nuke-config-template.txt
scripts/nuke.sh
scripts/terraform-apply-after-nuke.sh

Use NUKE_ACCOUNT_IDS secret as source for the envs to be nuked

---

terraform/environments/equip/main.tf

Add additional block device to NPS-COR-A-EQP01 with 400 GB size

Change NPS-COR-A-EQP01-ebs-block-2 volume size to 200 from 400 GB

---

terraform/environments/equip/instance_role.tf
terraform/environments/equip/policy.tf

Equip: Added policy for the Citrix NetScaler instance https://mojdt.slack.com/archives/C01A7QK5VM1/p1652352369447769

Equip policy for the Citrix NetScaler instance

---

terraform/environments/equip/application_variables.json
terraform/environments/equip/securitygroup.tf

secg-equip-development-citrix-adc-vip 
secg-equip-development-spotfire
secg-equip-development-equip
secg-equip-development-citrix-host

Ensure that cross traffic is enabled on port 80 between these SGs:

---

terraform/environments/equip/application_variables.json
terraform/environments/equip/main.tf

* Set AMI values for Equip to current hard-coded values
* Alphabetise entries in json for security group rules

hard code Equip AMI values

---

terraform/environments/equip/application_variables.json
terraform/environments/equip/securitygroup.tf

* Allow all hosts to send to proxies on `tcp/4119`
* Allow EQP hosts to send to SF hosts on `tcp/1433`

Equip SG adjustments

---

terraform/environments/equip/application_variables.json
terraform/environments/equip/citrix_adc.tf
terraform/environments/equip/dlm-snapshot/main.tf
terraform/environments/equip/securitygroup.tf
terraform/environments/performance-hub/monitoring.tf
terraform/environments/sprinkler/monitoring.tf

* Recreated due to failure of original PR to complete all actions
* Adds content for DCs to talk to proxies on `tcp/4119`

Equip SG adjustment

---

terraform/environments/equip/alb.tf
terraform/environments/equip/application_variables.json
terraform/environments/equip/citrix_adc.tf
terraform/environments/equip/policy.tf
terraform/environments/equip/securitygroup.tf

* Adds security group rules requested by team
* Adds subnet reservation & private IP addressing requested by team

Equip ADC adjustments

---

terraform/environments/equip/application_variables.json
terraform/environments/equip/securitygroup.tf

* Updates security groups in line with updates from Equip team

Update Equip security groups

---

terraform/environments/equip/alb.tf
terraform/environments/equip/dns.tf
terraform/environments/equip/locals.tf

* Removes ACM generated certificate as this cannot be exported for use with netscaler

Equip production changes

---

terraform/environments/equip/alb.tf
terraform/environments/equip/application_variables.json
terraform/environments/equip/s3-awslogs.tf
terraform/environments/equip/versions.tf

* Amend listener and SG for alb-to-netscaler
* Add random suffix to log bucket names

Adjustments for netscaler

---

terraform/environments/equip/alb.tf
terraform/environments/equip/application_variables.json
terraform/environments/equip/securitygroup.tf

* Update listener rules to point at new targets
* Add security group statements required for these flows

updated ALB listener rules

---

terraform/environments/equip/alb.tf
terraform/environments/equip/data.tf
terraform/environments/equip/dns.tf

* Correct reference to host in target group
* Add DNS records for subdomains

Equip public dns records

---

terraform/environments/equip/securitygroup.tf

* Add egress rules to all hosts to allow domain controller traffic

Equip hosts to domain controllers

---

terraform/environments/xhibit-portal/database-server-baremetal.tf

Fix the error with the network adaptor that didn't show as we aren't deploying this server to dev or pre-prod to reduce costs

Update the network adaptor resource

---

terraform/environments/xhibit-portal/database-server-baremetal.tf

The count on the adaptor was causing issues with deploying, so removed.

Remove count on adaptor

---

terraform/environments/equip/s3-ukcloud-replica.tf
terraform/environments/equip/s3.tf

* Creates an S3 bucket purely for Equip Production

Equip production S3

---

terraform/environments/equip/application_variables.json
terraform/environments/equip/citrix_adc.tf
terraform/environments/equip/dns.tf
terraform/environments/equip/securitygroup.tf

* Create EIP
* Associated with Netscaler public interface
* Update `gateway.equip.service.justice.gov.uk` to point at EIP

Netscaler EIP

---

terraform/environments/nomis/application_variables.tf

Audit u02 filesystem increase from 800G to 5TB

Audit u02 filesystem increase from 800G to 5TB

---

terraform/environments/equip/main.tf
terraform/environments/equip/securitygroup.tf

Allow SOC instance to send emails through EQP01 for security alerts

added SOC security group to SOC instance

---

terraform/environments/equip/ses.tf

* Add conditional count statements to all SES resources where not present
* Amend attribute references to account for these conditional counts

made SES configured only applicable to production

---

terraform/environments/xhibit-portal/importmachine.tf

increasing size or volume to 60GB

increase import machine root vol to 60GB

---

terraform/environments/xhibit-portal/database-server-baremetal.tf

These changes add a new disk and ENI for the app server, which will be migrated to the bare metal server we have running, for performance reasons

XPM-122: Add in the new Disk and ENI for the app server migration to the bare metal server.

---

terraform/environments/sprinkler/kms.tf
terraform/environments/sprinkler/main.tf
terraform/environments/sprinkler/monitoring.tf

This PR adds some configuration where appropriate to address tfsec/checkov reported issues, as well as ignore/skip statements where these reports are not relevant

Sprinkler tfsec/checkov checks

---

terraform/environments/nomis/application_variables.tf

Adding a test instance do conduct tests as per https://dsdmoj.atlassian.net/jira/software/c/projects/DSOS/boards/889?modal=detail&selectedIssue=DSOS-608

Added test CNOMT1 to investigate in-place updates of db instances

---

terraform/environments/nomis/application_variables.tf

Updating the AMI version to test the in place update of db instance

Update AMI on CNOMT1TEST

---

terraform/environments/xhibit-portal/lambda/delete_old_ami.py

Updating the error handling code (for ami/snapshots in use)

Update delete AMI lambda error handling

---

terraform/environments/nomis/application_variables.tf

- Adding NDH VM instance in prod.
- fmt.

DSOS-1407 - Build NDH VM in production

---

terraform/environments/sprinkler/data.tf
terraform/environments/sprinkler/db_manager.tf
terraform/environments/sprinkler/main.tf
terraform/environments/sprinkler/providers.tf

* Set up module to allow use of Github OIDC

Sprinkler OIDC

---

.github/workflows/nomis.yml
terraform/environments/nomis/ec2-jumpserver.tf
terraform/environments/nomis/providers.tf
terraform/environments/nomis/versions.tf

utilise the GitHub integration to get a list of users to create accounts for

Get user list from GitHub team

---

terraform/environments/xhibit-portal/prtg-load-balancer.tf
terraform/environments/xhibit-portal/waf-load-balancer.tf

The production deployment didn't work as I needed the count meta argument on the policies

Updated count for the bucket policy

---

terraform/environments/xhibit-portal/importmachine.tf

Re-apply prevent destroy flag after https://github.com/ministryofjustice/modernisation-platform-environments/pull/838

Update prevent destroy flag

---

terraform/environments/nomis/application_variables.tf
terraform/environments/nomis/modules/database/main.tf

Removing infra changes added as a part of the spike ticket

Removing CNOMT1TEST instance

---

terraform/environments/nomis/packer.tf

Adding permissions to packer-build profile so that it can access hmpps KMS key

Adding permissions to packer-build profile

---

.github/workflows/nomis.yml
terraform/environments/nomis/application_variables.tf
terraform/environments/nomis/ec2-test_instance.tf
terraform/environments/nomis/modules/test_instance_asg/README.md
terraform/environments/nomis/modules/test_instance_asg/main.tf
terraform/environments/nomis/modules/test_instance_asg/user_data/ansible.sh.tftpl
terraform/environments/nomis/modules/test_instance_asg/variables.tf
terraform/environments/nomis/variables.tf

Demonstration of how EC2 instances can be provisioned by ansible, and managed in-life by ansible.  Tested in nomis-test environment via the test-instance-asg module.
- added user-data ansible script
- added github branch and repo args to test-instance-asg module
Updated nomis pipeline to include branch name / gh actor name in same way as AMI repo.

nomis: DSOS-1466: ec2 provisioning strategy

---

terraform/environments/nomis/ssm-documents/templates/s3auditupload.yaml.tftmpl

- Adding Ansible script.
- Fixing hosts targets.
- Fixing typo.
- Adding SSM document.
- Removing duplicate resource.
- Commit changes made by code formatters
- terraform fmt.
- Fixing bucket
- Forgot a rather critical dependent package.

DSOS-1434: Add Git Dependency

---

terraform/environments/nomis/modules/sns_topic/main.tf
terraform/environments/nomis/modules/sns_topic/variables.tf
terraform/environments/nomis/sns.tf

create an empty parameter, don't munge the contents because we are updating by hand for now

update SNS setup

---

terraform/environments/cooker/locals.tf
terraform/environments/equip/locals.tf
terraform/environments/ppud/locals.tf
terraform/environments/tariff/locals.tf
terraform/environments/threat-and-vulnerability-mgmt/locals.tf

Teams will need to do this, giving them a helping hand changing it before its a problem.

Changed body to response_body,  as The attribute body is deprecated.

---

terraform/environments/nomis/application_variables.tf

DSOS-1507: fix oracle-sids tag

---

terraform/environments/nomis/application_variables.tf

Added prod-nomis-db-2 to replace existing database-AUDIT.
Added comments re agreed naming with DBAs.
Dropped u02 down to 1TB following discussion with DBAs.

DSOS-1499: add production audit database

---

.github/workflows/terraform-static-analysis.yml
terraform/environments/example/application_variables.json
terraform/environments/example/data.tf
terraform/environments/example/loadbalancer.tf
terraform/environments/example/loadbalancer_using_module.tf
terraform/environments/example/rds.tf
terraform/environments/example/s3.tf
terraform/environments/example/versions.tf

Made some changes to the example code so that it builds.

Fix Example code

---

terraform/environments/nomis/ec2-database.tf

permission needed is 'ListBucket' not ListObject

fix permission typo

---

terraform/environments/performance-hub/README.md

Kept this fairly lightweight - let me know if you need more detail anywhere.

First draft of Performance Hub runbook

---

terraform/environments/xhibit-portal/network-infrastructure.tf

Xpm175 lock dn sec grp

---

terraform/environments/performance-hub/application_variables.json

This is the new one: https://eu-west-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ami-windows-latest/Windows_Server-2019-English-Full-ECS_Optimized/description?region=eu-west-1

Current AMI has been deprecated - adding new AMI ID

---

terraform/environments/performance-hub/application_variables.json

Sorry, I picked up the AMI ID for eu-west-1 earlier

AMI ID for eu-west-2 (hopefully)

---

terraform/environments/nomis/nomis-production.tf

increase u02 disk to 3TB on prod-nomis-db-2

---

terraform/environments/nomis/nomis-test.tf

Create a couple of NDH instances for Tony

DSOS-1543: add test NDH instances

---

terraform/environments/nomis/nomis-development.tf

Plus tweaked description of other dev ASGs.

nomis: DSOS-1440: add nomis ASG to dev for testing weblogic image

---

terraform/environments/nomis/nomis-development.tf

For weblogic testing using the T1 dataset.

Nomis: DSOS-1440: add dev db

---

terraform/environments/mlra/alb.tf
terraform/environments/mlra/ecs.tf
terraform/environments/mlra/modules/alb/main.tf
terraform/environments/mlra/networklb.tf

- Adds Network LoadBalancer that accepts incoming requests from LAA LZ and routes to internal-scheme ALB.
- Amends the ALBs ingress security group to use the LAA LZ CIDR parameter.

MLRA/LAWS-2887 - Adds NLB. Amends ALB ingress SG to use the laa lz cidr parameter.

---

.github/workflows/scorecards.yml

Start running OSSF scans to check for issues in github actions.

Start using OSSF scan

---

.github/workflows/format-code.yml
.github/workflows/generate-dependabot-file.yml
.github/workflows/go-tests.yml
.github/workflows/terraform-static-analysis.yml

As per github security guidance

Pin github actions to hash

---

terraform/environments/mlra/lz-conn-test.tf

LAWS-2898
To assist in troubleshooting inter-account connectivity

Add Session Manager Access to Network-Connectivity Test Instance

---

terraform/environments/nomis/nomis-test.tf

default iops and throughput are good enough 3000 baseline iops in gp3 + 125 MiBps

upgrade to gp3 in place DSOS-1565

---

terraform/environments/nomis/nomis-production.tf

then we can test from this baseline for any further performance issue.

squash all types to gp3 defaults - DSOS-1565

---

terraform/environments/mlra/lz-conn-test.tf

Network Connectivity Tester Instance - SG Changes

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/providers.tf

, refactor pending so this is just to get our RDS stuff up and running

update to reflect other environments

---

terraform/environments/nomis/ec2-common.tf
terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-jumpserver-new.tf
terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/modules/database/main.tf
terraform/environments/nomis/modules/database/versions.tf
terraform/environments/nomis/modules/ec2_autoscaling_group/main.tf
terraform/environments/nomis/modules/ec2_autoscaling_group/variables.tf
terraform/environments/nomis/modules/ec2_autoscaling_group/versions.tf
terraform/environments/nomis/modules/ec2_instance/main.tf
terraform/environments/nomis/modules/ec2_instance/variables.tf
terraform/environments/nomis/modules/ec2_instance/versions.tf
terraform/environments/nomis/nomis-production.tf
terraform/environments/nomis/nomis-test.tf

trying to give the optional var a default value to please checkov

DSOS-1586 - see if this pleases Checkov

---

terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/modules/ec2_autoscaling_group/main.tf
terraform/environments/nomis/nomis-development.tf
terraform/environments/nomis/nomis-test.tf

Added autoscale groups for base images - so we have another place to test as well as nomis-development.
Fixed modules as required so this worked

DSOS-1578: test baseimages for weblogic

---

terraform/environments/nomis/nomis-test.tf

Nomis: migrate ndh to asg

---

.github/workflows/mlra.yml

These were missed during the environment creation process

Uncomment missing environments

---

terraform/environments/delius-iaps/ad.tf
terraform/environments/delius-iaps/secrets.tf

Work item: https://dsdmoj.atlassian.net/browse/NIT-444
Added AD to IAPS

Added AWS directory service and secret

---

terraform/environments/delius-iaps/ad.tf
terraform/environments/delius-iaps/application_variables.json

Work item nit-444 - Adding in code to create a managed AD, with logging enabled and Route53 resolver rule to enable domain FQDN name resolution.

Introduce delius iaps AD

---

terraform/environments/mlra/alb.tf
terraform/environments/mlra/cloudwatch.tf
terraform/environments/mlra/ecs.tf
terraform/environments/mlra/networklb.tf
terraform/environments/mlra/selenium_s3.tf

All the module calls have been implemented, for this branch which sets up the ec2-instance with a http server in the Production account for TGW testing purposes.

remove comments from all module calls

---

terraform/environments/delius-iaps/application_variables.json
terraform/environments/delius-iaps/ec2.tf

Work item nit458.
Adding in launch template and ASG (to replace standalone instance)

Adding launch template and asg

---

terraform/environments/nomis/modules/ec2_autoscaling_group/README.md
terraform/environments/nomis/nomis-test.tf
terraform/environments/nomis/versions.tf

needs changing so as not to run into version constraints elsewhere

fix random provider version

---

terraform/environments/oasys/application_variables.json
terraform/environments/oasys/rds.tf

disable rds for oasys prod for time being

---

terraform/environments/nomis/modules/ec2_instance/locals.tf

second attempt, fix idiotic typo!

nomis: fix to ec2_instance module introduced couple of PRs ago v2

---

terraform/environments/digital-prison-reporting/main.tf
terraform/environments/digital-prison-reporting/modules/ec2/iam.tf
terraform/environments/digital-prison-reporting/modules/ec2/main.tf
terraform/environments/digital-prison-reporting/modules/kinesis_stream/main.tf

Remove hard coded account numbers

---

terraform/environments/performance-hub/application_variables.json
terraform/environments/performance-hub/db_manager.tf
terraform/environments/performance-hub/main.tf

Following best practice, removing hard coded account number references.

Remove hard coded account number references

---

terraform/environments/maatdb/application_variables.json
terraform/environments/maatdb/rds.tf

Remove hard coded account number

---

terraform/environments/nomis/ec2-jumpserver.tf
terraform/environments/nomis/ec2-test.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/locals.tf
terraform/environments/oasys/common.tf
terraform/environments/oasys/locals.tf
terraform/modules/ec2_autoscaling_group/data.tf
terraform/modules/ec2_autoscaling_group/locals.tf
terraform/modules/ec2_autoscaling_group/variables.tf

var simplication

---

terraform/environments/maatdb/application_variables.json
terraform/environments/maatdb/modules/rds/rds.tf
terraform/environments/maatdb/modules/rds/variables.tf
terraform/environments/maatdb/rds.tf

DB Identifier was a random value. This replaces it with something more useful.

Removed the random db identifier with a more useful value.

---

terraform/environments/ccms-ebs/bastion.tf
terraform/environments/ccms-ebs/bastion_linux.json

Add a bastion to the ccms-ebs environment to enable sideways ssh to problematic boxes that cannot connect through SSM

add bastion box

---

.github/workflows/ccms-ebs.yml

this enables the workflows for the new ccms accounts that have been created

enable ccms workflows for new environments

---

terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf

Add some additional tags, and corrected some existing tags, used by the prometheus monitoring

DSOS-1645: add additional tags for monitoring

---

terraform/environments/long-term-storage/bastion_linux.tf
terraform/environments/long-term-storage/hmpps-intranet.tf

Also added link to guidance doc provided to HMPPS

Comment out bastion whilst not in use

---

terraform/environments/ccms-ebs/application_variables.json
terraform/environments/ccms-ebs/iam.tf
terraform/environments/ccms-ebs/security_groups.tf

Make security group and iam more generic

generic fixes

---

terraform/modules/ec2_autoscaling_group/variables.tf

correct_monitoring_type

---

terraform/environments/oas/application_variables.json
terraform/environments/oas/data.tf
terraform/environments/oas/ec2.tf

code added to new branch with OAS code only as per ticket LAWS-2954: 
Create EC2 instance, security group, IAM instance profile, IAM role, EBS volumes, relevant secrets.
OAS code copied 
FROM old branch oas/ec2-core-dev-build 
TO
oas/ec2-oas-build

LAWS-2954: OAS ec2 core dev build

---

terraform/environments/nomis/monitoring-alerts.tf
terraform/modules/ec2_instance/README.md

alerts triggered if there's an issue with oracle db connectivity or the batch processing

alerts for oracle db connectivity

---

terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf

Sets up weblogic log groups for other platforms in nomis-* environment

add weblogic log group setup to other environments

---

terraform/environments/nomis/ec2-weblogic.tf

Otherwise the server gets killed if you take down weblogic

DSOS-1703: use EC2 healthcheck for weblogic ASG

---

terraform/environments/delius-iaps/application_variables.json
terraform/environments/delius-iaps/ec2-iaps-server.tf

Adding log groups for hmpps delius-iaps cloudwatch agent

---

terraform/environments/nomis/locals-test.tf

Some rejigging of load balancer code - first need to remove current setup

nomis: DSOS-1704: remove load balancer config from ASGs prior to refactor

---

terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/lb-listeners.tf
terraform/environments/nomis/locals-lb-listeners.tf
terraform/environments/nomis/locals-lbs.tf
terraform/environments/nomis/locals-test.tf
terraform/modules/lb_listener/main.tf
terraform/modules/lb_listener/variables.tf

Re-created the load balancers for T1.
The target groups now sit in the autoscaling group.

Nomis: DSOS-1704: redo loadbalancer part2

---

terraform/environments/nomis/locals-test.tf

This will allow Sandhya and myself to test independently of each other.

nomis: DSOS-1757: create 2nd weblogic ASG in nomis-test

---

terraform/environments/nomis/locals-production.tf

resize prod-nomis-db-3

---

terraform/environments/nomis/monitoring-alerts.tf

haven't quite understood alert naming so this fixes one of them as a test
will apply this across the board once it's approved

fix alert naming

---

terraform/environments/ccms-ebs/ec2_base.tf
terraform/environments/ccms-ebs/ec2_ftp.tf
terraform/environments/ccms-ebs/ec2_oracle_accessgate.tf
terraform/environments/ccms-ebs/ec2_oracle_ebs.tf
terraform/environments/ccms-ebs/ec2_oracle_ebs_apps.tf
terraform/environments/ccms-ebs/ec2_oracle_webgate.tf
terraform/environments/ccms-ebs/iam.tf

CCMS-EBS: iam_instace_profile_oracle_base -> iam_instace_profile_ccms_base

CCMS-EBS: iam_instace_profile_oracle_base -> iam_instace_profile_ccms_base

---

terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-test.tf

Drop ASG count back down to zero for the 2nd weblogic ASG since not needed right now
Also removed misleading branch comment which would have no effect if you uncommented.

Nomis: DSOS-1757: weblogic testing

---

terraform/modules/ec2_autoscaling_group/variables.tf
terraform/modules/ec2_instance/variables.tf

Need to allow others to not supply a value for this into the module

add empty default value to module

---

terraform/environments/oasys/locals_development.tf

Commas are not allowed in tag values.

Removed comma from tag

---

terraform/environments/laa-oem/platform_backend.tf
terraform/environments/tipstaff/platform_backend.tf

This is in the new template but currently not working.

Remove dynamodb table for state locking

---

.github/workflows/ppud.yml

Also commenting out prod for now until they are ready to build out this env.

Amend workflow to start deployments to preprod

---

.github/workflows/reusable_terraform_plan_apply.yml

Fix to re-usable pipeline.  Mistake in apply step.  Fixing

nomis: DSOS-1519: pipeline fix plan file should be last arg in apply

---

terraform/environments/apex/networking.auto.tfvars.json
terraform/environments/ccms-ebs/networking.auto.tfvars.json
terraform/environments/cooker/networking.auto.tfvars.json
terraform/environments/data-and-insights-wepi/networking.auto.tfvars.json
terraform/environments/delius-iaps/networking.auto.tfvars.json
terraform/environments/delius-jitbit/networking.auto.tfvars.json
terraform/environments/digital-prison-reporting/networking.auto.tfvars.json
terraform/environments/equip/networking.auto.tfvars.json
terraform/environments/example/networking.auto.tfvars.json
terraform/environments/laa-oem/networking.auto.tfvars.json
terraform/environments/long-term-storage/networking.auto.tfvars.json
terraform/environments/maatdb/networking.auto.tfvars.json
terraform/environments/mlra/networking.auto.tfvars.json
terraform/environments/nomis-combined-reporting/networking.auto.tfvars.json
terraform/environments/nomis/networking.auto.tfvars.json
terraform/environments/oas/networking.auto.tfvars.json
terraform/environments/oasys/networking.auto.tfvars.json
terraform/environments/performance-hub/networking.auto.tfvars.json
terraform/environments/ppud/networking.auto.tfvars.json
terraform/environments/refer-monitor/networking.auto.tfvars.json
terraform/environments/sprinkler/networking.auto.tfvars.json
terraform/environments/tariff/networking.auto.tfvars.json
terraform/environments/tipstaff/networking.auto.tfvars.json
terraform/environments/xhibit-portal/networking.auto.tfvars.json

This is currently preventing deployments.

Revert changes to networking configuration

---

.github/workflows/reusable_terraform_strategy.yml

Fixed typo to ensure deploys to prod after merge into main

nomis: DSOS-1519: reusable pipeline fix

---

terraform/environments/oasys/locals_development.tf

DSOS-1697/onr-db

---

terraform/environments/oasys/locals_development.tf

shutdown-onr-db-for-now

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/main.tf
terraform/environments/oasys/security_groups.tf

Also adding the associated security group. This deployment does not include the listeners. They will be deployed in future PRs.

Adding load balancer in oasys-development

---

terraform/environments/tipstaff/application_variables.json
terraform/environments/tipstaff/member_secrets.tf
terraform/environments/tipstaff/platform_providers.tf
terraform/environments/tipstaff/rds.tf

Reverts ministryofjustice/modernisation-platform-environments#1498

Revert "Fix Tipstaff rds on development env"

---

terraform/environments/nomis/locals-test.tf

Create a 2nd weblogic ASG which runs ansible from a branch for testing purposes

nomis: create second weblogic ASG for Sandhya

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_development.tf

web and db use rh 8.5

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_development.tf

update os version

---

terraform/environments/oasys/locals_development.tf

adjust oasys db disks

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_development.tf
terraform/environments/oasys/main.tf

database to asg for dev

---

terraform/environments/oasys/locals.tf

oasys-db-disk-changes

---

terraform/environments/oasys/data.tf
terraform/environments/oasys/locals.tf
terraform/environments/oasys/templates/ansible-ec2provision.sh.tftpl

test oasys db ansible

---

terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-test.tf

Drop test ASG count back down to zero
Update weblogic AMI image which aligns oracle UIDs with the database

Nomis: DSOS-1817: update weblogic ami

---

terraform/environments/oasys/locals_development.tf

Sandhya was still using one of the servers. Sorry Sandhya! 😬

Rolling back the previous PR

---

terraform/environments/delius-core/ecs_cluster.tf
terraform/environments/delius-core/ecs_service_delius_db.tf

Probation webops work item 579. 
Creation of ECS cluster for delius core and service/task definition for delius testing db.

HMPPS Delius Core ECS cluster and testing db service

---

terraform/environments/example/certificates.tf

Create a certificate in example, providing a template for other customers to use.

added content for example certificate creation

---

.github/workflows/ppud.yml

In response to a request from the PPUD team to start building out their production environments, this PR enables the `production` environment in the PPUD workflow.

enable PPUD production workflow

---

terraform/environments/delius-core/application_variables.json
terraform/environments/delius-core/rds.tf

Create RDS instance and related resources for delius core

Adding delius-core rds-related resources

---

terraform/environments/performance-hub/database.tf
terraform/environments/performance-hub/ecs.tf
terraform/environments/performance-hub/module/ecs/main.tf
terraform/environments/performance-hub/module/ecs/outputs.tf
terraform/environments/performance-hub/module/ecs/variables.tf
terraform/environments/performance-hub/module/ecs/versions.tf
terraform/environments/performance-hub/outputs.tf

New Module created for performance hub as the current module is going to be retired move function added but hashed out for use later
the move function is required so that no resources will be destroyed
currently with the move module unhashed out the plan fails in development as this is currently not built so there is no module to move from.

New performance hub ecs module

---

terraform/environments/nomis-combined-reporting/baseline.tf
terraform/environments/nomis-combined-reporting/locals_test.tf
terraform/modules/baseline/rds_instance.tf
terraform/modules/baseline/variables.tf
terraform/modules/baseline_presets/rds_instance.tf
terraform/modules/rds_instance/data.tf
terraform/modules/rds_instance/main.tf
terraform/modules/rds_instance/variables.tf

RDS Baseline Preset Take 1

---

terraform/environments/oasys/locals_preproduction.tf

create a test instance
re-create the bastion in oasys-preproduction as deletion wasn't 100% successful due to a dependency issue on deletion

Oasys/dsos 1801/deploy test instance

---

.github/workflows/format-code.yml

In line with [this story](https://github.com/ministryofjustice/modernisation-platform/issues/3396) in the modernisation-platform repository, this PR replaces the code-formatter that fires in response to a pull request with a scheduled job that runs on a scheduled basis during the week.

Replace code formatting job

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_development.tf
terraform/modules/baseline_presets/ec2_instance.tf

oasys-db-disks

---

.github/workflows/format-code.yml

Every day is excessive and extra work approving PRs daily, once per week should be enough

Run code formatter once a week

---

terraform/environments/digital-prison-reporting/main.tf
terraform/environments/digital-prison-reporting/modules/dynamo_tables/outputs.tf
terraform/environments/digital-prison-reporting/modules/dynamo_tables/tables.tf
terraform/environments/digital-prison-reporting/modules/dynamo_tables/variables.tf
terraform/environments/digital-prison-reporting/outputs.tf

DPR-306, Onboard DynamoDB Table

---

terraform/environments/nomis/locals-test.tf
terraform/modules/baseline/lb.tf
terraform/modules/baseline/variables.tf
terraform/modules/lb_listener/locals.tf
terraform/modules/lb_listener/main.tf
terraform/modules/lb_listener/variables.tf

lb_listeners module creates alarms per `alarm_target_group_names` value for a particular listener

make lb alarms accessible from the lb_listeners module

---

terraform/environments/nomis-combined-reporting/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis-data-hub/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/templates/ansible-ec2provision.sh.tftpl
terraform/environments/oasys/templates/ansible-ec2provision.sh.tftpl

Updated ansible provisioning scripts so it can clone via a release tag or SHA1, not just a branch.
Updated T1 weblogic ASG to use a specific SHA which is known to work

Nomis: DSOS-1843: ansible template improvements

---

terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf

Fixed nomis DNS entries for the external mod platform domain

nomis: DSOS-1843: fix DNS entries

---

terraform/environments/oasys/locals.tf

oasys db set ansible

---

terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-test.tf

Getting rid of the old ASGs - will re-create via baseline in a later PR

nomis: DSOS-1847: remove old ASGs

---

terraform/environments/nomis/locals-test.tf

For Sandhya testing DB restore script

nomis: DSOS-1833: add second T1 DB for testing

---

terraform/environments/nomis/baseline.tf
terraform/environments/nomis/baseline_presets.tf
terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf

Add the dev ASGs back in.  Plus corrected some nbsp chars + added a few more baseline resources.

Nomis: DSOS-1847: add dev instances back in

---

terraform/environments/oasys/locals_production.tf

temporarily delete lb

---

terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/locals.tf

Decision following migration review to support new style service domain as well as the old az domain.  Add the necessary domains and update hostnames.

nomis: DSOS-1862: add new nomis DNS zones

---

terraform/environments/oasys/locals_production.tf

add back rule

---

terraform/environments/equip/monitoring.tf
terraform/environments/performance-hub/monitoring.tf
terraform/environments/sprinkler/monitoring.tf

Switching member DDOS alarms to the new pagerduty DDOS service.

Switch alarms to new pagerduty services

---

terraform/environments/nomis/baseline.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/locals.tf
terraform/environments/nomis/outputs.tf
terraform/modules/acm_certificate/README.md
terraform/modules/acm_certificate/locals.tf
terraform/modules/acm_certificate/main.tf
terraform/modules/acm_certificate/outputs.tf
terraform/modules/acm_certificate/variables.tf
terraform/modules/baseline/acm_certificate.tf
terraform/modules/baseline/lb.tf
terraform/modules/baseline/variables.tf

Allow an ACM certificate to include an external zone, e.g. hosted in Azure
- added additional options to support this (it's a 2 step process)
- updated README
- applied in nomis-test after much faffing

Nomis: DSOS-1862: updated nomis-test cert

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_production.tf
terraform/environments/oasys/locals_test.tf

neaten oasys web

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_production.tf

oasys rename tag

---

terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf

Need to add new service domain into SSL cert.  Before replacing the cert, need to temporarily remove the listeners (not in use yet)

DSOS-1862: remove preprod and prod listeners before we replace SSL cert

---

terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf

Include additional wildcards required for the migration

nomis: DSOS-1862: new preprod and prod certs for nomis

---

terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf

update validation status for new certs

nomis: DSOS-1862: update preprod and prod certs

---

terraform/environments/hmpps-intelligence-management/s3.tf

Adding s3 bucket for data extract

Hmpps intelligent management s3

---

terraform/environments/oasys/locals.tf

oasys web use ami disks

---

terraform/environments/example/r53.tf

Related to this ticket- https://github.com/ministryofjustice/modernisation-platform/issues/3032
I added the creation of a record pointing at a public load balancer DNS address which already existed in example. 
Terraform applies and works.

Created nnew file for the r53 record for example.

---

.github/workflows/labeler.yml

Added the labeler file before but forgot the action. Facepalm.

Add missing labeler action

---

terraform/environments/nomis/locals-test.tf
terraform/modules/baseline/ec2_autoscaling_group.tf
terraform/modules/baseline/ec2_instance.tf
terraform/modules/baseline/route53.tf
terraform/modules/baseline/security_groups.tf
terraform/modules/lb_listener/main.tf
terraform/modules/rds_instance/main.tf

Raised tickets and disabled some checkov errors in baseline.

Nomis: DSOS-1847: checkov fixes

---

terraform/environments/data-platform/glue_job.tf
terraform/environments/data-platform/glue_script/glue_transform_script.py
terraform/environments/data-platform/locals.tf

glue job infra and script for transforming data product and registering in glue catalog

Dplab 42/glue job

---

.github/workflows/reusable_terraform_plan_apply.yml
terraform/environments/nomis/baseline.tf
terraform/environments/nomis/ec2-common.tf
terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/locals.tf
terraform/environments/nomis/scripts/terraform-state-mv.conf
terraform/environments/nomis/scripts/terraform-state-mv.sh
terraform/environments/nomis/scripts/update-db-az-sas-token.sh

Just moving stuff around and into baseline module.  Added a script to do the terraform state move which I've already ran.  So plan should be clean.

Nomis: DSOS-1847: baseline log groups

---

terraform/environments/nomis/locals-production.tf

nomis: DSOS-1847: correct prod log retention

---

terraform/environments/ppud/kms.tf
terraform/environments/ppud/monitoring.tf

Setting up the DDOS attack AWS Shield enablement for ppud. Needed for some security checks on 26th April.
Manually set the SRT access as per our instructions.

Adding new monitoring on ppud for use in development, initially

---

terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf

Create new weblogic.  Note using a/b naming since green ran into name length issues

Nomis: DSOS-1847: test weblogic with new policies

---

terraform/environments/nomis/baseline_presets.tf
terraform/environments/nomis/ec2-database.tf
terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-development.tf
terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf
terraform/environments/nomis/monitoring-setup.tf

Temporarily zap current resources

Nomis: DSOS-1847: migrate sns part1

---

terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf

Switch to the -b servers which I've checked our working.  Drop the -a count down to zero.

nomis: DSOS-1847: switch to the new weblogic servers

---

terraform/environments/delius-jitbit/application_variables.json
terraform/environments/delius-jitbit/rds.tf

Changes snapshot name and some small terraform fmt reformatting.

Restore hmpps jitbit dev db from new rds snapshot

---

terraform/environments/nomis/ec2-weblogic.tf
terraform/environments/nomis/locals-preproduction.tf
terraform/environments/nomis/locals-production.tf
terraform/environments/nomis/locals-test.tf

Update the non-active "A" weblogic group to use new database string.

Nomis: DSOS-1815: test new weblogic connection string

---

terraform/environments/mlra/modules/codebuild/main.tf

This updates the codebuild resource with the amended runtime version that's recently been applied in the LZ. Note the deployment error in Test concerns a known bug with the mod platform's S3 module.

Update mlra coebuild runtime

---

terraform/environments/nomis/locals.tf
terraform/modules/baseline_presets/iam_policies.tf
terraform/modules/baseline_presets/variables.tf

Fix missing policy required for creating backups

nomis: add additional policy for oracle secure web

---

terraform/environments/mlra/modules/alb/main.tf

Updates the version of the remote s3 module used to 6.4.

---

terraform/environments/example/application_variables.json
terraform/environments/example/ecs.tf
terraform/environments/nomis/ec2-common.tf

example code for ecs

---

terraform/environments/delius-jitbit/application_variables.json
terraform/environments/delius-jitbit/s3.tf

nit-634 - Codifying required configuration to allow migration of content from source account.

Support Datasync migration to HMPPS Jitbit app bucket

---

terraform/environments/nomis/locals_database.tf

alarm description references wrong service

alarm description was incorrect

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/main.tf

new code appears to be working.  Switch to the new deployment and zap the old.  Plus some comments

nomis: DSOS-1874: switch to green deployment

---

terraform/environments/oasys/locals_test.tf

oasys-test-public-lb

---

terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_production.tf
terraform/environments/oasys/locals_security_groups.tf
terraform/environments/oasys/locals_test.tf

I made changes to `terraform/environments/oasys/locals_security_groups.tf`. All other changes are a result of `terraform fmt`.

Added CIDR block to security group

---

terraform/environments/laa-oem/application_variables.json
terraform/environments/laa-oem/member_certificates.tf
terraform/environments/laa-oem/member_data.tf
terraform/environments/laa-oem/member_locals.tf
terraform/environments/laa-oem/oem_ec2_app.tf
terraform/environments/laa-oem/oem_ec2_app_efs.tf
terraform/environments/laa-oem/oem_ec2_app_lb_internal.tf
terraform/environments/laa-oem/oem_ec2_app_sg.tf
terraform/environments/laa-oem/oem_ec2_db.tf
terraform/environments/laa-oem/oem_ec2_db_efs.tf
terraform/environments/laa-oem/oem_ec2_db_sg.tf
terraform/environments/laa-oem/oem_ec2_wl.tf
terraform/environments/laa-oem/oem_ec2_wl_sg.tf
terraform/environments/laa-oem/oem_outputs.tf
terraform/environments/laa-oem/oem_route53.tf
terraform/environments/laa-oem/templates/oem-user-data-db.sh
terraform/environments/laa-oem/templates/oem-user-data-wl.sh

- Amended OEM App LB configuration (listeners, target groups).
- Amended rules in Security Groups.
- Amended ec2_oem_instance_type_db, ec2_zone.
- Use the ebs_shared KMS key in volumes.
- Added code for generating certificates.
- Added restorable_by_user_ids to data.aws_ebs_snapshot blocks.
- Added aws_key_pair resources.
- Added volume-backup tags.
- Added an internal Load Balancer for App (for testing purposes).
- Added a Weblogic instance (for testing purposes).

Multiple changes in laa-oem

---

terraform/environments/laa-oem/oem_ec2_app_lb_internal.tf

data.aws_subnets fix: private-public -> shared-private.

data.aws_subnets fix: private-public -> shared-private.

---

terraform/environments/laa-oem/application_variables.json
terraform/environments/laa-oem/member_data.tf
terraform/environments/laa-oem/oem_ec2_app.tf
terraform/environments/laa-oem/oem_ec2_db.tf
terraform/environments/laa-oem/oem_ec2_wl.tf
terraform/environments/laa-oem/oem_outputs.tf

LAA-OEM: data.aws_ami ec2_laa_oem_development -> ec2_laa_oem.

LAA-OEM: data.aws_ami ec2_laa_oem_development -> ec2_laa_oem.

---

terraform/environments/oasys/locals.tf

unpin oasys db ansible

---

terraform/environments/nomis/locals_development.tf

Added new ASG for RHEL8.5 testing on Sandhya's request.  Will be for Oracle Enterprise Management testing.
Also set the dev ASGs to use any availability zone.

nomis: DSOS-1363: asg for oem testing

---

terraform/environments/oasys/locals.tf

oasys db use older ansible

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_test.tf
terraform/modules/baseline/route53.tf

oasys web lb

---

terraform/environments/nomis/locals_test.tf

Add new T1 DB (already created) and delete old ones that are no longer used

Nomis: DSOS-1833: add new t1 DB and delete old DBs

---

terraform/environments/oasys/locals.tf

oasys-db-latest-ansible

---

terraform/environments/ccms-ebs/application_variables.json
terraform/environments/ccms-ebs/secrets.tf
terraform/environments/ccms-ebs/ses.tf

CC-1805: Initial SES configuration.

CC-1805: Initial SES configuration.

---

terraform/environments/ccms-ebs/ec2_mailrelay.tf
terraform/environments/ccms-ebs/secrets.tf
terraform/environments/ccms-ebs/templates/ec2_user_data_mailrelay.sh

CC-1804: Updated ec2_user_data_mailrelay.sh

CC-1804: Updated ec2_user_data_mailrelay.sh

---

terraform/environments/ccms-ebs/alb.tf

Create aws_lb_listener.ebsapps_listener in Production.

Create aws_lb_listener.ebsapps_listener in Production.

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_security_groups.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/modules/ip_addresses/modernisation_platform.tf
terraform/modules/ip_addresses/outputs.tf

Extended size of t1 DB.
Updated DNS entries for secondary DBs to point at mod platform
Set t1-nomis-web-a test for new init.d scripts
Add additonal mod platform IPs into IP module

nomis: DSOS-1820: weblogic miscellaneous changes

---

terraform/environments/ccms-ebs/ec2_mailrelay.tf

CC-1804: Commented out aws_route53_record.route53_record_mailrelay

CC-1804: Commented out aws_route53_record.route53_record_mailrelay

---

terraform/environments/ccms-ebs/templates/ec2_user_data_mailrelay.sh

CC-1804: Use current region in /etc/postfix/sasl_passwd.

CC-1804: Use current region in /etc/postfix/sasl_passwd.

---

terraform/environments/ccms-ebs/templates/ec2_user_data_mailrelay.sh

CC-1804: Fixed typos.

---

terraform/environments/data-platform/glue_job_spark.tf
terraform/environments/data-platform/lambda_for_authoriser.tf
terraform/environments/data-platform/lambda_for_code.tf
terraform/environments/data-platform/lambda_for_data.tf
terraform/environments/data-platform/lambda_for_presigned_url.tf
terraform/environments/data-platform/src/presigned_url/main.py

https://github.com/ministryofjustice/data-platform/issues/395

Presigned url generator lambda

---

terraform/environments/laa-oem/oem_ec2_wl.tf
terraform/environments/laa-oem/oem_ec2_wl_sg.tf

OEM: Added a condition to not launch the WL instance in Production.

OEM: Added a condition to not launch the WL instance in Production.

---

terraform/environments/ccms-ebs/templates/ec2_user_data_mailrelay.sh

CC-1804: Added mynetworks_style to Postfix configuration.

CC-1804: Added mynetworks_style to Postfix configuration.

---

terraform/environments/oasys/locals_development.tf
terraform/environments/oasys/main.tf

These resources have already been deployed.

New resources in oasys-development

---

terraform/environments/laa-oem/member_locals.tf
terraform/environments/laa-oem/oem_ec2_app_lb.tf
terraform/environments/laa-oem/oem_ec2_app_lb_internal.tf
terraform/environments/laa-oem/oem_ec2_app_sg.tf
terraform/environments/laa-oem/oem_ec2_db_sg.tf
terraform/environments/laa-oem/oem_ec2_wl_sg.tf

OEM: Added subnet of Production Workspaces.

OEM: Added subnet of Production Workspaces.

---

terraform/environments/nomis/locals_test.tf

Create an ASG for XTAG testing for Sandhya.  Already applied.

nomis: xtag asg

---

terraform/environments/nomis/locals_test.tf

Add trdat DNS entries as we are failing over that DB as well
Update or-b entry to point at AWS
Update ndh default entry to point at AWS now it has been migrated.

nomis: DSOS-1889: add trdat DNS entries

---

terraform/environments/ccms-ebs/templates/ec2_user_data_mailrelay.sh

CC-1804: Postfix mynetworks_style subnet -> class.

CC-1804: Postfix mynetworks_style subnet -> class.

---

terraform/environments/ccms-ebs/ses.tf

SES: Added a condition to aws_iam_policy_document.ses_identity_policy

SES: Added a condition to aws_iam_policy_document.ses_identity_policy

---

terraform/environments/nomis/locals_test.tf

Correct XTAG ASG and spin up ASG.  Both are for testing by Sandhya

nomis: DSOS-1912: add OEM ASG

---

terraform/environments/oasys/locals_test.tf

Created T2 OASys certificate

---

terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

Nomis: DSOS-1916: t2 weblogic

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_development.tf
terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_production.tf
terraform/environments/oasys/locals_test.tf

add-a-b-oasys

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/glue_job_spark.tf
terraform/environments/data-platform/lambda_for_authoriser.tf
terraform/environments/data-platform/lambda_for_code.tf
terraform/environments/data-platform/lambda_for_data.tf
terraform/environments/data-platform/lambda_for_presigned_url.tf
terraform/environments/data-platform/src/authoriser/main.py
terraform/environments/data-platform/src/presigned_url/main.py

* Create a REST API endpoint to call the presigned URL lambda
* Test the lambda can upload files
* Attach and test the lambda authoriser to the presigned url endpoint
* Standardise spelling of authorise to americani**z**ed form to align with terraform's spelling

Added API upload endpoint

---

terraform/environments/data-platform/glue_script/glue_spark_transform_script.py

fixes some minor omissions from `glue_spark_transform_script.py` change in #2270

add full s3 path and table params

---

terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_production.tf

oasys fix prod deploy

---

terraform/environments/nomis/locals_weblogic.tf

Already applied in nomis-test.  Probably should merge it.  Continue testing weblogic tweaks from main branch

nomis: DSOS-1915: set weblogic-a deployment to use main

---

terraform/environments/equip/application_variables.json

Allow Domain Controllers to contact WSUS Server and Kaseya

Allow Domain Controllers to contact WSUS Server and Kaseya

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/main.tf
terraform/modules/baseline/ec2_autoscaling_group.tf
terraform/modules/baseline/ec2_instance.tf
terraform/modules/baseline/outputs.tf
terraform/modules/baseline/ssm.tf
terraform/modules/baseline/variables.tf

Here's baseline code for SSM parameters.  Previously these were manually created.  However, there is a weird for_each issue going on which is unrelated so just merging baseline changes for now.

Nomis: DSOS-1918: ssm parameters in code

---

terraform/environments/nomis/locals_test.tf

Enable out-of-hours powerdown for XTAG ASG
Fix branch for XTAG

Nomis: DSOS-1932: xtag asg

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/modules/baseline/ssm.tf
terraform/modules/baseline/variables.tf

Nomis: ssm tweak

---

terraform/environments/oasys/locals_test.tf
terraform/modules/baseline/lb.tf
terraform/modules/baseline/variables.tf

add alb target group

---

terraform/environments/nomis/locals_test.tf

create asg for t3-nomis-web-b in order to deploy one t3 ec2 nomis-web instance and check it all works

Nomis/dsos 1939/t3 weblogic frontend

---

terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

this will create a bunch of version "a" asg's in the nomis-* environments for testing
part of blue/green deployment updating [step 1](https://dsdmoj.atlassian.net/wiki/spaces/DSTT/pages/4427808916/Deployment+Process#Bring-new-release-version(s)-up-to-date-%26-submit-a-PR)

create "a" instances x 1, enable warm pool + hooks, change config guid

---

terraform/environments/digital-prison-reporting/data.tf
terraform/environments/digital-prison-reporting/locals.tf
terraform/environments/digital-prison-reporting/main.tf
terraform/environments/digital-prison-reporting/modules/dms/main.tf
terraform/environments/digital-prison-reporting/modules/ec2/iam.tf
terraform/environments/digital-prison-reporting/modules/ec2/variables.tf
terraform/environments/digital-prison-reporting/secrets.tf

- Add Ability to Add Secrets through Jump Server
- Add Secrets for DMS, manage source connection config through Secrets Manager
- Fix Kinesis Agent IAM Policies

Add Dynamic Endpoint Settings for DMS and Fix Kinesis Policy for Bastion Agent

---

terraform/environments/nomis/locals_security_groups.tf

Fixes monitoring from Prometheus

add studio hosting and nomis api

---

terraform/environments/nomis/locals_test.tf

create missing -a instances for testing

create missing t2 and t3 nomis-web-a instances

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_development.tf
terraform/environments/oasys/locals_test.tf

add oasys bip asg

---

terraform/environments/data-platform/lambda_for_athena_load.tf

small change to image tag for the athena load lambda function

updating image tag for lambda

---

terraform/environments/portal/idm_ec2.tf
terraform/environments/portal/oam_ec2.tf
terraform/environments/portal/oim_ec2.tf
terraform/environments/portal/rds.tf

Uncomment the SG ingress rule changes for the ec2 instances and rds instances, to include the access to the Source SG

LAWS-3282: SG ingress changes for the ec2 instances and rds instances

---

terraform/environments/nomis/locals_security_groups.tf

Nomis: allow icmp from cloud platform

---

terraform/environments/nomis/locals_test.tf

Add a new DB instance for backup restore testing.

nomis: DSOS-1935: add t1-nomis-db-1-a DB

---

terraform/environments/nomis/locals_test.tf

For testing XTAG ansible improvements

nomis: DSOS-1932: add xtag-b ASG

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_development.tf
terraform/environments/oasys/locals_test.tf

add-t2-oasys-db

---

terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms_lists.tf

this isn't being used by anything at the moment but making it available for elsewhere

add the collectd services alarm to the baseline module and ec2_asg list

---

terraform/environments/hmpps-oem/locals_oem.tf
terraform/environments/hmpps-oem/locals_test.tf
terraform/environments/hmpps-oem/templates/ansible-ec2provision.sh.tftpl

Fix user data template so ansible_args is actually used

DSOS-1955: fixes for oracle-19c

---

terraform/environments/nomis/locals_test.tf

Correct T3 ModPlatform DB DNS entry
Remove some unused DNS entries

correct T3 DB DNS entries and remove some unused ones

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_test.tf
terraform/environments/oasys/main.tf

t2 oasys db instance

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/lambda_for_api_docs.tf
terraform/environments/data-platform/lambda_for_athena_load.tf
terraform/environments/data-platform/src/docs/index.html
terraform/environments/data-platform/src/docs/main.js
terraform/environments/data-platform/src/docs/swagger.json

* Added /docs endpoint and proxy following https://code.mendhak.com/api-gateway-self-hosted-documentation/
* Created swagger docs for the /upload_data endpoint

Added /docs endpoint to API with swagger docs

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/scripts/.gitignore
terraform/environments/nomis/scripts/del-ssm-parameters.sh
terraform/environments/nomis/scripts/describe-ssm-parameters.sh
terraform/environments/nomis/scripts/get-ssm-parameters.sh
terraform/environments/nomis/scripts/put-ssm-parameters.sh
terraform/environments/nomis/templates/ansible-ec2provision.sh.tftpl

Re-created t1-nomis-db-1-a with new ansible code with fixes a couple of bugs with selinux and the FLASH disk group.
Remove t2-nomis-db-1-a for now.  We will rebuild this after T1 is done.
Added some scripts for management of SSM parameters
Fixed ansible provisioning template

Nomis: DSOS-1960: oracle 11g fix testing

---

terraform/environments/nomis/locals_test.tf

Add DNS entries for T1 MIS database

nomis: add MIS DB DNS entries

---

terraform/environments/data-platform/route53.tf

Delegating zone to Apps and Tools account

Data Platform Apps and Tools NS delegation

---

terraform/environments/data-platform/src/presigned_url/main.py

Commented the MD5 for now to get it working with hackathon UI

Fix in presigned url generation

---

terraform/environments/oasys/locals_test.tf
terraform/modules/baseline_presets/ec2_instance.tf

db_default_no_terminate

---

terraform/environments/data-platform/s3.tf

The extra policies to secure the bucket existed  for the bucket but wasnt attached to the bucket . Terraform   was added attach the policy to bucket

Attached extra bucket policy around the data bucket

---

terraform/environments/ccms-ebs/README.md

CC-1940-Update-CCMS-Support-Details

---

terraform/environments/nomis/templates/new-jumpserver-user-data.yaml

should run everything apart from compatibility mode and url allow lists to check that these settings work first

re-add steps without site compatibility and allow lists

---

terraform/environments/nomis/locals.tf
terraform/modules/baseline/ec2_autoscaling_group.tf
terraform/modules/baseline/ec2_instance.tf

Put top-level ssm-parameters into code (placeholder values which are then overwritten manually)

Nomis: DSOS-1964: add top-level ssm-parameters into code

---

terraform/environments/nomis/templates/new-jumpserver-user-data.yaml

script fails otherwise
- testing everything else then will go back and fix whatever's broken

turn off fail on error preference

---

terraform/environments/ccms-ebs/platform_versions.tf
terraform/environments/ccms-ebs/s3.tf
terraform/environments/laa-ccms-infra-azure-ad-sso/platform_versions.tf
terraform/environments/laa-oem/platform_versions.tf

CCMS upgrades

---

terraform/environments/oasys/locals_test.tf

oasys-recreate-db

---

terraform/environments/delius-jitbit/application_variables.json

db.t3.xlarge is the smallest instance class sql server is compatible with

NIT-734 correct jitbit db config

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/locals_xtag.tf

Ensure all SSM parameters are in code.  Note these are placeholder values, the actual values are set outside of terraform

Nomis: DSOS-1964: add ssm params

---

terraform/environments/data-platform/glue_job_spark.tf
terraform/environments/data-platform/lambda_for_athena_load.tf

increasing max concurrency for lambda function

increasing concurrency

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_security_groups.tf
terraform/environments/oasys/locals_test.tf
terraform/environments/oasys/main.tf
terraform/modules/baseline/lb.tf

oasys nlb to alb

---

terraform/environments/nomis/locals_security_groups.tf
terraform/modules/ip_addresses/moj.tf

Add Azure Landing Zone and Mojo Wifi to our trusted enduser IP list

nomis: DSOS-2001: add landing zone to trusted IP list

---

.gitignore
terraform/environments/ccms-ebs/ccms-sns.tf
terraform/environments/ccms-ebs/member-data.tf

• Rearranged aws_iam_policy_document.sns_topic_policy_s3

CC-1947: Fixed SNS changes in every Terraform plan

---

terraform/environments/digital-prison-reporting/application_variables.json
terraform/environments/digital-prison-reporting/data.tf
terraform/environments/digital-prison-reporting/domain_builder.tf
terraform/environments/digital-prison-reporting/locals.tf
terraform/environments/digital-prison-reporting/main.tf
terraform/environments/digital-prison-reporting/modules/lambdas/generic/main.tf
terraform/environments/digital-prison-reporting/modules/lambdas/generic/variables.tf
terraform/environments/digital-prison-reporting/modules/s3_bucket/main.tf
terraform/environments/digital-prison-reporting/modules/s3_bucket/variables.tf
terraform/environments/digital-prison-reporting/policy.tf
terraform/environments/digital-prison-reporting/s3.tf

- Flyway Lambda
- Lambda Trigger (S3 Event Changes)
- Transfer Bucket (NON Domain Builder Requirement)

Domain Builder - Flyway 

---

terraform/environments/nomis/locals_test.tf

up desired count for t3-nomis-web-b

nomis: weblogic deployment testing

---

terraform/environments/data-platform/glue_script/glue_spark_transform_script.py
terraform/environments/data-platform/locals.tf

Minor addition so glue job script adheres to bucket policy it is writing to.

add bucket owner full control to objects written to s3

---

terraform/environments/hmpps-oem/locals_security_groups.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_security_groups.tf
terraform/environments/nomis/locals_test.tf

Updating security groups in nomis and hmpps-oem to allow OEM connectivity.

DSOS-2010: setup oem connectivity with Nomis

---

terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_xtag.tf

Configure XTAG in T2 environment
Update T1 to use new AMI image

Nomis: DSOS-1990: xtag ami and T2 instance

---

terraform/environments/mojfin/rds.tf

changed the db engine name for the DB option group

 LAWS-3380: changed engine name for db_option_group in mojfin

---

terraform/environments/mojfin/rds.tf

 LAWS-3380: changed time zone name in option group

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_security_groups.tf
terraform/environments/oasys/locals_test.tf
terraform/environments/oasys/outputs.tf

t2-oasys-lb-rules

---

terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_production.tf
terraform/environments/oasys/locals_security_groups.tf

oasys-tidy

---

terraform/environments/nomis-data-hub/locals_test.tf
terraform/environments/nomis-data-hub/templates/ndh-user-data.yaml

- installs software list except sql developer
- sets up local time and locale settings

initial windows machine setup in ndh environment

---

terraform/environments/nomis-data-hub/locals_test.tf
terraform/environments/nomis-data-hub/templates/ndh-user-data.yaml

Need to create a windows ami for this environment before this can work

comment out failing windows server till am ami is available

---

terraform/environments/corporate-staff-rostering/locals_security_groups.tf

Removed opening from App security group

10.0.0.0/8  removed for app SG rule

---

terraform/environments/oasys/locals_test.tf

oasys dns use aws db

---

terraform/environments/corporate-staff-rostering/locals_security_groups.tf

Amended SG rules for data-db to include oracle rules

added orable db rules to SGs

---

terraform/environments/corporate-staff-rostering/locals_security_groups.tf

removed references to nomis SGs

removed refs to non existent SGs

---

terraform/environments/oasys/locals.tf

oasys update sid

---

terraform/environments/oasys/main.tf
terraform/modules/baseline_presets/s3.tf
terraform/modules/baseline_presets/variables.tf

add db backup buckets

---

terraform/environments/nomis-data-hub/locals_test.tf
terraform/environments/nomis-data-hub/templates/ndh-user-data.yaml

* installs software via chocolatey
* gets NDH software from WindowsInstall folder in NDH S3 bucket
* gets CloudwatchAgent windows config from hmpps cloudwatchagent common bucket
* checks the config file has downloaded/is available before trying to start the service, something that broke silently before
* gets SQL Developer and installs from hmpps common bucket
* none of the scripts fail
Will comment $ErrorActionPreference = 'Stop' back in when we're happy with all the setup
Unzipping/copying all the NDH zip files/executables to correct place will be done in a separate item

Ndh/dsos 2015/windows server new ami

---

terraform/modules/baseline/cloudwatch.tf

nomis: DSOS-2019: rman backup alarm fix

---

terraform/environments/oasys/locals_test.tf
terraform/modules/baseline_presets/ec2_autoscaling_group.tf

oasys web cold standby

---

terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/templates/jumpserver-user-data.yaml

* split up jumpserver user-data script into discreet steps
* add check for cloudwatch-agent config before trying to use it
* use new common hmpps-windows-server-2022 ami
* change to latest user-data schema version 1.1

Nomis/dsos 2043/tidy up nomis amis

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_test.tf

shut down t1 oasys for now

---

terraform/environments/nomis-data-hub/locals.tf
terraform/environments/nomis-data-hub/locals_test.tf
terraform/environments/nomis-data-hub/templates/cloud_watch_windows.json
terraform/environments/nomis-data-hub/templates/ndh-user-data.yaml

- add windows cloudwatch config ssm document
- change to use windows ssm document for cloudwatch setup/start
- use release version of common hmpps windows server 2022 ami
- use version 1.1 of user-data schema

use local env ssm parameters

---

terraform/environments/oasys/locals_security_groups.tf
terraform/modules/ip_addresses/external.tf
terraform/modules/ip_addresses/outputs.tf

oasys allow cloud platform

---

terraform/environments/oasys/locals_production.tf
terraform/modules/baseline_presets/s3.tf

correct preprod s3 access policy

correct preprod s3 access policy

---

terraform/environments/dacp/rds.tf

…sg is created per environment

dacp-update-security-group

---

terraform/environments/portal/application_variables.json
terraform/environments/portal/locals.tf

Add all the portal hosted zones in the application_variables.json and locals.tf files

LAWS-3323: added all portal hosted zones

---

terraform/environments/example/ecs.tf

This PR adds a namespace variable for the update to ecs-cluster v3 module

Example environment update to ECS-Cluster v3 module

---

terraform/environments/portal/data.tf
terraform/environments/portal/route53.tf

LAWS-3315: added .aws to all domain names for route53 records

LAWS-3315: added .aws to all domain names for route53 records

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_xtag.tf

- add alarm for monitoring each xtag service

add alarms list to xtag defaults

---

terraform/environments/digital-prison-reporting/domain_builder.tf
terraform/environments/digital-prison-reporting/locals.tf
terraform/environments/digital-prison-reporting/modules/apigateway/serverless-lambda-gw/main.tf
terraform/environments/digital-prison-reporting/policy.tf

* add api gw resource for `publish` endpoint
* add preview policy encapsulating additional permissions required for preview

DPR-659 add support for publish endpoint

---

terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

Sandhya has finished with her testing and the release branch is merged.  Revert back to what it was.

nomis: zap test weblogic server and revert to main branch

---

terraform/environments/hmpps-oem/locals.tf
terraform/environments/hmpps-oem/locals_oem.tf
terraform/environments/hmpps-oem/locals_test.tf
terraform/environments/hmpps-oem/main.tf

Enable daily/weekly backup
Don't powerdown overnight
Rename server on Sandhya's request.

Nomis: DSOS-2088: oem improvements

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_test.tf

oasys-t1-db

---

terraform/environments/data-platform/lambda.tf

upversion of image for athena load lambda. Plus correction to description i spotted whilst doing that

upversion image tag

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

Create updated deployments using bigger instances.  Already deployed in T3.

DSOS-2091: update weblogic deployments in T3 and preprod

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/locals_xtag.tf

Comment out collectd alarms
Set weblogic-b to use testing branch
Fix to preprod weblogic-b config

Nomis: DSOS-2050: update weblogic to use new alarms

---

terraform/environments/nomis-combined-reporting/locals_security_groups.tf

Add OEM port to data security group

nomis combined reporting: DSOS-2097: allow OEM port

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_development.tf
terraform/environments/corporate-staff-rostering/locals_security_groups.tf
terraform/environments/corporate-staff-rostering/locals_test.tf
terraform/environments/corporate-staff-rostering/main.tf

- create db-backup bucket for dba's

enabling db back up for t3-csr-db-a-backup

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_test.tf

t1-oasys-web

---

terraform/environments/corporate-staff-rostering/locals_test.tf
terraform/environments/corporate-staff-rostering/templates/web-server-user-data.yaml

create test web server instance

test ami rebuild

---

terraform/environments/nomis/locals_production.tf
terraform/modules/baseline/route53.tf

This zone is currently hosted in FixNGo but needs to be migrated here.  Setting up the relevant NS records.

nomis: add NS records for top level nomis zone

---

terraform/environments/oasys/locals_test.tf

oasys db stop turning off

---

terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

Add syscon nomis weblogic server

Nomis: DSOS-1949: syscon setup

---

terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/scripts/put-ssm-parameters.sh

Update ansible branch + tweak to ssm param script

nomis: DSOS-1948: weblogic fix

---

terraform/environments/delius-jitbit/lb.tf
terraform/environments/delius-jitbit/locals.tf
terraform/environments/delius-jitbit/route53.tf

This change is needed to allow temporary access to the production instance for debugging

NIT-829 disable all production specific modifications

---

terraform/environments/portal/application_variables.json
terraform/environments/portal/cloudfront.tf
terraform/environments/portal/external_alb.tf
terraform/environments/portal/locals.tf
terraform/environments/portal/route53.tf

Updating cloudfront route53 and acm certs

Updating cloudfront route53 and acm certs

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_security_groups.tf
terraform/environments/oasys/locals_test.tf

oasys bip sec group

---

terraform/environments/data-and-insights-wepi/network.tf
terraform/environments/data-and-insights-wepi/redshift.tf

* Disable cross-zone load balancing
* Refactor Redshift Cluster SG to replace inline rules with individual rule resources
* Allow redshift traffic in from VPC

Change data-and-insights redshift cluster SG to use single resource rules

---

terraform/environments/corporate-staff-rostering/ec2_common.tf
terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_development.tf
terraform/environments/corporate-staff-rostering/ssm-documents/csr-server-config.yaml
terraform/environments/corporate-staff-rostering/templates/app-server-user-data.yaml

- use 2012 r2 ami from ami-builds
- create test ssm params
- create test ssm doc using ssm params

win 2012 asg for testing in csr-dev and ssm POC

---

terraform/environments/ccms-ebs/application_variables.json
terraform/environments/ccms-ebs/ccms-ec2-security_groups.tf

Added 'application' field to SG rules.

CC-2036: Added 'application' field to SG rules.

---

terraform/environments/corporate-staff-rostering/locals_development.tf

- use non SQL server ami
- reduce disk size

use new non-sql server ami

---

terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_jumpserver.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/templates/jumpserver-user-data.yaml
terraform/environments/nomis/templates/jumpserver-user-data.yaml.tftpl
terraform/modules/baseline_presets/ec2_autoscaling_group.tf

Improvements for Syscon:
- added load balancer and ACM cert for Syscon environment
- updated jump server userdata to take parameters + set these up appropriately
- move jumpserver terraform config into separate locals file

Nomis: DSOS-2128: syscon environment setup

---

terraform/environments/data-platform/lambda.tf

Reinstate old lambda policies now that resources they depend on to form have been made.

Reinstated old lambda policies with resource dependencies

---

terraform/environments/oasys/locals_preproduction.tf

oasys pp cert

---

terraform/environments/oasys/locals_preproduction.tf

oasys cert whoops mistake

---

terraform/environments/data-platform/infra_route53.tf

Adding NS records for zones that only apply on main

🌐 Reconcile Data Platform DNS

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_development.tf
terraform/environments/corporate-staff-rostering/locals_security_groups.tf

- duplicate SG rules for dc access into corporate-staff-rostering env from azure-ad-fixngo

create domain-controller related security-group

---

terraform/environments/data-platform/application_variables.auto.tfvars.json

bumping the docs image version

upversion-docs

---

terraform/environments/oasys/locals_preproduction.tf

pp-oasys cert 2

---

terraform/environments/corporate-staff-rostering/ec2_common.tf
terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_development.tf
terraform/environments/corporate-staff-rostering/locals_security_groups.tf
terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml
terraform/environments/corporate-staff-rostering/templates/test-user-data.yaml

- add domain-controller sg
- create outline windows-domain-join ssm document (unfinished)
- poc for calling ssm documents via user-data
- development environment has (commented out) windows test instances
- test ssm parameters added, will be removed later

Csr/dsos 2171/fix ad connectivity

---

terraform/environments/delius-jitbit/rds.tf

Remove ignore snapshot ready to restore MP prod db from legacy snapshot

Jitbit: Remove ignore changes lifecycle block for RDS

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

- push ssm document to environment for testing
- details for prod domain and domain search settings incomplete, will be addressed in a subsequent PR

Csr/dsos 2178/windows domain join ssm document

---

terraform/environments/corporate-staff-rostering/locals_security_groups.tf

- extend inbound port range for RDP traffic to "azure"
- added http ports to webserver SG
- fixed SG issues with prod access to fixngo

address web server connectivity issues and extend inbound range for RDP

---

terraform/environments/nomis-data-hub/locals.tf
terraform/environments/nomis-data-hub/locals_preproduction.tf
terraform/environments/nomis-data-hub/locals_production.tf
terraform/environments/nomis-data-hub/locals_test.tf
terraform/environments/nomis-data-hub/main.tf

introduce test, preprod and prod DNS zones

DSOS-2153: introduce zones for NDH

---

terraform/environments/nomis/locals_production.tf

add NDH prod NS records to nomis prod account

DSOS-2153: update nomis prod

---

terraform/environments/corporate-staff-rostering/locals_security_groups.tf

- allow inbound port 1521 traffic for other sg's in the CSR environment

add data_db sg ingress on port 1521 for other servers

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_security_groups.tf

- add missing internal sg connectivity
- this setup is going to need refactoring pretty soon, this is just to get the csr-test environment working

Csr/dsos 2079/add sg groups internal networking

---

terraform/modules/baseline/lb.tf

Use new version of module which has another couple of Athena fixes

DSOS-2150: loadbalancer logging fix v2

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

This is an instance created from an AMI snapshot of the instance that was migrated with AWS MGN.

add initial config for pre-prod web server 7

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

Reverts ministryofjustice/modernisation-platform-environments#3421

Revert "add initial config for pre-prod web server 7"

---

terraform/environments/nomis/locals_preproduction.tf

Spin up new weblogic servers on A deployment to test new release

Update nomis preprod release

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

- refactor powershell code
- fix checking whether hostname already exists
- improve logging output
- if hostname already exists, SSM document status will show as 'failed'

Csr/dsos 2178/refactor ssm document code

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

- this was missing from the SSM Document as a requirement

add PowerShell AD Windows Feature

---

terraform/environments/data-platform/infra_route53.tf

🌐 Adding PagerDuty Status Page Route 53 records

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

fix yaml formatting

---

terraform/environments/nomis/locals_preproduction.tf

move to the new release in preprod

DSOS-2191: switch to new preprod servers

---

terraform/environments/nomis/locals_production.tf

Also removing DNS entry which is no longer used.

DSOS-2155: Add production DR nomis DBs

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

Use new SSM parameter structure for weblogic. Add policies which restrict access to EC2s in the given environment

Nomis: DSOS-2196: weblogic ssm parameter update

---

terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

Update weblogic releases to latest branch

Nomis: DSOS-2191: update weblogic release

---

terraform/environments/oasys/locals_preproduction.tf

oasys pp db use main

---

terraform/environments/hmpps-oem/locals.tf
terraform/environments/hmpps-oem/locals_preproduction.tf
terraform/environments/hmpps-oem/locals_test.tf

First attempt at creating a preprod OEM.

DSOS-2176: add preprod OEM

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

Repoint T1,T2 and prod to latest instances.

nomis: DSOS-2191: update weblogic endpoints

---

terraform/environments/nomis/locals_production.tf

Drop size of disk from 3TB to 500GB for /u02.  Re-enabling servers

Nomis: DSOS-2155: rebuild DR dbs part2

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

Corrected DB names following discussion with Sandhya.
Added Azure param for Sas token.

nomis: DSOS-2205: updated SSM parameters

---

terraform/environments/nomis/locals_production.tf

whoops, removing some extra spaces which crept in there

nomis: DSOS-2205: fix nomis prod SSM params

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

- can't pass these as booleans

pass true or false values as strings

---

terraform/environments/corporate-staff-rostering/ssm-documents/windows-domain-join.yaml

fix syntax

---

terraform/environments/nomis-data-hub/locals.tf
terraform/environments/nomis-data-hub/locals_security_groups.tf
terraform/environments/nomis-data-hub/locals_test.tf

ndh sec groups

---

terraform/environments/data-platform/infra_route53.tf

This PR adds a new sub-domain for User Guidance in Data Platform

Adding new DNS for User Guidance

---

terraform/environments/corporate-staff-rostering/locals_database.tf
terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_test.tf
terraform/environments/nomis-combined-reporting/locals_database.tf
terraform/environments/nomis-combined-reporting/locals_test.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/scripts/all-ssm.sh
terraform/environments/nomis/scripts/describe-ssm-parameters.sh
terraform/environments/nomis/scripts/get-ssm-parameters.sh
terraform/environments/nomis/scripts/put-ssm-parameters.sh
terraform/environments/nomis/scripts/update-db-az-sas-token.sh
terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_test.tf
terraform/environments/oasys/main.tf

Adding SSM params in code.  These will replace the ones that Sandhya has added manually.

DSOS-2205: put Sandhya's ssm params in code

---

terraform/environments/nomis/iam.tf

Adding a role in to allow the GitHub workflow to update the SAS token stored for pre-production and production

DSOS-2209: Testing IAM role for GitHub role

---

terraform/environments/nomis/iam.tf

because we are using SecureString to store the value, we need kms:Encrypt for our general HMPPS kms key

DSOS-2209: remove GetParameter, add kms:Encrypt

---

terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

zap old parameters.  All servers have got new code now

nomis: DSOS-2230: ssm param tidy

---

terraform/environments/data-platform/infra_route53.tf

Updating our Apex Domain to point directly at github pages IPs

Updating Front Door to A record

---

terraform/environments/hmpps-oem/locals_production.tf

There were a few issues, rebuilding

DSOS-2228: rebuild prod OEM server, zapping first

---

terraform/environments/hmpps-oem/locals_production.tf

DSOS-2228: re-enable prod-oem-a using latest branch

---

terraform/environments/delius-core/modules/environment_all_components/db_service.tf

Following restart of the database, private IP changed. This PR is to update the db dns record

NIT-858 delius core db dns record updated

---

terraform/environments/data-platform/data-product-table-schema-json-schema/v1.0.0/moj_data_product_table_spec.json
terraform/environments/data-platform/lambda.tf

New json schema for validating data product schema user inputs against

Dpl 1194 create table schema

---

terraform/environments/nomis/ec2_common.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_jumpserver.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/locals_xtag.tf

Moving terraform around a bit , no real material changes barring user-data updates for git branch.
Putting more of the code in locals_test, preproduction etc.. so it's a bit easier to follow.
Re-ordered so variables in alphabetical order with tags at the end, consistent with the aws terraform resources.
This should make it a bit easier to see the configuration and hopefully reduce risk of mistakes.
Already applied in dev/test.

nomis: DSOS-2233: terraform rejig

---

terraform/environments/tribunals/asg-shared.tf
terraform/environments/tribunals/ec2-shared-user-data.sh

restructure shared asg terraform
add ec2 volume permissions
set update default-version true for launch template
extra debug for userdata script

Legacy tribunals shared ecs cluster

---

terraform/environments/nomis-data-hub/locals_security_groups.tf

ndh-ems-7224

---

terraform/environments/nomis/locals.tf
terraform/modules/baseline_presets/outputs.tf
terraform/modules/baseline_presets/s3.tf

Update S3 lifecycle policy on audit S3 buckets

Nomis: DSOS-2241: fix audit s3 retention

---

terraform/environments/ccms-ebs/ccms-iam.tf

CC-2121: Extended ec2_to_s3_policy to allow access to LZ S3 in/outbound buckets.

CC-2121: Allow access to LZ buckets from MP instances.

---

terraform/environments/dacp/bastion_linux.json
terraform/environments/dacp/ec2_bastion_linux.tf
terraform/environments/dacp/rds.tf

Bastion server with changes to rds security to allow rds tunnelling

Dacp bastion for all 3 environments

---

terraform/environments/digital-prison-reporting/application_variables.json
terraform/environments/digital-prison-reporting/locals.tf
terraform/environments/digital-prison-reporting/metric_alarms.tf
terraform/environments/digital-prison-reporting/modules/cw_alarm/main.tf
terraform/environments/digital-prison-reporting/modules/cw_alarm/outputs.tf
terraform/environments/digital-prison-reporting/modules/cw_alarm/variables.tf
terraform/environments/digital-prison-reporting/modules/dms/outputs.tf

- # Alarm - "Redshift Health Status"
- # Alarm - "DMS Stop Monitor"
- # Alarm - "DMS Start Monitor"
- # Alarm - "DMS CPU Utilization Monitor"
- # Alarm - "DMS FreeMemory Monitor"
- # Alarm - "DMS FreeableMemory Monitor"
- # Alarm - "DMS SWAP Usage Monitor"
- # Alarm - "DMS Network Transmit Throughput Monitor"
- # Alarm - "DMS Network Receive Throughput Monitor"
- # DMS, CDCLatencySource
- # DMS, CDCLatencyTarget
- # DMS CDCIncomingChanges (Waiting Events)

CloudWatch Alarm Reusable Module - Add Alarms

---

terraform/environments/data-platform/application_variables.auto.tfvars.json

bumping create metadata version

upversion create_metadata

---

terraform/environments/data-platform/secrets.tf

We need to run this terraform first before we can set the secrets via the console.
After this is applied, I will raise another PR to use the secret.

Add secrets for API auth

---

terraform/environments/data-platform/lambda.tf
terraform/environments/data-platform/locals.tf
terraform/environments/data-platform/secrets.tf

This reads the token we have manually set in secrets manager.

Read auth token from secrets manager

---

.github/workflows/reusable_terraform_plan_apply_test.yml
terraform/environments/data-platform/tests/run_smoke_tests.py

This in combination with https://github.com/ministryofjustice/modernisation-platform-environments/pull/3674 should fix the data platform smoketest.

Use correct auth token in smoketest

---

terraform/environments/hmpps-domain-services/ssm.tf

Will migrate the account details from Azure to SSM for use within ansible

AD Service Account Placeholder Secret

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

Fix policies for XTAG
Use latest branch for both weblogic and xtag in ASGs until code stabilises.

Nomis: DSOS-2238: xtag fix

---

terraform/environments/nomis/.ssh/README.md
terraform/environments/nomis/.ssh/create-links.sh
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/templates/ansible-ec2provision.sh.tftpl
terraform/modules/baseline/variables.tf

Add oracle linux test ASG
Fix for RHEL6 ansible template
Script for setting up ssh keys
Remove accidental cut and paste in baseline

Nomis: DSOS-2093: add oracle linux test and ansible fix

---

terraform/environments/corporate-staff-rostering/ssm-documents/ami-build.yaml

terraform apply didn't love one of the task objects
removed as not needed at this stage

removing invalid document object

---

terraform/environments/corporate-staff-rostering/ssm-documents/ami-build.yaml

used the wrong value - needs to be abort not stop

updating the stop command to abort upon error

---

terraform/environments/corporate-staff-rostering/ssm-documents/ami-build.yaml

AWS actions not recognised for instance state change
Updated input to use powershell commands

updating tasks to use powershell rather than direct API call actions

---

terraform/environments/corporate-staff-rostering/ssm-documents/ami-build.yaml

comments to address switching commands if process is too slow

correcting some syntax and adding next steps

---

terraform/environments/data-platform-apps-and-tools/secrets.tf

Adding new secret store values to hold keys for ARC

Add three new secrets for ARC values

---

terraform/environments/corporate-staff-rostering/locals_security_groups.tf

- missing from previous commit

add rpc rule for udp port 135 to database SG

---

terraform/environments/corporate-staff-rostering/ssm-documents/ami-build.yaml

yaml syntax error

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_security_groups.tf
terraform/environments/corporate-staff-rostering/locals_test.tf

- refactor prod, preprod db code to use common locals_database.tf
- remove data_db security group

Csr/dsos 2325/refactor prod preprod db code

---

terraform/environments/mlra/README.md

Updates README for mlra.

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

A first try at the CSR load balancer config

DSOS-2327: initial config for preprod CSR lb

---

terraform/environments/nomis/locals_production.tf

Increase EC2 size + have 2 servers in prep for prod testing

nomis: DSOS-2324: prepare nomis weblogic for prod testing

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

Add sticky config to load balancer for CSR

csr: DSOS-2327: enable LB stickiness

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- r2 in 7771 and 7781 rules
- r2.pp.csr.service.justive.gov.uk
- r1, r4 added for completeness but no instances in those yet

add r2 region for CSR

---

terraform/environments/data-platform/environment-configurations.tf
terraform/environments/data-platform/observability-platform.tf

This pr is to enable log collection

enable log collection

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

rogue hyphen

---

terraform/environments/data-platform/api.tf
terraform/environments/data-platform/lambda.tf

Few issues with resources was incorrect. Updated them now

Query Data api end point 

---

terraform/environments/data-platform/application_variables.auto.tfvars.json
terraform/environments/data-platform/iam.tf
terraform/environments/data-platform/lambda.tf

Upgraded to new version and changed IAM permissions

upgraded version

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- updating termination and stop api calls on preprod servers
- adding missing r53 records on some servers

safeguarding preprod servers from stop or termination in console

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- had two rules with the same priority

fix duplicate priority

---

terraform/environments/mlra/application_variables.json

Adding as a PR so that it doesn't get accidentally overwritten & reset.

Repoints MLRA test to Infox test in CP.

---

terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf

Prepare DNS entries for new audit DB.  Plus terraform fmt

Nomis: DSOS-2386: audit db connection string

---

terraform/modules/baseline/variables.tf

Should be optional instead of option . Plus removed unused var.

CSR: fix baseline error

---

terraform/environments/apex/dbconnect.js
terraform/environments/apex/dbsnapshot.js
terraform/environments/apex/event_triggers.tf
terraform/environments/apex/lambda.tf
terraform/environments/apex/locals.tf
terraform/environments/apex/modules/s3/main.tf

Ingress rule added for Lambda SG to allow ssh access to ec2 istance

inbound port 22 ssh access for lambda to connect to ec2 instance

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf

Add placeholder secret for Sandhya for Audit DB creds

nomis: DSOS-2389: add secrets for audit DB

---

terraform/environments/corporate-staff-rostering/locals.tf
terraform/environments/corporate-staff-rostering/locals_database.tf
terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/main.tf

Requested by Sandhya - add secret to be used for refresh creds

CSR: DSOS-2389: create db secrets for refresh

---

terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf

nomis: DSOS-2389: Update policies to allow GetSecretValue

---

terraform/environments/oasys/locals_test.tf
terraform/modules/baseline/ec2_instance.tf

combine-ssm-and-secrets in ec2 instance

combine-ssm-and-secrets in ec2 instance

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf

Add remaining SSM parameters as Secrets
Updated policies

Nomis: DSOS-2389: secret permissions

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf

Add preprod and prod database IAM policy for accessing secrets.

csr: DSOS-2389: fix secret permissions

---

terraform/environments/planetfm/locals.tf
terraform/environments/planetfm/locals_app.tf
terraform/environments/planetfm/locals_database.tf
terraform/environments/planetfm/locals_development.tf
terraform/environments/planetfm/locals_preproduction.tf

- add sns topic for planetfm
- add default alarms for all instance types
- add instance templates for all instance types (web, app, database - which is Windows this time)

add alarm defaults and templates for web, app and database instances

---

terraform/environments/planetfm/ec2-common.tf
terraform/environments/planetfm/ssm-documents/ami-build-automation.yaml
terraform/environments/planetfm/ssm-documents/ami-build-command.yaml
terraform/environments/planetfm/ssm-documents/windows-cloudwatch-agent-config.yaml

- ssm doc to install cloud agent on windows servers
- ssm doc to convert an azure server into an aws ec2 instance 
- ssm doc to create an ami from a migrated azure server

deploying automation ssm docs into planet fm

---

terraform/environments/nomis-combined-reporting/locals_test.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/oasys/locals_development.tf
terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_production.tf
terraform/environments/oasys/locals_test.tf
terraform/modules/baseline/lb.tf
terraform/modules/baseline/variables.tf

Using new version of LB
- fixes number of issues including annoying glue crawler plan bug
- supports NLB to ALB routing within baseline
- renames a misleading variable name

DSOS-2387: load balancer improvements

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

DSOS-2387: oops, missed a file in last PR

---

terraform/environments/oasys/locals_test.tf

correct comments

---

terraform/environments/oasys/locals.tf

remove some not needed secrets

remove some not needed secrets

---

terraform/environments/oasys/locals_secrets.tf
terraform/environments/oasys/locals_test.tf
terraform/environments/oasys/main.tf

To reflect changes made in oasys-bip role

oasys: DSOS-2360: update tags for test BIP server

---

terraform/environments/apex/alb.tf
terraform/environments/apex/application_variables.json
terraform/environments/apex/modules/alb/README.md
terraform/environments/apex/modules/alb/data.tf
terraform/environments/apex/modules/alb/main.tf
terraform/environments/apex/modules/alb/outputs.tf
terraform/environments/apex/modules/alb/templates/create_table.sql
terraform/environments/apex/modules/alb/variables.tf
terraform/environments/apex/modules/alb/versions.tf

Jira: https://dsdmoj.atlassian.net/browse/LAWS-3488

Apex load balancer setup

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

Timeout needs to be less than interval, hopefully this will work.

csr: DSOS-2387: lb timeout fix

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

Just try one listener with TCP healthcheck

csr: DSOS-2387: retry LB config

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

Trying a TCP target group with HTTP listener.

CSR: DSOS-2387: try adding HTTP healthcheck

---

terraform/environments/planetfm/locals_security_groups.tf

- re-add DB RDP access from jumpservers with correct name and description

re-instate RDP access from azure jumpservers

---

terraform/environments/nomis/locals_test.tf

Use this one for time being, until we get the latest fixed

DSOS-2089: fix ami version

---

terraform/environments/hmpps-oem/locals_test.tf

DOS-2318: add oracle-sids tags to hmpps-oem

---

terraform/environments/oasys/locals_test.tf

add t1 oasys bip

---

terraform/environments/oasys/locals_test.tf

temporarily delete t1 oasys bip

temporarily delete t1 oasys bip

---

.github/workflows/do-not-merge.yml

@ewastempel has told me I need to up my contributions to this repo. 😱
This is the first of many incredibly impactful PRs I intend to raise. 🙇

:pencil2: Fix typo

---

terraform/environments/data-platform/infra_route53.tf

This pull request points Data Platform Control Panel records to DPAT EKS

🌐 Add Data Platform Control Panel records

---

terraform/environments/data-platform/infra_route53.tf

This pull request creates the records for Auth0 custom domain

🌐 Data Platform Auth0 custom domain

---

terraform/environments/data-platform/infra_route53.tf

🚑 Fix Auth0 domain

---

terraform/environments/oasys/locals_test.tf

create t1 oasys bip

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- adding s3 log bucket
- NLB logging connected to this bucket will be in a subsequent PR

add log bucket

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/modules/baseline/lb.tf
terraform/modules/baseline/variables.tf

- add S3 bucket name to r34 NLB
- default value for access_logs is true so remove = false
- add existing_bucket_name variable to module reference

NLB r34 logs to S3 bucket 

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- remove csr-nlb log bucket
- have the lb module create an S3 bucket instead

Csr/dsos 2388/fix nlb s3 access

---

terraform/environments/nomis/locals_production.tf

DSOS-2359: monitoring fix for prod-nomis-db-2

---

terraform/environments/nomis/locals.tf
terraform/environments/nomis/locals_development.tf

add nomis dev secrets

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- add NLB for CSR regions 5 & 6
- will change the lb_alias_records in subsequent PR

add r5/r6 NLB

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

* test changing health-check settings in r5/r6 for CSR

use 7770/71 target groups for ports 7780/81

---

terraform/environments/hmpps-domain-services/locals.tf
terraform/environments/nomis/locals.tf
terraform/environments/oasys/locals_test.tf
terraform/modules/baseline_presets/ssm.tf

Remove some secrets. The equivalent SSM parameters are either created by mod platform directly, or created by baseline.
Updated descriptions to make this a bit clearer.

DSOS-2401: secret tidy up v1

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

used wrong id

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf
terraform/environments/hmpps-oem/locals_oem.tf
terraform/environments/nomis-combined-reporting/locals_database.tf
terraform/environments/nomis/locals_database.tf

Add ASM passwords as secrets for consistency.

DSOS-2406: add ASM passwords as secrets

---

terraform/environments/nomis/locals_preproduction.tf

nomis: DSOS-2386: preprod nomis db ha

---

terraform/environments/hmpps-domain-services/locals_test.tf
terraform/environments/hmpps-domain-services/templates/rds.yaml.tftpl

- Create components for RDS roles
- Add base user data for each instance

Add RDS components

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- add s3 bucket for logs for r53 Network Load Balancer
- uses lb module to do this

add lb module create s3 bucket for NLB logs

---

terraform/environments/digital-prison-reporting/modules/dms_s3/main.tf

* increase DMS timestamp precision from millisecond (10^3) to microsecond (10^6)

DPR2-215: Fix Avro schemas

---

terraform/environments/hmpps-domain-services/locals.tf
terraform/environments/hmpps-domain-services/locals_test.tf
terraform/environments/hmpps-domain-services/templates/rds.yaml.tftpl

- Remove breaking update command
- Update policy to allow ssm:sendCommand

User data fixes

---

terraform/environments/hmpps-oem/locals_oem.tf
terraform/modules/baseline/secretsmanager.tf
terraform/modules/baseline/variables.tf

split out secrets that can be shared across accounts versus other secrets.  Requires baseline changes to support

hmpps-oem: DSOS-2406: allow different policy per secret

---

terraform/environments/planetfm/locals_preproduction.tf

- comment out un-needed pre-prod dns records
- add pre-prod wildcard cert
- includes existing pre-prod domains in SANS

add preprod dns records

---

terraform/environments/planetfm/locals_preproduction.tf

- set external_validation_records_created to false, re-run to fix the terraform issue

set to false and re-run

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/hmpps-domain-services/locals_test.tf
terraform/environments/hmpps-oem/locals_oem.tf
terraform/environments/hmpps-oem/locals_preproduction.tf
terraform/environments/hmpps-oem/locals_production.tf
terraform/environments/hmpps-oem/locals_test.tf
terraform/environments/nomis-combined-reporting/locals_test.tf
terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_development.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/locals_xtag.tf

Remove SSM params that have been migrated to Secrets

DSOS-2406: remove unused ssm parameters

---

terraform/environments/corporate-staff-rostering/locals_production.tf

- CSR production network LB
- will create LB alias records on subsequent PR
- IIS settings locally still need documenting and implementing

Csr/dsos 2427/csr network load balancer

---

terraform/environments/corporate-staff-rostering/locals_production.tf

- prod lb alias records for r1-r6

add lb_alias_records

---

terraform/environments/ccms-ebs-upgrade/application_variables.json
terraform/environments/ccms-ebs-upgrade/ec2-oracle_ebs_db.tf

Added snapshot_id to aws_ebs_volume.backup

CC-2235: Added snapshot_id to aws_ebs_volume.backup

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_test.tf
terraform/environments/oasys/templates/ansible-ec2provision.sh.tftpl

create t1 oasys bip b

---

terraform/environments/nomis/locals_test.tf
terraform/modules/baseline_presets/outputs.tf
terraform/modules/baseline_presets/s3.tf

update baseline module to add a development DB backup bucket.  Also correct some permissions

DSOS-2430: create dev db backup bucket

---

terraform/environments/oasys/locals_secrets.tf
terraform/environments/oasys/locals_test.tf

oasys goodbye ssm params

---

terraform/environments/hmpps-oem/locals_development.tf

Added new OEM in development account.  Had to copy new AMI as the existing one got nuked.

DSOS-2430: create dev oem

---

terraform/environments/planetfm/locals_preproduction.tf

speculative listener path change for LB

---

terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_test.tf

oasys preprod secrets

---

terraform/environments/oasys/locals_preproduction.tf
terraform/modules/baseline/lb.tf
terraform/modules/baseline/variables.tf

oasys add azure secrets

---

terraform/environments/nomis/locals_database.tf
terraform/environments/nomis/locals_preproduction.tf
terraform/environments/nomis/locals_production.tf
terraform/environments/nomis/locals_test.tf
terraform/environments/nomis/locals_weblogic.tf
terraform/environments/nomis/locals_xtag.tf
terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
terraform/modules/baseline_presets/outputs.tf

Various alarm improvements:
- include Confluence page in alarm description
- send DBA alerts to DBA instead of DSO
- aligned alarm naming, using dashes instead of underscores

nomis: DSOS-2427: alarm improvements

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_test.tf

pp-oasys-web

---

terraform/environments/corporate-staff-rostering/templates/ansible-ec2provision.sh.tftpl
terraform/environments/hmpps-domain-services/templates/ansible-ec2provision.sh.tftpl
terraform/environments/hmpps-oem/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis-combined-reporting/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis-data-hub/templates/ansible-ec2provision.sh.tftpl
terraform/environments/nomis/templates/ansible-ec2provision.sh.tftpl
terraform/environments/oasys/templates/ansible-ec2provision.sh.tftpl
terraform/environments/planetfm/templates/ansible-ec2provision.sh.tftpl

Align ansible templates with nomis
Add additional logic for reading new group_vars for when we have stacked environments, e.g. .environment_name_nomis_test_t1 or server_type_nomis_web_t1
Tested in nomis.

DSOS-2361: update ansible template script to support sub-environments

---

terraform/environments/nomis-combined-reporting/locals_bip.tf
terraform/environments/nomis-combined-reporting/locals_bip_cmc.tf
terraform/environments/nomis-combined-reporting/locals_database.tf
terraform/environments/nomis-combined-reporting/locals_test.tf
terraform/environments/nomis-combined-reporting/locals_tomcat.tf

Fix to terraform following baseline update.  Plus terraform fmt.

Nomis-combined-reporting: terraform alarm fix

---

terraform/modules/baseline_presets/iam_policies.tf

shared bucket permission fix

---

terraform/environments/oasys/locals_preproduction.tf

oasys pp web to db

---

terraform/environments/corporate-staff-rostering/locals.tf

This filter has been superseded by newer WIP implementation.

remove iWFM metric filter from CSR

---

terraform/environments/nomis/locals_preproduction.tf

More prep for preprod DB migration

nomis: add new DNS entries for preprod DBs

---

terraform/environments/hmpps-oem/locals_oem.tf

Add permissions for delius-core dev and test accounts to access shared secrets

DSOS-2430: give delius-core access to hmpps-oem shared secrets

---

terraform/environments/nomis/locals_preproduction.tf

Database is moving this morning 10am.  Update DB connection string DNS entries to reflect the change

nomis: Update DNS entries for preprod nomis DB

---

terraform/environments/nomis/locals_preproduction.tf

DSOS-2466: nomis XTAG build in preprod

---

terraform/environments/nomis/locals_preproduction.tf

Add monitoring tags and misload tags for preprod nomis DB migration

nomis: DSOS-2466: update preprod DB tags for monitoring

---

terraform/environments/delius-core/secrets.tf

as per: https://github.com/ministryofjustice/modernisation-platform-configuration-management/tree/main/ansible/roles/get-modernisation-platform-facts

Add ssm param containing ids of other mp accounts

---

terraform/environments/oasys/locals_preproduction.tf

oasys add pp db

---

terraform/environments/oasys/locals_preproduction.tf

oasys remake pp db

---

terraform/environments/oasys/locals_preproduction.tf

oasys pp db redo disk sizes

---

terraform/environments/nomis/locals_database.tf

nomis oracle license tracking

---

terraform/environments/oasys/main.tf

oasys add oracle enterprise managed server

oasys add oracle enterprise managed server

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/main.tf

add oasys db permissions

---

terraform/environments/oasys/locals_preproduction.tf

oasys pp db up

---

terraform/environments/oasys/locals_preproduction.tf

oasys db remake db

---

terraform/environments/oasys/locals_preproduction.tf

oasys db bigger disks

---

terraform/environments/oasys/locals_preproduction.tf

oasys db fix typo in policy

---

terraform/environments/equip/main.tf

This PR covers Work for creating 3 new servers with a new os version for the equip upgrade work that will be coming this year

New Windows 2022 servers for Equip upgrade

---

terraform/environments/planetfm/locals_security_groups.tf

add missing sg rules

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf

- create external network LB bucket for csr pre-prod and prod logs

create external bucket for lb logs

---

terraform/environments/nomis/locals_preproduction.tf

Need to re-create preprod xtag due to problem migrating directly from ASG->instance.  First delete it...

DSOS-2467: xtag fix - part 1

---

terraform/environments/nomis/locals_preproduction.tf

Recreate server ,should work this time with a bit of luck

DSOS-2467: xtag fix - part 2

---

terraform/environments/planetfm/locals_security_groups.tf

- avoid having to retrofit this later

add internal sg connectivity

---

terraform/environments/hmpps-oem/locals.tf
terraform/environments/nomis/locals.tf

Add a role and policy to allow db refreshes

DSOS-2483: add policy

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf

- set external bucket for r12 LB and test

specify external bucket for r12 LB

---

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
terraform/environments/corporate-staff-rostering/locals_production.tf

- adds s3 external bucket to remaining nlb's in pre-prod
- adds s3 external bucket to all nlbs in prod environment

set remaining external buckets for NLB in prod and preprod

---

terraform/environments/oasys/locals.tf
terraform/environments/oasys/locals_preproduction.tf
terraform/environments/oasys/locals_test.tf

Oasys db disk size
