ministryofjustice/modernisation-platform-environments

- terraform/environments/nomis/locals_development.tf
- terraform/environments/nomis/locals_preproduction.tf
- terraform/environments/nomis/locals_production.tf
- terraform/environments/nomis/locals_test.tf
- terraform/environments/nomis/locals_weblogic.tf
T1/T2 regularly failing - update the default size
> nomis: DSOS-2477: Update default weblogic instance size

- terraform/environments/hmpps-domain-services/locals_test.tf
Add a 2012 windows session host for license testing in hmpps-domain-services
> hmpps: DSOS-2478: add windows 2012 asg

- terraform/environments/corporate-staff-rostering/locals_preproduction.tf
- terraform/environments/corporate-staff-rostering/locals_production.tf
- set variable to allow these to be deleted
> allow force destroy on nlb log buckets

- terraform/environments/corporate-staff-rostering/locals_preproduction.tf
- terraform/environments/corporate-staff-rostering/locals_production.tf
> destroy s3 buckets for nlb logs

- terraform/environments/corporate-staff-rostering/locals_defaults.tf
* reduce alarm threshold to 75% to allow plenty of time to ID and fix the issue
> change high-memory-usage threshold for csr app servers

- terraform/modules/baseline_presets/iam_roles.tf
Updated IAM identifier for observability-platform IAM role from production to development
> Fix onboard dso to observability platform

- terraform/environments/data-platform-apps-and-tools/environment-configuration.tf
- terraform/environments/data-platform-apps-and-tools/powerbi-gateway-iam.tf
- terraform/environments/data-platform-apps-and-tools/powerbi-gateway-keypair.tf
- terraform/environments/data-platform-apps-and-tools/powerbi-gateway-security-group.tf
- terraform/environments/data-platform-apps-and-tools/powerbi-gateway-server.tf
https://github.com/ministryofjustice/data-platform/issues/2452
Configuration for PowerBI Gateway for Analytical Platform
> DPAT: PowerBI Gateway Configuration

- terraform/environments/data-platform-apps-and-tools/observability-platform.tf
> ♻️ Update DPAT OP module

- terraform/environments/hmpps-oem/locals.tf
> hmpps oem fix naming part 1

- terraform/environments/hmpps-oem/locals.tf
> hmpps-oem-naming-part-2

- terraform/environments/hmpps-domain-services/ec2_common.tf
- terraform/environments/hmpps-domain-services/ssm-documents/rds-app.yaml
- terraform/environments/hmpps-domain-services/ssm-documents/rds-collection.yaml
- terraform/environments/hmpps-domain-services/ssm-documents/rds-deploy.yaml
- terraform/environments/hmpps-domain-services/ssm-documents/rds-gateway.yaml
- Empty documents for now just for testing
> Initial ssm docs for deploying RDS

- terraform/environments/data-platform/application_variables.auto.tfvars.json
- use the version which has code changes to move data after a table delete
> Bumped delete table image version

- terraform/environments/nomis-data-hub/locals_security_groups.tf
> ndh ingress

- terraform/environments/hmpps-domain-services/locals_development.tf
- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
- terraform/environments/hmpps-domain-services/locals_test.tf
Prep work for RDGateway implementation
- add new zone as agreed with ops engineering
- build public LB with updated security policy
> DSOS-2537: hmpps domain RD Gateway zone and LB

- terraform/environments/oasys/locals_security_groups.tf
> oasys web access

- terraform/environments/hmpps-domain-services/locals_development.tf
- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
- terraform/environments/hmpps-domain-services/locals_rds.tf
- terraform/environments/hmpps-domain-services/locals_test.tf
Now the new domain is setup, we can enable the certs.
Removed duplication by moving common config into locals_rds.tf
Added initial preprod servers
> DSOS-2537: enable new hmpps domain certs

- terraform/environments/planetfm/locals.tf
- terraform/environments/planetfm/locals_defaults.tf
- terraform/environments/planetfm/locals_security_groups.tf
Add additional security group for remote desktop management from AWS IP ranges
> planetfm: DSOS-2537: add security groups for remote desktop

- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_test.tf
> test ords param file

- terraform/environments/oasys/locals_preproduction.tf
> make pp oasys web

- terraform/environments/oasys/locals_preproduction.tf
> pp oasys web down

- terraform/environments/oasys/locals_preproduction.tf
> pp oasys web up

- terraform/environments/hmpps-domain-services/ssm-documents/rds-app.yaml
- terraform/environments/hmpps-domain-services/ssm-documents/rds-collection.yaml
- terraform/environments/hmpps-domain-services/ssm-documents/rds-deploy.yaml
- terraform/environments/hmpps-domain-services/ssm-documents/rds-gateway.yaml
SSM documents created based on powershell scripts in https://dsdmoj.atlassian.net/browse/DSOS-2481
> RDS Deployment via SSM

- terraform/environments/oasys/locals_preproduction.tf
> pp oasys load balancer

- terraform/environments/planetfm/locals_production.tf
building newly migrated cafm web server in prod cafm
> adding in cafm web server

- terraform/environments/cdpt-chaps/database.tf
try again with the snapshot correctly shared with preprod env.
> snapshot shared

- terraform/environments/oasys/locals_preproduction.tf
> oasys pp add bip secret

- terraform/environments/hmpps-domain-services/locals.tf
- terraform/environments/hmpps-domain-services/locals_domain.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
- terraform/environments/hmpps-domain-services/locals_test.tf
- terraform/modules/baseline_presets/ssm.tf
Add initial secret for sharing domain creds across accounts
> hmpps: DSOS-2542: add domain secrets

- terraform/environments/hmpps-domain-services/locals_domain.tf
- terraform/environments/hmpps-domain-services/locals_test.tf
Remove old domain join secret
Configure policy for new prod secret
> hmpps: DSOS-2542: ad domain secrets v3

- terraform/environments/hmpps-domain-services/locals.tf
- terraform/environments/hmpps-domain-services/locals_development.tf
- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
- terraform/environments/hmpps-domain-services/locals_test.tf
- terraform/environments/hmpps-domain-services/main.tf
- terraform/environments/nomis/locals_preproduction.tf
- terraform/environments/nomis/locals_production.tf
- terraform/modules/baseline_presets/route53.tf
For preprod and prod only, enable DNS forwarding for DOM1 domain
> hmpps: DSOS: Add DNS forwarding for DOM1

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_preproduction.tf
> dsos-1718/oasys pp bip up

- terraform/environments/hmpps-domain-services/locals_production.tf
Add redundant pair of RDGateway servers plus a RD deployment server
> hmpps: DSOS: Add configuration for production RDGateway for HMPP domain

- terraform/environments/oasys/locals_preproduction.tf
> oasys bip up preprod

- terraform/environments/electronic-monitoring-data/test_permissions.tf
- terraform/environments/electronic-monitoring-data/transfer_server_capita.tf
Adding in the ecdsa_sha2_nistp384 public key for capita and also test user
> ELM-1398 add capita public key

- terraform/environments/oasys/locals_preproduction.tf
pp oasys add secrets permission
> pp oasys add secrets permission

- terraform/environments/hmpps-domain-services/locals_development.tf
- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
- terraform/environments/hmpps-domain-services/locals_security_groups.tf
Add some more ASG/instances for RemoteDesktop testing.  Primarily Win2012 instances but also a RHEL8.5.
Zap the existing dev instances
Remove unused SG
> hmpps: DSOS-2559: Add some more hmpps-domain servers for testing

- terraform/environments/hmpps-domain-services/locals_development.tf
- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
Include windows 2012 in dev account as well for hmpps
Fix disk size issue on preprod/prod accounts.
Include RHEL 8.5 base image now AMI has been successfully created
> hmpps: DSOS-2559: Add windows 2012 into dev account and fix disk size issue

- terraform/environments/hmpps-domain-services/locals_domain.tf
Add additional sharing for domain secrets
> hmpps: DSOS-2542: Share domain secrets with planetfm and csr

- terraform/environments/oasys/locals_security_groups.tf
> oasys db bip sg

- terraform/environments/hmpps-domain-services/ec2_common.tf
- terraform/environments/hmpps-domain-services/locals_development.tf
- terraform/environments/hmpps-domain-services/ssm-documents/windows-domain-join.yaml
- terraform/environments/hmpps-domain-services/ssm-documents/windows-domain-leave.yaml
Rewrite of domain SSM docs to support new secrets.
> hmpps: DSOS-2542: domain secret fixes

- terraform/environments/hmpps-domain-services/ssm-documents/windows-domain-join.yaml
- terraform/environments/hmpps-domain-services/ssm-documents/windows-domain-leave.yaml
- terraform/environments/hmpps-domain-services/templates/windows_server_2022-user-data.yaml
Fixes required for 2012.  Also added back in option to set the hostname as useful for testing within ASGs.
> hmpps: DSOS-2542: domain secret fixes for 2012

- terraform/environments/hmpps-oem/locals_preproduction.tf
- terraform/environments/hmpps-oem/locals_production.tf
On Sandhya's request - first remove existing preprod and prop OEMs
> DSOS-2567: rebuild preprod oem part 1

- terraform/environments/hmpps-oem/locals_preproduction.tf
On Sandhya's request, rebuild preprod OEM.  Part 2.
> DSOS-2567: re-add preprod OEM

- terraform/environments/hmpps-domain-services/locals_production.tf
- terraform/environments/hmpps-domain-services/locals_rds.tf
Temporarily add another load balancer endpoint to test 2012 rds vs Planet FM prod 2012 session hosts
> DSOS-2559: windows 2012 rds test

- terraform/environments/hmpps-domain-services/locals_production.tf
> DSOS-2559: Fix hmpps RDS LB priorities

- terraform/environments/cdpt-chaps/loadbalancer.tf
- terraform/environments/cdpt-chaps/locals.tf
- terraform/environments/cdpt-chaps/route53.tf
Remove so that a certificate for a new domain can be added.
> Chaps - Remove certificate

- scripts/terraform-plan-evaluator.sh
- terraform/environments/equip/iam.tf
Member infrastructure code moved from mp repo to equip environments
> Member infrastructure migration from modernisation-platform repo to equip environment

- terraform/environments/data-platform-apps-and-tools/lambda-functions.tf
This PR was raised to fix the lambda function. The function is supposed to feed a secret ID to the handler instant of string.
> Fix lambda-function for JML

- terraform/environments/data-platform-apps-and-tools/lambda-functions.tf
This PR was raised to fix the lambda function. The function is supposed to feed a secret ID to the handler instant of string for email secret.
> fix lambda function email secret

- terraform/environments/corporate-staff-rostering/locals.tf
- terraform/environments/nomis/locals.tf
- terraform/modules/baseline_presets/iam_policies.tf
- terraform/modules/baseline_presets/iam_roles.tf
- terraform/modules/baseline_presets/ssm.tf
- terraform/modules/baseline_presets/variables.tf
On Sandhya's request - enable Azure SAS token in CSR to facilitate DB refreshes.
Moved code into baseline
> CSR: DSOS: enable azure sas token

- terraform/environments/ppud/iam.tf
Member infrastructure code moved from mp repo to PPUD environments
> Member infrastructure migration from modernisation-platform repo to PPUD environment

- terraform/environments/planetfm/iam.tf
Member infrastructure code moved from mp repo to planetfm environment
> Moved planetfm member infrastructure from mp repo

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_preproduction.tf
> oasys onr db

- terraform/environments/ccms-ebs/ccms-iam.tf
Member infrastructure code moved from mp repo to ccms-ebs environment
> Moved ccms-ebs member infrastructure from mp repo

- terraform/environments/oasys/locals_preproduction.tf
> oasys onr db down

- terraform/environments/oasys/locals_preproduction.tf
> oasys onr add db

- terraform/environments/delius-jitbit/iam.tf
- terraform/environments/delius-jitbit/secrets.tf
Member infrastructure code moved from mp repo to delius-jitbit environments
> Moved member infrastructure code from MP repo to delius-jitbit

- terraform/environments/data-platform-apps-and-tools/lambda-functions.tf
The PR changes the image version because the new image is created due to some changes in the handler.
> JML: changed-image-version

- terraform/environments/data-platform-apps-and-tools/lambda-functions.tf
> JML-updated-image-v3

- terraform/environments/data-platform-apps-and-tools/lambda-functions.tf
update the policy statements to access the Cloudwatch log
> JML- update-policy-statements

- terraform/environments/data-platform-apps-and-tools/lambda-functions.tf
Seeing if we can get a permission over the log group to actually take effect
> Trying new way of specifying log group

- terraform/environments/data-platform-apps-and-tools/lambda-functions.tf
Adding missing permission to allow lambda to query cloudwatch
> Adding GetQueryResults for JML Lambda

- terraform/environments/equip/main.tf
This PR fixes a bug where the ebs_block_device was being overwritten.
> Fix ebs_blocks_devices list.

- terraform/environments/planetfm/locals_production.tf
- fix some issue with the ami as only 1 block device exists
- fix tag regex validation
> Planetfm/dsos 2587/prod rds app server test fix

- terraform/modules/ip_addresses/moj.tf
Removing MoJDSD and adding missing Global protect IPs
> DSOS-2463: Update global protect alpha ranges

- terraform/environments/ppud/sns.tf
Creation of UAT SNS topic and subscription.
> Update 010224 2

- terraform/environments/ppud/iam.tf
- terraform/environments/ppud/sns.tf
Updated IAMs role/policy for UAT SNS topic & subscription.
> Update 010224 4

- terraform/environments/oasys/locals_preproduction.tf
> onr db down

- terraform/environments/sprinkler/main.tf
Updated the IP allow list for Sprinkler 
[Link to slack for more details](https://mojdt.slack.com/archives/C01A7QK5VM1/p1706801589493239)
> Update the Global Protect VPN IPs

- terraform/environments/hmpps-domain-services/locals_security_groups.tf
Allow inbound RPC from RD session hosts
> hmpps: DSOS-2560: rdp security group fix

- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
Create new cert for Remote Desktop allowing for PlanetFM domains
> hmpps: DSOS-2560: Create new ACM cert include PlanetFM domains

- terraform/environments/planetfm/locals_preproduction.tf
- terraform/environments/planetfm/locals_production.tf
Removal of web servers agreed by Glenn/Hope
Added DNS entries required for hmpps-domain cert
Added CNAME entries for new RDWeb solution
> DSOS-2560: Remove unused planet servers and setup RDWeb cert and DNS entry

- terraform/environments/planetfm/locals_preproduction.tf
- terraform/environments/planetfm/locals_production.tf
need to enable termination first
> DSOS-2560: PlanetFM fix for deleting servers part 1

- terraform/environments/planetfm/locals_preproduction.tf
- terraform/environments/planetfm/locals_production.tf
- terraform/environments/planetfm/locals_test.tf
hopefully will work now API termination re-enabled
> planetfm: DSOS-2560: second attempt at deleting unused planetfm servers

- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
New cert is ready so enable that.
Zap existing RDS ASG and EC2 ready for rebuild
> hmpps: remove old RDS test infra

- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
Remove old certificate and re-create RDS servers
> hmpps: DSOS-2560: rebuild RDS servers

- terraform/environments/electronic-monitoring-data/main.tf
Give Civica access to their sftp server
> ELM-1458 add civica access credentials

- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
re-attach instances and add planetfm dns entry
> hmpps: DSOS-2560: rdp fixes v5

- terraform/environments/corporate-staff-rostering/locals.tf
Reverts ministryofjustice/modernisation-platform-environments#4807
> Revert "csr: add log group for CW agent config doc"

- terraform/environments/delius-core/application_variables.json
- terraform/environments/delius-core/modules/components/oracle_db_instance/instance.tf
- [Change to instance managed EBS volumes (inline)](https://github.com/ministryofjustice/modernisation-platform-environments/commit/f511de1d5be9270e660c7fed85ca156c7c104bc4)
- [Permit delius-test (legacy) to write to LDAP migration S3 bucket](https://github.com/ministryofjustice/modernisation-platform-environments/commit/a489708f17a38cb7b0b62501f42a48be9767fb8e)
> Change to instance managed ebs volumes (and LDAP change)

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_preproduction.tf
> upsize onr db

- terraform/environments/corporate-staff-rostering/locals_preproduction.tf
- test worked so remove this alarm
> remove test alarm

- terraform/environments/nomis/locals_preproduction.tf
Add secret for PPCNOMHA database on Sandhya's request
> nomis: add PPCNOMHA secret

- terraform/environments/hmpps-domain-services/locals_production.tf
> hmpp: add smtp relay

- terraform/environments/nomis/locals_test.tf
> nomis: extend T1/T3 disks

- terraform/environments/planetfm/locals_production.tf
- remove app servers 14, 15 and the test one (16)
- remove web 4 and 5
- remove loadbalancer listener, rules and lb alias for web 4 and 5
> remove un-needed planetfm prod servers

- terraform/environments/planetfm/locals_production.tf
- set allow termination of instances to be killed
> set allow termination on instances to be killed

- terraform/environments/planetfm/locals_production.tf
add 150 and 250 GB volumes to planetfm prod db instances
> add more volumes to prod db instances

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_development.tf
- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
- terraform/environments/oasys/locals_test.tf
- terraform/environments/oasys/main.tf
> oasys db monitoring

- terraform/environments/mlra/task_definition.json
Add `APP_GOOGLE_ANALYTICS_4_TAG_ID` to MLRA `task_definition.json`
Jira: https://dsdmoj.atlassian.net/browse/LASB-2808
The outstanding static code analysis issues will be addressed in the future as part of https://dsdmoj.atlassian.net/browse/LASB-3029
> LASB-2808 Add APP_GOOGLE_ANALYTICS_4_TAG_ID to MLRA task_definition.json

- terraform/environments/oasys/locals_preproduction.tf
> onr db dns

- terraform/environments/electronic-monitoring-data/modules/landing_zone/main.tf
Now files are moved to
```
/<supplier>/<user>/<uploaddate>/
```
> ELM-1490 Add upload date as additional directory

- terraform/environments/maat/api-param.tf
- terraform/environments/maat/maat-ecs.tf
- terraform/environments/maat/maat-int-lb.tf
TF code for internal load balancer for MAAT
> LAWS-3625: tf code for internal load balancer for MAAT

- terraform/environments/equip/main.tf
[#5981](https://github.com/ministryofjustice/modernisation-platform/issues/5981)
> New server request for an upgrade to Power BI 

- terraform/environments/corporate-staff-rostering/locals_development.tf
Reverts ministryofjustice/modernisation-platform-environments#4927
> Revert "csr: add test instance to dev"

- terraform/environments/oasys/locals_security_groups.tf
oasys db access from mp environment
> oasys db access from mp environment

- terraform/environments/planetfm/locals_security_groups.tf
- this traffic is also getting blocked from the vpc flow logs to the db instance
> add http in from end user instances

- terraform/environments/oasys/locals_security_groups.tf
oasys db add access from jumpservers
> oasys db add access from jumpservers

- terraform/environments/oasys/locals_preproduction.tf
> oasys add db dns

- terraform/environments/planetfm/locals_security_groups.tf
- seem to be missing TCP protocol for 137-9
- also missing WinRm and WinRMs for other components
> add missing rules

- terraform/environments/oasys/locals_preproduction.tf
oasys pp dns try large wildcard
> oasys pp dns

- terraform/environments/oasys/locals_preproduction.tf
> temporarily remove listeners

- terraform/environments/oasys/locals_preproduction.tf
oasys pp dns external validation records created
> oasys pp dns add new cert

- terraform/environments/oasys/locals_preproduction.tf
> oasys dns swap cert

- terraform/environments/oasys/locals_preproduction.tf
> oasys dns change cert

- terraform/environments/oasys/locals_preproduction.tf
> oasys pp dns swap back cert

- terraform/environments/oasys/locals_preproduction.tf
> oasys pp dns remove old cert

- terraform/environments/electronic-monitoring-data/locals.tf
- terraform/environments/electronic-monitoring-data/main.tf
Forgot to push final commit to previous [PR](https://github.com/ministryofjustice/modernisation-platform-environments/pull/5023)
> ELM-1519 rename test accounts for clarity

- terraform/environments/oasys/locals_security_groups.tf
oasys pp sg add azure oasys app
> oasys pp sg add azure oasys app

- terraform/environments/oasys/locals_security_groups.tf
> oasys db sec group additions

- terraform/environments/hmpps-domain-services/locals_development.tf
- terraform/environments/hmpps-domain-services/templates/rds-gateway-user-data.yaml
- User data script has been adapted so that the machine joins the domain and then configures the RDS gateway
> Test to automate domain join + configure gateway

- terraform/environments/hmpps-domain-services/ssm-documents/rds-gateway.yaml
- terraform/environments/hmpps-domain-services/templates/rds-gateway-user-data.yaml
- Added logic to handle hostname changes after joining the domain
> RDS gateway user data update

- terraform/environments/oasys/locals_security_groups.tf
> oasys allow sudio hosting

- terraform/environments/oasys/locals_security_groups.tf
> oasys allow even more

- terraform/environments/equip/application_variables.json
- terraform/environments/equip/main.tf
- terraform/environments/equip/securitygroup.tf
This work is to update the newly created power bi server to windows 2022 and create a new security group based on the information from issue Equip PowerBI network requirements
[#5979](https://github.com/ministryofjustice/modernisation-platform/issues/5979)
> PowerBi server changes

- terraform/environments/electronic-monitoring-data/locals.tf
Ahead of migration Thursday, update the civica access credentials
> ELM Rotate civica public ssh key

- terraform/modules/ip_addresses/modernisation_platform.tf
- terraform/modules/ip_addresses/outputs.tf
Add proposed ModPlatform domain controller IPs into ip addresses module
> DSOS-2615: add IPs for Mod Platform DCs

- terraform/environments/oasys/locals_security_groups.tf
> oasys web sec groups

- terraform/environments/corporate-staff-rostering/locals_defaults.tf
- terraform/environments/planetfm/locals_defaults.tf
> change alarm params ASAP

- terraform/environments/corporate-staff-rostering/iam.tf
- terraform/environments/corporate-staff-rostering/lambda.tf
Final resources added - only deploying to CSR for now.
> Second build adding CW event bridge policies and trigger

- terraform/environments/oasys/locals_development.tf
- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
- terraform/environments/oasys/locals_test.tf
> oasys add timeout limit

- terraform/environments/planetfm/ec2-common.tf
- delete these first due to naming issue
> looks like these need deleting first

- terraform/environments/hmpps-domain-services/locals_test.tf
- terraform/environments/hmpps-domain-services/templates/user-data-pwsh.yaml
> DSOS-2615: add test rdgateway

- terraform/environments/planetfm/ec2-common.tf
- put these all back now the naming issue in dev should be gone
> put docs back

- terraform/environments/hmpps-domain-services/locals_domain.tf
adding lambda fn CSR iam role arns to domain secret access iam policy
> domain services secret access

- terraform/environments/ppud/instances.tf
> Restore_190224_2

- terraform/environments/ppud/instances.tf
> Restore_190224_3

- terraform/environments/ppud/instances.tf
> Restore_200224

- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
- terraform/environments/oasys/locals_test.tf
> oasys extend timeout

- terraform/environments/ppud/instances.tf
> Restore_200224_2

- terraform/environments/electronic-monitoring-data/main.tf
Change the active usernames for the G4S sftp server
> rotate g4s account

- .github/workflows/terraform-static-analysis.yml
This PR is the beginning of the fix for the TSA. The fix is will limit the pull of the github repo to the current branch of the PR. This covers work for MP Environments TF static code analysis bug
[#6175](https://github.com/ministryofjustice/modernisation-platform/issues/6175)
done some testing but not quite got the ref for the branch working so reverting to the original plan of changing the fetch depth to 1 this seems to work
> Bug fix test for TSA

- terraform/environments/electronic-monitoring-data/calculate_checksum_lambda.py
- terraform/environments/electronic-monitoring-data/data_store.tf
Quadruple lambda memory due to timing out processing chunky files.
Also updated lambda python code to be more functional, and have a print to keep track of processed chunks.
> Increase memory for lambda function

- terraform/environments/electronic-monitoring-data/data_store.tf
- terraform/environments/electronic-monitoring-data/main.tf
- terraform/environments/electronic-monitoring-data/modules/landing_zone/landing_zone_user/main.tf
- terraform/environments/electronic-monitoring-data/modules/landing_zone/landing_zone_user/variables.tf
- terraform/environments/electronic-monitoring-data/modules/landing_zone/main.tf
- terraform/environments/electronic-monitoring-data/modules/landing_zone/server_security_group/main.tf
- terraform/environments/electronic-monitoring-data/modules/landing_zone/server_security_group/variables.tf
- terraform/environments/electronic-monitoring-data/modules/landing_zone/variables.tf
- terraform/environments/electronic-monitoring-data/modules/s3_log_bucket/main.tf
- terraform/environments/electronic-monitoring-data/modules/s3_log_bucket/variables.tf
Per [mod platform documentation](https://technical-guidance.service.justice.gov.uk/documentation/standards/documenting-infrastructure-owners.html#mandatory) all resources should have certain tags associated with them
> ELM add mandatory tags to resources

- terraform/environments/electronic-monitoring-data/main.tf
Change the g4s accounts for next data delivery
> ELM Rotate g4s server accounts

- terraform/environments/corporate-staff-rostering/ssm-documents/windows-cloudwatch-agent-config.yaml
- terraform/environments/planetfm/ssm-documents/windows-cloudwatch-agent-config.yaml
- added pre-condition for executing this on WINDOWS hosts only
> add precondition otherwise this runs on Linux hosts and breaks things

- terraform/environments/ccms-ebs/ccms-ec2-oracle_accessgate.tf
> CC-2394: Fixed a typo.

- terraform/modules/patch_manager/README.md
- terraform/modules/patch_manager/patch-manager.tf
- terraform/modules/patch_manager/variables.tf
- Module to help create patch schedules for Windows instances for different environments
- https://dsdmoj.atlassian.net/browse/DSOS-2616
> New patch manager module

- terraform/environments/hmpps-domain-services/patch.tf
- terraform/modules/patch_manager/patch-manager.tf
- Test use of patch module
- Specify correct task to run
- Don't create unnecessary resources
> Patch Manager Test

- terraform/environments/cdpt-ifs/application_variables.json
added application variables for staging and production
> Cdpt ifs staging

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_preproduction.tf
> resize onr db

- terraform/environments/hmpps-domain-services/patch.tf
> Patch environment conditional

- terraform/environments/oasys/locals_security_groups.tf
- terraform/modules/ip_addresses/azure_studio_hosting.tf
- terraform/modules/ip_addresses/outputs.tf
> oasys monitoring sec groups

- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
> oasys production add cert

- terraform/environments/oasys/locals_production.tf
> oasys prod cert correction

- terraform/environments/oasys/locals_production.tf
> oasys prod cert validation

- terraform/environments/oasys/locals_production.tf
> oasys prod secrets

- terraform/environments/corporate-staff-rostering/locals_development.tf
> create a dev windows 2022 asg for testing

- terraform/environments/electronic-monitoring-data/main.tf
Trying to massage new account in without needing to destroy resources manually
> Remove accounts that aren't active right now

- terraform/environments/oasys/locals.tf
> onr db extend flash

- terraform/environments/hmpps-domain-services/locals_preproduction.tf
- terraform/environments/hmpps-domain-services/locals_production.tf
Correct description tags for preprod and prod.
> DSOS: hmpps-domain-services: tag fix

- terraform/environments/corporate-staff-rostering/locals_production.tf
Volume sizes updated to be identical to primary db config
> rebuilding secondary db in csr pd

- terraform/environments/hmpps-oem/locals_production.tf
> DSOS-2228: create production OEM server

- terraform/environments/ppud/lambda.tf
Update to eventbridge rules and lambda functions to suppress cpu alarms over the weekend.
> Update 060324 3

- terraform/environments/oasys/locals_production.tf
> oasys add ptctrn db

- terraform/environments/oasys/locals_production.tf
> oasys destroy ptctrn db

- terraform/environments/ppud/lambda.tf
Updates to eventbridge rules and lambda functions to suppress cpu alarms over the weekend.
troubleshooting and fixing typos
> Update 060324 9

- terraform/environments/electronic-monitoring-data/server_backups.tf
Hopefully this is the missing piece required for restoring the backups.
The S3 bucket backups are kept in has encryption enabled but the RDS IAM didn't have permission to decrypt. Buckets using AWS managed encryption so should only need to specify [decrypt with the bucket arn](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html#encryption-context).
> ELM Add decrpyt permission for RDS-S3

- terraform/environments/cdpt-chaps/bastion_linux.tf
- terraform/environments/cdpt-chaps/ecs.tf
Adds "logs:DescribeLogGroups" to ec2_instance_policy
> add ec2 instance role for logs

- terraform/environments/oasys/locals_production.tf
> oasys ptctrn db up

- terraform/environments/electronic-monitoring-data/server_backups.tf
autoscaling doesn't appear to gel with database backup restoration
> Increase the database storage

- terraform/environments/oasys/locals_production.tf
> oasys remake ptctrndb 1

- terraform/environments/oasys/locals_production.tf
> oasys remake ptctrn db

- terraform/environments/oasys/locals_production.tf
> oasys fix deploy

- terraform/environments/electronic-monitoring-data/locals.tf
Ready for drop two, changing the ssh keys
> Update access credentials for civica

- terraform/environments/oasys/locals_production.tf
> oasys add missing bip tag

- terraform/environments/electronic-monitoring-data/locals.tf
- terraform/environments/electronic-monitoring-data/main.tf
Ahead of next migration, reactivate the DDC accounts, and update the ssh keys
> ELM Update capita-DDC accounts

- terraform/environments/oasys/locals_production.tf
oasys ptctrn secrets permissions
> oasys ptctrn secrets permissions

- terraform/environments/corporate-staff-rostering/README.md
- terraform/environments/corporate-staff-rostering/locals_production.tf
Also some more readme formatting
> updating csr diwfm password secret path

- terraform/environments/oasys/locals_production.tf
> oasys rebuild ptctrn db

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_production.tf
> oasys db dns

- terraform/environments/nomis/locals_production.tf
- terraform/environments/nomis/locals_test.tf
Increasing production EC2 size inline with Azure
> Nomis: DSOS-2634: update weblogic instance size

- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
> oasys trn bip trn web ptc web

- terraform/environments/hmpps-oem/locals.tf
- terraform/environments/hmpps-oem/locals_development.tf
- terraform/environments/hmpps-oem/locals_oem.tf
- terraform/environments/hmpps-oem/locals_preproduction.tf
- terraform/environments/hmpps-oem/locals_production.tf
- terraform/environments/hmpps-oem/locals_test.tf
> Oem: DSOS-2671: enable monitoring part2

- terraform/environments/nomis/locals_production.tf
> DSOS-2634: fix weblogic AMI

- terraform/environments/oasys/locals_production.tf
> oasys ptc web up

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_production.tf
> oasys trn up

- terraform/environments/oasys/locals_production.tf
> oasys ptctrn load balancer

- terraform/environments/nomis-data-hub/locals_preproduction.tf
> ndh: add preprod secrets

- terraform/environments/oasys/locals_security_groups.tf
> oasys bip sg

- terraform/environments/analytical-platform-ingestion/application_variables.json
- terraform/environments/analytical-platform-ingestion/observability-platform.tf
- terraform/environments/analytical-platform-ingestion/vpc.tf
- Adds Observability Platform module to Analytical Platform Ingestion
> ✨ Add Observability Platform to Analytical Platform Ingestion

- terraform/environments/oasys/locals.tf
> oasys sas rotation

- terraform/environments/nomis/locals_production.tf
Move alarms from B to A deployment
Remove servers in B deployment
> nomis: fully swap to prod A deployment

- terraform/environments/corporate-staff-rostering/locals.tf
- terraform/environments/nomis/locals.tf
- terraform/environments/oasys/locals.tf
> add sas role and policy

- terraform/environments/corporate-staff-rostering/locals_development.tf
- terraform/environments/corporate-staff-rostering/locals_preproduction.tf
- terraform/environments/corporate-staff-rostering/locals_production.tf
- terraform/environments/corporate-staff-rostering/locals_test.tf
- terraform/environments/nomis-combined-reporting/locals.tf
- terraform/environments/nomis/locals_development.tf
- terraform/environments/nomis/locals_preproduction.tf
- terraform/environments/nomis/locals_production.tf
- terraform/environments/nomis/locals_test.tf
- terraform/environments/oasys/locals_development.tf
- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
- terraform/environments/oasys/locals_test.tf
- terraform/modules/baseline_presets/iam_roles.tf
> sas allow non main

- terraform/environments/nomis/locals_development.tf
Adding dev and qa11g weblogic servers.  Already applied
> DSOS-2667: build syscon env part2

- terraform/environments/equip/alb.tf
update tg-analytics to port 80 for testing
> update tg-analytics to port 80 for testing

- scripts/terraform-plan-evaluator.sh
- Adds `aws_route` to plan evaluator
> 🗺️ Add `aws_route` to plan evaluator

- terraform/environments/ppud/win_patchmgmt.tf
Minor updates to patching baseline.
> Update 210324 4

- terraform/environments/oasys-national-reporting/ec2_common.tf
- terraform/environments/oasys-national-reporting/locals.tf
- terraform/environments/oasys-national-reporting/locals_development.tf
- terraform/environments/oasys-national-reporting/locals_preproduction.tf
- terraform/environments/oasys-national-reporting/locals_production.tf
- terraform/environments/oasys-national-reporting/locals_test.tf
- terraform/environments/oasys-national-reporting/main.tf
- terraform/environments/oasys-national-reporting/outputs.tf
- terraform/environments/oasys-national-reporting/secrets.tf
- terraform/environments/oasys-national-reporting/ssm-documents/windows-cloudwatch-agent-config.yaml
- terraform/environments/oasys-national-reporting/ssm-documents/windows-domain-join.yaml
- terraform/environments/oasys-national-reporting/ssm-documents/windows-domain-leave.yaml
- terraform/environments/oasys-national-reporting/templates/ansible-ec2provision.sh.tftpl
- terraform/environments/oasys-national-reporting/templates/cloud_watch_windows.json
- terraform/environments/oasys-national-reporting/templates/install-ssm-agent.sh.tftpl
- terraform/environments/oasys-national-reporting/templates/post-ec2provision.sh.tftpl
- put in main scaffolding but not: 
- ec2 instances
- security groups, dns, lb's
- secrets
> onr scaffolding

- terraform/environments/electronic-monitoring-data/locals.tf
- terraform/environments/electronic-monitoring-data/main.tf
- terraform/environments/electronic-monitoring-data/platform_versions.tf
Add new sftp account to distinguish different data source.
> ELM Add sftp account for unstructured atrium data

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_test.tf
> oasys no scaling in prod

- terraform/environments/oasys/locals_production.tf
> oasys add missing url

- terraform/environments/oasys/locals_production.tf
> oasys correct link

- terraform/environments/electronic-monitoring-data/server_backups.tf
Only retain access to prod instance for lead engineer
> ELM revoke prod access to rds instance

- terraform/environments/oasys/locals_production.tf
> create temp ptctrn db

- terraform/environments/oasys/locals_production.tf
> remove temp ptctrn db

- terraform/environments/oasys/locals_preproduction.tf
> oasys create temp pp db

- terraform/environments/cdpt-chaps/database.tf
- terraform/environments/cdpt-chaps/ecs.tf
Reverts ministryofjustice/modernisation-platform-environments#5464
> Revert "Add config to address AWS SH findings"

- terraform/environments/observability-platform/data.tf
- terraform/environments/observability-platform/managed-grafana.tf
- Add the GitHub data source to Grafana
> :octocat: Add GitHub data source

- terraform/environments/hmpps-domain-services/locals_development.tf
- terraform/environments/hmpps-domain-services/locals_test.tf
- terraform/environments/hmpps-domain-services/patch.tf
- terraform/modules/patch_manager/ExtractAndUploadPatches.yaml
- terraform/modules/patch_manager/README.md
- terraform/modules/patch_manager/patch-manager.tf
- terraform/modules/patch_manager/s3.tf
- terraform/modules/patch_manager/variables.tf
- Added logic to handle both windows and linux patching
- Updated SSM doc to extract and upload patches on linux
- Add required policies to rhel instance profile
- Add rhel ASG in test environment for testing
> Update Patch Manager to handle linux patching

- terraform/environments/oasys-national-reporting/locals_defaults.tf
- terraform/environments/oasys-national-reporting/locals_development.tf
- specify rhel versions in defaults using base ami's
- set defaults for other things like monitoring (all currently disabled)
> Onr/dsos 2679/onr defaults

- terraform/environments/nomis/locals_development.tf
DB has been cut over to AWS.  Update DNS entries and tags.
> Nomis: DSOS-2667: update syscon env

- terraform/environments/oasys/locals_production.tf
> oasys prod db

- terraform/environments/corporate-staff-rostering/main.tf
- terraform/environments/corporate-staff-rostering/variables.tf
- terraform/environments/planetfm/main.tf
- allow Glenn to create a dashboard in CSR prod which can also retrieve metrics from PlanetFM Prod
> adding variables to csr and planet env modules

- terraform/environments/oasys-national-reporting/locals_defaults.tf
- terraform/environments/oasys-national-reporting/locals_development.tf
- change some of the boe defaults
- set up an asg for this just for when it's being developed
> set up asg for testing boe install ansible

- terraform/environments/oasys-national-reporting/locals_development.tf
- add rhel 6 test instance, cannot be deployed as an asg due to instance age/networking
- add asg for web testing/ansible
> add test instances

- terraform/environments/oas/application_variables.json
- terraform/environments/oas/ec2.tf
- terraform/environments/oas/modules/rds/rds.tf
- terraform/environments/oas/modules/rds/variables.tf
- terraform/environments/oas/rds.tf
- terraform/environments/oas/userdata.sh
LAWS-3731: updated snapshot ID for EC2 instance
> LAWS-3731: updated snapshot ID for EC2 instance

- terraform/modules/ip_addresses/modernisation_platform.tf
Re-IP the Mod Platform azure.hmpp.root DCs so they can be reached from Mojo devices
> DSOS-2711: Update azure.hmpp.root DC IPs

- terraform/environments/oasys/locals_production.tf
> pd oasys db down

- terraform/modules/ip_addresses/modernisation_platform.tf
Removed some duplication of code re ip addresses.  Last PR I got wrong because I didn't see this duplication.
> DSOS-2711: remove ip address module duplication

- terraform/environments/oasys-national-reporting/locals_test.tf
- not expecting this to work yet but it'll show up what's possibly wrong
> pull a specific branch to get software

- terraform/environments/observability-platform/environment-configurations.tf
- terraform/environments/observability-platform/iam-policies.tf
- terraform/environments/observability-platform/lambda-functions.tf
- terraform/environments/observability-platform/managed-grafana.tf
- terraform/environments/observability-platform/managed-prometheus.tf
- terraform/environments/observability-platform/modules/prometheus/iam-role/main.tf
- Switches to a container for running Grafana API key Lambda
- Pins all module versions
> ♻️ Switch to container for Grafana API key Lambda

- terraform/environments/oasys/locals_preproduction.tf
> add pp oasys secrets

- terraform/environments/oasys/locals_production.tf
> oasys db a b up

- terraform/environments/cdpt-ifs/application_variables.json
- terraform/environments/cdpt-ifs/database.tf
DO NOT MERGE. Test to see whether changes to the ingress rules for db affect access. Dev only.
> restrict db access, ecs, cluster & bastion

- terraform/environments/ppud/lambda.tf
Update to eventbridge rule schedule (due to clock change).
> Update 080424 2

- terraform/environments/oasys/locals_production.tf
> oasys add web

- terraform/environments/oasys/locals_production.tf
> oasys add bip

- terraform/environments/nomis-combined-reporting/locals_security_groups.tf
- terraform/environments/nomis-combined-reporting/locals_test.tf
- terraform/environments/nomis-combined-reporting/locals_web.tf
Changes to allow access from Azure Jump Server to T1 CMC
> nomis-combined-reporting: update security groups

- terraform/environments/oasys/locals_production.tf
> oasys update ttl and ip

- terraform/environments/oasys/locals_production.tf
> oasys prod dns zone

- terraform/environments/oasys/locals_production.tf
> oasys record correction

- terraform/environments/oasys/locals_production.tf
> oasys dns correction

- terraform/environments/oasys/locals_production.tf
> oasys add onr dns

- terraform/environments/oasys/locals_production.tf
> oasys db b dns

- terraform/environments/oasys/locals_production.tf
> oasys new cert

- terraform/environments/oasys/locals_security_groups.tf
> oasys db sec group

- terraform/environments/oas/modules/rds/rds.tf
LAWS-3842: removed scheduling of RDS instance
> LAWS-3842: removed scheduling of RDS instance

- terraform/environments/oasys/locals_production.tf
> oasys switch cert

- terraform/environments/oasys/locals_production.tf
> remove old cert

- terraform/environments/ccms-ebs/ccms-ec2-mailrelay.tf
- terraform/environments/ccms-ebs/ccms-r53.tf
CC-1701: Added 'ftp', 'mail', 'mailrelay' and 'smtp' entries to R53.
> CC-1701: Added 'ftp', 'mail', 'mailrelay' and 'smtp' entries to R53.

- .github/workflows/delius-core.yml
Seeing inconsistent plans and crashes:
https://github.com/hashicorp/terraform/issues/34976
https://mojdt.slack.com/archives/C01A7QK5VM1/p1712832263950409
> Pin to 1.7 until 1.8 issues are resolved

- terraform/environments/oasys/locals_production.tf
> oasys scale web

- terraform/environments/electronic-monitoring-data/dms_data.tf
> v2-dms-module-prod-corrections

- terraform/environments/electronic-monitoring-data/dms_data.tf
- terraform/environments/electronic-monitoring-data/dms_iam.tf
- **adding bucket definition**
- **adding more perms for dms**
> Add more permissions for DMS EM role

- terraform/environments/nomis/locals_preproduction.tf
Check stability of an autoscaling schedule in preprod
> DSOS-2719: autoscaling-schedule-test

- terraform/environments/oasys/locals_production.tf
> oasys db url to azure

- terraform/environments/oasys/locals_production.tf
> oasys prod access logs

- terraform/environments/mlra/monitoring.tf
Adds Cloudwatch alarm, SNS topic, and PagerDuty integration to alert on detection of a DDOS attack.
> DDOS alarms for mlra

- terraform/environments/electronic-monitoring-data/dms_data.tf
- terraform/environments/electronic-monitoring-data/dms_glue_crawler.tf
- terraform/environments/electronic-monitoring-data/dms_iam.tf
- terraform/environments/electronic-monitoring-data/dms_replication_instance.tf
- terraform/environments/electronic-monitoring-data/modules/dms/variables.tf
> v4a-dms-module-prod-corrections

- terraform/environments/electronic-monitoring-data/dms_glue_crawler.tf
port added to JDBC_CONNECTION_URL
> v5a-dms-module-prod-corrections

- terraform/environments/electronic-monitoring-data/dms_glue_crawler.tf
"terraform/environments/electronic-monitoring-data/dms_glue_crawler.tf" -- corrected
> v6a-dms-module-prod-corrections

- terraform/environments/oasys/locals_production.tf
> oasys dns swap

- terraform/environments/oasys/locals_production.tf
> oasys correct db name

- terraform/environments/oasys/locals_production.tf
> oasys add secret dr

- terraform/environments/oasys/locals.tf
> oasys db flash speed

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_security_groups.tf
> oasys 7777

- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_security_groups.tf
- terraform/environments/oasys/locals_test.tf
- terraform/modules/baseline/variables.tf
- terraform/modules/lb_listener/main.tf
- terraform/modules/lb_listener/variables.tf
> oasys test redirect

- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
> oasys undo redirect test

- terraform/environments/nomis/locals_preproduction.tf
> nomis: DSOS-2719: fix autoscale schedule in preprod

- terraform/environments/oasys-national-reporting/locals_defaults.tf
- oracle client needs access to a swap
> add drive required by oracle client

- terraform/environments/electronic-monitoring-data/dms_data.tf
- terraform/environments/electronic-monitoring-data/dms_glue_crawler.tf
- terraform/environments/electronic-monitoring-data/dms_iam.tf
> dms-module-tags-added

- terraform/environments/delete-account/ec2.tf
EC2 created to help test scripted account deletion
> EC2 creation for test scripted account deletion

- terraform/environments/delete-account/ec2.tf
This task is to create resources in-order to test automated deletion of AWS resources using bash scripts. The code is creating an S3 buckets and also making use of json file to pass variables
> added S3 buckets and updated code to use variables

- terraform/environments/electronic-monitoring-data/dms_variables.tf
- terraform/environments/electronic-monitoring-data/server_backups.tf
Included RDS-DB Ingress Rule for MK
> Remove commented block db ipv4 mk

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_security_groups.tf
> oasys remove 7777

- terraform/environments/oasys/locals_preproduction.tf
> oasys pp db b more data

- terraform/environments/nomis/locals_preproduction.tf
Temporarily remove xtag in order to change config
> Nomis: DSOS-2600: rebuild xtag part1

- terraform/environments/analytical-platform-ingestion/environment-configuration.tf
- Adds `mojap-land` to `target_buckets`
> 📮 Update `target_buckets`

- terraform/environments/electronic-monitoring-data/dms_replication_task_settings.json
> dms_task_settings_altered_v1

- terraform/environments/oasys/locals_production.tf
> oasys db add s3 permissions

- terraform/environments/oasys/locals_preproduction.tf
> oasys more db s3 permissions

- terraform/environments/oasys/locals.tf
- terraform/modules/baseline_presets/iam_policy_statements_s3.tf
- terraform/modules/baseline_presets/s3.tf
- terraform/modules/baseline_presets/variables.tf
> oasys preprod write to prod

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_preproduction.tf
- terraform/modules/baseline_presets/iam_policy_statements_s3.tf
- terraform/modules/baseline_presets/s3.tf
- terraform/modules/baseline_presets/variables.tf
oasys preprod even more s3 permissions
> oasys preprod even more s3 permissions

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_production.tf
- terraform/modules/baseline_presets/iam_policy_statements_s3.tf
- terraform/modules/baseline_presets/s3.tf
- terraform/modules/baseline_presets/variables.tf
oasys prod s3 more permissions
> oasys prod s3 more permissions

- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
> oasys prod s3 perms

- terraform/environments/electronic-monitoring-data/glue-job/parquet_to_csv.py
forgot to change this one as well
> EM: glue job leaving in old bucket name

- terraform/environments/oas/application_variables.json
- terraform/environments/oas/userdata.sh
LAWS-3841: new ami and ebs snapshots
> LAWS-3841: new ami and ebs snapshots

- .github/workflows/delius-core.yml
Reverts ministryofjustice/modernisation-platform-environments#5680
> Revert "Pin to 1.7 until 1.8 issues are resolved"

- scripts/minimise-comments/README.md
- terraform/environments/apex/modules/alb/README.md
- terraform/environments/apex/modules/ecs/README.md
- terraform/environments/corporate-staff-rostering/.ssh/README.md
- terraform/environments/corporate-staff-rostering/README.md
- terraform/environments/corporate-staff-rostering/configs/prod/README.md
- terraform/environments/delius-iaps/.ssh/README.md
- terraform/environments/hmpps-oem/.ssh/README.md
- terraform/environments/mlra/README.md
- terraform/environments/mlra/modules/alb/README.md
- terraform/environments/mlra/modules/ecs/README.md
- terraform/environments/nomis-combined-reporting/.ssh/README.md
- terraform/environments/nomis-data-hub/.ssh/README.md
- terraform/environments/nomis/.ssh/README.md
- terraform/environments/nomis/README.md
- terraform/environments/oasys/.ssh/README.md
- terraform/environments/planetfm/.ssh/README.md
- terraform/environments/pra-register/README.md
- terraform/environments/wardship/README.md
- terraform/modules/acm_certificate/README.md
- terraform/modules/cost_usage_report/README.md
- terraform/modules/environment/README.md
- terraform/modules/lb_listener/README.md
PR to start reducing the 135 errors found in format code workflow
N.B. These are mainly formatting/layout changes, the context should remain the same. 
| Descriptor     | Linter        | Mode          | Files | Fixed | Errors | Elapsed time |
|--------------|---------------|---------------|-------|-------|--------|--------------|
| ✅ JSON       | prettier      | list_of_files |   171 |     0 |      0 |        2.48s |
| ⚠️ MARKDOWN  | markdownlint  | list_of_files |    88 |     0 |    135 |        2.62s |
| ✅ TERRAFORM | terraform-fmt | file          |  1554 |    13 |      0 |      170.05s |
> 📝  Format Code Markdown Warnings

- terraform/environments/electronic-monitoring-data/lambdas/manual_trigger_lambda.py
- terraform/environments/electronic-monitoring-data/register-my-data.tf
- **source code hash to force change**
- **copying structure of event trigger**
> Source code hash so no need to push the zip file as well

- terraform/environments/electronic-monitoring-data/lambdas/em_ap_transfer_lambda.py
- terraform/environments/electronic-monitoring-data/register-my-data.tf
adding get and list bucket perms for the AP bucket, also logging in the lambda
> EM: Adding more rmd permissions

- terraform/environments/electronic-monitoring-data/bastion_linux.tf
Adding 96GB of volume so I can unzip the 36GB file
> EM: Create new bastion linux for unzip

- terraform/environments/electronic-monitoring-data/bastion_linux.tf
- terraform/environments/electronic-monitoring-data/unzipped-s3-store.tf
Creating bucket and permissions for the ec2 instance acting as a filedump for the unzipped blob storage files
> Unzipped File Store Bucket

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_security_groups.tf
- terraform/environments/oasys/locals_test.tf
oasys test maintenance message
> oasys test maintenance message

- terraform/environments/electronic-monitoring-data/bastion_linux.tf
Adding outbound rule to allow connection to s3.
> EM: Adding outbound rule to connect to s3

- terraform/environments/nomis-combined-reporting/locals_bip.tf
- terraform/environments/nomis-combined-reporting/locals_etl.tf
- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
- terraform/environments/nomis-combined-reporting/locals_security_groups.tf
- terraform/environments/nomis-combined-reporting/locals_test.tf
- terraform/environments/nomis-combined-reporting/locals_web.tf
Added instance-access-policy tag
Updated security groups
> DSOS-2748: nomis combined reporting fixes

- terraform/environments/oasys-national-reporting/locals_defaults.tf
- terraform/environments/oasys-national-reporting/locals_test.tf
- add secrets for boe installation passwords
> add secretsmanager for boe passwords

- terraform/environments/nomis-combined-reporting/locals_bip.tf
- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
- terraform/environments/nomis-combined-reporting/locals_security_groups.tf
- terraform/environments/nomis-combined-reporting/locals_test.tf
- terraform/environments/nomis-combined-reporting/locals_web.tf
Prep for removing unused private and public security groups
> DSOS-2748: more security group tweaks for nomis combined reporting

- terraform/environments/ccms-ebs/ccms-s3.tf
CC-2532: Enabled versioning in the `artefact` and `logging` buckets.
> CC-2532: Enabled versioning in the 'artefact' and 'logging' buckets.

- terraform/environments/electronic-monitoring-data/data_store.tf
- terraform/environments/electronic-monitoring-data/lambdas/summarise_zip_lambda.py
- **upping memory size to max**
- **logging!!!!**
> Up the memory of lambda

- terraform/environments/analytical-platform-ingestion/environment-configuration.tf
- Adds `78.150.1.253/32` for @lalithanagarur
> 💻 Update Essex Police testing range

- terraform/environments/nomis-data-hub/locals_production.tf
Removing duplicate route53 entries
> ndh DNS fix

- terraform/environments/nomis/locals_production.tf
Update DNS NS record for ndh using new zone
> Ndh: dns fix part2

- terraform/environments/nomis/.ssh/README.md
- terraform/environments/nomis/.ssh/get-keys.sh
- terraform/environments/nomis/.ssh/put-keys.sh
- terraform/environments/nomis/locals.tf
- terraform/environments/nomis/main.tf
- terraform/environments/nomis/outputs.tf
- terraform/modules/baseline_presets/outputs.tf
- terraform/modules/baseline_presets/secretsmanager.tf
Add ec2-user .ssh secret
Also add efs/fsx baseline resources to nomis
> DSOS-2691: add nomis ec2user secret

- terraform/environments/oasys/locals_preproduction.tf
> oasys pp db down

- terraform/environments/oasys-national-reporting/locals_development.tf
- terraform/environments/oasys-national-reporting/locals_preproduction.tf
- terraform/environments/oasys-national-reporting/locals_production.tf
- terraform/environments/oasys-national-reporting/locals_test.tf
- dns zones for onr preproduction and production
> add route 53 zones for all onr environments

- terraform/environments/hmpps-oem/locals_development.tf
- terraform/environments/hmpps-oem/locals_preproduction.tf
- terraform/environments/hmpps-oem/locals_production.tf
- terraform/environments/hmpps-oem/locals_test.tf
For now, use nomis pagerduty services for general purpose DSO pagerduty integration
> OEM: DSOS-2761: add DSO pagerduty integration

- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
- terraform/modules/efs/main.tf
Fix a checkov and test EFS backup over the long weekend
> DSOS-2749: efs backup test

- terraform/environments/oasys-national-reporting/locals_production.tf
- add ns_records for test, development, preproduction
> add ns records for environments

- terraform/environments/oasys/locals.tf
> oasys no env cert

- terraform/environments/oasys-national-reporting/locals_test.tf
- need this tag to specify environment for BOE installer
- change tag value to t2 in line with other code
> add missing tag

- terraform/environments/oasys-national-reporting/locals_test.tf
- forgot to change the permissions when I changed the secrets
> add permissions

- terraform/environments/oasys/locals_test.tf
- recreate t2-onr-db-a in a branch
- assuming all the ansible automation runs correctly I'll do a PR to merge this
> put instance back

- terraform/environments/oasys-national-reporting/locals_jumpserver.tf
> add more drive space

- terraform/environments/nomis/locals_development.tf
- terraform/environments/nomis/locals_preproduction.tf
- terraform/environments/nomis/locals_production.tf
- terraform/environments/nomis/locals_test.tf
- terraform/environments/nomis/locals_weblogic.tf
- terraform/environments/nomis/templates/maintenance.html
- terraform/environments/nomis/templates/maintenance.html.tftpl
Add a maintenance mode message to the load-balancer.  This can be enabled/disabled via a script on the webservers
Tested in dev/test  - seems to work.
> Nomis: DSOS-2535: add maintenance lb rule

- terraform/environments/nomis/locals_production.tf
> nomis: DSOS-2535: fix prod maintenance rule

- terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Removes `78.150.1.253/32` and adds `2.99.13.52/32` for @lalithanagarur
> Update Essex Police testing range again

- terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Adds `78.150.12.143/32` for @lalithanagarur for testing
> Update Essex Police testing range dev

- terraform/environments/nomis-combined-reporting/locals.tf
- terraform/environments/nomis-combined-reporting/main.tf
Add missing backup configuration to nomis-combined-reporting
> ncr: enable backup plans

- terraform/environments/nomis/locals_production.tf
> DSOS-2759: increase db u02 disk space

- terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Update lambda versions in both Development and Production.
> 🔧 Update Lambda versions

- terraform/environments/analytical-platform-ingestion/environment-configuration.tf
- terraform/environments/analytical-platform-ingestion/lambda-functions.tf
This PR resolves the bug described in [this](https://github.com/orgs/ministryofjustice/projects/27/views/18?pane=issue&itemId=62741787) issue.
> :wrench: Add ACL permissions to Destination Bucket

- terraform/environments/hmpps-domain-services/patch.tf
-  Points to a test branch of the patch module
> Test patch module changes

- terraform/environments/oasys-national-reporting/locals_test.tf
- just need to be able to delete this instance for testing
> change asg settings to allow deletion

- terraform/environments/ppud/iam.tf
- terraform/environments/ppud/lambda.tf
- terraform/environments/ppud/terminate_cpu_process/terminate_cpu_process.py
- terraform/environments/ppud/win_patchmgmt.tf
Creation of a new lambda function to terminate high CPU processes on EC2 instances.
> Update 140524 4

- terraform/environments/ppud/lambda.tf
Updating the terminate_cpu_process aws cloudwatch event rule pattern event
Correcting a syntax error / typo.
> Update 140524 6

- terraform/environments/nomis/locals_production.tf
On DBA request - align MIS DB sizing with Nomis and increase iops
> nomis: DSOS-2759: resize prod DBs

- terraform/environments/hmpps-domain-services/patch.tf
-  Tests the patch module changes against different availability zones
> Test new module changes

- terraform/environments/observability-platform/environment-configurations.tf
See title.
Additionally updates the Observability Platform Grafana API Key rotator to the latest version (dependabot updates).
> 👁️ Onboard AP Compute to Observability Platform

- terraform/environments/nomis-combined-reporting/locals_production.tf
Nomis combined reporting prod build
> DSOS-2759: add nomis combined reporting prod DBs

- terraform/environments/hmpps-domain-services/patch.tf
- terraform/environments/hmpps-domain-services/platform_locals.tf
- Reference latest patch module
- Set schedules for production
> Set production patch schedules

- terraform/environments/hmpps-domain-services/patch.tf
- terraform/environments/hmpps-domain-services/platform_locals.tf
- Required to differentiate schedules within production
> Add suffix to patch schedules

- terraform/environments/nomis/locals_production.tf
> DSOS-2759: add nomis prod db secrets

- terraform/environments/oasys-national-reporting/locals_test.tf
- **initial commit of Windows BODS instance**
- **fix name of Windows BODS instance**
- **add missing merges with defaults for BODS**
- **fix typo on locals ref**
- **fix typo in locals ref**
- **add user-data-pwsh from baseline_presets**
> onr: add BODS instance to test environment

- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
- terraform/modules/baseline/efs.tf
- terraform/modules/baseline/variables.tf
- terraform/modules/efs/README.md
- terraform/modules/efs/main.tf
- terraform/modules/efs/outputs.tf
- terraform/modules/efs/variables.tf
Remove backup options from EFS - just use tags to opt in and out of mod platform backups
Renamed shared to follow naming convention
> ncr: DSOS-2766: efs tweak

- terraform/environments/nomis/locals_production.tf
Fix instance size for the new ASG and scale up to 8
> DSOS-2759: scale up nomis prod ASG

- terraform/environments/oasys-national-reporting/locals_test.tf
> deploy t2-onr-boe-1-a instance

- terraform/environments/nomis-data-hub/locals_production.tf
- adding the offloc S3 bucket
- adding the ssm param to contain the S3 bucket name
> DSOS-2779: add bucket for offloc to production

- terraform/environments/nomis/locals_production.tf
Enable misload scripts on prod
> nomis: DSOS-2759: add misload tag

- terraform/environments/ppud/lambda.tf
A small update to the lambda timeout value.
> Update iam permissions 170524 2

- terraform/environments/nomis-combined-reporting/locals_production.tf
> ncr: DSOS-2759: add prod db DNS entries

- terraform/environments/nomis/locals_production.tf
This moves from the 2 server deployment to the 8 server deployment (to be applied tomorrow)
> nomis: DSOS-2759: swap to b deployment

- terraform/environments/nomis/locals_production.tf
> Nomis: DSOS-2759: prod xtag build

- terraform/environments/nomis/locals_production.tf
Update iops for prod nomis migration
> DSOS-2759: update iops for mis DB

- terraform/environments/nomis/locals_production.tf
> DSOS-2759: update maintenance message

- terraform/environments/nomis/locals_production.tf
> DSOS-2759: resize -b nomis DBs

- terraform/environments/nomis/locals_production.tf
Enable monitoring and kill unused weblogic servers
> nomis: DSOS-2759: enable prod monitoring

- terraform/environments/nomis/locals_production.tf
Also remove DBs that have been moved to other servers
> DSOS-2792: add monitoring for nomis DRCNMAUD

- terraform/environments/nomis-combined-reporting/locals.tf
- terraform/environments/nomis-combined-reporting/locals_database.tf
- terraform/environments/nomis-combined-reporting/locals_development.tf
- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
- terraform/environments/nomis-combined-reporting/locals_production.tf
- terraform/environments/nomis-combined-reporting/locals_test.tf
- terraform/environments/nomis-combined-reporting/main.tf
Enable cloudwatch monitoring
Add pagerduty integration
> Ncr: DSOS-2792: add prod monitoring

- terraform/environments/nomis-combined-reporting/locals.tf
- terraform/environments/nomis-combined-reporting/locals_database.tf
- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
- terraform/environments/nomis-combined-reporting/main.tf
SNS topics are missing, add them now we have prod stuff in the environment
> DSOS-2792: add sns topics for nomis combined reporting

- terraform/environments/sprinkler/bastion_linux.tf
* Removed unsupported linux bastion module arguments
> Fix sprinkler

- terraform/environments/observability-platform/environment-configurations.tf
- terraform/environments/observability-platform/iam-policies.tf
- terraform/environments/observability-platform/lambda-functions.tf
- terraform/environments/observability-platform/managed-grafana.tf
- terraform/environments/observability-platform/managed-prometheus.tf
- terraform/environments/observability-platform/modules/grafana/amazon-prometheus-query-source/main.tf
- terraform/environments/observability-platform/modules/grafana/amazon-prometheus-query-source/providers.tf
- terraform/environments/observability-platform/modules/grafana/amazon-prometheus-query-source/variables.tf
- terraform/environments/observability-platform/modules/grafana/cloudwatch-source/providers.tf
- terraform/environments/observability-platform/modules/grafana/contact-point/pagerduty/providers.tf
- terraform/environments/observability-platform/modules/grafana/contact-point/slack/providers.tf
- terraform/environments/observability-platform/modules/grafana/team/main.tf
- terraform/environments/observability-platform/modules/grafana/team/providers.tf
- terraform/environments/observability-platform/modules/grafana/team/variables.tf
- terraform/environments/observability-platform/modules/grafana/xray-source/providers.tf
- terraform/environments/observability-platform/modules/observability-platform/tenant-configuration/main.tf
- terraform/environments/observability-platform/modules/observability-platform/tenant-configuration/providers.tf
- terraform/environments/observability-platform/modules/observability-platform/tenant-configuration/variables.tf
- terraform/environments/observability-platform/modules/prometheus/iam-role/main.tf
- terraform/environments/observability-platform/modules/prometheus/iam-role/providers.tf
- terraform/environments/observability-platform/observability-platform.tf
Resolves https://github.com/ministryofjustice/observability-platform/issues/86
- Adds support for reading remote Amazon Managed Prometheus workspaces
> ✨ Add support for reading remote Amazon Managed Prometheus workspaces

- terraform/environments/oasys-national-reporting/locals_test.tf
I will revert this to create a fresh instance.
> onr: remove bods instance

- terraform/environments/oasys-national-reporting/locals_test.tf
Reverts ministryofjustice/modernisation-platform-environments#6201
> Revert "onr: remove bods instance"

- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
- terraform/environments/nomis/locals_preproduction.tf
Prep for migrating LSAST DBs from Azure
> Nomis: DSOS-2796: lsast db build

- terraform/environments/wardship/load_balancer.tf
update LB to recommended tls security policy on DTS Legacy apps (test Wardship first)
> Update elb-security-policy to latest recommended version (Wardship)

- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_test.tf
> oasys tls not prod

- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_test.tf
> oasys t2 athena

- .devcontainer/devcontainer-lock.json
- .devcontainer/devcontainer.json
- terraform/environments/analytical-platform-compute/eks-cluster.tf
- terraform/environments/analytical-platform-compute/environment-configuration.tf
- terraform/environments/analytical-platform-compute/helm-charts-system.tf
- terraform/environments/analytical-platform-compute/iam-policies.tf
- terraform/environments/analytical-platform-compute/iam-roles.tf
- terraform/environments/analytical-platform-compute/route53-zones.tf
- terraform/environments/analytical-platform-compute/src/helm/cluster-autoscaler/values.yml.tftpl
- Updates the dev container feature versions
- Updates EKS module
- Updates IAM module
- Update EKS add-on versions
- Add Cluster Autoscaler
- _..._
> 🎡 Analytical Platform Compute EKS

- terraform/environments/oasys/locals_production.tf
> oasys tls public

- terraform/environments/example/data.tf
Missing save for the data file.
> Missing save

- terraform/environments/cdpt-ifs/database.tf
- terraform/environments/cdpt-ifs/ecs.tf
- terraform/environments/cdpt-ifs/loadbalancer.tf
removes critical security issues.
> Ifs security

- terraform/environments/analytical-platform-compute/helm-charts-system.tf
- terraform/environments/analytical-platform-compute/iam-roles.tf
- terraform/environments/analytical-platform-compute/route53-zones.tf
- terraform/environments/analytical-platform-compute/src/helm/external-dns/values.yml.tftpl
- terraform/environments/analytical-platform-compute/vpc-endpoints.tf
- Adds `external-dns` chart
- Update S3 VPC endpoint tag name
> 🌐 Add `external-dns`

- terraform/environments/ppud/iam.tf
- terraform/environments/ppud/lambda.tf
- terraform/environments/ppud/lambda_scripts/terminate_cpu_process_dev.py
Consolidating the lambda - iam permissions code from two functions into one. Introducing a 120 second sleep/timeout value for the cpu termination python script.
> Update lambda functions 280524 4

- terraform/environments/ppud/iam.tf
- terraform/environments/ppud/lambda.tf
- terraform/environments/ppud/lambda_scripts/terminate_cpu_process_dev.py
Consolidating the lambda - iam permissions code from two functions into one. Introducing a 120 second sleep/timeout value for the cpu termination python script.
> Update lambda functions 280524 3

- terraform/environments/ppud/iam.tf
- terraform/environments/ppud/lambda.tf
- terraform/environments/ppud/lambda_scripts/terminate_cpu_process_uat.py
Consolidating the lambda - IAM permissions code from two functions into one (UAT). Introducing a 120 second sleep/timeout value for the CPU termination python script (UAT).
> Update lambda functions 280524 6

- terraform/environments/oasys/locals_production.tf
oasys prod public ssl policy update
> oasys prod public ssl policy update

- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
New DNS zone for lsast environment
> ncr: DSOS-2796: add new zone for lsast

- terraform/environments/nomis-combined-reporting/locals_production.tf
> DSOS-2796: NS records for lsast zone

- terraform/environments/oasys-national-reporting/locals_test.tf
- change asg values for test onr-web instance
- add get secrets permissions for onr-bods instances
> change t2-test-onr-web instance defaults

- terraform/environments/oasys-national-reporting/locals_defaults.tf
- add missing drives for onr-web instances defaults
> change drive defaults for onr-web

- terraform/environments/oasys-national-reporting/locals_test.tf
Reverts ministryofjustice/modernisation-platform-environments#6300
> Revert "onr: remove bods server"

- terraform/environments/nomis/locals.tf
- terraform/environments/nomis/locals_development.tf
- terraform/environments/nomis/locals_preproduction.tf
- terraform/environments/nomis/locals_production.tf
- terraform/environments/nomis/locals_test.tf
- terraform/modules/baseline_presets/cloudwatch_dashboards.tf
Move from SELECT to SEARCH query-  this allows more than 3 hours to be shown
> Nomis: DSOS-2797: dashboard tweaks

- terraform/environments/oasys-national-reporting/locals_test.tf
- change mod-plaform-config-management branch for t2-test-web-asg
- points to the branch with the silent installer steps in & work on that 
- add commented out t2-onr-web instance for deployment later
> add commented out t2-onr-web and change test branch for asg

- terraform/environments/electronic-monitoring-data/lambdas/create_athena_external_table.py
- terraform/environments/electronic-monitoring-data/lambdas/create_athena_external_tables.py
- terraform/environments/electronic-monitoring-data/lambdas/get_metadata_from_rds.py
- terraform/environments/electronic-monitoring-data/lambdas_cloudwatch.tf
- terraform/environments/electronic-monitoring-data/lambdas_iam.tf
- terraform/environments/electronic-monitoring-data/lambdas_main.tf
- terraform/environments/electronic-monitoring-data/step_functions_iam.tf
- terraform/environments/electronic-monitoring-data/step_functions_main.tf
- **setting up triggering**
- **allow invoke function**
> Trigger lambdas for each semantic table

- terraform/environments/nomis/locals.tf
- terraform/environments/nomis/locals_development.tf
- terraform/environments/nomis/locals_preproduction.tf
- terraform/environments/nomis/locals_production.tf
- terraform/environments/nomis/locals_test.tf
- terraform/modules/baseline_presets/cloudwatch_dashboards.tf
- terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
- terraform/modules/cloudwatch_dashboard/outputs.tf
Split out EC2 instance and autoscaling group metrics - fixes issue where some ASG metrics are not shown
> nomis: DSOS-2797: cloudwatch dashboard improvements

- terraform/environments/nomis/locals_production.tf
Oops - missed out some widgets
> DSOS-2797: add missing nomis prod widgets

- terraform/environments/analytical-platform-compute/kubernetes-namespaces.tf
- terraform/environments/analytical-platform-compute/secrets.tf
- Adds `actions-runner` namespace in production only
- Adds `actions-runner/create-a-derived-table` secret in production only
> 🏃 Actions Runner Setup

- terraform/environments/oasys-national-reporting/locals.tf
- terraform/environments/oasys-national-reporting/locals_defaults.tf
- terraform/environments/oasys-national-reporting/locals_test.tf
- create a rhel 6 onr-web asg for web-tier installer testing
- fix formatting in some files
> add base rhel 6 onr-web asg for testing, fix formatting

- terraform/environments/observability-platform/environment-configurations.tf
- Updates Grafana API key rotator to 1.0.5
- Removes Data Platform tenant
- Update Analytical Platform Compute production's AMP workspace configuration
> 🔭 Observability Platform updates

- terraform/environments/delius-core/locals_development.tf
- terraform/environments/delius-jitbit/application_variables.json
- terraform/environments/delius-jitbit/lambda/bounce_email_notification/bounce_email_notification.py
- terraform/environments/delius-jitbit/monitoring.tf
- terraform/environments/delius-jitbit/ses.tf
- terraform/environments/delius-jitbit/ses_bounce.tf
- terraform/environments/delius-jitbit/ses_logging.tf
- **✨ Enable delivery_delay logging**
> ✨ Jitbit bounce logging improvements + enable custom mail_from for dmarc ✅ 

- terraform/environments/hmpps-oem/locals.tf
- terraform/environments/hmpps-oem/locals_development.tf
- terraform/environments/hmpps-oem/locals_preproduction.tf
- terraform/environments/hmpps-oem/locals_production.tf
- terraform/environments/hmpps-oem/locals_test.tf
- terraform/environments/hmpps-oem/main.tf
Cosmetic changes to align terraform + use new baseline dashboard
> DSOS-2797: align hmpps-oem terraform with nomis

- terraform/environments/corporate-staff-rostering/locals.tf
- terraform/environments/corporate-staff-rostering/locals_defaults.tf
- terraform/environments/corporate-staff-rostering/locals_development.tf
- terraform/environments/corporate-staff-rostering/locals_preproduction.tf
- terraform/environments/corporate-staff-rostering/locals_production.tf
- terraform/environments/corporate-staff-rostering/locals_test.tf
- terraform/environments/corporate-staff-rostering/main.tf
- terraform/environments/corporate-staff-rostering/outputs.tf
align terraform with nomis - so easier to manage and to enable dashboard sharing
> DSOS-2797: align terraform with nomis

- terraform/environments/corporate-staff-rostering/locals.tf
- terraform/environments/corporate-staff-rostering/locals_defaults.tf
- terraform/environments/corporate-staff-rostering/locals_preproduction.tf
- terraform/environments/corporate-staff-rostering/locals_production.tf
Miscellaneous changes:
- enable OAM link to hmpps-oem account
- opt out of mod platform backup as we are using DSO backup policy
- align tags
- enable delete protection but allow instance stop
> DSOS-2797: csr: fix tags and setup oam

- terraform/environments/oasys-national-reporting/locals_test.tf
> remove references to branches that don't exist

- .github/workflows/analytical-platform-compute.yml
- .github/workflows/delius-core.yml
- .github/workflows/reusable_terraform_plan_apply.yml
- terraform/environments/analytical-platform-compute/data.tf
- Adds concurrency groups so workflows will wait for previous runs to finish
- Testing https://github.com/ministryofjustice/modernisation-platform/pull/7159
> 🎨 Terraform workflow enhancements

- terraform/environments/oasys-national-reporting/locals_test.tf
- deploy a persistent onr-web EC2 Instance
> deploy t2 onr-web instance

- terraform/environments/nomis/locals_preproduction.tf
> nomis: DSOS: add tags for lsast DB

- terraform/environments/example/shield.tf
- terraform/modules/shield_advanced/README.md
- terraform/modules/shield_advanced/shield.tf
- terraform/modules/shield_advanced/variables.tf
* Consistently apply a simple `count/block` WAF action
* Show an implementation in `example`
> Shield Advanced module updates

- terraform/environments/nomis/locals_preproduction.tf
Create secrets, policy and ASG for lsast
> nomis: DSOS: create lsast weblogic

- terraform/environments/observability-platform/environment-configurations.tf
- Is part of https://github.com/ministryofjustice/modernisation-platform/issues/6818
- Pending https://github.com/ministryofjustice/modernisation-platform/pull/7166
> 🔭 Add Modernisation Platform's Core Network Services account to Observability Platform

- terraform/environments/nomis/locals_preproduction.tf
needs to have weblogic as well
> nomis: add missing secret for lsast

- terraform/environments/example/shield.tf
- terraform/modules/shield_advanced/README.md
- terraform/modules/shield_advanced/monitoring.tf
- terraform/modules/shield_advanced/shield.tf
- terraform/modules/shield_advanced/variables.tf
* Included the `"aws_shield_application_layer_automatic_response"` resource.
* Concatenated the variables used to supply values to the shield resources.
With this PR, all the functional requirements for [MP Repo #7032](https://github.com/ministryofjustice/modernisation-platform/issues/7032) ought to have been met!
> Updated `shield_advanced` module to include automatic mitigation option

- terraform/environments/nomis/locals_preproduction.tf
Setup another ASG with warm pool and ready hook - same as prod. For testing rolling updates.
> nomis: DSOS-2838: preprod ASG test

- terraform/environments/nomis/locals_preproduction.tf
- terraform/modules/baseline/variables.tf
Test rolling update in preprod
> nomis: DSOS-2838: ASG rolling update test

- terraform/environments/nomis/locals_preproduction.tf
Nothing happening... trying with 50
> nomis: DSOS-2838: rolling update test

- terraform/modules/baseline/ec2_autoscaling_group.tf
Need to merge into main in order to test rolling update in nomis-preproduction. It won't break anything.
> DSOS-2838: asg instance refresh test

- terraform/modules/baseline/ec2_autoscaling_group.tf
Change is now in main - update baseline accordingly
> DSOS-2838: update ASG module version

- terraform/environments/nomis-data-hub/locals.tf
- terraform/environments/nomis-data-hub/locals_development.tf
- terraform/environments/nomis-data-hub/locals_ndh.tf
- terraform/environments/nomis-data-hub/locals_preproduction.tf
- terraform/environments/nomis-data-hub/locals_production.tf
- terraform/environments/nomis-data-hub/locals_test.tf
- terraform/environments/nomis-data-hub/main.tf
- terraform/environments/nomis-data-hub/outputs.tf
- terraform/modules/baseline_presets/variables.tf
> ndh: DSOS-2829: align terraform with nomis

- terraform/environments/nomis/locals_preproduction.tf
Scale down - test was successful
> DSOS-2838: scale down ASG used for instance refresh test in nomis-preprod

- terraform/environments/oasys-national-reporting/locals.tf
- terraform/environments/oasys-national-reporting/locals_preproduction.tf
- terraform/environments/oasys-national-reporting/locals_production.tf
- terraform/environments/oasys-national-reporting/locals_security_groups.tf
- terraform/environments/oasys-national-reporting/locals_test.tf
- create loadbalancer security group (lb)
- remove "oracle_weblogic_admin" rule temporarily to be able to fix description text properly
- add test environment wildcard cert
- LB settings currently commented out
Subsequent PR's will 
1. put the "oracle_weblogic_admin" rule back
2. change external validation records created to true
3. create LB in test environment
> Onr/dsos 2733/onr test alb

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_test.tf
> oasys test ansible

- terraform/environments/oasys/locals_security_groups.tf
There are duplicate entries causing issue
> oasys: remove duplicates from SGs

- terraform/environments/oasys-national-reporting/locals_production.tf
- validation of test records seems to be failing so 'edit' ns records to force them to be recreated
> change ttl to force recreation/update

- terraform/environments/nomis/locals_database.tf
- terraform/environments/nomis/locals_development.tf
> Nomis: DSOS-2798: oracle 19c build

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_defaults.tf
- terraform/environments/oasys/locals_development.tf
- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
- terraform/environments/oasys/locals_security_groups.tf
- terraform/environments/oasys/locals_test.tf
- terraform/environments/oasys/main.tf
- terraform/environments/oasys/outputs.tf
- terraform/modules/baseline_presets/outputs.tf
- terraform/modules/baseline_presets/variables.tf
Cosmetic changes - align terraform with nomis
> DSOS-2829: align oasys terraform with nomis

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/locals_preproduction.tf
- terraform/environments/oasys/locals_production.tf
- terraform/environments/oasys/locals_test.tf
Enable DSO backup plan
Enable dashboard
Reduce iops/bandwidth for test/preprod DBs
Remove duplicate validation record
Add NS records for reporting
> Oasys: terraform fixes

- terraform/environments/oasys-national-reporting/locals.tf
- terraform/environments/oasys-national-reporting/locals_test.tf
- terraform/environments/oasys-national-reporting/main.tf
- terraform/environments/oasys-national-reporting/outputs.tf
- add nfs share for test environment
- add missing locals/vars/etc. for efs module
> add nfs share for test env

- terraform/environments/oasys/locals.tf
- terraform/environments/oasys/main.tf
- terraform/environments/planetfm/locals.tf
- terraform/environments/planetfm/locals_development.tf
- terraform/environments/planetfm/locals_preproduction.tf
- terraform/environments/planetfm/locals_production.tf
- terraform/environments/planetfm/locals_test.tf
- terraform/environments/planetfm/main.tf
- terraform/environments/planetfm/outputs.tf
- terraform/modules/baseline/cost_usage_report.tf
- terraform/modules/baseline/resource_explorer.tf
- terraform/modules/baseline/variables.tf
Cosmetic changes only - align terraform with nomis so all applications have same terraform structure + hopefully easier to manage.
> DSOS-2829: align planetfm terraform with nomis

- terraform/environments/nomis-data-hub/locals.tf
- terraform/environments/nomis-data-hub/locals_development.tf
- terraform/environments/nomis-data-hub/locals_ndh.tf
- terraform/environments/nomis-data-hub/locals_preproduction.tf
- terraform/environments/nomis-data-hub/locals_production.tf
- terraform/environments/nomis-data-hub/locals_test.tf
Add dashboard and alarms.
Pagerduty integration to be enabled in separate PR.
Also added `instance-access-policy` tag for ssh access for Glenn.
> ndh: DSOS-2847: enable monitoring

- terraform/environments/nomis-data-hub/locals_development.tf
- terraform/environments/nomis-data-hub/locals_preproduction.tf
- terraform/environments/nomis-data-hub/locals_production.tf
- terraform/environments/nomis-data-hub/locals_test.tf
- terraform/modules/baseline_presets/cloudwatch_dashboards.tf
- terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
Enable pager duty integration
Fix alarms for filesystem check
Add dashboard widgets for filesystem check
> ndh: DSOS-2847: enable monitoring v2

- terraform/modules/baseline_presets/cloudwatch_dashboards.tf
- terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
Typoed the metric. Also updated confluence pages
> DSOS-2847: fix ndh filesystem monitoring

- terraform/environments/oasys-national-reporting/locals_defaults.tf
- terraform/environments/oasys-national-reporting/locals_security_groups.tf
- add external routes
- modify ONR security groups to add jumpserver sg to loadbalancer (in) and web instance (in) rules
> Onr/dsos 2733/add external routes

- terraform/environments/oasys-national-reporting/locals_security_groups.tf
> used wrong name for sg

- terraform/environments/nomis-combined-reporting/locals_development.tf
- terraform/environments/nomis-combined-reporting/locals_jumpserver.tf
- terraform/environments/nomis-combined-reporting/locals_security_groups.tf
- add WindowsServer 2019 jumpserver asg
- add private-jumpserver security group
> add jumpserver asg to dev env

- terraform/environments/observability-platform/environment-configurations.tf
- Adds #mod-plat-observ-test for @ep-93 
> ✉️ Add Modernisation Platform's Slack channel to their Observability Platform configuration

- terraform/environments/oasys-national-reporting/locals.tf
- terraform/environments/oasys-national-reporting/locals_defaults.tf
- terraform/environments/oasys-national-reporting/locals_development.tf
- terraform/environments/oasys-national-reporting/locals_preproduction.tf
- terraform/environments/oasys-national-reporting/locals_production.tf
- terraform/environments/oasys-national-reporting/locals_security_groups.tf
- terraform/environments/oasys-national-reporting/locals_test.tf
- terraform/environments/oasys-national-reporting/main.tf
- terraform/environments/oasys-national-reporting/outputs.tf
Primarily cosmetic changes to align with nomis terraform. 
Some minor plan changes as removed hmpps domain requirement and user-data corrections.
> onr: DSOS-2829: align terraform

- terraform/environments/digital-prison-reporting/s3.tf
- Onboard Structured Historical
> Onboard Structured Historical

- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
Otherwise EC2s will get rebuilt on apply
> ncr: DSOS-2829: fix ami versions for preprod

- terraform/environments/analytical-platform-compute/kubernetes-roles.tf
> 🚑 Add `patch` verb to Airflow SA management role

- terraform/environments/ppud/certificate_mgmt.tf
New eventbridge rule to manage certificates approaching expiration.
This time for the production environment.
> EventBridge_Rule_CAE_130624_5

- terraform/environments/nomis/locals_development.tf
- terraform/modules/baseline_presets/ssm-documents/ec2-configuration-management-linux.yaml
Add dev-nomis-web19c-a autoscaling group for Oracle 19c project
Tweak to linux config management ssm doc cleanup output
> nomis: DSOS-2800: weblogic 19c

- terraform/environments/analytical-platform-compute/helm-charts-system.tf
> 📌 Update Helm system releases

- terraform/environments/ccms-ebs-upgrade/iam.tf
- terraform/environments/ccms-ebs-upgrade/sns.tf
- terraform/environments/ccms-ebs/ccms-iam.tf
CC-2554: Added 'EC2 operations' policy to the OracleBase role.
> CC-2554: Added 'EC2 operations' policy to the OracleBase role.

- terraform/modules/baseline_presets/cloudwatch_dashboards.tf
- Insert the correct dimension
- Reformat UnHealthyHostCount to make it more readable
- Remove TargetTLSNegotiationErrorCount as no data returns
> Fix NLB metrics

- terraform/environments/oasys/locals_production.tf
- terraform/environments/oasys/locals_security_groups.tf
> oasys add public networks

- terraform/environments/digital-prison-reporting/main.tf
- terraform/environments/digital-prison-reporting/modules/dms/outputs.tf
- terraform/environments/digital-prison-reporting/modules/dms_dps/outputs.tf
- terraform/environments/digital-prison-reporting/modules/dms_s3_v2/outputs.tf
- terraform/environments/digital-prison-reporting/modules/dms_s3_v2/variables.tf
- terraform/environments/digital-prison-reporting/modules/domains/dms-task/outputs.tf
- terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf
- terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/variables.tf
- terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/pipeline.tf
- terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/variables.tf
- terraform/environments/digital-prison-reporting/modules/glue_job/main.tf
- terraform/environments/digital-prison-reporting/modules/glue_job/variables.tf
This PR adds a step to stop the DMS task to the replay and reload pipelines.
Some of the static code analysis were also fixed.
> DPR2-713: Add job to stop a running DMS task

- terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/3544
- Adds a new runner for CaDeT to access DPR
> ✨ Actions Runner for CaDeT DPR

- terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Added Essex Police Key and IP to Prod
> Add Essex Police Key+IP to Prod

- terraform/environments/nomis/locals.tf
Enable Session Manager logging via baseline option
> nomis: DSOS-2229: reenable session loggin

- terraform/environments/mlra/modules/alb/main.tf
Revert part of previous change.
`default_root_object = "Empty"`
Jira: [LASB-3291](https://dsdmoj.atlassian.net/browse/LASB-3291)
[LASB-3291]: https://dsdmoj.atlassian.net/browse/LASB-3291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LASB-3291 Revert default_root_object = "Empty"

- terraform/environments/nomis-combined-reporting/locals_security_groups.tf
- add connection for azure temporarily
> add connectivity for universe designer port from azure

- scripts/echo-hello.sh
- terraform/environments/electronic-monitoring-data/modules/lambdas/main.tf
Fixes attempted:
Got an interesting error, `program output must be a JSON encoded map of string keys and string values`. So 
Evidence of passing run: https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/9600016506
> Small PR to fix a bug in development caused by removing external data source between plans

- terraform/environments/nomis/locals_production.tf
Reduce number of weblogic servers
Reduce prod iops/bandwidth settings
> nomis: DSOS-2862: prod weblogic and iops changes

- terraform/environments/digital-prison-reporting/main.tf
- terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/glue.tf
- terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/variables.tf
- terraform/environments/digital-prison-reporting/operational_datastore.tf
- Add glue connection parameters to domain ingestion jobs module
- Add Operational Datastore Glue connection to DataHub Glue jobs in this repo
> DPR2-893: Glue Connection for ingestion jobs module

- terraform/modules/baseline_presets/iam_policies.tf
- terraform/modules/baseline_presets/iam_policy_statements_ec2.tf
- terraform/modules/baseline_presets/s3.tf
- terraform/modules/baseline_presets/variables.tf
> CSR shared bucket permission fixes

- terraform/environments/observability-platform/environment-configurations.tf
- Adds Data Engineering and their Sandbox A account
> ✨ Add Data Engineering to Observability Platform

- terraform/environments/analytical-platform-compute/environment-configuration.tf
- terraform/environments/analytical-platform-compute/helm-charts-mlops.tf
- terraform/environments/analytical-platform-compute/iam-policies.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/4275
- Updates MLFlow to use an Analytical Platform Control Panel created bucket as the backend
> 🔧 Update MLFlow artefact bucket

- terraform/environments/analytical-platform-compute/cloudwatch-log-groups.tf
- terraform/environments/analytical-platform-compute/eks-cluster.tf
- terraform/environments/analytical-platform-compute/helm-charts-mlops.tf
- terraform/environments/analytical-platform-compute/helm-charts-system.tf
- terraform/environments/analytical-platform-compute/kms-keys.tf
- terraform/environments/analytical-platform-compute/rds.tf
- Updates Helm charts and Terraform modules
> 📌 Patch APC

- terraform/environments/corporate-staff-rostering/locals.tf
- terraform/environments/oasys-national-reporting/locals.tf
- terraform/modules/baseline_presets/s3.tf
> DSOS-2690: fix s3 variable names

- terraform/environments/nomis/locals_preproduction.tf
- terraform/environments/nomis/locals_production.tf
> DSOS-2682: further scale down of weblogic servers

- terraform/environments/corporate-staff-rostering/locals.tf
- terraform/environments/corporate-staff-rostering/locals_development.tf
- terraform/environments/corporate-staff-rostering/locals_preproduction.tf
- terraform/environments/corporate-staff-rostering/locals_production.tf
- terraform/environments/corporate-staff-rostering/locals_test.tf
- terraform/environments/nomis-combined-reporting/locals.tf
- terraform/environments/nomis-combined-reporting/locals_development.tf
- terraform/environments/nomis-combined-reporting/locals_preproduction.tf
- terraform/environments/nomis-combined-reporting/locals_production.tf
- terraform/environments/nomis-combined-reporting/locals_test.tf
- terraform/modules/baseline_presets/s3.tf
Update db backup settings as agreed with DBAs
Opt out of AWS backup for S3
> DSOS-2690: update db backup retention

- terraform/environments/electronic-monitoring-data/dms_capita_alcohol_monitoring_task_tables_selection.json
- terraform/environments/electronic-monitoring-data/dms_civica_orca_task_tables_selection.json
- terraform/environments/electronic-monitoring-data/dms_g4s_atrium_task_tables_selection.json
- terraform/environments/electronic-monitoring-data/dms_main.tf
- **add for single table**
- **adding two new jobs**
> EM: Add new jobs for DMS to migrate new databases

- terraform/environments/hmpps-domain-services/locals.tf
Add this into baseline so it gets the lifecycle changes for free
> DSOS-2690: update s3 lifecycle in hmpps-domain-services

- terraform/environments/nomis/locals_production.tf
- recreate this to test GPOs in a clear environment
> re-apply test server

- terraform/environments/analytical-platform-compute/eks-cluster.tf
- terraform/environments/analytical-platform-compute/helm-charts-system.tf
- terraform/environments/analytical-platform-compute/iam-policies.tf
- terraform/environments/analytical-platform-compute/kms-keys.tf
- terraform/environments/analytical-platform-compute/kubernetes-namespaces.tf
- terraform/environments/analytical-platform-compute/service-linked-roles.tf
- terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/Chart.yaml
- terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/ec2-node-class-bottlerocket-general.yaml
- terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-general-on-demand.yaml
- terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-general-spot.yaml
- terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/values.yaml
- terraform/environments/analytical-platform-compute/src/helm/values/karpenter-configuration/values.yml.tftpl
- terraform/environments/analytical-platform-compute/src/helm/values/karpenter/values.yml.tftpl
- terraform/environments/analytical-platform-compute/src/helm/values/kyverno/values.yml.tftpl
- terraform/environments/analytical-platform-compute/vpc.tf
- Installs Karpenter
- Adds Karpenter EC2 node class and node pools for general on-demand and spot
> ✨ APC Karpenter

- terraform/modules/baseline_presets/s3.tf
> DSOS-2690: tweak lifecycle settings for db backup buckets

- terraform/environments/apex/alb.tf
- terraform/environments/maat/maat-int-lb.tf
- terraform/environments/portal/external_alb.tf
- terraform/environments/portal/internal_alb.tf
LAWS-3910: changed LB ssl policy
> LAWS-3910: changed LB ssl policy

- terraform/environments/corporate-staff-rostering/locals_production.tf
- terraform/environments/oasys/locals_production.tf
- terraform/modules/baseline_presets/s3.tf
- terraform/modules/baseline_presets/variables.tf
glacier isn't going to work.
update retention periods as per advice from Sandhya
> DSOS-2690: tweak lifecycle settings for db backup buckets again

- scripts/terraform-plan-evaluator.sh
- terraform/environments/analytical-platform-compute/data.tf
- terraform/environments/analytical-platform-compute/transit-gateway-vpc-attachments.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/4490
- Attaches PTTP TGW to APC VPC
- Blocked by https://github.com/ministryofjustice/modernisation-platform/pull/7347
> ✨ APC PTTP TGW attachment

- terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
- Increases the replica count for create-a-derived-table and airflow now we're pushing more work through them
> ⏫ Increase replica count for create-a-derived-table and airflow

- .github/workflows/awsnuke.yml
- .github/workflows/nuke-redeploy.yml
This amends the nuke workflows so as to mask the account_number values appearing in the log output.
> Adds the mask for ACCOUNT_NUMBER variable in nuke workflows

- terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
New image release `2.317.0` -> `2.317.0-2`
> :wrench: Update airflow runner image version

- terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
> :wrench: Update Airflow Action Runner version

- terraform/environments/electronic-monitoring-data/dms_iam.tf
@matt-heery and I looking at Data quality directly in DMS and seeing if it might help with creating reporting metrics to validate our data, and speed of DMS migration jobs
> initial attempt to change DMS permissions

- terraform/environments/analytical-platform-compute/data.tf
- terraform/environments/analytical-platform-compute/environment-configuration.tf
- terraform/environments/analytical-platform-compute/helm-charts-system.tf
- terraform/environments/analytical-platform-compute/quicksight.tf
- Updates Bottlerocket to `1.20.3-5d9ac849`
- Updates EBS CSI driver to `v1.32.0-eksbuild.1`
- Updates Cert Manager to `v1.15.1`
- Updates Kube Prometheus Stack to `61.1.0`
- Updates Prometheus Operator CRD to `v0.75.0`
- Grabs SSO instance ARN for QuickSight
> 📌 APC updates

- terraform/modules/baseline_presets/ssm-documents/Session/SSM-SessionManagerRunShell.json
- Increase idle timeout for sessions
> Increase idle timeout for sessions

- terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
- terraform/environments/analytical-platform-compute/kms-keys.tf
- terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf
- terraform/environments/analytical-platform-compute/kubernetes-namespaces.tf
- terraform/environments/analytical-platform-compute/kubernetes-secrets.tf
- terraform/environments/analytical-platform-compute/random.tf
- terraform/environments/analytical-platform-compute/rds.tf
- terraform/environments/analytical-platform-compute/secrets.tf
- Creates KMS and RDS for AP UI
- Creates Kubernetes namespace for UI
- Creates Kubernetes secret for UI RDS
- Creates Kubernetes External Secret for Sentry DSN
> ✨ Analytical Platform UI RDS

- terraform/environments/corporate-staff-rostering/iam.tf
- terraform/environments/corporate-staff-rostering/lambda.tf
- terraform/environments/corporate-staff-rostering/locals_development.tf
- add exceptions to CSR env for static analysis to pass
- mostly ref: lambda in this env
> run plan to make static analysis fail

- terraform/environments/oasys-national-reporting/templates/cloud_watch_windows.json
Need to do some experimentation. Will do that on a test branch.
Reverts ministryofjustice/modernisation-platform-environments#6868
> Revert "add config for procstat in CloudWatch agent"

- terraform/modules/baseline/s3_bucket.tf
- terraform/modules/baseline/variables.tf
- terraform/modules/baseline_presets/iam_policy_statements_ec2.tf
- terraform/modules/baseline_presets/iam_policy_statements_s3.tf
- terraform/modules/baseline_presets/s3.tf
At some point mod platform repo changed the default permissions - changing it back to what we need. Also widening the Get permissions so we can get the ACLs.
> nomis: DSOS: s3 permission fix

- terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf
Adds kubernetes secret for azure client and tenant IDs
> Uncomment ui-azure-secrets

- terraform/environments/nomis/locals_preproduction.tf
- terraform/environments/nomis/locals_production.tf
Align both production ASGs to same branch, same with preproduction. Tweaking the release process.
> nomis: DSOS: weblogic release testing

- terraform/environments/nomis-data-hub/locals.tf
For updated CDE distribution pipeline
> DSOS-2868: add azure sastoken ssm param to ndh

- terraform/environments/contract-work-administration/backups.tf
[LAWS-3906] Added vault backup policy for CWA
[LAWS-3906]: https://dsdmoj.atlassian.net/browse/LAWS-3906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LAWS-3906] Added vault backup policy for CWA

- terraform/environments/oasys-national-reporting/locals_test.tf
- terraform/environments/planetfm/locals_production.tf
- set t2-onr-client-a jumpserver ami so it doesn't update
- set over-ride on planetfm-production lb to keep logs longer
> fix test jumpserver ami so it doesn't update

- terraform/environments/oasys/locals_production.tf
> oasys web b

- terraform/environments/hmpps-domain-services/lambda.tf
- terraform/environments/hmpps-domain-services/patch.tf
- terraform/environments/hmpps-domain-services/platform_versions.tf
- add tags to lambda module call and checkov exception
- add checkov exception to patches module calls
- archive provider needs a version for static analysis to pass
> fix tflint errors

- terraform/environments/oasys/templates/ansible-ec2provision.sh.tftpl
oasys skip crypto collection error
> oasys skip crypto collection error

- terraform/environments/electronic-monitoring-data/step_functions_main.tf
- **all result selection**
- **select just a portion of the input**
Check [this guidance](https://docs.aws.amazon.com/step-functions/latest/dg/input-output-inputpath-params.html) that ive tried to follow....
> EM: Step Function tweak

- terraform/environments/electronic-monitoring-data/dms_capita_forms_and_subject_id_task_tables_selection.json
- terraform/environments/electronic-monitoring-data/dms_g4s_emsys_tpims_task_tables_selection.json
- terraform/environments/electronic-monitoring-data/dms_g4s_fep_task_tables_selection.json
- terraform/environments/electronic-monitoring-data/dms_g4s_rf_hours_task_tables_selection.json
- terraform/environments/electronic-monitoring-data/dms_g4s_tasking_task_tables_selection.json
- terraform/environments/electronic-monitoring-data/dms_main.tf
- **all dms jobs**
- **table selection**
> EM: add all dms jobs

- terraform/environments/oasys/locals_production.tf
- terraform/environments/oasys/templates/ansible-ec2provision2.sh.tftpl
> oasys web b ptc and trn

- terraform/environments/oasys/locals_production.tf
> fix number of conditions

- terraform/environments/observability-platform/environment-configurations.tf
as per ticket https://github.com/ministryofjustice/modernisation-platform/issues/7221 this PR adds the core modernisation platform accounts to the observability platform.
> ✨ Add Modernisation Platform core accounts to Observability Platform

- terraform/environments/portal/rds.tf
> LAWS-3974: Update Portal RDS WorkSpace allow rules

- terraform/environments/oasys/locals_production.tf
oasys rationalise load balancers
> oasys rationalise load balancers

- terraform/environments/oasys/locals_production.tf
> oasys scale up web b

- terraform/environments/digital-prison-reporting/locals.tf
- terraform/environments/digital-prison-reporting/operational_datastore.tf
- terraform/environments/digital-prison-reporting/transfer_component.tf
Currently using temporary ODS.
> DPR2-902: Transfer component lambda for operational datastore.

- terraform/environments/oasys/locals_production.tf
> oasys correct practice b link

- terraform/environments/analytical-platform-compute/environment-configuration.tf
- terraform/environments/analytical-platform-compute/helm-charts-applications.tf
- terraform/environments/analytical-platform-compute/src/helm/values/ui/values.yml.tftpl
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/4456
- Deploys AP UI
> ✨ Analytical Platform UI Initial Deployment

- terraform/environments/analytical-platform-compute/kubernetes-secrets.tf
- Adds an `environment` key to UI's app secrets
> 🚧 Add environment for APUI

- terraform/environments/nomis-data-hub/locals.tf
- terraform/environments/nomis-data-hub/locals_production.tf
- terraform/environments/nomis-data-hub/locals_test.tf
Add offloc upload bucket in all NDH accounts.
Fix access permissions, we shouldn't let dev/test accounts access prod
Remove unused ssm param
> ndh: DSOS-2868: add offloc storage account in all accounts

- terraform/environments/cdpt-ifs/monitoring.tf
changes the current metric from HTTPCode_Target_5XX_Count to HTTPCode_ELB_5XX_Count
> change metric to HTTPCode_ELB_5XX_Count

- terraform/environments/oasys/locals_production.tf
> oasys switch to b side

- terraform/environments/cdpt-chaps/monitoring.tf
This adds a cloudwatch alarm and creates PagerDuty integration for #cdpt-chaps
> add cloudwatch alarm for loadbalancer 5xx

- terraform/environments/nomis/locals_test.tf
> DSOS: nomis: increase number of client test servers

- terraform/environments/oasys/locals_production.tf
oasys scale down unused a side
> oasys scale down unused a side

- .github/workflows/awsnuke.yml
- .github/workflows/nuke-redeploy.yml
This PR is part of [this issue](https://github.com/ministryofjustice/modernisation-platform/issues/7395) in the `modernisation-platform-environments` repository.
It does the following:
* Adds a Slack notification step based off of a common pattern used elsewhere in this repository
> Notify team when nuke / nuke rebuilds fail

- terraform/environments/hmpps-domain-services/patch.tf
- Testing against linux and windows instances
> Test ssm patch module refactor

- terraform/environments/digital-prison-reporting/data.tf
- terraform/environments/digital-prison-reporting/locals.tf
- terraform/environments/digital-prison-reporting/main.tf
- terraform/environments/digital-prison-reporting/operational_datastore.tf
- terraform/environments/digital-prison-reporting/secrets.tf
- terraform/environments/digital-prison-reporting/transfer_component.tf
- Remove old ODS secret
- Replace with Hari's new ODS secret
- Replace JDBC connection string with the one for the new ODS
- Glue data connection uses new JDBC connection string
- Glue connection created in every environment rather than just dev
- Glue connection and secret added to the glue jobs in every environment rather than just dev
> DPR2-892 Connect jobs to real Operational DataStore

- terraform/environments/cica-tariff/data.tf
- terraform/environments/cica-tariff/locals.tf
- terraform/environments/cica-tariff/tariff_ec2_app.tf
- terraform/environments/cica-tariff/tariff_ec2_app_sg.tf
- terraform/environments/cica-tariff/tariff_ec2_iam.tf
Create Tariff instance, volumes, security group and other related resources.
> Cdi 208 tariff dev instance

- terraform/environments/digital-prison-reporting/transfer_component.tf
- Deploy transfer component lambda in all environments
> DPR2-902: Deploy transfer component lambda in all environments.

- terraform/environments/analytical-platform-compute/helm-charts-applications.tf
Adds sentry functionality to AP UI
> bump APUI to rc1

- terraform/environments/hmpps-oem/locals.tf
- terraform/environments/hmpps-oem/locals_development.tf
- terraform/environments/hmpps-oem/locals_ec2_instances.tf
- terraform/environments/hmpps-oem/locals_security_groups.tf
- terraform/environments/hmpps-oem/locals_test.tf
- terraform/environments/hmpps-oem/main.tf
- terraform/environments/hmpps-oem/outputs.tf
Enable
- session manager logging
- automated SSM Agent update
- EC2 windows dashboard widgets
Remove
- unused SSM parameter
- unused alarms
> hmpps-oem: DSOS-2876: align features with nomis

- terraform/environments/nomis-combined-reporting/locals_production.tf
- added test pd-ncr-db-2-c server for role testing
> add temp db for testing

- terraform/environments/nomis-combined-reporting/locals_production.tf
- we don't need to run ALL these machines as part of the knowledge transfer
- keep only required ones for now
> comment out un-needed servers in prod

- terraform/environments/nomis/locals.tf
- terraform/environments/nomis/locals_preproduction.tf
- terraform/environments/nomis/locals_test.tf
Minor enhancements following feedback on the automatic power-up/down of environments:
- improve error message
- remove unhealthy host alarm on environments which have overnight power downs
> Nomis: DSOS-2899: start and stop environment improvements

- terraform/environments/cica-tariff/tariff_vpc_endpoints.tf
Add endpoints to VPC that are required for SSM access
> ✨ Add VPC Interface endpoints

- terraform/environments/cica-tariff/tariff_vpc_endpoints.tf
Fix reference subnets datasource to return subnet ids
> 🐛 Fix subnet data source reference

- terraform/environments/planetfm/locals_production.tf
- add new cert as per DSOS-2894
- set external validation = false initially
> add new acm cert

- terraform/environments/oasys/iam.tf
> oasys add migration user

- terraform/environments/nomis-combined-reporting/locals_production.tf
- deploy cms-b
New plan - deploy all the things then turn the machines off in Prod apart from the db instances
> deploy prod cms-b

- terraform/environments/hmpps-oem/locals.tf
- terraform/environments/oasys-national-reporting/locals.tf
- terraform/environments/oasys-national-reporting/locals_development.tf
- terraform/environments/oasys-national-reporting/main.tf
Enable metric sharing from ONR to hmpps-oem
Add dashboards in hmpps-oem
> onr: DSOS-2890: align terraform with nomis v3

- terraform/environments/data-platform/infra_route53.tf
> Remove DP TDT record

- terraform/environments/nomis-combined-reporting/locals_production.tf
- need the web-admin instance up for prod deployment
> deploy ncr-web-admin-a instance

- terraform/environments/electronic-monitoring-data/lambdas_iam.tf
> Remove IAM permissions

- terraform/environments/nomis-combined-reporting/locals_production.tf
- only one web instance deployed at the moment, add more later
> add lb for production
