ministryofjustice/modernisation-platform-environments

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
- Bumps `actions-runner` to `2.317.0`
=> 📌 Update APC Actions Runner chart

terraform/environments/hmpps-oem/locals.tf, terraform/modules/baseline/cloudwatch.tf, terraform/modules/baseline/variables.tf, terraform/modules/baseline_presets/cloudwatch_dashboards.tf, terraform/modules/baseline_presets/outputs.tf, terraform/modules/cloudwatch_dashboard/main.tf, terraform/modules/cloudwatch_dashboard/variables.tf
Add additional dashboards in OEM account for nomis and corporate-staff-rostering. Not fully working yet due to permission issue which I'll fix separately.
=> DSOS-2797: add oem dashboards

terraform/environments/oasys-national-reporting/locals_defaults.tf, terraform/environments/oasys-national-reporting/locals_test.tf
- Deployed EC2 instances used fixed ami references when deployed so disks/instance doesn't change
- ASG's use wildcards/latest for testing
=> fix onr-bods ami at specific version

terraform/environments/analytical-platform-compute/data.tf, terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/helm-charts-system.tf, terraform/environments/analytical-platform-compute/kubernetes-manifests.tf, terraform/environments/analytical-platform-compute/src/helm/values/amazon-prometheus-proxy/values.yml.tftpl
Resolves https://github.com/ministryofjustice/analytical-platform/issues/4424
- Switches from vanilla Prometheus to `kube-prometheus-stack` which includes `prometheus-operator` 
TODO before merging:
=> 🔭 Switch APC to `kube-prometheus-stack`

terraform/environments/example/application_variables.json, terraform/environments/example/shield.tf, terraform/modules/shield_advanced/shield.tf, terraform/modules/shield_advanced/variables.tf
As noted, this allows a module user to supply values which can be excluded from association with the AWS Shield managed WAF ACL. I don't have a good way to supply them without hard-coding, so in `example` I've placed the relevant ID to be excluded into the application json.
Ideally I'd be able to use a data source like `data.aws_shield_protections` but as I'm currently using an `external` data source to get this information there are limits to what I can achieve without adding extra complication.
=> Allowed optional exclusion of protection IDs from shield module

terraform/modules/shield_advanced/variables.tf
Adds a `default` to `var.excluded_protections` so that it's correctly optional. Tested through local Terraform plan.
=> Set `shield_advanced` variable input to optional

terraform/environments/oasys/locals_security_groups.tf, terraform/modules/baseline/security_groups.tf
SG fails if there are duplicate cidrs, try to prevent accidents by putting distinct logic in baseline
=> Oasys: DSOS-2829: put securitygroup fix in baseline

terraform/environments/nomis/locals_production.tf
Enable instance refresh on production weblogic servers and lock to a particular commit
Will be applied Saturday a.m.
=> nomis: DSOS-2838: enable instance refresh for the weekend

terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/kubernetes-namespaces.tf, terraform/environments/analytical-platform-compute/route53-zones.tf
- Updates EKS node version
- Updates VPC CNI version
- Updates Route53 module
- Sets `pod-security.kubernetes.io/enforce` to `baseline` for `airflow` namespace, we found that jobs wouldn't schedule when using `restricted` due to security context not being set
=> 📌 Update APC EKS

terraform/modules/baseline_presets/iam_policy_statements_ec2.tf
s3:GetObjectTagging is required by `aws s3 cp` command when restoring from Glacier. Adding this permission so this can be triggered from EC2 instances.
Tested against the artefact bucket in core-shared-services-production
=> DSOS: glacier restore fix

terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/kubernetes-role-bindings.tf, terraform/environments/analytical-platform-compute/kubernetes-roles.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/4319
- Is being tested in https://github.com/moj-analytical-services/airflow/pull/3605
- Adds GitHub assumable role for https://github.com/moj-analytical-services/airflow
- Creates Kubernetes role and role binding for SA management in Airflow namespace
- Adds EKS access entry for role
=> 🛂 Airflow repository access to APC

terraform/modules/baseline_presets/ec2_autoscaling_group.tf
Forgot to commit this - allow min size of 0 for warm pools.  So you can delete instances if you really want to.
=> DSOS-2759: allow warm pool with zero instances

terraform/environments/ppud/certificate_mgmt.tf
New eventbridge rule to manage certificates approaching expiration.
=> Event bridge rule cae 130624 4

terraform/environments/corporate-staff-rostering/locals.tf, terraform/modules/baseline_presets/cloudwatch_dashboards.tf
Updated CloudWatch module to include the following metrics for NLB:
- UnHealthyHostCount
- ActiveFlowCount
- NewFlowCount
- PeakPacketsPerSecond
- ProcessedPackets
- TargetTLSNegotiationErrorCount
Enabled for CSR
=> Updated NLB metrics

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/locals_test.tf, terraform/environments/oasys-national-reporting/platform_versions.tf
HARDCODE AWS PROVIDER VERSION to 5.53.0 for now as currently a bug - due to be fixed in 5.57.0
- add sns topics / pagerduty links for test, preproduction and production
- commented out for now as we don't want these to be live yet
- using oasys_alarms value to send alarms to about things like "server down" etc.
=> add sns topics

.github/workflows/cooker.yml, .github/workflows/example.yml, .github/workflows/sprinkler.yml
https://github.com/ministryofjustice/modernisation-platform/issues/7160
I've removed `types` from `pull_request` in all the MP-owned workflows so I can test the behaviour of the workflows when I merge this in for all the applications in MPE in PR https://github.com/ministryofjustice/modernisation-platform-environments/pull/6578
=> Test removing `types` from `pull_request:` for MP Workflows

terraform/environments/performance-hub/loadbalancer.tf
Hello! I'm working on a Modernisation Platform story on behalf of the SOC team. The story is about load balancer listeners that support less-than-secure versions (TLS 1.1 and 1.0). I can see some alerts in the story that point at performance-hub load balancers, and long story short if you don't specify a listener in terraform, you get assigned an old default policy that supports less-than-secure listeners.
The `ELBSecurityPolicy-2016-08` policy is the default security policy for HTTPS listeners created using the AWS CLI.
=> Update `ssl_policy` for performance-hub https listeners

terraform/environments/nomis/locals_ec2_autoscaling_groups.tf, terraform/modules/baseline_presets/ssm.tf
Add SSM association for nomis-client server to re-run powershell provisioning script. This will update choco packages and cloudwatch agent.
=> nomis: DSOS-2829: auto update nomis client servers

terraform/environments/analytical-platform-compute/environment-configuration.tf
- Updates Bottlerocket OS to [`v1.20.2`](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.20.2)
- Updates EKS pod identity to `v1.3.0-eksbuild.1`
- Updates EFS CSI to `v2.0.4-eksbuild.1`
=> 📌 Update Bottlerocket, EKS pod identity and EFS CSI versions

terraform/modules/baseline/variables.tf, terraform/modules/baseline_presets/variables.tf
- according to google this needs to be above the resource/variable declaration
=> move tflint-ignore string

terraform/modules/baseline/bastion_linux.tf, terraform/modules/cost_usage_report/main.tf
- add exception for S3 module call in 
- baseline/bastion_linux.tf updated GUID/ref - will change value next week
- modules/cost_usage_report
- fix tflint issues with tf v0.11 parsing as newer 0.12 release will now trigger tflint errors
- see [here](https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_interpolation.md) for explanation
=> fix trivy flagging s3 key in modules - static analysis should pass now

terraform/environments/digital-prison-reporting/data.tf, terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/operational_datastore.tf, terraform/environments/digital-prison-reporting/secrets.tf
- Limit created resources to Dev/Sandbox only
- Create a Glue JDBC Data Connection for attachment to DataHub Glue jobs to give them Operational Datastore access
- Temporarily populate it with the manually created Dev/Sandbox RDS details which will be replaced by the actual Operational Datastore details
- Create a secret for the credentials used by the DataHub Glue jobs to write to the Operational Datastore
- Create a Security Group associated with the Glue JDBC Data Connection
- it will be associated with a glue job automatically when the connection is attached to it
- this is a requirement of Glue and it allows Glue to communicate with itself by allowing TCP ingress on all ports from the security group. See https://docs.aws.amazon.com/glue/latest/dg/setup-vpc-for-glue-access.html
- the …
=> DPR2-893: Glue connection and placeholder operational datastore secret

terraform/environments/planetfm/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
-  Chose same policy as oasys
- https://dsdmoj.atlassian.net/browse/DSOS-2793
=> Update SSL policy for planetfm

terraform/environments/corporate-staff-rostering/locals.tf, terraform/modules/baseline_presets/s3.tf
For copying files inbetween preprod and prod. Needs to be separate to the DB Backup bucket.
=> csr: Add shared S3 bucket for DBAs

terraform/environments/nomis/locals_production.tf
- add another nomis client instance
- temporary, being used for GPO SSO allow testing
=> create prod-nomis-client-b instance for testing GPO changes to allow SSO

terraform/environments/hmpps-oem/locals.tf, terraform/environments/nomis/locals.tf, terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_production.tf, terraform/environments/nomis/locals_test.tf, terraform/environments/oasys/locals.tf, terraform/modules/baseline_presets/iam_policies.tf, terraform/modules/baseline_presets/iam_policy_statements_ec2.tf, terraform/modules/baseline_presets/outputs.tf, terraform/modules/baseline_presets/s3.tf, terraform/modules/baseline_presets/variables.tf
A bit of tidy up before updating S3 lifecycles across accounts:
- updated baseline presets db backup so it works with nomis
- tidy up baseline s3 code a little, make it consistent with other resources
- updating variable naming for s3 buckets for consistency
- added the default bucket lifecycle into baseline_presets
=> DSOS-2690: s3 lifecycle changes

terraform/environments/nomis/locals_production.tf
- delete this temporarily
- expect a PR to put it back shortly
- goal is to re-create this from scratch and make sure it all still works under the revised GPO
=> remove prod-nomis-client-b temporarily

.github/workflows/reusable_terraform_plan_apply.yml, .github/workflows/reusable_terraform_plan_apply_test.yml
Masks the values of ACCOUNT_NUMBER and BACKEND_NUMBER to prevent the account number being displayed in env outputs of this repository's workflows.
=> Issue 13 - Masking account numbers in workflow logs.

scripts/redact-output.sh
This adds two additional patterns to the redact script to pick out occurrences of account numbers listed in terraform plan and apply outputs and replace them with a mask. Two additional sed statements are required as some ARNS have double colons "::" and sone just one ":".
=> Issue 13 - Adds additional sed statements to the redact-output script.

terraform/environments/nomis/locals_test.tf
- default computer OU on dev/test DC has been changed
- check this will come up and still be accessible
=> create a test client server to check OU default redirect works

terraform/environments/nomis/locals_production.tf, terraform/environments/nomis/locals_test.tf
- remove test-nomis-client-b asg, no longer needed for testing
- remove prod-nomis-client-b asg, no longer needed for testing
=> remove nomis client asg's for testing OU defaults for mod-platform

terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_test.tf
T1/lsast rarely used - there's new functionality to start these on demand.
=> DSOS-2861: enable start-on-demand functionality for t1 and lsast

terraform/environments/nomis/locals_ec2_autoscaling_groups.tf, terraform/environments/nomis/locals_production.tf
Double iops/bandwidth on prod-nomis-db-1-a prior to failover test
Update DNS entries for the backup hostnames
Adjust schedule for client jump server
=> Nomis: DSOS: ha failover test prep and jumpserver schedule change

terraform/environments/nomis/locals_production.tf
18000 not allowed... 16000 is the max
=> DSOS: ha failover prep - increase iops

terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/pipeline.tf
This PR updates the names of the steps in the replay pipeline to make them clearer:
- `Copy Data to Temp-Reload Bucket` was changed to `Copy Curated Data to Temp-Reload Bucket`
- `Truncate Data` was changed to `Empty Structured and Curated Data`
- `Truncate Raw Data` was changed to `Empty Raw Data`
=> DPR2-713: Refactor replay pipeline step names

terraform/environments/digital-prison-reporting/policy.tf
This was needed to be able to cancel an executed statement via the Redshift Data API.
=> DPR2-757 added CancelStatement policy action

terraform/environments/digital-prison-reporting/main.tf
- This is required for glue to access the connection
- If it is not provided then the job will not write to the operational datastore, so other environments will continue to function without an operational datastore available
- The `glue_job_extra_args` local will be inlined once all environments have a data store and so can have this parameter added
=> DPR2-894: Add connection name and data store write feature flag args to glue batch job in the dev environment

terraform/environments/digital-prison-reporting/policy.tf
Fixed the redshift-data:CancelStatement policy action. 
Based on the [documentation](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonredshiftdataapi.html) for the cancel statement action all resources ("*") to which the policy applies must be specified.
=> DPR2-757 fix cancel statement action

terraform/environments/analytical-platform-compute/data.tf, terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/modules/routes/main.tf, terraform/environments/analytical-platform-compute/modules/routes/providers.tf, terraform/environments/analytical-platform-compute/modules/routes/variables.tf, terraform/environments/analytical-platform-compute/routes.tf, terraform/environments/analytical-platform-compute/transit-gateway-vpc-attachments.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/4490
- Creates a module to add transit gateway routes to the existing private route tables
=> 🗺️ APC Transit Gateway routing

terraform/environments/corporate-staff-rostering/locals_production.tf, terraform/environments/nomis/locals_production.tf
Reduce Nomis IOPS.  Seems existing settings were good enough even with the HA DB running on the -a server.
Increase CSR IOPS on request from DBAs.
=> DSOS: iops tweaks for Nomis and CSR

terraform/environments/nomis/locals_production.tf
- add a prod-nomis-client-b instance for testing but default it to zero instances
- leave this in for testing purposes this time
=> put in a nomis-client-b for testing, number of instances is 0 by default

terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_test.tf
Include legacy URLs to prevent alarms when environment in maintenance mode
Also shutdown T2 which is now started on demand
=> nomis: DSOS: fix lsast alarm

terraform/environments/sprinkler/main.tf
This removes the certificate with the domain name test.modernisation-platform.service.justice.gov.uk as this was causing a number of problems for ops eng.
=> Removes the "test" certificate.

terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf, terraform/environments/analytical-platform-compute/kubernetes-secrets.tf, terraform/environments/analytical-platform-compute/random.tf, terraform/environments/analytical-platform-compute/secrets.tf
Adds secrets to be used to create env vars in the AP UI helm chart:
- django secret key
- azure tenant ID and client ID
=> Add django app secret

terraform/modules/baseline/bastion_linux.tf
- use reference which shouldn't smash into static analysis issues in S3 module call from bastion-linux module call
=> update bastion module commit hash

terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/glue.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/variables.tf, terraform/environments/digital-prison-reporting/modules/glue_job/main.tf, terraform/environments/digital-prison-reporting/modules/glue_job/variables.tf
* Updates glue job and domains/ingestion_jobs modules to allow addition of access to extra secrets
* Adds access to the operational datastore secret for the jobs in this repo
=> DPR2-892: Add permission to access operational datastore secret

terraform/environments/electronic-monitoring-data/step_functions_main.tf
Looks like the result paths were overlapping and caused a strange error once a few loops ran. Have been more specific here with the names of result paths
=> EM: Fixing broken step function

terraform/environments/data-platform-apps-and-tools/helm-charts-applications.tf, terraform/environments/data-platform-apps-and-tools/opensearch.tf
- Removes OpenMetadata and supporting OpenSearch
=> 🔥 Retire OpenMetadata and OpenSearch

terraform/environments/electronic-monitoring-data/step_functions_main.tf
Just select output of the lambda function, not both input and output which was causing conflicts.
=> EM: Fix step function, reduce conflict for step function

scripts/terraform-plan-evaluator.sh
Companion to this PR: https://github.com/ministryofjustice/modernisation-platform/pull/7455
Work tracked in: https://github.com/ministryofjustice/analytical-platform/issues/4358
Since the linked PR is asking for some Resource Access Manager read/write permissions, adding resources that can be created with those permissions to the plan evaluator.
=> Adding RAM shares and Lake Formation permissions to evaluator

terraform/environments/electronic-monitoring-data/dms_replication_task_settings.json
Enable detailed debugging on the following components
- VALIDATOR
- VALIDATOR_EXT
- VALIDATOR_SOURCE
- VALIDATOR_TARGET
Please refer to below documentation on enabling detailed debug logging for your DMS task for more information.
[+] https://repost.aws/knowledge-center/dms-debug-logging
When we are done with this we will likely need to revert it back to original settings due to increased memory consumption and it being intended only for debugging purposes
=> update log detail as per CASE 171958993900761

.github/workflows/awsnuke.yml
This PR relates to [this issue](https://github.com/ministryofjustice/modernisation-platform/issues/7395) tracked in the Modernisation Platform repository.
Our AWS Nuke action is using a version from [May 2022](https://github.com/rebuy-de/aws-nuke/releases/tag/v2.19.0). The most recent version available is dated [August 2023](https://github.com/rebuy-de/aws-nuke/releases/tag/v2.25.0).
While our AWS Nuke action does run and delete the majority of unfiltered resources in our sandbox-level accounts, the newer version of this tool offers a broader range of resources, uses a more recent version of `Go`, prevents attempts to remove SSO-created roles & policies, among other improvements.
=> Bump AWS Nuke version to most recent

scripts/nuke-config-template.txt
This PR is part of [this issue](https://github.com/ministryofjustice/modernisation-platform/issues/7395) tracked in the `modernisation-platform` repository.
Our recent runs of the `nuke-rebuild` job have failed due to a missing SSM parameter. This parameter - `data.aws_ssm_parameter.modernisation_platform_account_id` - is created from the `modernisation-platform` repository through our bootstrap process.
While it can be recreated through a run of our scheduled baselines, I think it's appropriate to keep the parameters made by the bootstrap from being removed by the Nuke process.
=> Amend nuke filter

.github/workflows/terraform-static-analysis.yml
As we don't address `checkov` or `trivy` alerts in customer code, we don't need to informed when this job fails.
=> Remove slack notification from SCA failures

terraform/environments/hmpps-domain-services/patch.tf
- Reference latest patch module
=> Reference latest patch module

terraform/environments/nomis-combined-reporting/locals_production.tf
- added 2 extra tomcat servers (5 in total i.e. 4 + admin)
- added extra ETL server, 2 in total
- added extra 3 processing servers, 4 in total
- pd client
- pd cms instances x 2
- lb included but commented out, changed headers & includes web-admin instance < possibly not correct
- added secrets
- added Ec2PDReportingPolicy
- add efs
- add certificates management
=> add instances but not lb

terraform/environments/nomis-combined-reporting/locals_production.tf
- FIX acm_certificates and efs locals block not in baseline_production locals
- add code comments so I know which instances/items to comment out temporarily
- re-ordered items into alphabetical order
=> Ncr/dsos 2892/prod env comments

terraform/environments/corporate-staff-rostering/locals_ec2_instances.tf
Typo - used windows instead of linux alarm for CSR DB
=> DSOS-2876: fix csr alarm

terraform/environments/digital-prison-reporting/application_variables.json, terraform/environments/digital-prison-reporting/policy.tf
Original details:
https://github.com/ministryofjustice/modernisation-platform-environments/pull/7090
Tracking issue: https://github.com/ministryofjustice/analytical-platform/issues/4358
The share role is missing an `iam:GetRole` permission on the LakeFormationServiceRole. Additionally, Analytical Platform terraform is managed in a hub and spoke model. The initial terraform runs all originate with a role housed in the same account that holds our terraform state. So the role needs to be assumed from that account instead of the target account. As Modernisation Platform is configured similarly, added an option to specify a assume account if different from target.
=> MS037 - Adding Missing Permission & Ability to Assume Role from Central Terraform-running Account

terraform/environments/digital-prison-reporting/policy.tf
Original details:
https://github.com/ministryofjustice/modernisation-platform-environments/pull/7090
Tracking issue: https://github.com/ministryofjustice/analytical-platform/issues/4358
Follow-on to:
https://github.com/ministryofjustice/modernisation-platform-environments/pull/7148
Adding the missing `iam:CreateServiceLinkedRole`
This permission wasn't initially identified as required since I carried out testing on an account where it existed. Apologies!
=> MS037 - Adding Missing Permission for Service Role Creation

terraform/environments/digital-prison-reporting/policy.tf
Original details:
https://github.com/ministryofjustice/modernisation-platform-environments/pull/7090
Tracking issue: https://github.com/ministryofjustice/analytical-platform/issues/4358
Follow-on to:
https://github.com/ministryofjustice/modernisation-platform-environments/pull/7150
Adding the missing `lakeformation:DescribeResource`
This permission wasn't initially identified as required since I carried out testing on an account where it existed. Apologies!
=> MS037 - Adding Missing Permission for Service Role Creation 

terraform/environments/electronic-monitoring-data/lambdas_iam.tf
the dlt documentation suggests at a minimum we will need [these permissions](https://dlthub.com/docs/dlt-ecosystem/destinations/filesystem#:~:text=You%20can%20create%20the%20S3,and%20permissions%20to%20the%20bucket.&text=To%20grant%20permissions%20to%20the,click%20on%20%E2%80%9CAdd%20Permissions%E2%80%9D.) to look at files in s3. So I've added them. They made no difference in dev, but im guessing maybe because the files are slightly bigger it is doing something slightly different to them.
=> Using suggested IAMs from documentation

terraform/environments/nomis-combined-reporting/locals_production.tf
- add tags for machines where the software is installed
- deploy remaining processing and web instances
Will turn all these off once software is installed
=> deploy remaining prod instances to install software

terraform/environments/corporate-staff-rostering/locals.tf, terraform/environments/corporate-staff-rostering/locals_cloudwatch_metric_alarms.tf, terraform/environments/corporate-staff-rostering/locals_ec2_instances.tf, terraform/environments/corporate-staff-rostering/locals_preproduction.tf, terraform/environments/corporate-staff-rostering/locals_production.tf, terraform/environments/hmpps-domain-services/locals.tf, terraform/environments/hmpps-domain-services/locals_ec2_instances.tf, terraform/environments/hmpps-domain-services/locals_lbs.tf, terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/hmpps-domain-services/locals_production.tf, terraform/environments/hmpps-domain-services/locals_test.tf, terraform/environments/hmpps-oem/locals.tf, terraform/environments/hmpps-oem/locals_ec2_instances.tf, terraform/environments/nomis-combined-reporting/locals.tf, terraform/environments/nomis-combined-reporting/locals_cloudwatch_metric_alarms.tf, terraform/environments/nomis-combined-reporting/locals_ec2_autoscaling_groups.tf, terraform/environments/nomis-data-hub/locals.tf, terraform/environments/nomis-data-hub/locals_ec2_instances.tf, terraform/environments/nomis/locals_cloudwatch_metric_alarms.tf, terraform/environments/oasys-national-reporting/locals.tf, terraform/environments/oasys/locals.tf, terraform/environments/oasys/locals_cloudwatch_metric_alarms.tf, terraform/environments/planetfm/locals.tf, terraform/modules/baseline_presets/cloudwatch_dashboards.tf
More alignment:
- enable resource explorer across accounts
- remove unused Azure policy
- ensure EC2 stopped alarm is enabled across accounts where appropriate
- fixed CSR DR DB alarm
- enable LB unhealthy host alarms in hmpps-domain-services
- remove unattached policies
- added missing dashboard to OEM account
- tweaked network LB dashboard
=> DSOS-2890: terraform alignment mop up v2

terraform/environments/hmpps-domain-services/locals_production.tf
Need to allow the existing URL on the LB
=> planetfm: fix for cafmtx RDWeb

terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/glue.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/variables.tf
This PR modifies the reload pipeline so it does not delete records from the archive but instead computes the diff between the reload dataset and the archive and then copies (moves) the generated diffs to their respective archive locations.
In summary, the reload process does:
1. Stops the ingestion
2. Ensures all pending files have been processed and archived
3. Make the full-load to the raw zone
4. Computes the diffs between the raw data and the archive
5. Moves the diffs to the archive
6. Start the ongoing replication pipeline
The actual steps of the reload pipeline are:
1. Deactivate Archive Trigger
7. Stop Archive Job
8. Stop DMS Replication Task
9. Check All Pending Files Have Been Processed
10. Stop Glue Streaming Job
11. Archive Remaining Raw Files
12. Update Hive Tables
13. …
=> DPR2-714: Preserve archive data during reload

terraform/environments/digital-prison-reporting/transfer_component.tf
* This allows for the prisoner_prisoner materialised view to be created which takes 2 or 3 minutes
=> DPR2-899: Increase timeout for migrations transfer component lambda

terraform/environments/digital-prison-reporting/operational_datastore.tf
- This is necessary for the migrations to be able to enable the pg_cron extension
- It requires a restart for the setting to take effect before the migration enabling pg_cron can be run
=> DPR2-899: Add parameter group entry to set pg_cron database to the operational datastore database

terraform/environments/oasys/locals_lbs.tf
- Decreasing the idle timeout of the load balancer.
- AWS default is 60 so 240 may still be quite high but can drop it again providing there are no issues.
https://dsdmoj.atlassian.net/browse/DSOS-2696
=> Optimise load balancer timeout

terraform/environments/nomis/locals_lbs.tf
- Decreasing the idle timeout of the load balancer.
- AWS default is 60 so 240 may still be quite high but can drop it again providing there are no issues.
- https://dsdmoj.atlassian.net/browse/DSOS-2696
=> Nomis - load balancer optimisation

terraform/environments/analytical-platform-compute/vpc-endpoints.tf
- Removes S3 Gateway VPC endpoint as Airflow workloads on APC cannot perform cross region replication actions. Due to split regionality of Analytical Platform.
=> 🔥 Remove S3 VPC endpoint

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/create-a-derived-table/values.yml.tftpl
- Migrates `moj-analytical-services/create-a-derived-table` to ephemeral autoscaled compute capability
=> ✨ Migrate MoJAS CaDeT to APC's KEDA + Karpenter compute

terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/Chart.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-general-on-demand.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-general-spot.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-gpu-on-demand.yaml
- Sets `spec.disruption.consolidationPolicy` to `WhenEmpty` as per https://karpenter.sh/preview/concepts/nodepools/
> If using `WhenEmpty`, Karpenter will only consider nodes for consolidation that contain no workload pods
It was noticed that if KEDA scheduled many GitHub Actions runners at once on a **large** node, once _some_ were complete, it would consolidate **even** if jobs were still running, as by design it would evict pods, but these are jobs with their restart policy set to never.
This pull request changes the `consolidationPolicy` from `WhenUnderutilized` to `WhenEmpty`
=> 🧹 Set `spec.disruption.consolidationPolicy` to `WhenEmpty`

terraform/environments/analytical-platform-compute/secrets.tf
- Creates a new secret `actions-runners/airflow-create-a-pipeline`
=> 🤐 Create secret for airflow-create-a-pipeline

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
This PR relates to the newly released versions of the images used in the Analytical Platform Ingestion service: 
- https://github.com/ministryofjustice/analytical-platform-ingestion-transfer/releases/tag/0.0.12
- https://github.com/ministryofjustice/analytical-platform-ingestion-notify/releases/tag/0.0.13
- https://github.com/ministryofjustice/analytical-platform-ingestion-scan/releases/tag/0.0.7
=> :wrench: Update Image Release Versions

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/airflow-create-a-pipeline/values.yml.tftpl
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/4785
- Adds a new release to enabled self-hosted capability for airflow-create-a-pipeline
=> ✨ airflow-create-a-pipeline self-hosted  release

terraform/environments/nomis/locals_cloudwatch_metric_alarms.tf, terraform/environments/nomis/locals_test.tf
- these instances are being turned on/off overnight so disabling the 'this isn't running' alarm till we can implement a better approach
=> turn off alarm which triggers overnite for xtag t1 and t2

terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/Chart.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-gpu-spot.yaml
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/4757
- Adds `p3.8xlarge`
- Adds `gpu-spot`
=> 🪵 Add GPU Spot NodePool to APC

terraform/environments/delius-core/locals_development.tf, terraform/environments/delius-core/locals_preproduction.tf, terraform/environments/delius-core/locals_stage.tf, terraform/environments/delius-core/locals_test.tf, terraform/environments/delius-core/modules/components/dms/dms_db_endpoints.tf, terraform/environments/delius-core/modules/components/dms/instance.tf
Disable auto_minor_version_upgrade for DMS instances as this does not work well when specifying an engine version, since workflows will continually attempt to downgrade auto-upgraded instances.
=> Dba 699 no auto minor version upgrade

terraform/environments/nomis-data-hub/locals_ec2_instances.tf
- disable alarm as this always triggers overnight
- needs re-instating when there's a 'alarm within timeframe' solution
=> stop ndh alarms firing overnight when instance stopped

terraform/environments/ccms-ebs-upgrade/ec2-oracle_ebs_apps-alb.tf, terraform/environments/ccms-ebs-upgrade/ec2-oracle_webgate-alb.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_ebs_apps-alb.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_webgate-alb.tf, terraform/environments/laa-oem/oem_ec2_app_lb.tf, terraform/environments/laa-oem/oem_ec2_app_lb_internal.tf
CC-2605: ssl_policy ELBSecurityPolicy-2016-08 -> ELBSecurityPolicy-TLS13-1-2-2021-06
=> CC-2605: ssl_policy ELBSecurityPolicy-2016-08 -> ELBSecurityPolicy-TLS13-1-2-2021-06

terraform/environments/delius-iaps/ad.tf, terraform/environments/delius-iaps/rds.tf, terraform/environments/delius-iaps/secrets.tf
Removes version from terraform management so that the data refresh process doesn't try to recreate it
=> :fire: Remove AD admin secret version

terraform/environments/delius-nextcloud/modules/components/nextcloud/locals.tf, terraform/modules/ip_addresses/moj.tf
Add new globalprotect prisma public IPs for allow listing
=> DSOS-2915: add new globalprotect prisma IPs

terraform/environments/planetfm/locals_production.tf
Temporarily drop web-37 from LB to see if this fixes sign-in issue
=> planetfm: DSOS-2918: drop web-37 from lb

terraform/environments/planetfm/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
Add HTTP re-direct from the old AZ URL to new service URL to ensure cookies and any cached login details are reset when migration to AWS.
Note that production PlanetFM web servers are still in Azure, only a handful of people using AWS.
=> planetfm: DSOS-2918: add HTTP redirect for old azure URL to new AWS URL

terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf
This PR modifies the ingestion pipeline so it can be used to re-ingest an already running data pipeline.
It also makes a minor modification to the reload pipeline so that the raw-zone data is deleted before restarting the DMS load thus ensuring that any left over data does not corrupt the archive.
=> DPR2-1053: Stop pipeline before ingestion

terraform/environments/planetfm/locals_production.tf
Case raised with AWS as issue seems to be related to Windows-Auth and ALB.
Re-adding 37 back into the web pool
Remove HTTP rule that was used for testing.
=> DSOS-2918: planetfm: revert lb config

terraform/environments/delius-core/locals_development.tf, terraform/environments/delius-core/locals_preproduction.tf, terraform/environments/delius-core/locals_stage.tf, terraform/environments/delius-core/locals_test.tf
dev: r6i.xlarge to r7i.large
test: r6i.xlarge to r7i.xlarge
stage: r6i.xlarge to r7i.2xlarge
preprod: r6i.xlarge to r7i.4xlarge
=> chore: Update instance types for delius-core development, preproduction, stage, and test environments

terraform/environments/nomis/locals_production.tf
Following query in mod platform, some of our DNS entries / documentation is out of date re the production NOMIS_APIRO database. This is now running on prod-nomis-db-1-a.  DNS entries need correcting as a result. Safest to do this in 2 stages just in case.
Confirmed with DBAs the intention is to leave it in this configuration.
=> nomis: update pnomisapiro DNS entry to reflect recent DB changes

terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/s3_bucket/main.tf, terraform/environments/digital-prison-reporting/modules/s3_bucket/variables.tf
These changes modify the S3 bucket lifecycle policy to remove the data also for Athena results not just for Redshift.
The lifecycle policy currently is in place only for Redshift results stored under the reports folder.
Since the Athena queries now run in a workgroup, the workgroup outputs its results to `dpr-working-development/dpr/` .
=> DPR2-1058 add lifecycle to Athena query folder

terraform/environments/corporate-staff-rostering/locals_cloudwatch_metric_alarms.tf, terraform/environments/corporate-staff-rostering/locals_ec2_instances.tf, terraform/environments/corporate-staff-rostering/templates/cloud_watch_windows.json, terraform/environments/oasys-national-reporting/locals_cloudwatch_metric_alarms.tf, terraform/environments/oasys-national-reporting/locals_ec2_instances.tf, terraform/environments/oasys-national-reporting/locals_test.tf, terraform/environments/planetfm/locals_cloudwatch_metric_alarms.tf, terraform/environments/planetfm/locals_ec2_instances.tf, terraform/environments/planetfm/templates/cloud_watch_windows.json
For now, we are only monitoring the CloudWatch and SSM agents.
ONR has received extra alarms for BODS processes (this is supported by PRs #7060, #7116, #7455). However, these metrics will need to be revised in future. This is because the CloudWatch config applies to all instances. Not all instances have BODS processes.
- Add CloudWatch config for procstat for CSR and PlanetFM
- Add metric alarms to watch the procstat metrics
- Additionally apply the alarms to instances
- Set metric alarms to null in ONR ASGs (they don't need alarms)
=> (csr, onr, planetfm): add procstat metric and alarms

terraform/environments/nomis/locals_production.tf
Follow on from last PR. This change updates the standby (-b) DNS entry
Previously, the active database was on the -b server, and the standby on the -a, which was somewhat confusing.
=> nomis: update pnomisapiro DNS entry to reflect recent DB changes 

terraform/environments/analytical-platform-compute/helm-charts-system.tf, terraform/environments/analytical-platform-compute/src/helm/values/karpenter-crd/values.yml.tftpl
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5087
- Install Karpenter's CRD chart
TODO before merging/applying to production:
- https://keda.sh/docs/2.15/concepts/scaling-deployments/#pausing-autoscaling 
- if ec2nodeclasses hangs then `kubectl patch crd/ec2nodeclasses.karpenter.k8s.aws -p '{"metadata":{"finalizers":[]}}' --type=merge`
=> 🪵 Karpenter CRD deployment

terraform/environments/corporate-staff-rostering/locals.tf, terraform/environments/corporate-staff-rostering/locals_cloudwatch_metric_alarms.tf, terraform/environments/corporate-staff-rostering/locals_lbs.tf, terraform/environments/corporate-staff-rostering/locals_preproduction.tf, terraform/environments/corporate-staff-rostering/locals_production.tf
- use new corporate-staff-rostering-production and preproduction sns topics
- allows users to quickly see who/what is failing
- should also make it obvious 'which' LB or other shared resource is having an issue
=> set new alarm sns topics

terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/Chart.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-gpu-on-demand.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-gpu-spot.yaml
- Switches from `p3.2xlarge` to `g5` and `g6` families
=> 🎮 APC GPU pool

terraform/environments/nomis/locals_ec2_autoscaling_groups.tf
On request from DBAs - 8GB min memory requirement
=> nomis: DSO: increase default instance size for web19c project

terraform/environments/nomis/locals.tf, terraform/environments/nomis/locals_cloudwatch_metric_alarms.tf, terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_lbs.tf, terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_production.tf, terraform/environments/nomis/locals_test.tf
- replace dso_pagerduty alarms everything will go to nomis_alarms_non_prod channel apart from alarms raised in prod which will go to nomis_alarms_prod channel in slack
=> use new pagerduty service definitions for alarms

terraform/environments/digital-prison-reporting/cross-account.tf, terraform/environments/digital-prison-reporting/data.tf, terraform/environments/digital-prison-reporting/lake_formation.tf, terraform/environments/digital-prison-reporting/policy.tf
Analytical Platform tracking ticket: https://github.com/ministryofjustice/analytical-platform/issues/4358
This PR adds `lakeformation:GetDataAccess` permission to the Github role because it interacts with resources that are managed via Lake Formation.
Note: All roles that interact with objects whose underlying location is registered with LakeFormation **must** have this policy attached.
=> Lake Formation Data Access role added to Github Actons runner role

terraform/environments/hmpps-domain-services/locals_preproduction.tf
Add additional permissions to instance to check if it can generate a LetsEncrypt cert
=> DSOS-2927: add permissions to hmpps-domain-services to test LetsEncrypt certificate

terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/planetfm/locals_ec2_instances.tf, terraform/environments/planetfm/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
Removing the LetsEncrypt permissions from hmpps-domain-services as that was just for a test
Adding them to PlanetFM web servers instead.
Corrected some other tags while at it.
=> DSOS-2927: permissions for letsencrypt acme v2

terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/glue.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/variables.tf, terraform/environments/digital-prison-reporting/modules/glue_job/main.tf, terraform/environments/digital-prison-reporting/modules/glue_job/variables.tf
This PR makes the maintenance window during which the glue job will be restarted configurable
=> DPR2-709: Set maintenance window to Sun at 2am for CDC jobs

terraform/environments/nomis-data-hub/locals.tf, terraform/environments/nomis-data-hub/locals_development.tf, terraform/environments/nomis-data-hub/locals_preproduction.tf, terraform/environments/nomis-data-hub/locals_production.tf, terraform/environments/nomis-data-hub/locals_test.tf
- update pagerduty settings for nomis-data-hub environments
- no settings required for development env as nothing is deployed in there
=> update pagerduty integration for test, preproduction and production env

terraform/environments/oasys/locals.tf, terraform/environments/oasys/locals_cloudwatch_metric_alarms.tf, terraform/environments/oasys/locals_development.tf, terraform/environments/oasys/locals_lbs.tf, terraform/environments/oasys/locals_preproduction.tf, terraform/environments/oasys/locals_production.tf, terraform/environments/oasys/locals_test.tf
- set up oasys-test, production and preproduction services
- alarms will show services so easier to trace
- remove dba_* sns topics as not used by DBA's anyway
=> use pagerduty integration and remove defaults from development env

scripts/nuke-config-template.txt
As part of Some AWS Nuke workflows fail with error 255
[#7623](https://github.com/ministryofjustice/modernisation-platform/issues/7623)
i have looked at the errors and want to add in an exception for transfer to see if this fixes one of the errors
=> Adding transfer to the exception list

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/airflow-create-a-pipeline/values.yml.tftpl, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/create-a-derived-table/values.yml.tftpl
- Switches all self-hosted runners over to 2.319.1-1
=> 📁 Switch all self-hosted runners over to use cache and spot

terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/airflow-create-a-pipeline/values.yml.tftpl, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/airflow/values.yml.tftpl, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/create-a-derived-table/values.yml.tftpl
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/4995
- Disables caching of self-hosted runners
=> 😞 disable caching on runners

terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/Chart.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-general-on-demand.yaml
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5192
- Sets `karpenter.k8s.aws/instance-generation` to greater than 4
=> 🎹 Tune Karpenter instance generations 

terraform/environments/planetfm/locals_preproduction.tf
Bug fix - you shouldn't have a CNAME as the Apex DNS record. Changing to A record.
=> planetfm: TM-151: change apex DNS test record from CNAME to A

terraform/environments/oasys/locals_preproduction.tf, terraform/environments/oasys/locals_production.tf, terraform/environments/oasys/locals_security_groups.tf, terraform/environments/oasys/locals_test.tf, terraform/modules/ip_addresses/modernisation_platform.tf
- need these to allow monitoring from hmpps-oem accounts to things like public endpoints
- this will allow adding the nat gateway endpoints to the "allow" lists for PUBLIC_lb security groups for each application we're wanting to monitor an external endpoint for
- adding these to oasys to test the idea overall
=> add nat endpoints to ip_addresses module

terraform/environments/oasys/locals_security_groups.tf
- add another group and append only to public_lb
- this should make sure that private_web security group in production doesn't fail due to too many rules
=> add https_external_monitoring rule group so private_web-http rules okay

terraform/environments/planetfm/locals_preproduction.tf
Swap cafmwebx preprod URL from Application LB to Network LB.
Tested manually on JumpServer by hacking around with /etc/hosts. Stakeholders aware.
=> planetfm: TM-152: switch preprod to network LB

terraform/environments/planetfm/locals_production.tf
Add network LB for PlanetFM for both training and prod.  For testing purposes. A subsequent PR will migrate the traffic
=> planetfm: TM-152: add network lbs in prod

terraform/environments/planetfm/locals_production.tf
This has been tested by Glenn - now make it live. Hardly anyone using training right now so has minimal impact.
=> planetfm: TM-152: migrate training env to network LB

terraform/environments/planetfm/locals_production.tf
Switch prod DNS entry from ALB to NLB. Glenn confirmed this URL is not in use by many people so minimal impact.
=> planetfm: TM-152: switch to network lb prod

terraform/environments/hmpps-oem/locals.tf, terraform/environments/planetfm/locals.tf, terraform/environments/planetfm/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
Final tidy up for planetfm NLB migration:
- add network lb widgets to dashboard
- remove ALBs
- add alarms to network lb
Also fixed couple of things in OEM while at it:
- custom widgets in default dashboard
- enable pagerduty integration
=> planetfm: TM-152: remove alb

terraform/environments/corporate-staff-rostering/locals.tf, terraform/environments/corporate-staff-rostering/locals_preproduction.tf, terraform/environments/corporate-staff-rostering/locals_production.tf, terraform/environments/oasys-national-reporting/locals.tf, terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/locals_test.tf, terraform/environments/planetfm/locals.tf, terraform/environments/planetfm/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
- fix planetfm preproduction ref for pagerduty alarms
- move reference to cloudwatch_metric_alarms_default_actions = ["pagerduty"] into locals.tf in csr and other envs
=> fix pagerduty alarm locals

terraform/environments/nomis/locals_preproduction.tf
Preprod database now sitting on -a server, update DNS accordingly (this entry only used for SSH tunnelling)
=> nomis: update preprod DNS entry

terraform/environments/equip/platform_versions.tf, terraform/environments/equip/s3-awslogs.tf, terraform/environments/equip/securitygroup.tf
Addressed some SCA failures that the switch to Trivy has identified.
=> Address `equip` SCA failures

terraform/environments/equip/shield.tf, terraform/modules/shield_advanced/shield.tf
From the [terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_association):
> [resource_arn](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_association#resource_arn) - (Required) The Amazon Resource Name (ARN) of the resource to associate with the web ACL. This must be an ARN of an Application Load Balancer, an Amazon API Gateway stage (REST only, HTTP is unsupported), an Amazon Cognito User Pool, an Amazon AppSync GraphQL API, an Amazon App Runner service, or an Amazon Verified Access instance.
We associate the following resources with AWS Shield Advanced through the [organisation-security account code](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terra …
=> Prevent `eipalloc` ARNs from being applied through `aws_wafv2_web_acl_association` resource

terraform/environments/cdpt-chaps/shield.tf
* removes the standalone DDOS monitoring that was implemented through the previous clickops approach to AWS Shield Advanced.
* implements AWS Shield Advanced through code, removing reliance on clickops and allowing better visibility as to the current configuration.
=> Implement `cdpt-chaps-production` AWS Shield Advanced through code

terraform/environments/cdpt-ifs/shield.tf
* removes the standalone DDOS monitoring that was implemented through the previous clickops approach to AWS Shield Advanced.
* implements AWS Shield Advanced through code, removing reliance on clickops and allowing better visibility as to the current configuration.
=> Implement `cdpt-ifs-production` AWS Shield Advanced through code

terraform/environments/oasys-national-reporting/locals_lbs.tf, terraform/environments/oasys-national-reporting/locals_security_groups.tf, terraform/environments/oasys-national-reporting/locals_test.tf
Add IP allow listed public LB with setup to BODS web interface so we can test access directly from Mac on Global Protect
=> onr: TM-483: add public LB for MacOS testing

terraform/environments/dacp/shield.tf
=> Manage `dacp-production` shield response team access through code

terraform/environments/pra-register/shield.tf
=> Manage `pra-register-production` shield response team access through code

terraform/environments/wardship/shield.tf
=> Manage `wardship-production` shield response team access through code

terraform/environments/ncas/shield.tf
=> Manage `ncas-production` shield response team access through code

terraform/environments/tipstaff/platform_versions.tf, terraform/environments/tipstaff/shield.tf
* Sets the GitHub provider to prevent implicit use of the latest version (due to [this bug](https://github.com/integrations/terraform-provider-github/issues/2357)).
=> Manage `tipstaff-production` shield response team access through code

terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/glue_job/main.tf
The data reconciliation job needs to access statistics from the DMS API and the data in the Raw zone and Raw archive.
- Add dms:DescribeTableStatistics permission to glue job to allow Data Reconciliation Glue job to access DMS table statistics to compare to counts by operation in Raw zone
- Add raw and raw archive s3 paths to reconciliation job
- Add --dpr.dms.replication.task.id to the job description
=> DPR2-1124: Add Change Data Reconciliation functionality to Data Reconciliation Job

terraform/environments/digital-prison-reporting/modules/domains/stop-cdc-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/notifications.tf
This PR
- Disables alerts for stopped glue jobs. This will prevent noise when the CDC pipelines are stopped
- Set the maximum period for which the CDC stop pipeline should wait to ensure all pending files are processed to 120 minutes
=> DPR2-1170: Disable alerts for stopped glue jobs

terraform/environments/analytical-platform-compute/helm-charts-applications.tf
Fixes bug that prevents users from assigning permissions to tables with duplicated names across different databases
=> Bump AP UI to 0.2.4

terraform/environments/oasys-national-reporting/locals_ec2_instances.tf, terraform/environments/oasys-national-reporting/locals_test.tf, terraform/environments/oasys-national-reporting/templates/user-data-onr-bods-pwsh.yaml.tftpl
- set up test bods asg
- we _might_ need to move it directly into an ec2 instance to get "something" to work but I can't remember what it was
- possibly something network/db connectivity related?
- let's just make the defaults for disks etc. generally available in locals_ec2_instances.tf anyway
- will run apply on development env and blow away anything we don't need there anymore
=> add settings for bods asg test instance

terraform/environments/wardship/dns_ssl.tf, terraform/environments/wardship/load_balancer.tf
Add conditional resources to dns_ssl.tf to create different certificate/dns entries based on whether it is production or non-production. Previously, 2 certs were created in production
=> Refactor dns/route53 records so only 1 certificate gets created

terraform/environments/corporate-staff-rostering/locals_preproduction.tf
- remove trainab alarms for loadbalancer in preproduction
=> get rid of csr trainab lb alarms

terraform/environments/planetfm/locals_production.tf
- change params on web-37-a and web-36-b instances to fire if CPU max sits about 75%
- should give us a better chance to see what's going on before it collapses
=> change web-36-b alarm params

terraform/environments/digital-prison-reporting/data.tf, terraform/environments/digital-prison-reporting/glue-connections.tf, terraform/environments/digital-prison-reporting/main.tf
- Add glue connections for each configured dps service
- Add glue connection and perms to access secrets for configured dps services to the reconciliation job
- Update job params
=> DPR2-1127: Update job so that current counts reconciliation works with DPS Activities and Nomis

terraform/environments/observability-platform/environment-configurations.tf
This PR onboards `analytical-platform-production` to Observability Platform, this is being done to aid [this](https://github.com/ministryofjustice/analytical-platform/issues/5242) piece of work in that account.
=> :wrench: Onboard AP Production to Observability Platform

terraform/environments/cdpt-chaps/shield.tf
Tracked as part of ticket [#7975](https://github.com/orgs/ministryofjustice/projects/17/views/4?pane=issue&itemId=80386408) 
- These changes are intended to enhance the security posture by proactively blocking unwanted or malicious traffic.
- No Count Action Triggered Previously: Looking at the CloudWatch metrics, the "count" action did not trigger, which suggests the traffic patterns have not reached the defined threshold, and it is safe to move to blocking action.
- Consistent Protection: Changing both actions to "block" ensures consistency in how traffic is managed, with requests being denied both at the resource level (load balancer) and at the WAF level.
=> Update WAF rule and resource actions from "Count" to "Block" for better protection against DDOS attacks

terraform/environments/oasys-national-reporting/locals_ec2_instances.tf, terraform/environments/oasys-national-reporting/locals_test.tf, terraform/environments/oasys-national-reporting/templates/user-data-onr-bods-pwsh.yaml.tftpl
- add t2-onr-bods-1-b as new main CMS node but not deployed yet
- add t2-onr-bods-2-a node as secondary but not deployed yet
- ./templates/user-data-onr-bods-pwsh.yaml.tftpl file is a pre-requisite for installing BODS 4.2 successfully 
- intializes drives as part of the setup
- changes hostname based on value supplied directly to the template
=> add new instances as EC2 not asg

terraform/environments/analytical-platform-compute/quicksight.tf
https://github.com/ministryofjustice/analytical-platform/issues/5383
We manage quicksight groups manually at the moment, so adding an ignore block so they're not reset on every run.
=> Ignoring QS author and admin groups as those are not managed in code

terraform/environments/planetfm/locals_production.tf
As agreed with Glenn, double size of instance to try and resolve production issue
=> PlanetFM: increase instance size for w-36

terraform/environments/nomis-combined-reporting/locals_preproduction.tf
There's a couple of issues with using standalone EC2 instances instead of ASG.  Need to try this again, zap it first.
=> ncr: TM-534: zap CMS as needs to be rebuilt

terraform/environments/nomis-combined-reporting/locals_ec2_instances.tf, terraform/environments/nomis-combined-reporting/locals_preproduction.tf
Second attempt - no need to bother with DNS records as we aren't renaming hosts. Update instance sizes.
=> ncr: TM-534: rebuild preprod

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
- Relates to https://github.com/ministryofjustice/data-platform-support/issues/864
- Updates Actions Runners to [2.320.0-1](https://github.com/ministryofjustice/analytical-platform-actions-runner/releases/tag/2.320.0-1)
=> :octocat: Actions Runners 2.320.0-1

terraform/environments/cdpt-ifs/shield.tf
Tracked as part of ticket [#7975](https://github.com/orgs/ministryofjustice/projects/17/views/4?pane=issue&itemId=80386408) 
- These changes are intended to enhance the security posture by proactively blocking unwanted or malicious traffic.
- No Count Action Triggered Previously: Looking at the CloudWatch metrics, the "count" action did not trigger, which suggests the traffic patterns have not reached the defined threshold, and it is safe to move to blocking action.
- Consistent Protection: Changing both actions to "block" ensures consistency in how traffic is managed, with requests being denied both at the resource level (load balancer) and at the WAF level.
=> Update WAF rule and resource actions from "Count" to "Block" for better protection against DDOS attacks 

terraform/environments/digital-prison-reporting/maintenance_jobs.tf
This fixes the failures in the domain layer maintenance jobs by passing the `dpr.config.bucket` argument.
=> DPR2-1105: Fix error in domain layer maintenance jobs

terraform/environments/equip/shield.tf
Tracked as part of ticket [#7975](https://github.com/orgs/ministryofjustice/projects/17/views/4?pane=issue&itemId=80386408) 
- These changes are intended to enhance the security posture by proactively blocking unwanted or malicious traffic.
- No Count Action Triggered: Looking at the CloudWatch metrics, the "count" action did not trigger after increasing the rate limit which suggests the traffic patterns have not reached the defined threshold, and it is safe to move to blocking action.
=> Update WAF rule and alb actions from "Count" to "Block" for better protection against DDOS attacks

terraform/environments/nomis-combined-reporting/locals_preproduction.tf
Environment needs to be turned off in a more controlled way, i.e. via a pipeline. Disable the mod platform solution.
=> ncr: TM-598: disable instance scheduling in preprod

terraform/environments/electronic-monitoring-data/platform_versions.tf, terraform/environments/ppud/platform_versions.tf, terraform/environments/sprinkler/platform_versions.tf
Reverts temporary fixes to avoid issues with aws provider 5.71.0 that have now been resolved.
See bug https://github.com/hashicorp/terraform-provider-aws/issues/39676 for further information.
=> Revert temporary fixes due to issues with aws provider 5.71.0

terraform/environments/ppud/shield.tf
Tracked as part of ticket [#7975](https://github.com/orgs/ministryofjustice/projects/17/views/4?pane=issue&itemId=80386408) 
- These changes are intended to enhance the security posture by proactively blocking unwanted or malicious traffic.
- No count action triggered after increasing the threshold: Looking at the CloudWatch metrics, the "count" action did not trigger, which suggests the traffic patterns have not reached the defined threshold, and it is safe to move to blocking action.
=> Changed the actions from count to block for better protection against DDOS attacks

terraform/environments/electronic-monitoring-data/cloudwatch-event-rules.tf, terraform/environments/electronic-monitoring-data/cloudwatch-event-targets.tf, terraform/environments/electronic-monitoring-data/lambdas_iam.tf, terraform/environments/electronic-monitoring-data/lambdas_main.tf, terraform/environments/electronic-monitoring-data/modules/lambdas/main.tf, terraform/environments/electronic-monitoring-data/modules/lambdas/variables.tf, terraform/environments/electronic-monitoring-data/s3.tf
This PR implements
* lambdas for updating the virus definitions and scanning files
* permissions for the lambdas to access the required s3 buckets (see attached picture for architecture
* cloudwatch trigger for updating the definitions daily
* updated the lambda module so `ephemeral_storage` can be changed, default variable value is the terraform default.
=> ELM-2785 add virus scanning

terraform/environments/electronic-monitoring-data/lambdas_iam.tf, terraform/environments/electronic-monitoring-data/lambdas_main.tf
As it says on the tin, forgot to include the actual trigger to the lambda for definition updates to run daily.
=> Add lambda permission for cloudwatch event trigger

terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/locals.tf
https://github.com/ministryofjustice/analytical-platform/issues/5532
Adding a role assumable from Analytical Platform Dev/Prod to allow Control Panel to access and manage QuickSight.
=> Adding Control Panel service role to Ananlytical Platform Compute

terraform/environments/analytical-platform-compute/src/helm/values/aws-for-fluent-bit/values.yml.tftpl
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/5680
- Sets `priorityClassName` to  `system-node-critical`
- Add `operator: Exists` toleration which allows pod to schedule on any node, including those with `NoSchedule` taint
=> 🚢  Fix AWS Fluent Bit log shipping for Karpenter nodes

terraform/environments/analytical-platform-ingestion/security-groups.tf
- Allows egress to VPC from DataSync VPC endpoint
=> 🚑 Allow egress from DataSync VPC endpoint SG

terraform/environments/analytical-platform-compute/cloudwatch-log-groups.tf, terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/eks-pod-identities.tf, terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/helm-charts-system.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/kms-keys.tf, terraform/environments/analytical-platform-compute/locals.tf, terraform/environments/analytical-platform-compute/rds.tf, terraform/environments/analytical-platform-compute/s3-buckets.tf, terraform/environments/analytical-platform-compute/secrets.tf
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/5661
- Switches to m6a for general purpose compute
- Switches to r7i for Airflow's high-memory compute
Do not merge until maintenance window at 1500!
=> 📌 APC Patching 16/10/24

terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/rds/aws-aurora/main.tf, terraform/environments/digital-prison-reporting/modules/rds/aws-aurora/versions.tf, terraform/environments/digital-prison-reporting/modules/rds/postgres/main.tf, terraform/environments/digital-prison-reporting/modules/rds/postgres/versions.tf, terraform/environments/digital-prison-reporting/modules/redshift/main.tf, terraform/environments/digital-prison-reporting/modules/redshift/secrets.tf, terraform/environments/digital-prison-reporting/modules/redshift/variables.tf, terraform/environments/digital-prison-reporting/modules/redshift/versions.tf
Configure non-domain reconciliation job to:
- fail job if reconciliation fails
- not write cloudwatch metrics
This is because this job is generally used to manually check reconciliation where we want the job to fail to indicate failure rather than cloudwatch metrics.
Also includes a bunch of checkov, linting, etc. changes
=> DPR2-1136: Add new reconciliation job parameters

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
Sets up a runner for create-a-derived-table for our test em account to ensure we can work stuff before promoting both to prod, linked to [this issue here](https://github.com/ministryofjustice/analytical-platform/issues/5376)
=> CADT runner for EM

terraform/environments/observability-platform/environment-configurations.tf, terraform/environments/observability-platform/modules/grafana/athena-source/main.tf, terraform/environments/observability-platform/modules/grafana/athena-source/providers.tf, terraform/environments/observability-platform/modules/grafana/athena-source/variables.tf, terraform/environments/observability-platform/modules/grafana/team/main.tf, terraform/environments/observability-platform/modules/grafana/team/variables.tf, terraform/environments/observability-platform/modules/observability-platform/tenant-configuration/main.tf, terraform/environments/observability-platform/modules/observability-platform/tenant-configuration/variables.tf
Raised in relation to [this](https://github.com/ministryofjustice/analytical-platform/issues/5382) piece of work. 
Raised in conjunction with [this PR](https://github.com/ministryofjustice/terraform-aws-observability-platform-tenant/pull/52) in the [terraform-aws-observability-platform-tenant](https://github.com/ministryofjustice/terraform-aws-observability-platform-tenant) repository.
2.5k lines of Terraform Static Analysis is borderline unreadable but from what I can see it's not related to the work here.
=> 👁️  Observability: Add Athena Data Source

terraform/environments/oasys-national-reporting/locals_test.tf, terraform/environments/oasys-national-reporting/templates/user-data-onr-bods-pwsh-drive-init.yaml.tftpl
- use a different user-data script for testing in -test env
- also want to 'apply' this to get rid of all the critical-national-infra tag updates
=> use different user-data script for testing

terraform/environments/nomis/locals_security_groups.tf
Allow RDP access to the JumpServer from our standard RD gateways
=> nomis: allow RDP access from gateways

terraform/environments/analytical-platform-compute/locals.tf
Fixing the trust policy for the Control Panel service role to allow it to be assumed from within Analytical Platform Data Production account.
=> Fixing trust policy to point to the correct account

terraform/environments/observability-platform/modules/grafana/athena-source/main.tf
Looked at `https://<url>/api/datasources/` and compared to existing data sources.
=> :wrench: Correct data source type

terraform/environments/analytical-platform-compute/secrets.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5784
- Adds a secret for the GitHub App credentials
=> 🤫 Add secret for APC Self-Hosted Runners GitHub App

.devcontainer/devcontainer-lock.json, terraform/environments/analytical-platform-compute/kms-keys.tf, terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5784
- Adds a new ExternalSecret `actions-runner-github-app`
- Updates `ghcr.io/ministryofjustice/devcontainer-feature/terraform` to `1.2.0`
- Runs a `terraform fmt` on APC
=> 🔒 Add External Secret for GitHub App

terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf
- Adds the commented secret back in
It will not plan unless the Secrets Manager secret exists
=> 🔒 Add APC GitHub Self-Hosted Runner ESO

.github/workflows/terraform-static-analysis.yml
We've all seen / been impacted by the below `TOOMANYREQUEST` error causing our TSCA workflow to fail, well thanks to @jacobwoffenden we now have the option to download the trivy database from ECR 🥳 
available in version https://github.com/ministryofjustice/github-actions/releases/tag/v18.3.0 and upwards.
```
ERROR	[vulndb] Failed to download artifact	repo="ghcr.io/aquasecurity/trivy-db:2" err="oci download error: failed to fetch the layer: GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:cae74bde88d988a66b3a4fb824b17b48f38c92258dfecbb748975694233641be: TOOMANYREQUESTS: retry-after: 205.218µs, allowed: 44000/minute"
2024-10-23T15:32:51Z	FATAL	Fatal error	init error: DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to …
```
=> Enable use_trivy_ecr_database - TOOMANYREQUESTS 🔥

terraform/environments/ppud/alb_external.tf, terraform/environments/ppud/alb_internal.tf, terraform/environments/ppud/kms.tf, terraform/environments/ppud/s3.tf
Trivy scan exclusions added for logging on S3 buckets, KMS permissions, WAF on ALBs. Additional logging enabled for Dev & UAT ALB.
=> Update 251024 2

terraform/environments/analytical-platform-compute/s3-buckets.tf
- contributes to [this ticket](https://github.com/ministryofjustice/analytical-platform/issues/5599)
- deletes the mojap-compute-derived-tables-replication bucket region in `eu-west-2`, to be created in `eu-west-1` in separate PR
Signed off by: Anthony Fitzroy <anthony.fitzroy@justice.gov.uk>
=> delete bucket - mojap-compute-derived-tables-replication

terraform/environments/analytical-platform-ingestion/kms-keys.tf, terraform/environments/analytical-platform-ingestion/secrets.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5175
- Adds a new KMS key and Secrets Manager secret for storing our DOM1 credential to be consumed by Terraform when configuring DataSync location/task
=> 🪟 Add KMS key and secret for DOM1 credentials

.devcontainer/devcontainer-lock.json
> [!NOTE]
> Code formatting makes changes to `.devcontainer/devcontainer-lock.json` but this file is automatically generated
- Bumps `ghcr.io/ministryofjustice/devcontainer-feature/aws` to `1.0.1`
- Bumps `ghcr.io/ministryofjustice/devcontainer-feature/kubernetes` to `1.0.2`
=> 🎡 Bump Dev Container features

terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/lakeformation-data-lake-settings.tf, terraform/environments/analytical-platform-compute/lakeformation-registrations.tf
https://github.com/ministryofjustice/analytical-platform/issues/5600
This registers the bucket location in LakeFormation so we can begin adding data location permissions from within the Data Engineering Database Access Repository.
Additionally, this creates a service role for the GithubActions service role in Data Engineering Database Access to assume to carry out permissions changes.
=> Registering CaDeT Bucket + Adding service role to LF Admins

terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/s3-buckets.tf
relates to ministryofjustice/analytical-platform#5599
- adds ap-data-prod replication role permissions on replication destination bucket
- obfuscates account number
=> feat: AP-5599 add ap-data-prod replication role permissions on replication destination bucket

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/5666
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/5776
- Adds a new Actions Runner deployment for CaDeT using our general-on-demand Karpeneter fleet
- Parameterises all account numbers
=> ✨ Add non-spot runners for CaDeT

terraform/modules/fargate_graceful_retirement/eventbridge.tf
This pull request includes a change to the `terraform/modules/fargate_graceful_retirement/eventbridge.tf` file to enhance the IAM policy document for handling health events. The most important change is the addition of a new statement to allow starting executions of a specific state machine.
Enhancements to IAM policy document:
* [`terraform/modules/fargate_graceful_retirement/eventbridge.tf`](diffhunk://#diff-af31f80a5e202ea1dcbb3f244e11fdee796abe47fc5cdf0202a4d09f39bb0da4R77-R85): Added a new statement to the `aws_iam_policy_document` to allow the action `states:StartExecution` on the specified state machine resource.
=> Add `states:StartExecution` to eventbridge role

terraform/environments/analytical-platform-ingestion/cloudwatch-log-groups.tf, terraform/environments/analytical-platform-ingestion/ec2-instances.tf, terraform/environments/analytical-platform-ingestion/environment-configuration.tf, terraform/environments/analytical-platform-ingestion/route53-resolver-query-logging.tf, terraform/environments/analytical-platform-ingestion/security-group-rules.tf, terraform/environments/analytical-platform-ingestion/security-groups.tf, terraform/environments/analytical-platform-ingestion/vpc-endpoints.tf, terraform/environments/analytical-platform-ingestion/vpc.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5175
- Creates debug resources (EC2, SG VPC endpoints and NGW), will be removed later
- Creates resources for Route53 resolver logging
- Sends all internal traffic that isn't local down the transit gateway
- Fixes a references in `resource.`connected_vpc_endpoints_allow_all_vpc`
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/5902
=> 🧪 Debugging MoJO

terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/secrets.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5962
- Adds a secret for the newly created GitHub App
=> 🤐 Add secret for APC GitHub App

terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/maintenance-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/maintenance-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/variables.tf
This PR passes the retry arguments to the ingestion, reload, replay and maintenance pipelines so they can be used to retry S3 failures while listing files.
=> DPR2-1447: Add S3 retry configs to pipelines

terraform/modules/baseline/variables.tf
Fixes issue in #8629. This caused [the hmpps-domain-services workflow to fail](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/11782749900/job/32818469556#step:11:511).
=> fix missing defaults in baseline module

terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5962
- Adds a new ExternalSecret that consumes the secret from https://github.com/ministryofjustice/modernisation-platform-environments/pull/8639
=> 🔐 Add external secret for GitHub App

terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf, terraform/environments/analytical-platform-compute/kubernetes-secrets.tf
- Adds the missing `decodingStrategy` to `private_key` so it renders as expected
=> 🤔 Add decoding strategy for fetching private key from Secrets Manager

terraform/modules/baseline/schedule_alarms_lambda.tf
This previously didn't work as intended. I've tested this new method with a local plan and it's now working as expected.
=> check array length instead of comparing `[]`

terraform/environments/analytical-platform-ingestion/environment-configuration.tf, terraform/environments/analytical-platform-ingestion/iam-policies.tf, terraform/environments/analytical-platform-ingestion/iam-roles.tf, terraform/environments/analytical-platform-ingestion/s3.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5175
- Adds S3 replication (test) to mojap-land mojap-land-dev
=> 🪣 DataSync S3 replication

terraform/environments/analytical-platform-ingestion/environment-configuration.tf, terraform/environments/analytical-platform-ingestion/kms-keys.tf, terraform/environments/analytical-platform-ingestion/s3.tf
Issue: https://github.com/ministryofjustice/analytical-platform-ithc-2024/issues/26
=> Adding external SFTP users

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
@matt-heery @pricemg Does this look more correct?
See our S3 buckets:
Before: s3://emds-prod-json-directory-structure-20240918073115968100000008/g4s/atrium_unstructured/
After: s3://emds-prod-json-directory-structure-20240918073115968100000008/load/g4s_atrium_unstructured/structure/
=> fix the file path to the parquet data for Atrium unstructured

terraform/environments/electronic-monitoring-data/modules/landing_bucket/main.tf, terraform/environments/electronic-monitoring-data/modules/landing_bucket/variables.tf, terraform/environments/electronic-monitoring-data/s3.tf
Allow optional specifying of cross account role to landing bucket permissions and code in access for Allied to send test and preprod feeds.
=> ELM-2758 Configure MDSS feed landing zone permissions

terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
Tweak defaults for endpoint alarm as it is too noisy at moment.
=> oem: tweak endpoint alarm thresholds

terraform/environments/analytical-platform-ingestion/ext-user-2024.tf
Closes https://github.com/ministryofjustice/analytical-platform-ithc-2024/issues/26
Updated the role in the bucket policy for the test bucket.
=> Bucket policy now points to actual security role

terraform/environments/electronic-monitoring-data/bastion_linux.tf
This is for [ELM-3049](https://dsdmoj.atlassian.net/browse/ELM-3049) in order to have enough memory to store the largest zip and an uncompressed zip for it at the same time.
Also need to be able to put back a rebuilt zip file.
[ELM-3049]: https://dsdmoj.atlassian.net/browse/ELM-3049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> provisioned temporary higher memory and permissions

terraform/environments/digital-prison-reporting/application_variables.json
* Add dps-case-notes to the list of dps_domains
* This will create a secret manager secret and a glue connection for dps-case-notes
* Note that the secret will contain placeholder values and so the glue connection will start off with placeholder connection details
* The pipeline will need reapplying once the secret has been populated with the genuine details
=> DPR2-1435: Add DPS Case Notes service secrets and glue connections.

terraform/environments/hmpps-oem/locals.tf, terraform/environments/nomis/locals.tf, terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_production.tf, terraform/environments/nomis/locals_test.tf, terraform/modules/baseline_presets/cloudwatch_dashboards.tf, terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
Add scheduled SSM command run monitoring - alarm and dashboard widgets. Alarm just added to nomis-test for now to see if OK.
=> TM-679: ssm command widgets

.gitattributes
Tracked upstream by [#8393](https://github.com/ministryofjustice/modernisation-platform/issues/8393) in the Modernisation Platform repository.
Implements [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage) for zip archives in this repository.
=> Add zip files to LFS through `.gitattributes`

.gitattributes
Reverts ministryofjustice/modernisation-platform-environments#8706
This caused us some outside issues such as here: https://github.com/ministryofjustice/modernisation-platform/actions/runs/11912296203/job/33195577979?pr=8529#step:9:112
This PR is more of a stopgap before implementing a better approach to storing binaries in Git so we'll revert this for now.
=> Revert "Add zip files to LFS through `.gitattributes`"

terraform/environments/analytical-platform-compute/environment-configuration.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/4490
- Sends all 10.0.0.0/8 traffic to MoJO TGW that isn't destined for VPC
=> 🚚 Update APC Transit Gateway routing

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
Change the EKS role ARN to reference the production role for the actions runner configuration.
=> Update EKS role ARN to production role

terraform/environments/oasys/locals_security_groups.tf
Previous PR failed due to breaching maximum number of rules in a single SG.
Remove some old rules to make space:
- studio hosting, this is about to be decommissioned
- J5, checked the flow logs and there is no traffic from these IPs
=> oasys: TM-749: remove unused IPs in oasys whitelist

terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf
This PR contributes to ministryofjustice/analytical-platform#6133.
This PR adds a role assumable by [the CaDeT GitHub runner role ](https://github.com/ministryofjustice/analytical-platform/blob/main/terraform/aws/analytical-platform-data-production/github-actions-roles/mojas-create-a-derived-table.tf#L107). This assumable role is used by [this workflow](https://github.com/moj-analytical-services/create-a-derived-table/pull/2465/files) to add tables to the glue catalog copied from `analytical-platform-data-production` `eu-west-1`, and then run `MSCK REPAIR TABLES` on hive tables to ensure the partitions are up to date.
=> feat: AP-6133 add cadet assumable role for apdp->apc-prod metadata copy

terraform/environments/analytical-platform-compute/kms-keys.tf, terraform/environments/analytical-platform-compute/s3-buckets.tf
feat: add athena query buckets (london) for environments, kms encrypted with bucket keys
=> feat: add athena query buckets (london) for compute environments

terraform/environments/nomis/locals.tf
Removing this monitoring - going to add via baseline across all accounts
=> TM-720: remove ssm command monitoring from nomis

terraform/environments/hmpps-oem/locals.tf, terraform/environments/hmpps-oem/main.tf, terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf, terraform/modules/baseline_presets/outputs.tf, terraform/modules/baseline_presets/sns_topics.tf, terraform/modules/baseline_presets/variables.tf
Enable ssm-command monitoring in hmpps-oem account with alarms going into the dso_alerts_pipeline channel
=> TM-720: add ssm endpoint monitoring to hmpp-oem

terraform/environments/observability-platform/environment-configurations.tf
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/5669
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/5735
- Adds `cloudwatch_custom_namespaces` to Digital Prison Reporting accounts
=> 📈 Add CloudWatch custom metric namespaces for Digital Prison Reporting accounts

terraform/environments/oasys-national-reporting/locals_test.tf
- deploy t2-onr-bods-1
- change asg code for second bods instance for testing
Since t2-onr-bods-1 is needed I'm actually going to merge this
Need a subsequent PR to put the LB back in at some point
=> deploy t2-onr-bods-1 and enable asg for testing adding 2nd bods machine

terraform/environments/hmpps-oem/locals.tf, terraform/environments/hmpps-oem/main.tf, terraform/modules/baseline/cloudwatch.tf, terraform/modules/baseline/ssm.tf
Add endpoint monitoring widgets to default OEM dashboard
Add separate dashboard for endpoints and pipelines
Fixed hmpps-oem dashboard so it just shows oem EC2 metrics
Fixed SSM dependency
=> TM-720: add endpoint dashboard

terraform/environments/corporate-staff-rostering/locals.tf, terraform/environments/corporate-staff-rostering/main.tf, terraform/environments/hmpps-domain-services/locals.tf, terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/hmpps-domain-services/main.tf, terraform/environments/hmpps-oem/locals.tf, terraform/environments/hmpps-oem/locals_cloudwatch_metric_alarms.tf, terraform/environments/hmpps-oem/main.tf, terraform/environments/nomis-combined-reporting/locals.tf, terraform/environments/nomis-combined-reporting/main.tf, terraform/environments/nomis-data-hub/locals.tf, terraform/environments/nomis-data-hub/main.tf, terraform/environments/nomis/locals.tf, terraform/environments/nomis/main.tf, terraform/environments/oasys-national-reporting/locals.tf, terraform/environments/oasys-national-reporting/main.tf, terraform/environments/oasys/locals.tf, terraform/environments/oasys/main.tf, terraform/environments/planetfm/locals.tf, terraform/environments/planetfm/main.tf, terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf, terraform/modules/baseline_presets/variables.tf
Miscellaneous monitoring changes to be applied across all DSO accounts:
- Enable alerting for failed scheduled SSM commands - to do in dso_alerts_pipeline channel as suspect will be a bit noisy initially.
- Also aligned main.tf everywhere including Keir's schedule_alarms_lambda stuff, plus a URL fix for that also.
- Removed HPA preprod alert as it's been shutdown
=> TM-720: enable scheduled ssm command monitoring

terraform/environments/corporate-staff-rostering/locals_preproduction.tf, terraform/environments/hmpps-oem/locals_cloudwatch_metric_alarms.tf
More tidy up:
- remove CSR preprod LB alerts as endpoint alarms cover this
- group alarms by services and use AWS URLs wherever possible
=> TM-720: endpoint monitoring improvements

terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/modules/baseline/outputs.tf, terraform/modules/baseline/schedule_alarms_lambda.tf, terraform/modules/baseline/variables.tf
Fix + tidy up of schedule alarms
- start/end time were wrong way round
- add module output to baseline outputs (plus ssm stuff that was missing as well)
- hardcode function name so it is consistent. There is only one instance of module so may as well hardcode the name.
=> TM-720: fix schedule alarms

terraform/environments/observability-platform/environment-configurations.tf, terraform/environments/observability-platform/modules/grafana/amazon-prometheus-query-source/main.tf, terraform/environments/observability-platform/modules/grafana/amazon-prometheus-query-source/variables.tf, terraform/environments/observability-platform/modules/observability-platform/tenant-configuration/main.tf, terraform/environments/observability-platform/modules/observability-platform/tenant-configuration/variables.tf
- Allows tenants to set a region for their AMP workspace with `amazon_prometheus_workspace_region` - This is for Analytical Platform as their infrastructure runs in `eu-west-1`
=> 🌐 Allow tenants to set AMP region

terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/dms_s3_v2/main.tf, terraform/environments/digital-prison-reporting/modules/s3_bucket/main.tf, terraform/environments/digital-prison-reporting/modules/s3_bucket/variables.tf, terraform/environments/digital-prison-reporting/modules/s3_bucket/versions.tf
The DMS Postgres source heartbeat frequency is supposed to default to 5 minutes according to the AWS docs but it seems that it actually defaults to zero and runs in a tight loop (at least when created using the AWS terraform provider's module).
Also the settings do not update correctly via terraform when you update postgres settings. For example, changing the heartbeat frequency shows up in the terraform plan but does not apply. This means that you have to either delete and recreate the terraform resources or manually update the settings.
See https://github.com/hashicorp/terraform-provider-aws/issues/35834
=> DPR2-1435: Default Postgres DMS source heartbeat frequency to 5 minutes.

terraform/environments/digital-prison-reporting/modules/dms_s3_v2/main.tf, terraform/environments/digital-prison-reporting/modules/dms_s3_v2/variables.tf
This avoids the terraform plan being polluted with changes to postgres settings for oracle sources that need reapplying on every terraform run.
=> DPR2-1435: Make postgres_settings configuration block conditional on the engine type being postgres

terraform/environments/analytical-platform-compute/iam-policies.tf
This PR is tracked as part of ministryofjustice/analytical-platform#6133
(as title) add athena bucket access for custom query bucket for metadata copy policy
=> feat: AP-6133 add athena bucket access for custom query bucket for metadata copy policy

terraform/environments/nomis/locals_test.tf, terraform/environments/oasys/locals_test.tf, terraform/modules/baseline_presets/iam_roles.tf, terraform/modules/baseline_presets/variables.tf
Delete old observability platform code since Cloudwatch/Pagerduty is sufficient for us.
=> Nomis: clean up old observability platform code

terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf
This PR is tracked as part of ministryofjustice/analytical-platform#6133.
This PR makes the role name for the metadata-copy role clearer and more precise. It also adds [`lakeformation:*LFTag*` permissions required to create and update LFTags](https://docs.aws.amazon.com/lake-formation/latest/dg/permissions-reference.html#persona-engineer) (assuming the tag was added by this role).
>As tag creator , the principal gets Alter permission on this LF-Tag and can update or remove any tag value from this LF-Tag. The LF-Tag creator principal can also grant Alter permission to another principal to update and remove tag values on this LF-Tag.
[docs](https://docs.aws.amazon.com/lake-formation/latest/dg/TBAC-creating-tags.html)
It needs to be coordinated with the merging of …
=> style: AP-6133 clearer role and policy names for APDP metadata-copy-to-compute assumable role & add `lakeformation:*LFTag*` perms

terraform/environments/ppud/shield.tf
Import block is only required once - removing as this seems to be causing some issues in terraform 1.10 and is not longer required.
=> Removed import block for ppud

terraform/environments/analytical-platform-compute/lakeformation-data-lake-settings.tf
This PR contributes to ministryofjustice/analytical-platform#6133.
The metadata copy assumable role requires sufficient LF permissions (`Alter`) on CaDeT LF tables it touches in order to update them. This permission is automatically granted to a role that creates a resource (table, database), or a Lake Formation Admin. After swapping the role name for a more accurate name, the new role no longer has permission to update tables from previous runs of the metadata copy workflow. Adding the new role as a Lake Formation in `eu-west-2` will resolve this issue without needing to add the permissions to the role one at a time.
=> feat: AP-6133 add cadet metadata copy assumable role as lf admin in eu-west-2

terraform/environments/analytical-platform-compute/src/helm/values/amazon-prometheus-proxy/values.yml.tftpl
- Enables kube-state-metrics to include labels
=> 🏷️ Enable pod labelling in kube-state-metrics

terraform/environments/analytical-platform-compute/lakeformation-permissions.tf
This PR relates to ministryofjustice/analytical-platform#6133
add LFTag `source` into terraform in APC production account
Signed off by tom.webber@justice.gov.uk
=> feat: AP-6133 import `source` LFtag into code into prod account

.github/workflows/awsnuke.yml, .github/workflows/nuke-redeploy.yml
Failure notifications not working on aws nuke jobs e.g. https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/12105218464/job/33749551976#step:9:29
This has already been fixed for MP workflows here: https://github.com/ministryofjustice/modernisation-platform/pull/8612
Fix notification failure steps by adding `webhook-type` input for compatibility with `slackapi/slack-github-action` v2.0.0
=> Fix notification failure steps by adding `webhook-type` input for compatibility with `slackapi/slack-github-action` v2.0.0

terraform/environments/digital-prison-reporting/glue-connections.tf, terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/dms/main.tf, terraform/environments/digital-prison-reporting/modules/dms/variables.tf, terraform/environments/digital-prison-reporting/modules/dms/versions.tf, terraform/environments/digital-prison-reporting/modules/dms_dps/main.tf, terraform/environments/digital-prison-reporting/modules/dms_dps/variables.tf, terraform/environments/digital-prison-reporting/modules/dms_dps/versions.tf, terraform/environments/digital-prison-reporting/modules/dms_s3_v2/main.tf, terraform/environments/digital-prison-reporting/modules/rds/postgres/sg.tf, terraform/environments/digital-prison-reporting/sg.tf
Configure DMS to send all inserts, updates and deletes to the Raw zone rather than just inserts and updates by removing the `cdc_inserts_and_updates = true` setting.
The `cdc_inserts_and_updates` setting configures DMS to only propagate inserts and updates to the S3 sink. This means we are missing deletes in the raw zone.
You can see this in the DMS logs:
```2024-11-29T13:57:07 [TARGET_APPLY    ]W:  Updates/Deletes will be ignored because cdcInsertsOnly or cdcInsertsAndUpdates is set by customer  (file_apply.c:1212)```
=> DPR2-1435: Configure DMS to send deletes to the raw zone

terraform/environments/long-term-storage/call-centre-migration.tf, terraform/environments/long-term-storage/data.tf
* Creates an IAM role and policy for the call center connector to use.
* KMS permissions are broad as these are also controlled by the KMS policy
=> Call centre connector IAM role

terraform/environments/digital-prison-reporting/modules/domains/maintenance-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/maintenance-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/stop-cdc-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/stop-cdc-pipeline/variables.tf
This PR:
- Enables reduction of the S3 polling frequency for the step which checks if all data files have been processed
- The change applies to the reload, replay, maintenance and stop-cdc pipelines
=> DPR2-1492: Reduce polling frequency when checking processed files

terraform/environments/oasys-national-reporting/locals_preproduction.tf
- disable api termination for pp-onr-bods-1 so it can't be killed accidentally
=> disable termination for pp-onr-bods-1 as this is now in use

terraform/environments/nomis-combined-reporting/locals_efs.tf, terraform/modules/efs/main.tf
Disable EFS automatic backup, should go into everything vault instead
Opt into backup using same policy as DBs.
=> ncr: TM-738: efs backup fix

terraform/modules/schedule_alarms_lambda/main.tf
- BE QUIET!!
Okay, joking aside I did actually review what checkov was shouting about and there are notes in the skip=ckv_aws_ comments but I can't see that any of these are needed, maybe the concurrency limit one but also 🤷 
Trivy doesn't run in this environment so that particular set of checks fails in here BUT it will pass everywhere else now.
I just want to avoid seeing red crosses as per my un-related PR here https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/12162819398/job/33920666092?pr=8902
=> get checkov to shut up

terraform/environments/equip/shield.tf
Following some investigation detail in [this Slack thread](https://mojdt.slack.com/archives/C01A7QK5VM1/p1733405114654599) we're reducing the threshold for AWS Shield Advanced WAF rules. These may need to be adjusted back upwards, but this should give sufficient headroom for occasional busy periods.
=> Lower Equip AWS Shield threshold

scripts/nuke-config-template.txt
The scheduled AWS Nuke workflow has been [failing](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/12105218464/job/33749552820) with a common issue in the logs related to OpenSearch packages.
e.g.
```
eu-west-2 - OSPackage - pkg-59fc48a9d14d467ac47dcd5269e6446955f885f1 - [CreatedTime: "2024-11-07T10:55:14Z", PackageID: "pkg-59fc48a9d14d467ac47dcd5269e6446955f885f1", PackageName: "titaniam-lockbox"] - failed
eu-west-2 - OSPackage - pkg-ef5a4cd1f0ed1bfb5cce31d3a108c9e24cdb346d - [CreatedTime: "2024-11-11T19:26:05Z", PackageID: "pkg-ef5a4cd1f0ed1bfb5cce31d3a108c9e24cdb346d", PackageName: "rni"] - failed
``` 
I've added more filters to the Nuke config to ignore these packages. As far as I can tell these aren't specific resources that are created by users …
=> Filter OpenSearch Packages causing aws-nuke failures

terraform/environments/oasys-national-reporting/locals_test.tf, terraform/environments/oasys-national-reporting/versions.tf, terraform/modules/baseline/versions.tf
- replace (more expensive) multiple AZ with single_az_1 version
- unfortunately, having used the test environment to test removing the deprecated feature the only way to recover this is to blow away t2-onr-bods-1 and t2-onr-bods-2 and start again 😢 
- also update provider versions to address issues with other module code
=> deploy single az to T2

terraform/environments/equip/shield.tf
In response to [this Slack request](https://mojdt.slack.com/archives/C01A7QK5VM1/p1733735679084179?thread_ts=1733405114.654599&cid=C01A7QK5VM1) the threshold for Equip AWS Shield is being bumped back up to 1000.
=> Bumped equip waf threshold

terraform/environments/electronic-monitoring-data/lambdas_sg.tf
Introduce security group rules to allow S3 traffic for both ingress and egress in the Lambda security group configuration.
=> Add S3 ingress and egress rules to lambda security group

terraform/environments/oas/bastion.tf, terraform/environments/oas/ec2.tf, terraform/environments/oas/files/bastion_linux.json
=> [TM-810] OAS: added bastion

terraform/environments/nomis/locals_test.tf
Alarm not needed for misload in test as it is only used ad-hoc.
Also can remove test weblogic server
=> nomis: remove t1 misload alarm

terraform/environments/oasys-national-reporting/locals_preproduction.tf
- adding permissions to pp-onr-bods-1 to run aws diagnostics tool as to why FSX creation doesn't work
- delete the existing (failed) fsx deployment
=> give instance more permissions and kill failed fsx deployment

terraform/environments/digital-prison-reporting/application_variables.json
- Add dps-incident-reporting to the list of dps_domains
- This will create a secret manager secret and a glue connection for dps-incident-reporting
=> DPR2-1316: Add incident reporting service glue connections and secrets.

.github/workflows/terraform-static-analysis.yml
Updating `ministryofjustice/github-actions` to `v18.6.0`
This version pins the trivy version to `v0.57.1` as the latest version has been causing us some errors.
=> Bump github-actions to `v18.6.0`

terraform/environments/digital-prison-reporting/application_variables.json
- Unfortunately 'dps-incident-reporting' is too long for our platform naming conventions
- 17 characters seems to be the longest allowed domain name otherwise we see errors when creating IAM roles
For example:
```
│ Error: expected length of name to be in the range (1 - 64), got dpr-create-reload-diff-dps-incident-reporting-development-glue-role
│ 
│   with module.ingestion-jobs["dps-incident-reporting"].module.create_reload_diff_job.aws_iam_role.glue-service-role[0],
│   on .terraform/modules/ingestion-jobs/terraform/environments/digital-prison-reporting/modules/glue_job/main.tf line 66, in resource "aws_iam_role" "glue-service-role":
│   66:   name  = "${var.name}-glue-role"
│ 
╵
╷
│ Error: expected length of name to be in the range (1 - 64), got …
```
=> DPR2-1316: Shorten dps-incident-reporting

terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf
Include new S3 bucket paths for pipeline data in the IAM role permissions of the Airflow module.
=> Add additional S3 bucket paths for IAM role permissions in Airflow module

terraform/environments/digital-prison-reporting/modules/dms_s3_v2/main.tf, terraform/environments/digital-prison-reporting/modules/dms_s3_v2/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/dms-endpoints/endpoints.tf, terraform/environments/digital-prison-reporting/modules/domains/dms-endpoints/variables.tf
- We need to be able to turn heartbeat off for read replicas since DMS cannot create, and insert into, the heartbeat table on an RDS Postgres read replica where only read operations are allowed.
=> DPR2-1213: Make postgres DMS source heartbeat configurable

terraform/environments/nomis/locals_production.tf
Update nomis iops / bandwidth:
- flash: make consistent across all DBs. Widgets show 200 still leaves plenty of headroom
- db-1-a data: drop back down to 300 (was increased to 500 following incident but subsequently shown to be not needed)
- db-1-b data: align with db-1-a to make failover easier
- db-2-a data: increase to 300 (widgets show we are hitting 250 at some points)
=> TM-776: nomis: ebs bandwidth tweaks

terraform/environments/nomis-combined-reporting/locals_ec2_instances.tf, terraform/environments/oasys-national-reporting/locals_development.tf, terraform/environments/oasys-national-reporting/locals_ec2_instances.tf
- use correct Windows drive letters for EBS in nomis-combined-reporting EC2 instance BODS default
- change to Bods `server-type` tag in both NCR and ONR EC2 instance BODS default
- modify the bods asg instance in the ONR development environment to test the 'get-config' function works 
- will be used for testing only anyway
=> deploy a test bods instance

terraform/environments/electronic-monitoring-data/athena_main.tf
Update the Athena workgroup configuration to increase the bytes scanned cutoff per query from 1 GB to 1 TB.
=> Increase Athena workgroup bytes scanned cutoff to 1 TB

terraform/environments/ccms-ebs/application_variables.json
CC-3036: Updated 'ebs_backup_snapshot_id'.
=> CC-3036: Updated 'ebs_backup_snapshot_id'.

terraform/environments/corporate-staff-rostering/locals_production.tf
Drop CSR iops back to default - same as DR. We're not getting close to the default 3000, never mind 6000.
=> TM-776: align csr db primary and secondary iops

terraform/environments/electronic-monitoring-data/api_gateway.tf, terraform/environments/electronic-monitoring-data/lambdas_iam.tf, terraform/environments/electronic-monitoring-data/lambdas_main.tf, terraform/environments/electronic-monitoring-data/modules/api_step_function/main.tf, terraform/environments/electronic-monitoring-data/modules/api_step_function/variables.tf
Introduce an IAM role and module configuration for the API Gateway authorizer to enhance security and functionality.
=> Add API Gateway authorizer IAM role and module configuration

terraform/environments/digital-prison-reporting/main.tf
This PR updates the name of the job which switches the data source used by the prisons hive tables
=> DPR2-1629: Update the name of job to switch prisons data source

terraform/environments/nomis-data-hub/locals_production.tf
Remove alarm + dashboard widgets for the mounted Azure filesystem since it has now been removed.
=> ndh: remove filesystem monitoring as it has been removed

terraform/environments/nomis/locals_cloudwatch_metric_alarms.tf
The current threshold of 40% is being regularly breached. Up to 75% but reduce the amount of time it takes for the alarm to trigger. As discussed with DBAs.
=> TM: nomis: tweak thresholds for iowait alarm to avoid false positive alarms

terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf, terraform/environments/nomis-combined-reporting/locals_test.tf, terraform/environments/nomis-combined-reporting/templates/maintenance.html.tftpl
Add maintenance mode LB rule for nomis combined reporting test and preprod
=> TM-844: ncr: add maintenance mode lb option

scripts/generate-dependabot-file.sh
Tracked upstream by [#7503](https://github.com/ministryofjustice/modernisation-platform/issues/7053).
This PR replaces the use of multiple `directory` keys with a single `directories`.
=> Update dependabot script to use `directories:` key

terraform/environments/nomis/locals_cloudwatch_metric_alarms.tf
Temporarily increase the threshold to 90% to avoid flapping alerts while we fix the issue
=> TM-860: nomis: temporarily increase web disk space alarm threshold

.github/workflows/generate-dependabot-file.yml
The script in the workflow is failing because it expects the `$GITHUB_TOKEN` environment variable, but this variable is not defined in the workflow.
=> Fix missing GITHUB_TOKEN environment variable in workflow

terraform/environments/electronic-monitoring-data/analytical_platform_share.tf, terraform/environments/electronic-monitoring-data/modules/lakeformation_database_share/main.tf
Introduce a resource for AWS Glue catalog databases to facilitate granting access to specified databases.
=> Add AWS Glue catalog database resource for database access grants

terraform/environments/electronic-monitoring-data/analytical_platform_share.tf, terraform/environments/electronic-monitoring-data/modules/lakeformation_database_share/main.tf, terraform/environments/electronic-monitoring-data/modules/lakeformation_database_share/variables.tf
Introduce permissions for the DE role in the lakeformation_database_share module, allowing it to access data locations and databases. Update the module to accept a DE role ARN for permission grants.
=> Add DE role permissions to lakeformation_database_share module

terraform/environments/corporate-staff-rostering/locals_cloudwatch_dashboards.tf, terraform/environments/corporate-staff-rostering/locals_production.tf, terraform/environments/nomis/locals_cloudwatch_dashboards.tf, terraform/environments/nomis/locals_production.tf, terraform/environments/oasys/locals_cloudwatch_dashboards.tf, terraform/environments/oasys/locals_production.tf, terraform/modules/baseline_presets/cloudwatch_dashboards.tf, terraform/modules/cloudwatch_dashboard/main.tf, terraform/modules/cloudwatch_dashboard/variables.tf
On request from Glenn, add additional widget showing network bandwidth (in Megabits / second)
- ec2 network in
- ec2 network out
- ebs attachment status
- alb processed data
Updated nlb processed data to align with the above.
Seems to have worked in nomis-test and hmpps-oem-test
=> TM-861: add ec2 throughput to dashboards

terraform/environments/nomis-combined-reporting/locals_preproduction.tf
Allow LB rule priorities to be updated from EC2 to aid with clean shutdown. Also enable maintenance mode page for the admin console.
=> TM-680: ncr: lb permissions for clean start and stop of env

terraform/environments/nomis/locals_cloudwatch_metric_alarms.tf
Disk space issue on web servers has been fixed - reverting the alarm threshold back to what it was
=> TM-860: nomis: revert disk space alarm threshold

terraform/environments/nomis/locals_production.tf
Following incident review, increase the number of prod web servers to 6.
Also update pinned branch to the latest. This has been tested in the -a deployment already.
=> TM-860: nomis: update number of webservers to 6 using latest release

terraform/environments/operations-engineering/audit_log_streaming_github.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/5127
- To re-create the infrastructure that currently exists in the MoJ Digital Services account to migrate workloads to Modernisation Platform Accounts
- Added required infrastructure for GitHub Audit Log Streaming
- Currently doing a like for like migration, optimisations will come later
=> ✨ Add Audit Log Streaming Infrastructure for GitHub

terraform/environments/operations-engineering/audit_log_streaming_github.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/5127
- To give GitHub permissions to stream audit log data to S3 Bucket
- Added GitHub OIDC Provider
- Added a role for GitHub to assume to write to S3 Bucket and Encrypt data using custom KMS Keys
=> ✨ Add Access For GitHub Audit Log Streaming

terraform/environments/analytical-platform-compute/kms-keys.tf, terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
Creates a SageMaker endpoint in the analytical-platform-compute account, with an IAM role that can be assumed from an OpenSearch connector in Cloud Platform.  This is to explore using SageMaker in Analytical Platform / Modernisation Platform to support semantic search for probation data.
Initially using a very basic configuration with a publicly available model and image, to prove the end-to-end process.
Related changes:
* IAM role - https://github.com/ministryofjustice/cloud-platform-environments/pull/28893
* OpenSearch configuration - https://github.com/ministryofjustice/hmpps-probation-integration-services/pull/4541
=> PI-2526 SageMaker resources to support Probation Search

terraform/environments/operations-engineering/audit_log_streaming_github_cloudtrail.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/5127
- To create a role that allows our Dormant Users Python script to query CloudTrail
- Added GitHub Actions OIDC Provider
- Added Role for Dormant Users Python Script to assume to query CloudTrail
=> ✨ Add Role For GitHub Actions to Query CloudTrail

terraform/environments/analytical-platform-compute/iam-policies.tf
was getting a permission error on the namespace so amending the policy
=> remove `/` from fmd quicksight policy resource

terraform/environments/analytical-platform-compute/acm.tf, terraform/environments/analytical-platform-compute/alb.tf, terraform/environments/analytical-platform-compute/data.tf, terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/kms-keys.tf, terraform/environments/analytical-platform-compute/kubernetes-namespaces.tf, terraform/environments/analytical-platform-compute/kubernetes-role-bindings.tf, terraform/environments/analytical-platform-compute/kubernetes-roles.tf, terraform/environments/analytical-platform-compute/mwaa.tf, terraform/environments/analytical-platform-compute/route53-records.tf, terraform/environments/analytical-platform-compute/s3-buckets.tf, terraform/environments/analytical-platform-compute/s3-objects.tf, terraform/environments/analytical-platform-compute/security-groups.tf, terraform/environments/analytical-platform-compute/src/airflow/kube_config, terraform/environments/analytical-platform-compute/src/airflow/requirements.txt, terraform/environments/analytical-platform-compute/versions.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/6542
- Creates the required infrastructure for running AWS MWAA in APC
=> ✈️ APC MWAA

terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/kubernetes-role-bindings.tf, terraform/environments/analytical-platform-compute/kubernetes-roles.tf
- Creates a new role and rolebinding for MWAA namespace base on existing Airflow
- Adds entry to EKS access for Airflow repo role
=> 🛂 Add Kubernetes role and role binding for MWAA service account management

terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf
adds in other allowed domains to the policy and the new IRSAs from prod and preprod to trusted role arns
=> add other trusted roles and allowed domains to fmd quicksight policy

terraform/modules/baseline_presets/backups.tf
Revising backup policies to provide a opt-in vis enabled versions due to AWSEC2-CreateVssSnapshot SSM doc failures making it hard to see genuine SSM doc failures.
=> tm-713: revising-policies

terraform/environments/oasys-national-reporting/templates/cloud_watch_windows.json
In the current config we can't have an ssm doc > 4096 characters
Will ask Mod-Platform about changing this but in the meantime remove some params from procstat to take it to 3975 which makes it deployable
=> if the config is too long we can't deploy it

terraform/environments/oasys-national-reporting/templates/cloud_watch_windows.json, terraform/modules/baseline/ssm.tf, terraform/modules/baseline/variables.tf, terraform/modules/baseline_presets/ssm.tf
I think this is all that's needed to change the ssm parameter store for 'cloudwatch-config-windows' from Standard (4Kb) to 'Advanced' (8Kb)
- set defaults to null so nothing else is impacted
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter#tier-1
=> change param to advanced

terraform/environments/analytical-platform-common/iam-policies.tf
- Adds `DeleteObject` as per https://developer.hashicorp.com/terraform/language/backend/s3#permissions-required as we want to use workspaces
=> 🛂 Add `DeleteObject` permissions

terraform/environments/analytical-platform-common/iam-policies.tf
- Allows `arn:aws:iam::509399598587:role/analytical-platform-github-actions` to assume `arn:aws:iam::593291632749:role/analytical-platform-infrastructure-access`
Reference: https://github.com/ministryofjustice/analytical-platform-airflow/actions/runs/12996713991/job/36246076658?pr=13
=> 🛂 Allow GHA role to assume infrastructure access role

terraform/environments/analytical-platform-common/iam-policies.tf, terraform/environments/analytical-platform-common/kms-keys.tf, terraform/environments/analytical-platform-common/secrets.tf
- Creates a KMS key for common secrets
- Creates a secrets for APC cluster data
- Adds permissions to GHA role
- Accessing KMS
- Accessing Secret
- Accessing EKS
=> 🔒 Add resources for storing cluster data

terraform/environments/observability-platform/data.tf, terraform/environments/observability-platform/managed-grafana.tf
- Operations Engineering will soon be assessing tools and services to visualise FinOps/GreenOps type data sets, giving them admin access to assess how the Observability Platform currently does this for other existing tenants will be useful during this proccess
- Updated the admin assignment to allow for multiple identity groups to be given admin privileges
- Added `operations-engineering` to the list of admins
- NA
=> ✨ Add `operations-engineering` Team as Observability Platform Admins

.github/workflows/reusable_terraform_plan_apply.yml, .github/workflows/reusable_terraform_plan_apply_test.yml
https://mojdt.slack.com/archives/C01A7QK5VM1/p1738246528900189
This change updates the terraform init command to remove the outdated -backend-config=assume_role argument that references the modernisation-account-terraform-state-member-access role. The role is no longer needed, and simplifying the command will ensure it runs correctly.
Changes:
Removed the -backend-config=assume_role argument from the terraform init command.
Replaced the old backend configuration with a simpler terraform init command.
=> fix: update terraform init command to remove outdated assume_role backend config

terraform/environments/observability-platform/iam-policies.tf, terraform/environments/observability-platform/lambda-functions.tf, terraform/environments/observability-platform/managed-grafana.tf, terraform/environments/observability-platform/managed-prometheus.tf, terraform/environments/observability-platform/modules/prometheus/iam-role/main.tf, terraform/environments/observability-platform/secrets.tf
- Relates to https://github.com/ministryofjustice/analytical-platform/issues/6628
- Adds a secret for storing account ID that aren't part of Modernisation Platform
=> 🔒 Add secret for holding non MP account IDs

terraform/environments/electronic-monitoring-data/bash_scripts/import_databases.sh, terraform/environments/electronic-monitoring-data/modules/lakeformation_database_share/main.tf
Introduce a script for importing databases into the Glue catalog and modify lifecycle settings to prevent resource destruction.
=> Add database import script and update Glue catalog lifecycle settings

terraform/environments/oasys-national-reporting/locals_cloudwatch_metric_alarms.tf, terraform/environments/oasys-national-reporting/locals_ec2_instances.tf, terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_production.tf
- created bods_primary and bods_secondary alarm groups
- bods_secondary does not have the CMS alarm as this service doesn't run there
=> enable alarms for pd-onr-bods-1

terraform/environments/analytical-platform-ingestion/data.tf, terraform/environments/analytical-platform-ingestion/kms-keys.tf, terraform/environments/analytical-platform-ingestion/secrets.tf
This PR relates to ministryofjustice/analytical-platform#5175.
This PR adds a secret to hold the paths to exclude as part of the datasync task.
**Questions for the reviewer:**
- why is the [CIDR group changing](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/13134364902/job/36646326486?pr=9550#step:11:687)?
- Is it necessary to add a new kms key for this secret?
=> feat: AP-5175 create datasync 'exclude paths' secret

terraform/environments/analytical-platform-ingestion/datasync-tasks.tf
This PR relates to ministryofjustice/analytical-platform#5175.
This PR uses the secret from #9550 (updated manually) to exclude paths from the datasync task.
=> feat: add exclude filter from exclude paths secret string value

terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf
Introduce environment-specific suffixes for IAM role names in the Airflow module to enhance clarity and organization across different environments.
=> Add environment suffixes for IAM role naming in Airflow module

terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf
Correct the formatting of the IAM role name suffix in the Airflow module to ensure proper concatenation of variables.
=> Fix IAM role name suffix formatting in Airflow module

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
Introduce a Helm release for the actions runner to create a derived table in the pre-production environment. This addition supports the deployment of necessary configurations and resources.
=> Add Helm release for actions runner in pre-production

terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Revise the OIDC provider count logic to include the preproduction environment, ensuring proper handling of IAM roles in both production and preproduction contexts.
=> Update OIDC provider logic for preproduction environment

terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Enhance the suffix logic to differentiate between production, preproduction, test, and development environments in the Terraform configuration.
=> Update suffix logic for environment differentiation in Terraform configuration

.github/workflows/analytical-platform-ingestion.yml, .github/workflows/reusable_terraform_components_strategy.yml, terraform/environments/analytical-platform-ingestion/dms/platform_base_variables.tf
https://github.com/ministryofjustice/analytical-platform/issues/6602
With introduction of components, it now becomes important to differentiate between components that have committed changes in a branch and those that aren't.
This PR introduces code into the strategy workflow that only includes components (and/or root) that have `git diff` from `main`.
The complexity to arises out of the fact that new code can be in either root or component level so it's important to identify which one.
=> Amending strategy workflow to only pass changed app/components

terraform/environments/analytical-platform-ingestion/dms/iam-policies.tf
This is a test to confirm that the inability to replication from `analytical-platform-ingestion` to `analytical-platform-data-production` is due to permissions
=> 🧪 Permissions Test - to be reverted

terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/eks-pod-identities.tf, terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/helm-charts-system.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/locals.tf, terraform/environments/analytical-platform-compute/s3-buckets.tf, terraform/environments/analytical-platform-compute/s3-objects.tf, terraform/environments/analytical-platform-compute/security-groups.tf, terraform/environments/analytical-platform-compute/vpc-endpoints.tf, terraform/environments/analytical-platform-compute/vpc.tf
- completes this ticket: https://github.com/ministryofjustice/analytical-platform/issues/6651
- patches `analytical-platform-compute` and upgrades the EKS cluster to new version
Signed off by: Anthony Fitzroy <anthony.fitzroy@justice.gov.uk>
=> 🔨 Patch APC and upgrade EKS cluster

terraform/environments/analytical-platform-ingestion/lambda-functions.tf
This doesn't appear to impact the working of the function but in the logs, the scan lambda keeps hitting an access denied error due to being unable to read object tags form the source file.
=> Adding get tagging permission to scan lambda

terraform/environments/hmpps-domain-services/sns.tf, terraform/modules/environment/data.tf, terraform/modules/environment/outputs.tf
Testing a subscription to the pre-existing failed backup topic.
=> TM-964: failed-backup-alert-preprod

terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/dms/variables.tf, terraform/environments/digital-prison-reporting/modules/dms_dps/variables.tf, terraform/environments/digital-prison-reporting/modules/dms_s3_v2/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/dms-endpoints/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/dms-instance/variables.tf
* t2 instance type is now migrating to t3
* Additional PR to follow in the domains repo
From AWS:
```Q - What instance type(s) will my Replication instances be auto-upgraded to?
• We will make our best effort to upgrade your Replication instance from C4→C5, M4→R5, R4→R5, and T2→T3 and typically keep its original sizes.
• In cases that we cannot keep the original size, we will first attempt to migrate your Replication instance to another Availability Zone (AZ) in the same region. If this is unsuccessful, we will migrate your Replication instances to one size smaller than its original size.
• The upgraded instance types are priced identically or lower than the older generation instance types. For the most up-to-date prices, please refer to the AWS DMS pricing page [1].
```
=> DPR2-1744: Update EOL DMS instance types and delete unused variables.

terraform/environments/analytical-platform-ingestion/iam-policies.tf, terraform/environments/analytical-platform-ingestion/kms-keys.tf, terraform/environments/analytical-platform-ingestion/s3-notifications.tf, terraform/environments/analytical-platform-ingestion/s3.tf
This PR corrects a key and removes an old unneeded key/bucket.
Additionally this sets `eventbridge = true` on the landing S3 bucket. This is required to stop cycling which would occur post the implementation of guardduty.
=> 🪣 🔥 Remove old DataSync S3 bucket

terraform/environments/digital-prison-reporting/application_variables.json, terraform/environments/digital-prison-reporting/locals.tf
- We currently configure the scheduled dataset lambda version for all environments (Dev, Test, Pre-Prod, Prod) in one variable shared across environments. 
- This causes issues where pipelines fail due to missing artifacts when a new version is released in one environment but not another.
- We also push a vLatest artifact which is the most recently released artifact for that environment ![image](https://github.com/user-attachments/assets/260174cb-5133-4024-b61b-44a8c2a81e21)
- This PR uses the vLatest tag to take the latest released version in each environment but also allows configuring the version by environment separately if required
=> Use latest released version of the scheduled dataset lambda in each environment

terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Expand the live_feed_dbs variable to include new entries for staging, intermediate processing, and mart databases.
=> Enhance live_feed_dbs variable for additional databases

terraform/environments/digital-prison-reporting/application_variables.json, terraform/environments/digital-prison-reporting/locals.tf
- Replaces `dps-health-and-medication-api` with `dps-health-and-medi`
- This is because otherwise IAM role names are too long, e.g. dpr-create-reload-diff-dps-health-and-medication-api-development-glue-role
- This causes errors such as this in the domains repo:
```
Error: expected length of name to be in the range (1 - 64), got dpr-create-reload-diff-dps-health-and-medication-api-development-glue-role
│ 
│   with module.ingestion-jobs["dps-health-and-medication-api"].module.create_reload_diff_job.aws_iam_role.glue-service-role[0],
│   on .terraform/modules/ingestion-jobs/terraform/environments/digital-prison-reporting/modules/glue_job/main.tf line 66, in resource "aws_iam_role" "glue-service-role":
│   66:   name  = "${var.name}-glue-role"
```
=> DPR2-1772: Shorten Health and Medication API service identifier

terraform/environments/analytical-platform-ingestion/datasync-tasks.tf
This PR disables the DataSync task in the development ingestion account `analytical-platform-ingestion-development`
=> :wrench: Disable DataSync task in Development

terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/route53-records.tf, terraform/environments/analytical-platform-compute/ses.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/6917
- Adds SES domain identity for compute
- Configures DKIM for SES domain
- Adds IAM policy for MWAA's SES IAM user (coming in another pull request)
- Production's plan is failing because the Route53 record module is trying to plan with data that does not exist yet, this should resolve itself when applying
=> ✈️ Add SES for MWAA

terraform/environments/delius-core/modules/components/oracle_db_shared/iam.tf
Temporary fix for delius-mis preprod. Policies can't be deleted without first being detached from the roles. Will undo changes in next PR.
=> Fix delius-mis preprod

terraform/environments/analytical-platform-compute/iam-users.tf, terraform/environments/analytical-platform-compute/mwaa.tf, terraform/environments/analytical-platform-compute/route53-records.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/6917
- Adds an IAM user which is consumed by MWAA
- Adds DKIM records back in
=> ✈️ Create IAM user for MWAA SMTP

terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Correct the logic to ensure that non-CADT databases are shared in the production environment.
=> Fix count logic for sharing non-CADT databases in production environment

terraform/environments/digital-prison-reporting/modules/dms/main.tf, terraform/environments/digital-prison-reporting/modules/dms_s3_v2/main.tf
This PR doubles the max_file_size to 240000 to test in pre-prod if it will speed up the DMS task for large tables e.g. offender_course_attendances
=> Set max_file_size to 240000

terraform/environments/analytical-platform-ingestion/secrets.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/7008
- Adds a secret to hold paths to include
=> 🔒 Add secret for paths to include in DataSync

terraform/environments/oasys-national-reporting/locals_preproduction.tf
Be consistent with nomis, no need for the leading `pp.`.  Change from `pp.preproduction.reporting.oasys.service.justice.gov.uk` to `preproduction.reporting.oasys.service.justice.gov.uk`
=> TM-992: onr: tweak preprod url

terraform/modules/baseline/ec2_autoscaling_group.tf, terraform/modules/baseline/ec2_instance.tf
- change ec2 and ec2 asg module references to v3.0.1
- replaces managed_policy_arns argument in module with aws_iam_role_policy_attachment
- this change is one-directional so will be applied to all environments using them
=> change module refs

terraform/environments/analytical-platform-ingestion/s3.tf
This is to ensure that collaborators don't have access to certain specific buckets that might contain sensitive information.
=> Removing S3 access to certain buckets for sandbox role

.github/workflows/ccms-ebs-upgrade.yml
This PR updates the workflow to use `reusable_terraform_plan_apply_components.yml` instead of `reusable_terraform_plan_apply.yml`. The new reusable workflow supports both root and component structures, allowing teams to transition to a component-based approach.
=> Update workflow to support component structure with reusable_terraform_plan_apply_components.yml

terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/secrets.tf
- Creates a secret placeholder for Incident Reporting to be able to access the Operational DataStore via a foreign data wrapper
- Username and password should be populated manually once the user is provisioned and given the appropriate grants
=> DPR2-1751: Operational DataStore access secret placeholder for incident reporting.

scripts/nuke-config-template.txt
https://github.com/ministryofjustice/modernisation-platform/issues/9427
AWS Nuke was failing in the YJAF Dev environment
This PR filters aws nuke for...
1. `WAFv2IPSet` - we already filter nuking WebACLs `WAFv2WebACL` and if IP sets are associated with an WebACL (as-is the case for YJAF) then they can't be deleted. In this case I suggest we just filter out nuking IP sets.
2. `RDSClusterSnapshot` - where they are of type `shared` or `automated`. In the case of YJAF the snapshot is shared in from another account so cannot be nuked. Also automated snapshots (if any are present) can also not be nuked so I've included this while I'm here for future-proofing.
Please describe the tests that you ran and provide instructions to reproduce.
In …
=> Filter `WAFv2IPSet` and `RDSClusterSnapshot` from aws nuke

terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/hmpps-domain-services/locals_test.tf
EC2s are powered down overnight, silence the corresponding alarms
=> TM: hmpps-domain-services: silence overnight alarms

terraform/environments/digital-prison-reporting/application_variables.json
- Current name is too long for creating roles in Pre-Prod, e.g. 'dpr-create-reload-diff-dps-health-and-medi-preproduction-glue-role' is too long
- I have left the old 'dps-health-and-medi' on purpose so that I can transfer the existing secrets over
- I will follow up to delete 'dps-health-and-medi' once the secrets are transferred over and the domains repo is updated
=> DPR2-1772: Use a shorter name for health & medication api service

terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_production.tf, terraform/environments/nomis/locals_test.tf
Create new nomis cert in all environments. 
This will eventually replace the existing cert which includes a domain that has subsequently been removed.
=> TM-1042: nomis: cert fix v1

terraform/environments/digital-prison-reporting/locals.tf
- If values are set to numeric values in AWS Secrets Manager it causes issues updating the secret values easily via the UI
- This solves this issue for the ODS incident reporting secret by converting the number to a string before storing it in the secret
=> DPR2-1751: Convert number to string to avoid issues updating secrets manually in secrets manager

terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_production.tf, terraform/environments/nomis/locals_test.tf
Remove old nomis azure zones. I've checked and there's no NS records pointing to these zones, and no DNS entries remaining within the zones.
=> TM-1042: nomis: remove unused zones

terraform/environments/analytical-platform-ingestion/dms/kms-keys.tf, terraform/environments/analytical-platform-ingestion/dms/secrets.tf
This sets up a dummy secret to hold database credentials for the AWS Database Manager Service endpoint to be added in a future PR. This secret will be referred to via [this parameter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#secrets_manager_arn-1) and requires the keys described in [AWS Documentation](https://docs.aws.amazon.com/dms/latest/userguide/security_iam_secretsmanager.html#security_iam_secretsmanager.console)
I've given this secret its own KMS, as this seems to be standard practice with credentials. This KMS will be also used for another secret to be added in a later PR
=> Add dummy secret and associated kms for CICA DMS Tariff Database Credentials

terraform/environments/analytical-platform-ingestion/dms/secrets.tf
This sets up a dummy secret to hold database credentials for the AWS Database Manager Service endpoint to be added in a future PR. This secret will be referred to via [this parameter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#secrets_manager_arn-1) and requires the keys described in [AWS Documentation](https://docs.aws.amazon.com/dms/latest/userguide/security_iam_secretsmanager.html#security_iam_secretsmanager.console)
=> Add dummy secret and associated kms for CICA DMS Tempus database Credentials

terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
This increases the maximum batch size passed to the Text Embeddings Inference container running on the SageMaker endpoint for Probation Search. This enables us to process larger text fields, and make use of smaller chunk sizes.
See:
* https://huggingface.co/docs/text-embeddings-inference/en/cli_arguments
=> PI-2908 Increase max batch size

terraform/environments/digital-prison-reporting/modules/domains/reconciliation-job/main.tf, terraform/environments/digital-prison-reporting/modules/domains/reconciliation-job/variables.tf
This PR exposes a flag to either create or destroy the service role for the reconciliation job.
This is required to cleanup domains which were partially created due to a failure during the terraform apply.
=> DPR2-1553: Expose flag to create/destroy reconciliation job role

terraform/environments/electronic-monitoring-data/modules/export_bucket_push/main.tf, terraform/environments/electronic-monitoring-data/modules/export_bucket_push/variables.tf, terraform/environments/electronic-monitoring-data/s3.tf
To account for the instance where the export location doesn't have a full mapping for our environments, tweaked the export bucket code to not spin up the lambda trigger if a destination bucket has not been provided.
=> Update export bucket module to conditionally create resources based on destination bucket ID

terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Introduce an IAM policy statement that allows the Airflow service account to assume a specified role using web identity.
=> Add IAM policy for Airflow service account role assumption

terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
Fixes https://github.com/ministryofjustice/analytical-platform/issues/7152
- Adds `lifecycle.replace_triggered_by` to `aws_sagemaker_endpoint` and `aws_sagemaker_endpoint_configuration` so that these resources get recreated on change.
This is required because changing `aws_sagemaker_model` does not cause an update to `aws_sagemaker_endpoint_configuration` or `aws_sagemaker_endpoint`.
=> ♻️ Replace SageMaker Endpoints on changes to SageMaker Models

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
This adds all the permissions required to configure an airflow pipeline for creating the p1 data exports.
That python code, runs an athena query and then copies the resulting query output from the athena query bucket to the p1 export bucket.
Run in test and the dev airflow account to check all is right.
=> Add IAM policy and role for P1 export data in Airflow

terraform/environments/analytical-platform-common/iam-policies.tf, terraform/environments/analytical-platform-common/iam-role.tf, terraform/environments/analytical-platform-common/s3-buckets.tf
This PR patches the following: 
- **Module Updates:**
- **iam-policy:** Updated version from `5.52.2` to `5.54.0`.
- **ecr_access_iam_role:** Updated version from `5.52.2` to `5.54.0`.
- **terraform_bucket:** Updated version from `4.5.0` to `4.6.0`.
=> :wrench: Common: Terraform Module Patching

terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
- Adds roles for https://github.com/moj-analytical-services/data-engineering-exports/pull/108
- Refactors SageMaker model and endpoint configuration
@jacobwoffenden has applied this locally due to cycling issues introduced by refactoring
=> PI-2859 Allow SageMaker to pull model from S3 bucket in AP

terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf, terraform/environments/analytical-platform-compute/secrets.tf, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/data-catalogue/values.yml.tftpl
- Adds a Secrets Manager secret to hold fine-grained token for `ministryofjustice`
- Adds a Kubernetes External Secret for the above Secrets Manager secret
- Updates DC self-hosted runner to use above External Secret
=> 🚑 Fix self-hosted runners for ministryofjustice repositories

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
- Bumps @ministryofjustice/data-catalogue's runner to [2.322.0-1](https://github.com/ministryofjustice/analytical-platform-actions-runner/releases/tag/2.322.0-1)
=> 📌 Bump DC's runner to 2.322.0-1

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
Introduce an IAM role and policy to facilitate the loading of SCRAM alcohol monitoring data, ensuring necessary permissions for Athena, S3, and Glue operations.
=> Add IAM role and policy for SCRAM alcohol monitoring data loading

terraform/environments/electronic-monitoring-data/ap_airflow.tf, terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Introduce a new placeholder for the Airflow CADT secret in the Terraform configuration to enhance secret management. Update references to use this new placeholder where necessary.
=> Add airflow_cadt_secret_placeholder to Terraform configuration

terraform/environments/analytical-platform-ingestion/dms/iam-policies.tf, terraform/environments/analytical-platform-ingestion/dms/kms-keys.tf, terraform/environments/analytical-platform-ingestion/dms/s3.tf
This is needed to unblock `terraform plan`/`apply`/testing in dev environment of [this PR](https://github.com/ministryofjustice/modernisation-platform-environments/pull/9955) by creating the dms ingestion bucket & KMS key in `analytical-platform-ingestion-development` as well as `analytical-platform-ingestion-production`
~Happy to remove the `count = 1` if people would prefer, but this removal will require either `terraform import`/destroy-create of (as yet unused) infrastructure in `analytical-platform-ingestion-production`~ 
Annoyingly i've had to break the replication out of the module to make it conditional, this is due to this issue https://github.com/hashicorp/terraform/issues/31039
=> Create CICA ingress bucket/kms in development, restrict replication to prod

terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
- Adds logic to use models from S3
- Updates execution role to connect to model storage in APDP 
=> PI-2859 Switch to pulling SageMaker model from S3 in dev

terraform/environments/analytical-platform-compute/kubernetes-roles.tf
- Adds permissions so that GitHub Actions in Airflow can create External Secrets
=> 🛂 Update mwaa-external-secrets permissions

terraform/environments/analytical-platform-compute/environment-configuration.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/7278
- Adds Cloud Platform's [VPC range](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/main.tf#L46) to our Transit Gateway routing
=> 🗺️ Add Cloud Platform's 172 range to Transit Gateway routing

terraform/environments/corporate-staff-rostering/main.tf, terraform/environments/hmpps-domain-services/main.tf, terraform/environments/hmpps-oem/main.tf, terraform/environments/nomis-combined-reporting/main.tf, terraform/environments/nomis-data-hub/main.tf, terraform/environments/nomis/main.tf, terraform/environments/oasys-national-reporting/main.tf, terraform/environments/oasys/main.tf, terraform/environments/planetfm/main.tf, terraform/modules/baseline/cloudwatch.tf, terraform/modules/baseline/variables.tf, terraform/modules/baseline_presets/cloudwatch.tf, terraform/modules/baseline_presets/outputs.tf
This piggy backs off the already implemented `pagerduty` SNS topics, which are linked to the alerting Slack channels. This PR can be reverted if the Eventbridge rule doesn't work out.
=> send aws.health events to pagerduty integrations

terraform/environments/analytical-platform-compute/helm-charts-system.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/7330
- Updates APC ingress-nginx to 4.2.1
=> 📌 Update APC ingress-nginx to 4.2.1

terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/glue.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/versions.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/maintenance-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/reconciliation-job/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/start-cdc-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/stop-cdc-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/step_function/main.tf, terraform/environments/digital-prison-reporting/modules/step_function/variables.tf, terraform/environments/digital-prison-reporting/modules/step_function/versions.tf
This PR:
- Refactors the reload, and ingestion step functions to support a batch only mode where the CDC phase is excluded
- Adds variable validation to prevent creation of jobs/pipelines which are not supported when batch only flag is set to true. These resources are: maintenance pipeline, CDC start pipeline, CDC stop pipeline, replay pipeline, glue streaming job.
- For batch only pipelines, the reconciliation glue job is ran in `current_state_counts` mode when the ingestion/reload is complete before switching the user data source to the newly loaded copy
- A validation is added to prevent configuring a schedule on the reconciliation glue job when batch_only = true
=> DPR2-1857: Make reload pipeline configurable as batch-only

terraform/environments/digital-prison-reporting/locals.tf
This PR adds the `heartbeat_endpoint` field to the DPS secrets
=> DPR2-1872: Add heartbeat_endpoint to DPS secrets

terraform/environments/analytical-platform-common/iam-policies.tf
- Adds `ecr:DescribeImages` to resolve [this](https://github.com/ministryofjustice/analytical-platform-airflow/actions/runs/14103217684/job/39503856250?pr=102)
```
An error occurred (AccessDeniedException) when calling the DescribeImages operation: User: arn:aws:sts::509399598587:assumed-role/ecr-access/GitHubActions is not authorized to perform: ecr:DescribeImages on resource: arn:aws:ecr:eu-west-2:509399598587:repository/moj-analytical-services/analytical-platform-airflow-python-example because no identity-based policy allows the ecr:DescribeImages action
```
=> 🛂 Add `ecr:DescribeImages` to ECR access policy

terraform/environments/nomis-combined-reporting/locals_production.tf
Contents of the fileshare has been moved to the multi-az one, can delete the single-az efs now
=> TM-1072: ncr: remove old EFS

.github/CODEOWNERS, .github/workflows/coat.yml
COAT team reported that they didn't have a workflow file for deploying their infra
https://mojdt.slack.com/archives/C013RM6MFFW/p1743676786746439
Ran the `provision-member-files.sh` script locally to make the necessary changes. We will raise a bug ticket to look into why it happened.
=> Add missing COAT files

terraform/environments/hmpps-domain-services/locals_test.tf
- use modified NartClient script for t2-jump2022-2 instance and adds to domain with this name
- adds test-rds-2-b instance
- set the ami names so they don't get accidentally recreated
Basically want to keep these there while messing about with the user-data scripts again
=> test instance, make sure it can be moved to correct OU

terraform/environments/hmpps-domain-services/locals_development.tf, terraform/environments/hmpps-domain-services/locals_ec2_autoscaling_groups.tf, terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/hmpps-domain-services/locals_production.tf, terraform/environments/hmpps-domain-services/locals_test.tf
Adding tags to ec2 instances for patch-manager.
Removing REDHAT baseline and hmpps-domain-service is Windows only.
=> tm-1165-patch-manager-deployment-tags

terraform/environments/digital-prison-reporting/application_variables.json, terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/glue_job/main.tf, terraform/environments/digital-prison-reporting/modules/glue_job/versions.tf
This PR creates:
- The glue job which generates the load on the DPR Postgres database
- The job is configured to insert data into Postgres for 1 hour per run
- A glue trigger which runs every 2 hours
=> DPR2-1884: Create glue job and trigger for the postgres data generation

terraform/environments/analytical-platform-compute/environment-configuration.tf
- Backports `property` tag - https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/14357215376/job/40249397324#step:11:1053
=> ⏪ Backport Lake Formation tag

terraform/environments/hmpps-domain-services/locals_development.tf, terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/hmpps-domain-services/locals_production.tf, terraform/environments/hmpps-domain-services/locals_test.tf
removing definitions from the baseline as this may be conflicting with auto-approval days setting and should not be applied to a baseline.
=> tm-1165-tuning-baseline

terraform/environments/hmpps-domain-services/locals_production.tf
Enabling AWS Patch Manager in hmpps-domain-services prod environment, after testing in all lower environments.
=> tm-1156: enabling-patch-mgr-hmpps-domain-services-prod

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
- Bumps `ghcr.io/ministryofjustice/analytical-platform-charts/actions-runner` to [2.232.0](https://github.com/ministryofjustice/analytical-platform-actions-runner/releases/tag/2.323.0)
=> 📌 Bump Actions Runners to 2.323.0

terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_ec2_instances.tf
Create qa11g nomis web server as a standalone EC2 instance for manual configuration
=> TM-1185: add nomis web12 manual build

terraform/environments/digital-prison-reporting/ecr.tf
- Used to store our custom clamav S3 scanner image for File Transfer In/Push
- This will be used by the dpr-landing-zone-check lambda
=> DPR2-1499 ECR repository for custom clamav S3 scanner

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/locals_test.tf
We're backing up FSX twice. Disable the automatic one, and align the backup tags in test with preprod and prod.
=> TM-923: onr: use aws backup for fsx

scripts/nuke-config-template.txt
Adds QuickSight resources to the nuke exclude list re issue 9789. These additional resource names were obtained by running "aws-nuke resource-types" from the latest version of aws-nuke installed on the local device.
```
~ » aws-nuke resource-types | grep Quick                                                                                                       
QuickSightSubscription                                native resource
QuickSightUser                                             native resource
=> Bug #9789 - Add Quicksight resources to the exclude list.

scripts/generate-dependabot-file.sh
GitHub support has informed me that the issue with `integrations/github` that we were seeing when using directories should now be resolved with this [PR](https://github.com/dependabot/dependabot-core/pull/12014) has been merged and the change has been included in version v0.308.0.
I also see we are hitting the default number of open dependabots (5), so I'm bumping this limit up to 15
=> Remove ignore for GitHub integration and increase dependabot limit

terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
We're seeing errors in OpenSearch that indicate SageMaker is now expecting a different request format following the TEI upgrade.
```
Received client error (422) from primary with message \\\"Failed to deserialize the JSON body into the target type: invalid length 3, expected struct EmbedRequest with 5 elements at line 1 column 139\\\". See https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logEventViewer:group=/aws/sagemaker/Endpoints/hmpps-probation-search-preprod in account 992382429243 for more information.
```
=> PI-3021 Revert TEI version upgrade

terraform/environments/analytical-platform-ingestion/dms/data.tf, terraform/environments/analytical-platform-ingestion/modules/dms/lambda-functions/metadata_generator/main.py
This is to work around the following error:
Runtime.ImportModuleError: Unable to import module 'main': cannot import name 'base_impl' from partially initialized module 'oracledb' (most likely due to a circular import) (/var/task/oracledb/__init__.py)
=> Remove sys.module override which isn't necessary in sqlalchemy>2.0

terraform/environments/analytical-platform-ingestion/dms/metadata/cica_tariff.json
The result will be that column corr_recipient will be loaded as it is required in the cica tariff data model
=> remove corr_recipient from column to remove rules

terraform/environments/analytical-platform-ingestion/dms/dms.tf
This was toggled off in terraform and toggled on manually for testing in development, but I negelected to renable it before merging the last PR
=> Renable glue connectivity for CICA Tempus

terraform/environments/digital-prison-reporting/application_variables.json
Github Action [Deploy digital prisons reporting tables to preprod](https://github.com/moj-analytical-services/create-a-derived-table/actions/workflows/deploy-preprod-digital-prisons-reporting.yml) fails with insufficient permissions.
This mirrors the Prod action workflow [configuration ](https://github.com/ministryofjustice/modernisation-platform-environments/blob/d8a334594ec3b0ee8bc205906165f1c0d85d418d/terraform/environments/digital-prison-reporting/application_variables.json#L663)to Preprod
Issue here: https://github.com/moj-analytical-services/dmet-prisons/issues/318
Slack discussion here: https://mojdt.slack.com/archives/C07U58QKEPL/p1746016926043149
=> Add glue wildcard to DPR preprod

terraform/environments/nomis/locals_production.tf
We can't test prod reporting testing unless we use a URL already in IE enterprise site list. Adding new zone to fix. Part 1.
=> TM-1247: add new nomis zone for prod reporting testing

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/powerbi/ec2.tf, terraform/environments/analytical-platform-compute/powerbi/kms.tf, terraform/environments/analytical-platform-compute/powerbi/security-groups.tf, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/create-a-derived-table/values.yml.tftpl
Resolves https://github.com/ministryofjustice/analytical-platform/issues/7630
- Bumps Actions Runner chart to [2.323.0-5](https://github.com/ministryofjustice/analytical-platform-actions-runner/releases/tag/2.323.0-5)
- Adds OneCrown endpoints to CaDeT deployment
=> 👑 Add OneCrown host aliases

terraform/environments/digital-prison-reporting/policy.tf
[Deploy digital prisons reporting tables to preprod](https://github.com/moj-analytical-services/create-a-derived-table/actions/runs/14888174786/job/41813293250) fails:
```
An error occurred (AccessDeniedException) when calling the GetTableVersions operation:
User: arn:aws:sts::972272129531:assumed-role/dpr-data-api-cross-account-role/botocore-session-1746634758
is not authorized to perform: glue:GetTableVersions on resource:
arn:aws:glue:eu-west-2:972272129531:catalog
because no identity-based policy allows the glue:GetTableVersions action
```
=> Add glue:GetTableVersions to digital prisons reporting `glue_catalog_readonly`

terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
We need to test the performance of a bulk data ingestion job, which relies on SageMaker for generating text embeddings. Based on rough estimates, we expect to be able to complete this within a weekend with 4 GPU-accelerated instances. Once confirmed in pre-prod, we will scale back to 1 instance and work on implementing auto-scaling to support future ingestion jobs.
This will require an AWS quota increase from 2 to 5.
=> PI-3053 Increase pre-prod initial instance count

terraform/environments/digital-prison-reporting/lake_formation.tf
Checking whether admin permissions changes led to the loss of LF tags and the issue reported here: https://mojdt.slack.com/archives/C06FUCUN9GC/p1746793193175119
=> dmet-prisons/318/revert admin permissions - still has tags

terraform/environments/digital-prison-reporting/operational_datastore.tf
The ODS has been auto-upgraded to postgres 16.6. This brings the terraform into sync with reality.
=> DPR2-1977: Update ODS engine version to 16.6.

terraform/environments/ccms-ebs/crowdstrike/platform_data.tf, terraform/environments/ccms-ebs/crowdstrike/secretsmanager.tf, terraform/environments/laa-portal-tactical/crowdstrike/platform_data.tf, terraform/environments/laa-portal-tactical/crowdstrike/secretsmanager.tf
This PR creates `aws_secretsmanager_secret` resources to hold API keys used by Crowdstrike.
=> Create secrets to hold crowdstrike API keys

terraform/environments/nomis/locals_development.tf
Remove scaling schedule for qa11g-nomis-web12-a on request from Syscon + enable backup.
Since an ASG and we can't easily modify tags on an existing EC2, adding a temporary backup plan just for this instance. Should only be needed for a few weeks according to Syscon.
=> TM: nomis dev: enable backup and disable autoscaling schedule

terraform/environments/digital-prison-reporting/application_variables.json, terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/metric_alarms.tf, terraform/environments/digital-prison-reporting/notifications.tf
This PR creates a Cloudwatch alarm is created to check if there is at least one failed invocations of the `postgres-tickle-function`. The alarm then sends a message which can then be matched with the following Eventbridge rule.
```
{
"source": [
"aws.cloudwatch"
],
"detail-type": [
"CloudWatch Alarm State Change"
],
"resources": [
"arn:aws:cloudwatch:${local.account_region}:${local.account_id}:alarm:${local.project}-postgres-tickle-function-failure"
]
}
```
=> DPR2-1966: Create alert when tickle lambda fails

terraform/environments/ccms-ebs/crowdstrike/crowdstrike.tf, terraform/environments/ccms-ebs/crowdstrike/providers.tf, terraform/environments/ccms-ebs/crowdstrike/secretsmanager.tf, terraform/environments/ccms-ebs/crowdstrike/versions.tf
This PR populates the `crowdstrike` component for ccms-ebs accounts with content from a template supplied to us. I've refactored it for brevity and to keep it in-line with MOJ style.
NB. This will need to be applied manually; the crowdstrike account resource needs to be applied before the subordinate module will successfully plan. Also, the crowdstrike account resource needs to be applied twice - the first application will fail due to an inconsistent result reported by the crowdstrike provider, but the re-run succeeds. I'll raise this as an issue on the relevant repository later.
=> Setup crowdstrike ccms-ebs

terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
This enables us to process large passages of text in chunks of 32 tokens at a time.
Currently, we get the following error for a handful of data items: `batch size 699 > maximum allowed batch size 512`
=> PI-3094 Increase max batch tokens

terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
This enables us to process large passages of text in chunks of 32 tokens at a time.
Currently, we get the following error for a (now very small) handful of data items: `batch size 1403 > maximum allowed batch size 1024`
=> PI-3094 Increase max batch tokens (again)

.github/workflows/terraform-static-analysis.yml
This PR updates the terraform-static-analysis.yml to use the recently pinned `checkov` version here https://github.com/ministryofjustice/modernisation-platform-github-actions/pull/55, while the syntax errors are investigated on newer versions of `checkov` (this is just a temporary measure).
=> :bug: Pin TSA Checkov Version

terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_test.tf
Updated branch for qa11g-nomis-web12-b as this is now built from code.
Remove dev-nomis-web19 ASGs, no longer in use (Syscon - Vinny).
Remove t1-nomis-db-1-b, no longer in use (DBAs - Jason).
Already applied
=> TM-1259: tidy up of unused nomis resources

terraform/environments/hmpps-domain-services/locals_test.tf
- remove t2-jump2022-2 as it's a test instance only, not linked to anything
=> remove t2 test jumpserver, not required

terraform/environments/planetfm/locals_preproduction.tf
- build upgrade test instance pp-cafm-a-19-a in plantefm preproduction based on snapshot ami
- we can attach a Server 2019 installation drive to this as a volume and run the upgrade test entirely independently from the application and the rest of the setup 
- less risk
=> Tm/tm 1257/build test instance in preprod

terraform/environments/coat/observability_platform.tf
The datasource is set up correctly for the dashboard but querying the data is unsuccessful
` Message: com.amazonaws.services.s3.model.AmazonS3Exception: User: arn:aws:sts::xxxx:assumed-role/observability-platform/xxxx is not authorized to perform: kms:Decrypt on resource: arn:aws:kms:eu-west-2:xxx:key/x because no identity-based policy allows the kms:Decrypt action `
This PR tries to fix it
=> Fix issue with Grafana role not allowed to do kms

terraform/environments/planetfm/locals_preproduction.tf
- deploy pd-cafm-a-19-a from an ami that isn't joined to the domain this time
=> deploy unjoined app server ami for upgrade

.github/workflows/reusable_terraform_components_strategy.yml
https://github.com/ministryofjustice/modernisation-platform/issues/9882
This adds a new section to the `reusable_terraform_components_strategy.yml` workflow to detect changes in the modules directory and determine which components reference the modified module(s) so they can be added to the Terraform job matrix.
The logic for adding this is that changes in the modules were not currently being added to the job matrix so their impact on the code referencing the module would not be tested.
**NOTE:** 
> This assumes that modules being referenced are located at the top level of the application folder i.e. `terraform/environments/application/modules`.
There are some examples of modules being referenced in other areas of the code including the top level i.e. `terraform/environments/modules` but …
=> Detect Module Changes in Components Strategy Workflow

terraform/environments/hmpps-domain-services/locals_production.tf, terraform/environments/hmpps-domain-services/locals_secretsmanager.tf
add a secret for a planetfm fileshare related pipeline - putting here as the servers are too old in planetfm for the script to work.
=> TM-1265: add GFSL planetFM secrets

terraform/environments/maatdb/application_variables.json, terraform/environments/maatdb/modules/rds/rds.tf
Interim change to ensure all can be built and ready for when the maat production sec groups are known.
=> MAAT Sec Groups - Prevent Prod env being blocked.

terraform/environments/maat/artifacts.tf, terraform/environments/maat/athena.tf, terraform/environments/maat/locals.tf, terraform/environments/maat/maat-cw.tf, terraform/environments/maat/maat-ec2-user-data.sh, terraform/environments/maat/maat-ecs.tf, terraform/environments/maat/maat-ext-lb.tf, terraform/environments/maat/s3_xdr_agent_bucket.tf
This PR introduces functionality to securely install and configure the Cortex XDR agent on EC2 instances used in our ECS cluster. Key changes include:
📦 XDR Agent S3 Bucket
Created an S3 bucket (via the Modernisation Platform Terraform S3 module) to store the Cortex XDR agent installation files.
- Bucket name is dynamically generated from the application name.
- Versioning is disabled and `force_destroy` is off to avoid accidental deletion.
- A lifecycle rule deletes files after 90 days.
- Shared tags are applied for consistency.
🔐 EC2 IAM Policy
- Granted `s3:GetObject` permission to the EC2 instance role.
⚙️ User Data Script
Updated the EC2 launch template user data to:
- Download the Cortex XDR agent archive from S3.
- Extract and install the RPMs.
- Copy the required `cortex.conf` …
=> Add new S3 bucket for storing XDR agent installer

terraform/environments/mlra/task_definition.json
This PR adds the missing `APP_` prefix to new environment variables for the MAAT API. MLRA is currently failing to send
requests to the MAAT API because it is expecting the prefixed environment variables which do not exist.
=> Add missing prefix to app environment variables

terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/pipeline-lambda/lambda.tf, terraform/environments/digital-prison-reporting/modules/domains/pipeline-lambda/versions.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/glue_job/main.tf
This PR:
- Creates a common Glue job for setting the start-time of a DMS task
- Adds permissions to allow the Glue job mentioned above modify a DMS task
- Modifies the ingestion and reload pipelines to support domains where the CDC task is separate from the Full-Load task
=> DPR2-1925: Add job to create the CDC DMS task

terraform/environments/digital-prison-reporting/modules/domains/pipeline-lambda/lambda.tf, terraform/environments/digital-prison-reporting/notifications.tf
This PR:
- Restricts the DMS alerts to only replication task failures
- Modifies the eventbridge pattern to ensure the pipeline notification lambda is triggered for replication task stoppage and failure events
=> DPR2-1925: Fix DMS event pattern

terraform/environments/analytical-platform-compute/actions-runner/src/helm/values/actions-runners/create-a-derived-table/values.yml.tftpl
This PR is tracked upstream by [#7851](https://github.com/ministryofjustice/analytical-platform/issues/7851) in the analytical-platform repository.
This PR introduces further host aliases for OneCrown endpoints.
=> Add onecrown host aliases to cadet template

terraform/environments/digital-prison-reporting/modules/domains/pipeline-lambda/lambda.tf
This PR broadens the eventbridge pattern match to trigger on all DMS events.
This is temporary and will allow inspecting the event which gets emitted when the `snapshot too old error` happens.
=> DPR2-1925: Fix DMS notification event pattern

.github/workflows/reusable_terraform_components_strategy.yml
Reported in the ask channel here: https://mojdt.slack.com/archives/C01A7QK5VM1/p1749220739931139
I've also had some direct comms from users who want to reinstate the previous strategy behaviour.
I've added a step to the new strategy (to replicate the behaviour of the previous strategy) so when running the pipeline from main branch the matrix is populated with a `plan_apply` action for all environments.
=> Update strategy to default to plan_apply action on main

terraform/environments/digital-prison-reporting/modules/domains/maintenance-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/maintenance-pipeline/variables.tf
This PR:
- Archives all the raw files during the maintenance window to reduce the performance impact on the spark streaming jobs when listing many files
=> DPR2-2029: Archive raw files during the maintenance pipeline

.github/workflows/reusable_terraform_components_strategy.yml
https://github.com/ministryofjustice/modernisation-platform/issues/10126
I've updated the strategy so that it behaves like the previous strategy when the pipeline is triggered manually i.e.
on main, it triggers `plan_apply` to all components/envs,
on feature branch, it triggers `plan_apply` to all components for dev/test and `plan` to all components for preprod/prod.
After receiving feedback from users, they want the ability to use this logic when they manually running pipelines because in certain circumstances they'll be making changes to a module that doesn't live in the root folder for the application they want to test it on.
=> Add default strategy for manually running pieplines

terraform/environments/oasys-national-reporting/locals_ec2_instances.tf, terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/templates/user-data-onr-bip-pwsh.yaml.tftpl
- destroy instance
- use newer instance type 
- better EBS/NVME integration so disk initialization doesn't fail
- add timeout so disk attach (it's large) can complete before initialization attempt
- newer instance == better memory bandwidth
=> WIP on TM/TM-1329/windows-bip-server-onr-preprod

terraform/environments/digital-prison-reporting/ecr.tf
- Rename the ECR repository so it is consistent with the github repository that manages the container image
- Allow mutable tags so we can have a latest version tag for the container image, as we do for jars used in lambdas
=> DPR2-1499: Rename antivirus check ECR repository as per github repository name for the image

terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf
This PR:
- Shortens the time between the completion of the Full-Load task and the start of the CDC task in the ingestion/reload pipelines by removing the compaction and vacuum steps. The compaction and maintenance steps will be eventually executed when the maintenance pipeline runs during the night.
- This will reduce the chance of the redo logs getting overwritten before the the CDC task starts
=> DPR2-1925: Shorten ingestion/reload of large pipelines by removing maintenance steps

terraform/environments/delius-core/locals_development.tf, terraform/modules/schedule_alarms_lambda/lambda/alarm_scheduler.py, terraform/modules/schedule_alarms_lambda/main.tf
If alarms triggered out-of-hours are still in effect this will allow a PagerDuty notification to be sent.
=> Set Alarms to Insufficient Data when Re-Enabled to Allow Re-Evaluation

terraform/environments/analytical-platform-common/ecr-repositories.tf, terraform/environments/analytical-platform-common/iam-policies.tf, terraform/environments/analytical-platform-common/iam-roles.tf, terraform/environments/analytical-platform-common/s3-buckets.tf
- Creates IAM policy and role to allow https://github.com/moj-analytical-services/data-engineering-datalake-access write state to `${module.terraform_bucket.s3_bucket_arn}/data-engineering-datalake-access/*` 
=> 🚰 Data Engineering Data Lake state access 

terraform/environments/digital-prison-reporting/metric_alarms.tf
This PR
- Ignores the tickle lambda alert when there is insufficient data
=> DPR2-2043: Ignore tickle lambda alert when data is insufficient

terraform/modules/ip_addresses/azure_fixngo.tf
Zap DCs from ip address module. This will cause a change in Security Groups in some accounts, e.g. CSR
=> TM-1320: hmpps: remove decommissioned Azure DCs from IP address list

terraform/modules/baseline/variables.tf, terraform/modules/baseline_presets/security_groups.tf, terraform/modules/ip_addresses/active_directory.tf, terraform/modules/ip_addresses/azure_fixngo.tf, terraform/modules/ip_addresses/moj.tf
Some more prep & fixes in order to tighten SGs in hmpps-domain-services:
- use dashes instead of underscores in naming to be consistent with SGs elsewhere
- simplified outbound rules to avoid running into maximum number of rules limit
- added rdp from rdgateway SG
- whitespace fixes
=> TM-1320: tighten hmpps-domain-services SGs part 1

terraform/modules/ip_addresses/azure_fixngo.tf
Remove references to Azure UK South network references for decommissioning.
=> TM-1319: remove-azuks-network-references

terraform/environments/corporate-staff-rostering/locals_development.tf, terraform/environments/corporate-staff-rostering/locals_ec2_instances.tf, terraform/environments/corporate-staff-rostering/locals_security_groups.tf, terraform/environments/corporate-staff-rostering/main.tf
Tightening of CSR rules part 1
- remove unnecessary comments
- remove unnecessary UDP rules
- remove duplicated RDP rules
- swap domain SG to the one created by baseline
- add remote-management SG
Validated using flow logs
=> TM-1320: csr security group tidyup v1

terraform/environments/corporate-staff-rostering/locals_development.tf, terraform/environments/corporate-staff-rostering/locals_ec2_instances.tf, terraform/environments/corporate-staff-rostering/locals_security_groups.tf, terraform/modules/baseline_presets/security_groups.tf
Tighten DB Security group for CSR:
- add oem-agent SG to baseline as this is common across all environments
- tightened oem-agent rules as access from azure no longer required
- removed duplicate rules from web and app
=> TM-1320: csr security group db tidyup

terraform/environments/nomis/locals.tf, terraform/environments/nomis/locals_ec2_autoscaling_groups.tf, terraform/environments/nomis/locals_ec2_instances.tf, terraform/environments/nomis/locals_security_groups.tf, terraform/environments/nomis/main.tf, terraform/modules/baseline_presets/security_groups.tf
Tighten Nomis SG rules
- remove ssh
- remove OEM agent from web tier as it was never used
- use baseline SGs for common rules: ad-join, oem-agent, ec2-linux, ec2-windows
=> TM-1320: nomis sg tweaks

terraform/environments/analytical-platform-compute/actions-runner/kubernetes-external-secrets.tf, terraform/environments/analytical-platform-compute/dashboard-service/kubernetes-external-secrets.tf, terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf, terraform/environments/analytical-platform-compute/kubernetes-secret-stores.tf
- Corrects a reference to Analytical Platform Data Production secret store
- [External Secrets Operator v1.17.0](https://github.com/external-secrets/external-secrets/releases/tag/v0.17.0) introduces a breaking change 😱 
> v0.17.0 Stops serving v1beta1 apis. You need to update your manifests from v1beta1 to v1 prior to updating from v0.16 to v0.17.
> 
> The only change needed is upgrading your manifests to v1 (i.e. removing the beta1 from v1beta1).
> 
> Be sure to do that to all your manifests prior to bumping to v0.17.0! v0.16.2 already supports v1 so this process should be smooth.
> 
Due to the API version being changed, Terraform wants to **recreate** ESO resources and cannot in-place upgrade. For `*SecretStore`, this should result in minimal to no downtime, but `Secret` will recreate …
=> 🔒 Prepare for ESO v1.17.0

terraform/environments/analytical-platform-compute/helm-charts-system.tf
Prior to updating the cluster these helm charts are being brought to their latest version. Preparation for the upgrade to `external-secrets` was done in [this](https://github.com/ministryofjustice/modernisation-platform-environments/pull/11113/files) PR. 
The latest [release](https://github.com/external-secrets/external-secrets/releases/tag/v0.18.0) of `external-secrets` mentions 'Potential Breaking Changes' but does not go any further so I am proceeding with caution.
Edit: applied to Development locally and re-ran plans, now appear with [no changes](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/15730557436/job/44331429416?pr=11127#step:13:734) as expected so I believe this can proceed to production. 
Applied to Test environment as well. 
- …
=> 🔧  EKS Compute: update helm charts

terraform/environments/analytical-platform-compute/environment-configuration.tf
This PR supersedes [this](https://github.com/ministryofjustice/modernisation-platform-environments/pull/11112) PR.
Upgrades EKS Cluster in Development and Test environments in `analytical-platform-compute-development` and `analytical-platform-compute-test` from 1.32 to 1.33.
=> AP Compute: EKS Upgrade Test/Dev `1.32` -> `1.33`

terraform/environments/oasys/locals.tf, terraform/environments/oasys/locals_ec2_instances.tf, terraform/environments/oasys/locals_security_groups.tf, terraform/environments/oasys/main.tf
Align Oasys Security Groups with other DSO apps:
- use baseline SGs for egress, self and OEM rules
- remove SSH (confirmed via FlowLogs that it's unused)
=> TM-1320: oasys: simplify SGs

terraform/environments/ccms-ebs/ccms-r53.tf, terraform/environments/ccms-ebs/member-data.tf
This DNS record currently sits in the LAA Production hosted zone, and points to the 3 EIPs attached to the NLB.
This adds in a new alias record to the new legalservices.gov.uk hosted zone in MP which will replace the LAA production hosted zone.
=> Add CCMS production DNS

terraform/environments/nomis-combined-reporting/locals_lbs.tf, terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf, terraform/environments/nomis-combined-reporting/locals_security_groups.tf, terraform/environments/nomis-combined-reporting/locals_test.tf
Add security group fix for EFS fileshare.
Also adding internal-LB rules back in as LB still exists, although not in use. But will remove that separately
=> TM-1320: ncr: security group fix

.github/workflows/generate-dependabot-file.yml
https://github.com/ministryofjustice/modernisation-platform/issues/10126
I've updated the `generate-dependabot-file.yml` workflow to fetch secrets from aws using the central action.
=> Centralise secrets for `generate-dependabot-file.yml` file

terraform/environments/nomis-data-hub/locals_preproduction.tf, terraform/environments/nomis-data-hub/locals_production.tf, terraform/environments/nomis-data-hub/locals_security_groups.tf
Taking extra care over new security group rules which are applied up to test.
To avoid any chance of error, add the new rules to the EC2s before removing the old ones. To do this, need to restore the old prod rules into the code.
=> TM-1320: ndh: restore prod security groups to fix drift

terraform/environments/oasys/locals_production.tf, terraform/environments/oasys/locals_security_groups.tf
Taking extra care over new security group rules which are applied up to preprod.
To avoid any chance of error, add the new rules to the EC2s before removing the old ones. To do this, need to restore the old prod rules into the code.
=> TM-1320: oasys: restore prod security groups to fix drift

terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/locals_security_groups.tf
Taking extra care over new security group rules which are applied up to preprod.
To avoid any chance of error, add the new rules to the EC2s before removing the old ones. To do this, need to restore the old prod rules into the code.
=> TM-1320: onr: restore prod security groups to fix drift

terraform/environments/planetfm/locals_production.tf, terraform/environments/planetfm/locals_security_groups.tf
Taking extra care over new security group rules which are applied up to preprod.
To avoid any chance of error, add the new rules to the EC2s before removing the old ones. To do this, need to restore the old prod rules into the code.
=> TM-1320: planetfm: restore prod security groups to fix drift

terraform/environments/analytical-platform-common/iam-policies.tf
We need to enable the data-engineering-datalake-access repository to access all DPR environments (dev, test, preprod, prod) via appropriate IAM roles and policies. This is already in place for Electronic Monitoring (EM).
There are two IAM roles involved:
[data-engineering-datalake-access-github-actions](https://github.com/ministryofjustice/modernisation-platform-environments/blob/4e0b8b06cf6a764707e9e6c403dcfcdfa6762d48/terraform/environments/analytical-platform-common/iam-roles.tf#L59-L75) – used by GitHub Actions
[data-engineering-datalake-access-terraform](https://github.com/ministryofjustice/modernisation-platform-environments/blob/4e0b8b06cf6a764707e9e6c403dcfcdfa6762d48/terraform/environments/analytical-platform-common/iam-roles.tf#L77-L94) – used for Terraform provisioning
We want …
=> Dmet prisons 400/setup OIDC on datalake repo

terraform/environments/planetfm/locals_production.tf
Add additional ad-join group which will replace the domain one. This allows IPs from MP domain controllers whereas existing rule only allows azure DCs.
=> TM-1376: planetfm: add AD join security group

terraform/environments/digital-prison-reporting/policy.tf
Ticket: https://github.com/moj-analytical-services/data-engineering-datalake-access/issues/38
A replication of this PR: https://github.com/ministryofjustice/modernisation-platform-environments/pull/11083/files
This allows the Data Engineering Data Lake repo and the associated github runner to assume the analytical platform share role `analytical-platform-data-production-share-role`
=> DMET-prisons: Update trust policy for share role

terraform/environments/coat/secrets.tf
Changing SSM Parameter names to match the namespaces for more clarity in future changes to exchange rates
=> Correcting variable names for more clarity on exchange rates

terraform/environments/corporate-staff-rostering/locals_production.tf
Remove the "domain" Security Group from single prod server. If OK, separate PR will remove from the other servers. This has been replaced with ad-join SG which also allows MP DCs.
=> TM-1376: csr: replace domain SG test

terraform/environments/corporate-staff-rostering/locals_ec2_instances.tf
The domain security group has been replaced with ad-join which has some additional rules for the MP DCs. Has already been tested + applied on a single prod server without issue.
=> TM-1376: csr: remove domain SG

terraform/environments/corporate-staff-rostering/locals_production.tf
Remove JumpServer security group on a single prod server. The jumpserver SG rules are either not needed or duplicate, but removing on one server only as a precaution.
=> TM-1376: csr: remove jumpserver SG test

terraform/environments/maat/maat-ecs.tf
This changes how the task definition version is obtained and used by the ecs service. The older approach of user a data call was not picking up changes to the TD version and so the service was using the prior version.
=> MAAT Task Definition

terraform/environments/planetfm/locals_production.tf
Test removal of domain SG on one of each server type. This has been replaced by ad-join SG.
=> TM-1376: planetfm: test removal of domain SG

terraform/environments/corporate-staff-rostering/locals_security_groups.tf
Remove duplicate or unnecessary rules from CSR database SG. No need for RPC as it's linux box.  SSH is too open. OEM covered by oem-agent SG.
=> TM-1376: csr: tighten database SG

terraform/environments/planetfm/locals_production.tf
These have been replaced by ec2-windows and ad-join so removing them from EC2s. Validated using flow logs. Already in place in preprod without issue.
=> TM-1376: planetfm: drop old jumpserver SG and sessionhost SG from EC2s

terraform/environments/maatdb/ftp_lambda.tf, terraform/environments/maatdb/ftp_secrets.tf
This fixes an issue whereby the data call getting the latest ftp secrets was failing to resolve if the version did not exist - which it would do at initial plan & apply.
=> Secrets version error fix

terraform/environments/hmpps-domain-services/locals_security_groups.tf
Just adding this back in as the one in the baseline ec2-linux is too permissive
=> TM-1376: hmpps-domain-services: add alltoself rule

terraform/environments/corporate-staff-rostering/locals_security_groups.tf
CSR FSX has been zapped so can now get rid of the associated SG
=> csr: remove unused fsx security group

terraform/environments/hmpps-domain-services/locals_production.tf
Changes have been applied in prod so we can zap this now there are no references to it
=> TM-1376: hmpps-domain-services: prod SG cutover v3

terraform/environments/digital-prison-reporting/application_variables.json, terraform/environments/digital-prison-reporting/data.tf, terraform/environments/digital-prison-reporting/dpr_rds_db.tf, terraform/environments/digital-prison-reporting/glue-connections.tf, terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/rds/aws-aurora/main.tf, terraform/environments/digital-prison-reporting/modules/rds/aws-aurora/outputs.tf, terraform/environments/digital-prison-reporting/modules/rds/aws-aurora/variables.tf, terraform/environments/digital-prison-reporting/modules/rds/cluster_parameter_group/main.tf, terraform/environments/digital-prison-reporting/modules/rds/cluster_parameter_group/outputs.tf, terraform/environments/digital-prison-reporting/modules/rds/cluster_parameter_group/variables.tf, terraform/environments/digital-prison-reporting/modules/rds/cluster_parameter_group/versions.tf, terraform/environments/digital-prison-reporting/modules/rds/parameter_group/main.tf, terraform/environments/digital-prison-reporting/modules/rds/parameter_group/outputs.tf, terraform/environments/digital-prison-reporting/modules/rds/parameter_group/variables.tf, terraform/environments/digital-prison-reporting/modules/rds/parameter_group/versions.tf, terraform/environments/digital-prison-reporting/modules/rds/postgres/main.tf, terraform/environments/digital-prison-reporting/modules/rds/postgres/outputs.tf, terraform/environments/digital-prison-reporting/modules/rds/postgres/sg.tf, terraform/environments/digital-prison-reporting/modules/rds/postgres/variables.tf, terraform/environments/digital-prison-reporting/operational_datastore.tf, terraform/environments/digital-prison-reporting/secrets.tf
This PR:
- Creates a test RDS database in the dev and test environments for the purpose of reproducing the read replica issue for AWS support to take a look at.
- Extracts the parameter group and cluster parameter group to their own modules
- Creates the secrets for the test database
=> DPR2-2072: Create test rds database

terraform/environments/hmpps-oem/locals_secretsmanager.tf, terraform/modules/baseline/iam_roles.tf, terraform/modules/baseline/secretsmanager.tf, terraform/modules/baseline_presets/iam_roles.tf
Remove unnecessary code in baseline re converting principal identifiers - this is causing a problem with the xsiam integration. Ran plans across all accounts and there are no plan changes with this.
=> TM-1325: baseline: fix for trusted principals

terraform/environments/youth-justice-networking/data.tf, terraform/environments/youth-justice-networking/ses.tf
https://github.com/ministryofjustice/modernisation-platform/issues/10594
Adds SES domain `yjb.gov.uk` which will generate some verifiction records which I will separately associate with the hosted zone in https://github.com/ministryofjustice/dns/blob/main/hostedzones/yjb.gov.uk.yaml
It also adds an smtp iam user to be used by ses and stores the access keys in secrets manager.
=> Add SES for yjaf networking account

terraform/environments/youth-justice-networking/ses.tf
https://github.com/ministryofjustice/modernisation-platform/issues/10594
Allows SMTP user to send to any verified identity within the account. Previously it only allowed sending to yjb.gov.uk which was not intended.
=> Fix SMTP user policy

terraform/environments/long-term-storage/iam.tf
This PR adds Terraform code to create an IAM user with read-only access to a specific S3 bucket, using a least-privilege policy. It also creates a Secrets Manager secret to store the user's credentials. [#issue](https://github.com/ministryofjustice/modernisation-platform/issues/10561)
=> Add IAM user with S3 read-only policy

terraform/environments/laa-ccms-soa/ec2_autoscaling.tf, terraform/environments/laa-ccms-soa/soa_database.tf
Disables ec2 and rds overnight halting in NP environments as per `https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/instance-scheduling.html` for `laa-ccms-soa`
=> fix: disable ec2 and rds shutdown for ccms-soa

terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_production.tf
The XSIAM cortex cloudwatch integration is no longer required as we have agents running on the hosts instead.
=> TM: nomis: remove cloudwatch xsiam integration

terraform/environments/electronic-monitoring-data/share_cloud_platform.tf
Previously, AC were piggy-backing on the role for cmt. Here we create a new role for them to use so that we can more finely control the permissions granted to them. We also remove their access to the old role.
=> Create service role for Acquisitive Crime

terraform/environments/hmpps-esupervision/locals.tf, terraform/environments/hmpps-esupervision/s3.tf
Define an S3 bucket to be used for rekognition image uploads for the e-supervision application. Objects in the bucket are encrypted using AES256.
=> Define S3 bucket for rekognition uploads for HMPPS esupervision

terraform/environments/xhibit-portal/xhibit-waf.tf
We had issues regarding blocking AWSManagedGroupRules so we need to switch them to Monitoring mode.
=> Switch AWSManagedGroupRules to Monitoring mode

terraform/modules/baseline_presets/route53.tf, terraform/modules/ip_addresses/azure_fixngo.tf
Updating DNS severs to point to MP homed servers in preference to AZ.
=> TM-1378: Update-mp-dns-severs

terraform/environments/ccms-edrms/chatbot.tf, terraform/environments/ccms-edrms/versions.tf
pinning chatbox version to v5.X as latest runs are trying to use v6.0 and failing: https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/16420592952/job/46397865977
=> Pin chatbot version to v5.X

terraform/environments/property-cafm-data-migration/main.tf
The latest release of the RDS Terraform module introduces significant functionality improvements. It now:
- Builds the SQL Server instance
- Restores the .bak file
- Transforms table data into Parquet format
- Stores the transformed data in S3
- Drops the database upon successful completion via the Step Function
However, in the currently deployed environment, the SQL Server was provisioned separately, outside the Step Function workflow. As a result, it does not align with the updated module flow, where provisioning and teardown are integrated into the state machine.
To align with the new functionality, I plan to:
- Destroy all resources previously created via the existing RDS module
- Re-deploy the updated RDS module to ensure that all resources—including the SQL Server—are managed …
=> drop rds module to add later

terraform/environments/analytical-platform-compute/cluster/environment-configuration.tf
This PR patches EKS Add Ons as well as EKS Node versions in the `analytical-platform-compute-test` EKS Cluster.
This PR makes use of [this](https://github.com/ministryofjustice/analytical-platform/pull/8158) script and forms part of [this](https://github.com/ministryofjustice/analytical-platform/issues/8049) piece of work.
| Addon                             | Previous Version         | Updated Version          |
|----------------------------------|---------------------------|---------------------------|
| `coredns`                         | `v1.12.1-eksbuild.2`      | `v1.12.2-eksbuild.4`      |
| `aws_ebs_csi_driver`             | `v1.44.0-eksbuild.1`      | `v1.46.0-eksbuild.1`      |
| `aws_efs_csi_driver`            | `v2.1.8-eksbuild.1`       | `v2.1.9-eksbuild.1`       |
| …
=> 🔧 Analytical Platform Compute Production: Patch EKS Add-ons + EKS Node Version

terraform/environments/coat/kms.tf, terraform/environments/coat/s3.tf
Manage COAT GitHub Team and Repos via IAC. [#191](https://github.com/ministryofjustice/cloud-optimisation-and-accountability/issues/191)
Creating **`coat-github-repos-tfstate`** S3 bucket and KMS key to store the state in COAT Production account only.
=> Coat GitHub tfstate

terraform/environments/ccms-ebs/cash-office-transfer-family.tf
Correct region for WAF/ACL region, needs to be us-east-1 to accomodate cloudfront
=> fix: waf resource region

terraform/environments/planetfm/locals_preproduction.tf
=> TM-1440: planetfm: add windows 2022 install volume to preprod

.github/workflows/reusable_terraform_components_plan_apply.yml
This PR updates the workflow to dynamically determine the GitHub Actions environment name based on whether a `component` input is provided.
- If `component` is not `root`, the environment will be set to: `<application>-<environment>-<component>`
- If `component` is `root`, it defaults to: `<application>-<environment>`
Previously, the `environment` field was always set to `<application>-<environment>`, which did not support the new component-level environments. This ensures the correct GitHub environment context is used when applying Terraform changes, aligning with the recently introduced per-component environments.
[#issue](https://github.com/ministryofjustice/modernisation-platform/issues/9879)
=> Dynamic environment name selection based on component input

terraform/environments/hmpps-esupervision/data.tf, terraform/environments/hmpps-esupervision/iam.tf, terraform/environments/hmpps-esupervision/s3.tf
Add IAM user to HMPPS esupervision environments. Add a policy granting the user access to the rekognition uploads bucket and attach the managed read-only policy for rekognition.
=> Add IAM user and access policies for S3 and Rekognition

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
var.environment is "production" |||| ([load_emsys_tpims_database](https://github.com/ministryofjustice/modernisation-platform-environments/blob/7935e51b48038108b8bbdf6e674da2c827251f9c/terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf#L219-L236) )
so local.env_suffixes[var.environment] = "" |||| ([locals.env_suffixes code](https://github.com/ministryofjustice/modernisation-platform-environments/blob/7935e51b48038108b8bbdf6e674da2c827251f9c/terraform/environments/electronic-monitoring-data/modules/ap_airflow_iam_role/main.tf#L9))
local.role_name_suffix comes from [role_name_suffix](https://github.com/ministryofjustice/modernisation-platform-environments/blob/7935e51b48038108b8bbdf6e674da2c827251f9c/terraform/environments/electronic-monitoring-data/modules/ap_airflow_iam_ro …
=> updated new airflow parameter

terraform/environments/planetfm/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
app-11 now on 2022. Tidy up:
- Remove install drives
- Remove temporary app-20 EC2
- Copy install volume config (commented out) for when we do prod
=> TM-1440: planetfm: preprod app-11 upgrade part5

terraform/environments/planetfm/locals_production.tf
Add installation media and remove alarms for app-11 in prep for 2012 -> 2019 -> 2022 upgrade
=> TM-1478: planetfm: prepare prod app-11 for 2022 upgrade

terraform/environments/ccms-edrms/application_variables.json, terraform/environments/ccms-edrms/ec2.tf, terraform/environments/ccms-edrms/iam.tf, terraform/environments/ccms-edrms/tds_database.tf, terraform/environments/ccms-edrms/templates/user-data.sh
Adds (prod only):
- S3 policy allowing S3 access to `ccms-shared` bucket
- Modifies launch template to allow cortex agent (XDR) installation for SOC integration (tested in dev)
Will also apply to prod outstanding changes (prod only):
- Cloudwatch alarm for RDS storage threshold breach
- Cloudwatch alarm for RDS CPU threshold breach
=> feat: add s3 perms for cortex deps

terraform/environments/delius-mis/locals_development.tf, terraform/environments/delius-mis/main_development.tf, terraform/environments/delius-mis/modules/mis_environment/databases.tf, terraform/environments/delius-mis/modules/mis_environment/dfi.tf, terraform/environments/delius-mis/modules/mis_environment/s3.tf, terraform/environments/delius-mis/modules/mis_environment/variables.tf, terraform/environments/delius-mis/modules/mis_environment/versions.tf
- add s3 bucket to mis-environments module
- cannot use lates s3 bucket version as this requires aws provider 6.0 which isn't supported in delius env
- set up in locals_development.tf 
- will likely have to change the 'condition' value for the dfi_report_bucket_policy resource
- however, let's set it up first and change it later
=> remove count, add s3 module, change params

terraform/environments/analytical-platform-compute/actions-runner/helm-charts-actions-runners.tf
This PR is required as part of the maintenance  [ticket](https://github.com/orgs/ministryofjustice/projects/27/views/34?pane=issue&itemId=117914402&issue=ministryofjustice%7Canalytical-platform%7C8048) , this [PR](https://github.com/ministryofjustice/analytical-platform-actions-runner/pull/217)  and updates the `actions-runner` chart to `2.327.1-1`
=> Update Helm charts actions-runner to latest runners version 2.327.1-1

.github/workflows/terraform-state-management.yml, scripts/terraform-remove.sh, terraform/environments/sprinkler/application_variables.json
https://github.com/ministryofjustice/modernisation-platform/issues/11214
1. I've set `set -o pipefail` to the `terraform-remove.sh` script to ensure it fails when any commands fail. The TF remove command was piped to the redact script (which succeeded) causing it to fail silently.
1. I've added single quotes around the commands which write the resource addresses into a text file for processing so that any resource addresses containing double quotes are preserved. This is common when `for_each` is used and you get indexes like `module.bastion_linux.aws_s3_object.user_public_keys["davidelliott"]`
1. I've updated the postgres db versions to match updates that have been automatically applied in the environment.
Successful run deleting a resource containing double quotes.. …
=> Fix State Remove job

.github/workflows/format-code.yml
Remove need for MP secrets and bump GitHub Actions version
=> Simplify `format-code` workflow

terraform/environments/hmpps-esupervision/application_variables.json, terraform/environments/hmpps-esupervision/iam.tf, terraform/environments/hmpps-esupervision/locals.tf, terraform/environments/hmpps-esupervision/s3.tf
Define a role which gives access to the resources required for Rekognition calls in the e-supervision application. Attach the Rekogntion read and custom S3 policy.
Allow the modernisation platform 'developer' role within the account to assume this role to be used for local development.
=> Define role for Rekognition access within esupervision

terraform/environments/hmpps-esupervision/iam.tf, terraform/environments/hmpps-esupervision/s3.tf
Issue ESUP-633 - Remove the IAM user used for Rekognition operations. The application is now configured to assume the rekognition role instead of using the access keys for the IAM user.
Remove the user from the S3 bucket encryption key policy.
Remove the secret manager secrets used to store the access keys.
=> Remove IAM user for Rekognition operations in E-supervision

terraform/environments/maatdb/application_variables.json, terraform/environments/maatdb/locals.tf, terraform/environments/maatdb/modules/rds/rds.tf, terraform/environments/maatdb/rds.tf
This PR applies two sets of changes:
1. Applies the updated zip python lambda script to the lambda terraform via the ref to the s3 bucket, folder and file version.
2. Adds a workaround for the hub2 RDS to S3 integration to avoid the terraform for that failing the rest of the build if either the hub2 changes have not been applied to the account & so don't exist, or the hub2 environment is missing - namely preproduction but the maatdb terraform will try and reference it.
Changes have been tested in dev and also deployed to test.
=> Updated zip lambda python lib version.

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
This PR alphabetises users in `environment-configuration.tf`, additionally it removes a duplicate entry in the CIDR blocks configuration which caused [this](https://arc.net/l/quote/jqdvtqax) error on a previous apply to production: 
```
Error: [WARN] A duplicate Security Group rule was found on (sg-0b4577304edad0d3b). This may be
│ a side effect of a now-fixed Terraform issue causing two security groups with
│ identical attributes but different source_security_group_ids to overwrite each
│ other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
│ information and instructions for recovery. Error: operation error EC2: AuthorizeSecurityGroupIngress, https response error StatusCode: 400, RequestID: 0c956427-ebb9-4456-9e43-f735457aa314, api error …
```
=> 🔢  Ingestion: Alphabetise users + remove duplicate `cidr_block`

terraform/environments/ccms-ebs/ccms-ftp-lambda.tf, terraform/environments/ccms-ebs/modules/ftp-lambda/main.tf
Failure alerts are triggered in slack channel for non prod over the weekend for ftp lambda when the ftp-server is down. Fix is added to changed the schedule to run from MON-FRI for non prod ONLY
=> fix failure alerts in non prod for ftp lambda 

.trivyignore.yaml, terraform/environments/xhibit-portal/xhibit-waf.tf
We have joined to the `alpha-transition-to-prisma` testing group to solve the Alpha VPN Split Tunnel issue.
I have added the Prisma VPN Gateway CIDR to provide single access from the MoJ devices.
=> Xhibit-Portal: add Prisma VPN access to PRTG WAF WebACL

terraform/environments/nomis/locals_production.tf, terraform/environments/oasys/locals_preproduction.tf, terraform/environments/oasys/locals_production.tf
Turn on oracle listener xsiam integration for nomis prod and oasys preprod/prod. Already implemented and tested in nomis preprod.
=> TM-1546: enable remaining oracle listener xsiam integration

terraform/environments/data-platform/aws-s3-access-logging.tf
Resolves https://github.com/ministryofjustice/data-platform/issues/15
- Creates bucket for S3 server access logging
This bucket does not use `SSE-KMS` as per the documentation ([source](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html))
>You can use [default bucket encryption](https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-bucket-encryption.html) on the destination bucket only if you use server-side encryption with Amazon S3 managed keys (SSE-S3), which uses the 256-bit Advanced Encryption Standard (AES-256). Default server-side encryption with AWS Key Management Service (AWS KMS) keys (SSE-KMS) is not supported.
=> 🪵 S3 access logging

terraform/environments/nomis-combined-reporting/locals_cloudwatch_metric_alarms.tf, terraform/environments/nomis-combined-reporting/locals_ec2_instances.tf, terraform/environments/nomis-combined-reporting/locals_production.tf
Add alerting for nomis-combined-reporting in advance of prod cutover
Non-prod alerts cater for the environment being shutdown over weekend.
=> TM-1239: ncr: add cloudwatch alarms

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
AP Ingestion service does not meet user needs
- 🔥 Remove `glenn-barber-cafm` config
- 🔥 Remove `glenn-barber` unused old config
=> 🔥 Remove CAFM config

terraform/environments/nomis-combined-reporting/locals_lbs.tf, terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf, terraform/environments/nomis-combined-reporting/locals_test.tf
Following operational testing, tweak nomis reporting load balancer health check thresholds so unhealthy hosts detected much quicker. Also enable alerting in prod for unhealthy hosts.
=> TM-1239: ncr: monitoring and redundancy improvements

terraform/environments/hmpps-oem/locals_cloudwatch_metric_alarms.tf
Add monitoring for admin reporting endpoint
In production only, try speeding up the detection of failed endpoints. There's already a retry mechanism in the endpoint detection script.
=> TM-1239: ncr: add admin reporting endpoint monitoring

terraform/environments/equip/main.tf
This PR updates the Equip server sizing (4 CPU / 16 GB RAM) as per the request https://github.com/ministryofjustice/modernisation-platform/issues/11496
=> Equip Server Sizing (EC2 Instance type)

terraform/environments/analytical-platform-compute/cloudwatch-network-monitor.tf, terraform/environments/analytical-platform-compute/environment-configuration.tf
- Adds a CloudWatch Network Monitor for Cloud Platform's internal ingress
The connectivity isn't working, but I think that is out of scope for this
```
analyticalplatform@network-debug:~$ curl --verbose https://ingress.internal-non-prod.cloud-platform.service.justice.gov.uk/
* Host ingress.internal-non-prod.cloud-platform.service.justice.gov.uk:443 was resolved.
* IPv6: (none)
* IPv4: 172.20.143.89, 172.20.95.25, 172.20.103.178
*   Trying 172.20.143.89:443...
*
```
=> ☁️ Cloud Platform Network Monitoring

terraform/environments/digital-prison-reporting/lake_formation.tf
The SSO role was previously a Lake Formation (LF) admin. This was removed [here](https://github.com/ministryofjustice/modernisation-platform-environments/commit/cebcef5ed78bfe1058bea711715a933d136b57e6).
The SSO role will need data location access to be able to access LF managed databases.
=> dmet-prisons - give data location access to DE SSO roles

terraform/environments/digital-prison-reporting/lake_formation.tf
Was removed in an earlier PR. 
This resulted in another terraform apply in datalake access failing: https://github.com/moj-analytical-services/data-engineering-datalake-access/actions/runs/18165660284/attempts/5
By adding back back the share role as LF admin this now runs fine: https://github.com/moj-analytical-services/data-engineering-datalake-access/actions/runs/18165660284/job/51877537830
=> dmet-prisons - add back the AP share role to LF admins

terraform/environments/cooker/versions.tf
Include the null provider in the Terraform configuration to fix [error](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/18258490711/job/51983172533#step:7:54)
=> Add null provider to Terraform configuration

terraform/environments/analytical-platform-compute/dashboard-service/helm-charts-dashboard-service.tf
Had to create a 0.2.9 to resolve errors writing to temp files in 0.2.8
=> Update dashboard-service Helm chart version to 0.2.9

terraform/environments/electronic-monitoring-data/bastion_linux.tf
[ELM-4040](https://dsdmoj.atlassian.net/browse/ELM-4040)
Doubled volume size again to help with decompression task of larger emsys_mvp zip
Emsys ZIP has gone from 370GB to 473GB in size and the current 500GB storage attached to EC2 will not support this.
Recommend to keep it at increased size until all decompression tasks are completed
[ELM-4040]: https://dsdmoj.atlassian.net/browse/ELM-4040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Double volume size on large EC2 instance
