ministryofjustice/modernisation-platform-environments

.github/dependabot.yml, terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/eks-pod-identities.tf, terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/helm-charts-system.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/rds.tf, terraform/environments/analytical-platform-compute/vpc-endpoints.tf, terraform/environments/analytical-platform-compute/vpc.tf
- Updates Dependabot configuration
- Updates EKS module
- Updates EKS Pod Identity module
- Updates Bottlerocket
- Updates kube-prometheus-stack chart
- Updates ingress-nginx chart
- Updates IAM module
- Updates RDS module
- Updates VPC module
=> 📌 APC Patching

terraform/environments/hmpps-oem/locals.tf, terraform/environments/nomis-combined-reporting/locals.tf, terraform/environments/nomis-combined-reporting/locals_development.tf
Allow metric sharing with OEM account and add dashboard there
=> ncr: DSOS-2890: nomis alignment v2

terraform/environments/analytical-platform-compute/data.tf, terraform/environments/analytical-platform-compute/lakeformation-data-lake-settings.tf, terraform/environments/analytical-platform-compute/platform_data.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/4461
- Adds LF settings to APC
=> 🌊 Add Lake Formation settings in APC

terraform/modules/baseline_presets/ssm-documents/Session/SSM-SessionManagerRunShell.json
- Vinny asked for the timeout to be upped, this is the maximum allowed value
=> BAU: update the SSM timeout to the maximum allowed value

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/airflow/values.yml.tftpl
- Switches moj-analytical-services/airflow GitHub Actions runner to KEDA powered system
=> 🔀 Switch Airflow to KEDA

terraform/environments/electronic-monitoring-data/lambdas_main.tf, terraform/environments/electronic-monitoring-data/s3_main.tf
- **remove .yaml**
- **remove yam;**
=> No YAML suffix

terraform/environments/electronic-monitoring-data/lambdas/get_metadata_from_rds.py
- **remove .yaml**
- **remove row_v cols**
=> Remove Binary Columns from metadata

terraform/environments/analytical-platform-compute/helm-charts-mlops.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/src/helm/values/mlflow/values.yml.tftpl
- Updates Analytical Platform MLFlow to 2.15.1-rc1
- Enables `MLFLOW_SERVER_DEV_MODE` to help with debugging https://github.com/ministryofjustice/data-platform-support/issues/787
=> 🤖 Update MLFlow

terraform/environments/oasys/locals_security_groups.tf
=> oasys allow azure to ssh

terraform/environments/ccms-ebs/application_variables.json, terraform/environments/ccms-ebs/ccms-s3.tf
CC-2686: Replaced hardcoded values in S3 bucket lifecycle policies with variables.
=> CC-2686: Replaced hardcoded values in S3 bucket lifecycle policies with variables.

terraform/environments/analytical-platform-compute/helm-charts-applications.tf, terraform/environments/analytical-platform-compute/kms-keys.tf, terraform/environments/analytical-platform-compute/kubernetes-secrets.tf, terraform/environments/analytical-platform-compute/random.tf, terraform/environments/analytical-platform-compute/rds.tf, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/Chart.yaml, terraform/environments/analytical-platform-compute/src/helm/values/ollamate/values.yml.tftpl, terraform/environments/nomis/locals_cloudwatch_metric_alarms.tf, terraform/environments/nomis/locals_test.tf
=> :wrench: Ollamate Chart

terraform/environments/oasys/locals_test.tf
Add secrets for T2OASYS2. These will be a clone of T2OASYS secrets - requested by DBAs.
=> oasys: DSOS-2914: additional secrets for new DB

terraform/environments/electronic-monitoring-data/lambdas_main.tf, terraform/environments/electronic-monitoring-data/modules/lambdas/main.tf, terraform/environments/electronic-monitoring-data/modules/lambdas/variables.tf
- **remove .yaml**
- **remove row_v cols**
- **meant to be dict**
- **meant to be dict**
=> EM: dlt to create a data task

terraform/environments/digital-prison-reporting/locals.tf
https://github.com/ministryofjustice/digital-prison-reporting-lambdas/pull/19
=> [DPR2-991] Update lambda version for bug fix

terraform/environments/oasys/locals_test.tf
New web ASG for testing Oasys replacement project "SAN" in T2 environment
=> DSOS-2917: add config for oasys T2 SAN environment

terraform/environments/planetfm/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
Second attempt at creating http-redirect this time using default rule. First attempt was rejected by AWS. Hopefully this will work as same approach as in Oasys
=> planetfm: DSOS-2918: redirect fix attempt 2

terraform/environments/planetfm/locals_production.tf
temporarily adding a http rule to allow wireshark testing. For investigation into prod migration issue
=> Planetfm: DSOS-2918: more http testing

terraform/environments/analytical-platform-compute/helm-charts-applications.tf, terraform/environments/analytical-platform-compute/src/helm/values/ui/values.yml.tftpl
Deploy AP UI to test latest releases https://github.com/ministryofjustice/analytical-platform-ui/releases/
This relates to 0.1.x releases
=> Deploy AP UI

terraform/environments/analytical-platform-compute/lakeformation-data-lake-settings.tf
Tracking Issue: https://github.com/ministryofjustice/analytical-platform/issues/4271
Adds the new AP UI service role as Lake Formation admin
=> APC: APUI Role added as LF Admin

terraform/modules/baseline_presets/cloudwatch_dashboards.tf
one each for:
- github failed workflow runs
- ssm command invocations
=> DSOS-2925: add widgets

terraform/environments/analytical-platform-compute/cloudwatch-log-groups.tf, terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/eks-pod-identities.tf, terraform/environments/analytical-platform-compute/environment-configuration.tf, terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/helm-charts-mlops.tf, terraform/environments/analytical-platform-compute/helm-charts-system.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/lakeformation-data-lake-settings.tf, terraform/environments/analytical-platform-compute/route53-zones.tf, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/Chart.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-gpu-on-demand.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-gpu-spot.yaml, terraform/environments/analytical-platform-compute/vpc-endpoints.tf, terraform/environments/analytical-platform-compute/vpc.tf
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/5084
- Updates Terraform modules
- Updates Actions Runner
- Updates MLFlow
- Updates Kubernetes Prometheus Stack
- Updates Prometheus Operator CRD
- ~Updates Karpenter~
- This is more involved and has been split out in to https://github.com/ministryofjustice/analytical-platform/issues/5087
- Updates Cert Manager
- Updates Ingress NGINX
- Updates External Secrets
- Updates KEDA
- Updates Bottlerocket OS
- Updates EKS Addons
- Removes `p3.8xlarge` from GPU node pools
=> 🚀 APC Patching

terraform/environments/electronic-monitoring-data/lambdas_iam.tf, terraform/environments/electronic-monitoring-data/lambdas_main.tf
Initial configuration of a lambda that will unzip files from our zipped up datastore
=> EM: unzip lambda

terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/helm-charts-system.tf
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/5087
=> 🪵 Karpenter 1.0.0

terraform/environments/electronic-monitoring-data/lambdas_main.tf
- **update tag**
- **readding unzip**
- **new tag!!!!**
=> g4s update tag

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Created in relation to [this](https://github.com/ministryofjustice/analytical-platform/issues/5096) piece of work.
=> 🔧 Update Image Release Versions

terraform/environments/planetfm/locals.tf, terraform/environments/planetfm/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
- add pagerduty integrations for services planetfm-preproduction and planetfm-production
- send to planetfm_alarms channel
=> use new pagerduty services

terraform/environments/delius-core/locals_preproduction.tf, terraform/environments/delius-core/locals_stage.tf
=> chore: Update legacy_engineering_vpc_cidr in pre-production and stage

terraform/environments/nomis-combined-reporting/locals.tf, terraform/environments/nomis-combined-reporting/locals_cloudwatch_metric_alarms.tf, terraform/environments/nomis-combined-reporting/locals_development.tf, terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf, terraform/environments/nomis-combined-reporting/locals_test.tf
- just do the nomis-combined-reporting changes for now
=> ncr alarm changes

terraform/environments/hmpps-domain-services/locals.tf, terraform/environments/hmpps-domain-services/locals_development.tf, terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/hmpps-domain-services/locals_production.tf, terraform/environments/hmpps-domain-services/locals_test.tf, terraform/environments/hmpps-oem/locals.tf, terraform/environments/hmpps-oem/locals_development.tf, terraform/environments/hmpps-oem/locals_ec2_instances.tf, terraform/environments/hmpps-oem/locals_preproduction.tf, terraform/environments/hmpps-oem/locals_production.tf, terraform/environments/hmpps-oem/locals_test.tf
- changed branch name
- hmpps-oem account slack changes 
- hmpps-domain-services slack account changes
=> Dso/dsos 2903/hmpps oem and domain services slack changes

terraform/environments/analytical-platform-compute/helm-charts-system.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/managed-prometheus.tf
- Resolves https://github.com/ministryofjustice/analytical-platform/issues/4425
=> 🚚 Import APC APS into module

terraform/environments/planetfm/locals_ec2_instances.tf, terraform/environments/planetfm/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
Add secret for letsencrypt cert
Undo previous policy changes as no longer required
=> DSOS-2927: planetfm letsencrypt renewal changes v4

terraform/environments/electronic-monitoring-data/lambdas_iam.tf, terraform/environments/electronic-monitoring-data/lambdas_main.tf, terraform/environments/electronic-monitoring-data/step_function_definitions/get_zipped_file.json.tmpl, terraform/environments/electronic-monitoring-data/step_functions_main.tf
- **init of step function**
- **updating iams**
- **correct reference to module**
- **correcting syntax for each**
- **templtaefile**
- **variable types**
- **mapping**
- **remove templating**
- **.json**
- **stringstringstring**
- **add api gateway**
- **output and arn**
- **ima policy**
- **updating the api gateway code**
- **rename resource**
- **whoops**
- **proper response**
- **pre signed url lambda**
=> EM: create presigned url lambda function

terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/variables.tf
This PR ensures there is no data downtime when running the ingestion pipeline.
=> DPR2-1053: Retain data availability during data ingest

terraform/environments/electronic-monitoring-data/api_gateway.tf, terraform/environments/electronic-monitoring-data/lambdas_iam.tf, terraform/environments/electronic-monitoring-data/lambdas_main.tf, terraform/environments/electronic-monitoring-data/modules/step_function/main.tf, terraform/environments/electronic-monitoring-data/modules/step_function/outputs.tf, terraform/environments/electronic-monitoring-data/modules/step_function/variables.tf, terraform/environments/electronic-monitoring-data/step_function_definitions/get_zipped_file.json.tmpl, terraform/environments/electronic-monitoring-data/step_functions_main.tf
- **init of step function**
- **updating iams**
=> EM: API Gateway to trigger step func

terraform/environments/analytical-platform-compute/lakeformation-data-lake-settings.tf, terraform/environments/analytical-platform-compute/providers.tf
Tracking story: https://github.com/ministryofjustice/analytical-platform/issues/5195
This PR creates a new TF provider in Ireland and bootstraps Lake Formation in that region.
=> AP: Configuring Lake Formation Admins in Ireland

terraform/environments/laa-oem/application_variables.json, terraform/environments/laa-oem/member_certificates.tf, terraform/environments/laa-oem/oem_ec2_app.tf, terraform/environments/laa-oem/oem_ec2_db.tf, terraform/environments/laa-oem/oem_ec2_wl.tf, terraform/environments/laa-oem/oem_ec2_wl_sg.tf
CC-2760: AMI IDs data -> variables.
=> CC-2760: Fix Terraform code for LAA OEM.

terraform/environments/planetfm/locals_preproduction.tf
To test migration of zone from Azure to AWS
=> planetfm: TM-151: add preprod az zone for testing

terraform/environments/planetfm/locals_lbs.tf, terraform/environments/planetfm/locals_preproduction.tf
Add network lb in preprod to test NTLM windows auth fix
=> planetfm: TM-152: add network LB in preprod

terraform/environments/planetfm/locals_lbs.tf
=> planetfm: TM-152: preprod LB fix

terraform/environments/analytical-platform-compute/helm-charts-applications.tf
Deploys database access management changes
=> Bump AP UI to 0.2.0

terraform/environments/nomis/locals_production.tf
=> nomis: increase throughput on prod EBS volumes

terraform/environments/planetfm/locals_production.tf
To apply Tue 10 at 7am - swaps the production endpoint from Azure to AWS network LB.
=> planetfm: TM-152: migrate prod web server endpoint to MP

terraform/environments/analytical-platform-compute/helm-charts-applications.tf
As title.
- Updates UI to include breadcrumbs to make database access navigation easier
=> Bumped AP-UI to 0.2.2

terraform/environments/nomis-combined-reporting/locals_preproduction.tf
- order the shutdown of each VM, in groups
=> TM-405: add a shutdown order tag for VMs

terraform/environments/planetfm/README.md
- added readme to PlanetFM as per modernisation-platform guidelines
=> Tm/tm 470/planetfm readme

terraform/environments/nomis/locals_development.tf
=> nomis: TM-472: add additional web19c server

terraform/environments/analytical-platform-compute/helm-charts-applications.tf
Adds admin to nav bar if user is staff
=> Bump AP UI to 0.2.3

terraform/environments/cica-tariff/bastion_linux.json, terraform/environments/cica-tariff/ec2_bastion_linux.tf, terraform/environments/cica-tariff/locals.tf, terraform/environments/cica-tariff/platform_providers.tf, terraform/environments/cica-tariff/tariff_ec2_app_sg.tf, terraform/environments/cica-tariff/tariff_vpc_endpoints.tf
Add CICA UAT IPs to security group ingress
=> 🛂 Add uat to security group

terraform/environments/hmpps-domain-services/locals_secretsmanager.tf, terraform/environments/oasys-national-reporting/locals.tf
Enable HMPPS domain join for ONR
=> onr: TM-483: allow domain join

terraform/environments/oasys-national-reporting/locals_test.tf
Testing - adding BODS to domain
=> onr: TM-483: add domain tag

terraform/environments/oasys-national-reporting/locals_security_groups.tf
Test - allow RDP from gateway in hmpp-domain-services
=> onr: TM-483: allow RDP from gateway

terraform/environments/xhibit-portal/shield.tf
* implements DDOS monitoring through code for AWS Shield Advanced.
* implements AWS Shield Advanced protection & WAF rule configuration through code, removing reliance on clickops and allowing better visibility as to the current configuration.
=> Implement `xhibit-portal-production` AWS Shield Advanced through code

terraform/environments/nomis-combined-reporting/locals_preproduction.tf
Create an ASG for preprod BIP build testing
=> ncr: TM-503: ASG for preprod build testing

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
- contributes to [this ticket](https://github.com/ministryofjustice/analytical-platform/issues/5365)
- updates image release versions for ingestion services
Signed off by: Anthony Fitzroy <anthony.fitzroy@justice.gov.uk>
=> 🔧 update ingestion image release versions

terraform/environments/digital-prison-reporting/main.tf
Update description for reconciliation job to include optional config to restrict the set of reconciliation checks that are run.
=> DPR2-1124: Update description for reconciliation job 

terraform/environments/electronic-monitoring-data/bash_scripts/copy_bucket.sh, terraform/environments/electronic-monitoring-data/bash_scripts/totally_empty_bucket.sh, terraform/environments/electronic-monitoring-data/s3.tf
- **adding bash scripts to clean all data from buckets and copy stuff over**
- **update commit hash of s3 module and change log buckets arg**
=> EM: Update S3 module commit hash

terraform/environments/oasys-national-reporting/locals_test.tf, terraform/environments/oasys-national-reporting/templates/user-data-onr-bods-pwsh.yaml.tftpl
- use EC2LaunchV2 tasks to change hostname
- easier to have it managed like this rather than putting the reboot in a script
=> Tm/tm 494/change hostname

terraform/environments/oasys-national-reporting/locals_test.tf
- very small PR to test some issue where an Administrator user is no longer created
=> make machine name equal hostname in user_data_raw

terraform/environments/nomis-combined-reporting/locals_ec2_autoscaling_groups.tf, terraform/environments/nomis-combined-reporting/locals_lbs.tf, terraform/environments/nomis-combined-reporting/locals_preproduction.tf
Remove existing test ASG with ASGs for each server type.
Add LB for access directly from Mac
=> ncr: TM-503: preprod testing v2

terraform/environments/digital-prison-reporting/modules/pipeline_trigger/main.tf, terraform/environments/digital-prison-reporting/modules/pipeline_trigger/variables.tf
This PR adds a flag to enable/disable the pipeline schedule. By default they will be disabled.
=> DPR2-1170: Add flag to disable/enable a pipeline trigger schedule

terraform/environments/delius-core/modules/components/dms/dms_s3.tf
Ensure old audited interaction staging data is cleared out
=> Add lifecycle rule for current versions of data

terraform/environments/ppud/iam.tf, terraform/environments/ppud/lambda.tf, terraform/environments/ppud/lambda_scripts/certificate_expiry_dev.py
Creation of a lambda function to check for certificate expiration
=> Update lambda certificate expiry 270924 2

terraform/environments/ppud/eventbridge.tf, terraform/environments/ppud/lambda_scripts/certificate_expiry_dev.py
Minor typo fix to code - update to lambda permission to invoke a function to check for expiring certificates.
=> Update eventbridge certificate approaching expiration 270924 2

terraform/environments/nomis-combined-reporting/locals_lbs.tf, terraform/environments/nomis-combined-reporting/locals_preproduction.tf
Fix subnets for preprod public LB
=> ncr: TM-531: fix preprod lb subnets

terraform/environments/nomis-combined-reporting/locals_lbs.tf, terraform/environments/nomis-combined-reporting/locals_secretsmanager.tf, terraform/environments/nomis-combined-reporting/locals_security_groups.tf
Fix web security group
Add logging to LB
Terraform fmt
=> ncr: TM-531: preprod lb fix v2

terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/Chart.yaml, terraform/environments/analytical-platform-compute/src/helm/charts/karpenter-configuration/templates/node-pool-airflow-high-memory.yaml, terraform/environments/analytical-platform-compute/transit-gateway-vpc-attachments.tf
- Adds a new _experimental_ node pool while we're testing some performance issues
=> ✈️ APC Karpenter high-memory equivalent

terraform/environments/delius-core/locals_preproduction.tf, terraform/environments/delius-core/locals_stage.tf, terraform/environments/delius-core/modules/components/dms/cloudwatch-alarms.tf
Set dummy values for replication targets for pre-prod & stage until prod exists.
=> Set dummy replication configuration for stage & preprod

terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/domains/reconciliation-job/main.tf, terraform/environments/digital-prison-reporting/modules/domains/reconciliation-job/variables.tf
- Extracts Reconciliation Job to a module so it can be used in the domains repo to add the job to the service bundle
=> DPR2-1135: Extract reconciliation job to a module

terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf, terraform/environments/nomis-combined-reporting/locals_test.tf
Avoids duplication of secrets within environment
=> ncr: TM-531: permissions fix

terraform/environments/ppud/certificate_mgmt.tf, terraform/environments/ppud/sqs.tf
Creation of lambda sqs queue and dead letter queue in uat and dev. Updating some of the lambda functions to reference these queues.
=> Sqs deadletter 021024 5

terraform/environments/ppud/iam.tf
Update to IAM permissions to allow lambda to perform several SQS functions.
=> Iam permissions 021024 2

terraform/environments/electronic-monitoring-data/lambdas_iam.tf, terraform/environments/electronic-monitoring-data/lambdas_main.tf, terraform/environments/electronic-monitoring-data/modules/lambdas/main.tf, terraform/environments/electronic-monitoring-data/modules/lambdas/variables.tf, terraform/environments/electronic-monitoring-data/modules/landing_bucket_iam_user_access/main.tf, terraform/environments/electronic-monitoring-data/modules/landing_bucket_iam_user_access/outputs.tf, terraform/environments/electronic-monitoring-data/modules/landing_bucket_iam_user_access/variables.tf, terraform/environments/electronic-monitoring-data/s3.tf
- **instigate infrastructure around rotation lambda**
- **add s**
- **instigate secrets module**
- **this might actually work**
=> ELM-2773: Rotation and trivy solve

terraform/environments/ppud/certificate_mgmt.tf
Removing dead letter queue configs from lambda functions, while I troubleshoot the IAM permissions.
=> IAM_Permissions_021024_3

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
relates to https://github.com/ministryofjustice/analytical-platform/issues/5504 issue
updates action runner version
=> update actions-runner version

terraform/environments/mlra/ecs.tf, terraform/environments/mlra/locals.tf, terraform/environments/mlra/modules/ecs/main.tf, terraform/environments/mlra/modules/ecs/variables.tf, terraform/environments/mlra/task_definition.json
removing `APP_MLRA_GOOGLE_ANALYTICS_4_TAG_ID` as per user request: 
https://mojdt.slack.com/archives/C01A7QK5VM1/p1727882996147749
=> Remove google analytics 4 tag id

terraform/environments/ppud/certificate_mgmt.tf
Enabling dead letter queues on certificate expiry lambda functions.
=> Enable_DLQ_Lambda_041024

terraform/environments/ppud/certificate_mgmt.tf, terraform/environments/ppud/lambda.tf
Creation of a lambda code signing configuration and signing profile
=> Create lambda csc 041024 3

terraform/environments/nomis-combined-reporting/locals_ec2_instances.tf, terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf, terraform/environments/nomis-combined-reporting/locals_secretsmanager.tf, terraform/environments/nomis-combined-reporting/locals_test.tf, terraform/environments/nomis/locals_development.tf
Miscellaneous Changes:
- clear out existing instances, they will be rebuilt using new ansible code next week
- update AMI to last officially supported version RHEL8.8
- add new secrets using naming consistent with oracle
=> NCR: TM-531: zap preprod

terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf, terraform/environments/nomis-combined-reporting/locals_security_groups.tf, terraform/environments/nomis-combined-reporting/locals_test.tf
Setup CMS first server in preproduction
- add `ppbipcms1` EC2
- remove unused secrets
- remove unused internal LB config
- update IP allow listing to allow access from JumpServers
- update reporting endpoint to use public LB
=> ncr: TM-531: rebuild preprod

terraform/environments/planetfm/locals_production.tf
=> planetfm: increase prod w-36 disk size

terraform/environments/nomis-combined-reporting/locals_ec2_instances.tf, terraform/environments/nomis-combined-reporting/locals_lbs.tf, terraform/environments/nomis-combined-reporting/locals_preproduction.tf
Second part of preprod build
- add redundant CMS, app and webadmin servers
- update LB config to use new servers
- add instance sizes
=> ncr: TM-534: preprod part 2

terraform/environments/oasys/locals_preproduction.tf, terraform/environments/oasys/locals_production.tf
Add additional secrets for new ONR Business Objects databases
=> TM: onr: secrets for bods db

terraform/environments/ppud/iam.tf, terraform/environments/ppud/lambda.tf
Update to lambda signing profile and IAM permissions
=> Update lambda 081024 5

terraform/environments/ppud/lambda.tf
Adding lambda code signing configurations.
=> Update lambda 081024 7

terraform/environments/electronic-monitoring-data/modules/landing_zone/main.tf, terraform/environments/electronic-monitoring-data/s3.tf
- **update days to 30**
- **trivy checks**
=> EM: Correct bucket set up for supplier buckets

terraform/environments/nomis-combined-reporting/locals_preproduction.tf
To allow testing of BI launch pad
=> ncr: TM-534: add web server to preprod

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Patching as per [this](https://github.com/orgs/ministryofjustice/projects/27/views/18?pane=issue&itemId=81705371) issue.
=> :wrench: Ingestion Patching

terraform/environments/ppud/shield.tf
=>  increasing WAF rate limit to reduce uneccessary triggers

terraform/environments/planetfm/locals_production.tf
Resize pd-cafm-w-37-a on request from Glenn Barber. To be applied at lunch time.
=> planetfm: resize w-37 EC2 instance

terraform/environments/ppud/cloudwatch_linux.tf, terraform/environments/ppud/instances.tf
Restore S609693LOV6VW110 from backup. Creation of cloudwatch alarms for the root volumes all linux tagged instances.
=> Instance_Restore_091024_1

terraform/environments/ppud/cloudwatch_linux.tf
Minor changes to cloudwatch alarms for the root volumes of all linux tagged instances.
=> CW_Update_091024_1

terraform/environments/ppud/shield.tf
=> increase waf rate limit

terraform/environments/ppud/alb_external.tf, terraform/environments/ppud/endpointservice.tf, terraform/environments/ppud/s3.tf
Trivy scan exclusions added for notifications on some S3 buckets, others have had it enabled. Logging enabled for some ALBs.
=> Update 111024 2

terraform/environments/ppud/s3.tf
Update to IAM permissions, delivery.logs.amazonaws.com given ACL & put access. S3 bucket SNS notification filter_prefix typo corrected.
=> Update 111024 5

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
[ELM-2823](https://dsdmoj.atlassian.net/browse/ELM-2823)
[ELM-2823]: https://dsdmoj.atlassian.net/browse/ELM-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EM: Permissions required for loading Atrium table

terraform/environments/electronic-monitoring-data/bastion_linux.tf
=> ELM-2827 use commit hash for bastion linux module

.github/workflows/format-code.yml
Reverts ministryofjustice/modernisation-platform-environments#7968
=> Revert "issue/7689"

terraform/environments/ppud/s3.tf, terraform/environments/ppud/sns.tf, terraform/environments/ppud/sqs.tf
Update to S3 bucket notification and lifestyle policies. Trivy scan exclusions put in place for SNS resources.
=> Update 141024 3

terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-pipeline/versions.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/reload-pipeline/versions.tf, terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/pipeline.tf, terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/variables.tf, terraform/environments/digital-prison-reporting/modules/domains/replay-pipeline/versions.tf
This PR:
- Configures the file transfer step in the data pipelines to retry 3 times when an S3 exception is encountered while copying/deleting a file
- Performs a compaction and vacuum before starting the CDC phase in the ingestion, reload and replay pipelines
=> DPR2-1240: Retry on file transfer failures

terraform/environments/nomis-combined-reporting/locals_production.tf
Increase flash from 200 -> 250 GB on prod
=> ncr: add 50GB to prod DB flash

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
Adding preprod runner and updating role in existing runner to target prod DPR account.
=> Create a derived table DPR runners

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_test.tf
- deploy t2-onr-bods-1 instance fully automatically
- change lb config to point to this
- include onr-bods asg for testing purposes but set instances to zero
=> create an asg in test env for convenience

terraform/environments/contract-work-administration/alb.tf, terraform/environments/example/certificates.tf, terraform/environments/example/data.tf, terraform/environments/example/ec2.tf, terraform/environments/example/ec2_autoscaling_group.tf, terraform/environments/example/ec2_bastion_linux.tf, terraform/environments/example/ec2_complete.tf, terraform/environments/example/ecs.tf, terraform/environments/example/loadbalancer.tf, terraform/environments/example/loadbalancer_module.tf, terraform/environments/example/macie.tf, terraform/environments/example/rds.tf, terraform/environments/example/s3.tf, terraform/environments/example/shield.tf
As part of issue Comment out Example Terraform code as default
[#7621](https://github.com/ministryofjustice/modernisation-platform/issues/7621)
I have hashed out resources that are not always required so that they are not created and will allow users to quickly create new resources on the example account
=> Remove resources that are not always required

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/templates/user-data-onr-bods-pwsh.yaml.tftpl
- remove pp-onr-bods-1
- remove disk init task as it returns inconsistent results
Will be fixed in user-data instead
=> destroy pp-onr-bods-1 and initialize disks another way

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/templates/user-data-onr-bods-pwsh.yaml.tftpl
- put initialize task back in, works for EC2 instances but not ASG's
- will deploy this and work around any issues manually
=> Tm/tm 584/fix disk init issue

terraform/environments/ppud/alb_external.tf, terraform/environments/ppud/iam.tf, terraform/environments/ppud/sns.tf
Created a new SNS topic policy with the added explicit permission for S3 to publish to SNS. Removed logging from PPUD-ALB.
=> Update 171024 2

terraform/environments/oasys-national-reporting/locals_security_groups.tf
- add jumpserver access as per ncr
=> allow jumpserver access to onr preprod

terraform/environments/apex/backups.tf
_window for the backup schedfule
=> TM-586 Remove invalid start

terraform/environments/analytical-platform-ingestion/data.tf, terraform/environments/analytical-platform-ingestion/transit-gateway-vpc-attachments.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5175
- Attaches MoJ TGW to ingestion's connected VPC
=> 🌐 Analytical Platform Ingestion Transit Gateway VPC attachment

terraform/environments/nomis/locals_ec2_autoscaling_groups.tf, terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_secretsmanager.tf
Add additional secret and tags to allow testing of nomis reporting in AWS
=> ncr: TM-596: preprod nomis link test

terraform/environments/electronic-monitoring-data/modules/lambdas/main.tf, terraform/environments/electronic-monitoring-data/modules/lambdas/variables.tf, terraform/environments/electronic-monitoring-data/modules/push_export_bucket/main.tf, terraform/environments/electronic-monitoring-data/modules/push_export_bucket/variables.tf, terraform/environments/electronic-monitoring-data/s3.tf
Updated the lambda module so that the function_uri could be set distinct from the function_name i.e. if you want to use the same function image for several lambda instances.
Added bucket and push lambda infra
=> ELM-2876 add push bucket module infrastructure

terraform/environments/nomis/locals_preproduction.tf
The build seems to be working now so make permanent.
=> ncr: TM-596: add second weblogic server for testing reporting

terraform/environments/corporate-information-system/ec2.tf, terraform/environments/corporate-information-system/locals.tf
CIS: implementing keepalive solution
=> [TM-618] CIS: implementing keepalive solution

terraform/environments/oasys-national-reporting/locals_preproduction.tf
- make BODS instance in pre-prod larger 
- add comment as to why
=> Increase onr bods ram as requested

terraform/environments/ppud/sns.tf
Update to SNS policy amended the Resource ARN.
=> Update 231024 9

terraform/environments/analytical-platform-ingestion/ec2-instances.tf, terraform/environments/analytical-platform-ingestion/environment-configuration.tf
This PR updates the lambda images used in ingestion. Related to [this](https://github.com/orgs/ministryofjustice/projects/27/views/18?pane=issue&itemId=83416225&issue=ministryofjustice%7Canalytical-platform%7C5663) issue.
=> 🔧  23/10/24 - Patching

terraform/environments/observability-platform/environment-configurations.tf
Update DB name from the default `data` to specifically created Athena database `moj-cur-athena-db`
=> Update Athena DB Name

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/airflow/values.yml.tftpl
- Updates `actions-runner-mojas-airflow` to `2.320.0-2`
=> 🧪 Upgrade Airflow Self-Hosted runner

terraform/environments/ppud/sns.tf
New SNS topic & subscription for S3 bucket notifications in development.
=> Update 241024 5

terraform/environments/delius-core/modules/components/dms/dms_outbound_tasks.tf
Fix wrong replication task name
=> Fix wrong replication task name

terraform/environments/analytical-platform-compute/kms-keys.tf, terraform/environments/analytical-platform-compute/s3-buckets.tf
- contributes to this [ticket](https://github.com/ministryofjustice/analytical-platform/issues/5599)
- creates logging bucket and kms keys in `eu-west-1`
Signed off by: Anthony Fitzroy <anthony.fitzroy@justice.gov.uk>
=> create logging bucket and kms keys in eu-west-1

terraform/environments/ppud/cloudwatch_alarms_linux.tf, terraform/environments/ppud/cloudwatch_alarms_windows.tf
Creation of cloudwatch alarms for service status.
=> Update 291024 3

terraform/environments/ppud/alb_external.tf, terraform/environments/ppud/iam.tf, terraform/environments/ppud/s3.tf
Updates to IAM policy statements, Trivy scan exclusion statements added for ALB and S3.
=> Update 041124 4

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
relates to https://github.com/ministryofjustice/analytical-platform/issues/5906 issue
updates action runner version
Signed off by: Brian Ellwood [brian.ellwood@jdigital.ustice.gov.uk](mailto:brian.ellwood@digital.justice.gov.uk)
=> Update actions-runner chart version

terraform/environments/delius-core/modules/components/dms/cloudwatch-alarms.tf
Reduce false alarms during startup
=> Reduce sampling frequency to every 2 minutes

terraform/environments/hmpps-domain-services/locals_security_groups.tf
Allow endpoints to be monitored from elsewhere within mod platform
=> TM-500: hmpps-domain-services: update allow list for endpoint monitoring

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/variables.tf
- **adding am role**
- **add s3 perms**
=> iam for athena

terraform/environments/analytical-platform-compute/data.tf, terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/lakeformation-data-lake-settings.tf, terraform/environments/analytical-platform-compute/quicksight.tf, terraform/environments/analytical-platform-compute/security-groups.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5736
=> 🔗 Attach APC QuickSight to MP's platform VPC

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/variables.tf
=> EM: OIDC role to s3 create-a-derived-table bucket

terraform/environments/hmpps-oem/locals_cloudwatch_metric_alarms.tf, terraform/modules/baseline_presets/cloudwatch_dashboards.tf
Enable remaining endpoint alarms as networking now fixed
Improved the dashboard widgets
=> TM-500: enable endpoint monitoring alerts

terraform/environments/analytical-platform-compute/iam-roles.tf
Issue: https://github.com/ministryofjustice/analytical-platform/issues/5600
After this PR, work outstanding:
=> Adding management production to the trust policy of the data engineering data access role

terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/5962
- Fixes my mistake
=> :shipit: Amend casing of decodingStrategy 

terraform/environments/analytical-platform-compute/data.tf, terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/airflow-create-a-pipeline/values.yml.tftpl, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/airflow/values.yml.tftpl, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/create-a-derived-table/values.yml.tftpl
- https://github.com/ministryofjustice/analytical-platform/issues/5962
=> 📌 APC Self Hosted Runners 2.320.0-4

terraform/environments/analytical-platform-ingestion/ext-user-2024.tf
Issue: https://github.com/ministryofjustice/analytical-platform-ithc-2024/issues/26
Now with 100% more bucket policy.
=> Adding bucket policy

terraform/environments/analytical-platform-ingestion/ext-user-2024.tf
Issue: https://github.com/ministryofjustice/analytical-platform-ithc-2024/issues/26
I don't even know.
=> Bucket policy

terraform/environments/planetfm/locals_production.tf, terraform/environments/planetfm/locals_security_groups.tf
bug fix - servers are missing default tags such as os-type
plus fixed a SG rule typo
=> TM-679: fix planetfm tags for ssm monitoring

terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf
=> EM: Get glue partitions

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_secretsmanager.tf, terraform/environments/oasys-national-reporting/locals_test.tf
- create config secrets holder to align with nomis-combined-reporting approach
=> add onr config secrets bucket

terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
Fix typo for github alarm and add missing data alarm for SSM monitoring
=> TM-679: ssm monitoring tweaks

terraform/environments/analytical-platform-compute/s3-buckets.tf
As per conversation here: https://mojdt.slack.com/archives/C04M8224WCV/p1732032950560999
=> Disabling backups on the replication + related buckets

terraform/environments/corporate-information-system/application_variables.json, terraform/environments/corporate-information-system/ec2-s3fs.tf, terraform/environments/corporate-information-system/iam.tf, terraform/environments/corporate-information-system/locals.tf
CIS: creation of s3fs ec2 instance
=> [TM-615] CIS: creation of s3fs ec2 instance

terraform/environments/analytical-platform-compute/iam-roles.tf
fixes iam role account reference mgmt account -> data prod account
=> fix: correct iam role account

.devcontainer/README.md
- Updates guidance, adding "Open in X" buttons
=> 📝 Update Dev Container README

terraform/environments/electronic-monitoring-data/modules/landing_bucket/main.tf
create a customer managed key that external users can be given access to for encrypting files prior to transfer
=> Add kms key generation for use with landing bucket

terraform/environments/observability-platform/environment-configurations.tf
Resolves https://github.com/ministryofjustice/observability-platform/issues/149
=> ♻️ Create OP Development Tenants in Production

terraform/environments/observability-platform/environment-configurations.tf
- Adds Analytical Platform's member-unrestricted accounts, including the Data Engineering accounts.
=> 🔭 Onboard Analytical Platform and Data Engineering accounts

terraform/environments/ppud/alb_external.tf
Updating Dev and Preprod listeners to use the newly created target groups.
=> Update 261124 5

terraform/environments/nomis-combined-reporting/locals_test.tf
Add secrets for new T1 BI databases for Nomis Reporting T1 AWS build
=> TM-739: ncr: Add T1 BI secrets

terraform/environments/observability-platform/environment-configurations.tf, terraform/environments/observability-platform/modules/grafana/amazon-prometheus-query-source/main.tf
- Un-hardcodes the region in APS workspace string
=> 🔀 Fix a hardcoded region in APS string

terraform/environments/ppud/alb_external.tf, terraform/environments/ppud/iam.tf, terraform/environments/ppud/lambda.tf
Update to WAM Target Group, IAM permissions updated for Lambda.
=> Update 271124 2

terraform/environments/hmpps-domain-services/locals_test.tf
Silenced the alarms in preprod but forgot about test
=> TM: silence overnight rdgw alarms in test

terraform/environments/ppud/iam.tf, terraform/environments/ppud/lambda.tf, terraform/environments/ppud/s3.tf
Update to IAM policy, creation of new s3 bucket & enabling of lambda layers for lambda function.
=> Update 281124 8

terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/observability-platform.tf
- Is part of https://github.com/ministryofjustice/observability-platform/issues/148
- Migrates DPR to OP Production
=> 🚚 Migrate DPR to OP Production

terraform/environments/observability-platform/environment-configurations.tf
- Is part of https://github.com/ministryofjustice/observability-platform/issues/148
- Off-boards DSO as per this https://mojdt.slack.com/archives/C05QXHR697S/p1732720987699179?thread_ts=1732720715.254049&cid=C05QXHR697S
=> 👋 Off-board DSO from OP 

terraform/environments/nomis-combined-reporting/locals_secretsmanager.tf, terraform/environments/nomis-combined-reporting/locals_test.tf
T1 build
Also updated permissions on secrets so NART can update passwords.
=> TM-739: ncr: T1 build

terraform/environments/ppud/iam.tf, terraform/environments/ppud/lambda.tf, terraform/environments/ppud/platform_secrets.tf
Update to Lambda IAM policy, creation of secure string SSM parameter for AWS elb account ID.
=> Update 281124 12

terraform/environments/hmpps-oem/locals_cloudwatch_metric_alarms.tf
Remove CSR and PlanetFM preprod alarms on request
=> remove-csr-and-planetfm-preprod-endpoint-alarms

terraform/environments/long-term-storage/call-centre-migration.tf, terraform/environments/long-term-storage/data.tf
* Add policy document to allow `transfer.amazonaws.com` and `s3.amazonaws.com` to use a KMS key
* Create KMS key with attached policy
* Encrypt S3 bucket with KMS key
=> Add KMS key with policy to encrypt bucket

terraform/environments/long-term-storage/call-centre-migration.tf
Adds a simple secret to be consumed by an `aws_transfer_connector` resource.
=> Call centre migration connector secret

terraform/environments/ccms-ebs/application_variables.json
CC-3015: Production EBS DB dbf04 500 -> 1000 GB.
=> CC-3015: Production EBS DB dbf04 500 -> 1000 GB.

terraform/environments/analytical-platform-compute/vpc.tf
Temporarily adding custom fields to flow log. Prod only please!
=> Adding more detail to the VPC flow log

terraform/environments/nomis/locals_test.tf
Add setup for testing T1 nomis reporting.  Already applied & tested.
=> Nomis: TM-738: add t1 weblogic test

terraform/environments/long-term-storage/call-centre-migration.tf, terraform/environments/long-term-storage/data.tf
* Creates an AWS Transfer Connector that will be used to retrieve files from the remote party and load them into S3
=> Create call centre sftp connector for testing

terraform/environments/digital-prison-reporting/application_variables.json
- Add dps-basm to the list of dps_domains
- This will create a secret manager secret and a glue connection for dps-basm
=> DPR2-1445: Add BASM service secrets and glue connections

terraform/environments/ppud/iam.tf, terraform/environments/ppud/lambda_scripts/send_cpu_graph_prod.py
Updates to IAM permissions and lambda function python script.
=> Update 061224 3

terraform/environments/oas/application_variables.json, terraform/environments/oas/ec2.tf
=> [TM-805] OAS: added 3443 egress

terraform/environments/oasys/locals_test.tf
=> oasys: increase swap on t2 DB

terraform/environments/oasys-national-reporting/locals_test.tf
- redeploy t2-onr-bods-1
- includes t2-onr-bods-2
- single_az fsx share
=> re-deploy t2-onr-bods-1

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/locals_test.tf
- deploy single_az fsx-windows share to onr-preprod
- put multi_az fsx-windows share commented out in production
=> deploy fsx-windows share to preprod

terraform/environments/oasys/locals_production.tf
=> oasys db b decrease ebs specs

terraform/environments/electronic-monitoring-data/lambdas_iam.tf, terraform/environments/electronic-monitoring-data/lambdas_main.tf
Introduce an environment variable to specify the destination bucket name in the Lambda module configuration.
=> Add environment variable for destination bucket in Lambda module

terraform/environments/oasys-national-reporting/locals_preproduction.tf
- have added delegated control to computer objects in the relevant OU so this should now work for this svc account
=> use svc_join_domain user

terraform/environments/oasys-national-reporting/locals_preproduction.tf
- broaden permissions to just do debug, I'll remove this all later
=> just give me the permissions already

terraform/environments/digital-prison-reporting/application_variables.json
This PR creates the placeholder secrets for the DPS CSIP.
=> DPR2-1436: Create dps-csip secrets

terraform/environments/oasys-national-reporting/locals_preproduction.tf
- use new svc_fsx_windows service account
- retain additional permissions for now so testing still works
=> use dedicated service account for fsx creation

terraform/environments/oasys-national-reporting/locals_preproduction.tf
=> remove onr preprod fsx-windows resource

terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_ec2_autoscaling_groups.tf
Add EC2 ASG for weblogic 12 PoC
=> TM-626: nomis weblogic 12 PoC

terraform/environments/oasys-national-reporting/locals_preproduction.tf
- have added the WriteDacl permission to 'Domain Join' group for the MODERNISATION_PLATFORM_SERVERS OU
- this should now work
=> this security group should have the correct permissions to make changes

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_production.tf, terraform/modules/fsx_windows/README.md
- remove test permissions from instance
- update comments in prod for (not yet deployed) fsx_windows file share in prod
- add link to Confluence in fsx_module ReadMe: explaining more about the AD setup required for hmpp (prod) domain
=> remove test script permissions from pp-onr-bods-1

terraform/environments/oasys-national-reporting/locals_production.tf
- create secrets for app install
=> secrets for onr prod

terraform/environments/digital-prison-reporting/application_variables.json
This domain is for testing things against our own Postgres database in Dev
=> DPR2-1213: Add secrets for dps-testing domain in Dev environment

terraform/environments/oasys/locals_production.tf
=> prod oasys db respec disks 2

terraform/environments/nomis/locals_production.tf, terraform/modules/cloudwatch_dashboard/locals_ebs_widgets.tf
Fixed metric typo for throughput widgets in cloudwatch dashboards
Add DR database dashboards for nomis
=> TM-776: throughput dashboard widget bug fix

terraform/environments/oasys/locals_production.tf
=> oasys align db disks

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
Final PR for the day on this, cleans up the test resource given we're halting on this ticket for the time being pending the Airflow spike on the same area.
=> Cleanup test resource to help keda

terraform/environments/analytical-platform-common/iam-policies.tf, terraform/environments/analytical-platform-common/iam-role.tf, terraform/environments/analytical-platform-common/kms-keys.tf
- Adds a KMS CMK for ECR
- Adds tags because I always forget this repo doesn't do it by default 🥲 
=> 🔑 Analytical Platform Common ECR KMS

terraform/environments/digital-prison-reporting/application_variables.json
This PR creates the placeholder secrets for the DPS Alerts service
=> DPR2-1437: Create placeholder secrets for DPS alerts

terraform/modules/ip_addresses/moj.tf
=> drop IP from SG to fix as max limit

terraform/environments/analytical-platform-common/iam-role.tf
- Fixes a typo of the org name 😂
=> 😬 Fix a typo in the organisation name

terraform/environments/oasys/locals_lbs.tf, terraform/environments/oasys/locals_security_groups.tf, terraform/modules/ip_addresses/moj.tf
Add additional security group as we reached the rule limit. So we can allow wifi access as requested in ask dso channel
=> oasys: TM-446: split security groups

terraform/environments/nomis-combined-reporting/locals_lbs.tf, terraform/environments/nomis-combined-reporting/locals_security_groups.tf
Split public rules over 2 SGs as we have reached rule count limit
=> nomis reporting: security group fix

terraform/environments/hmpps-oem/locals_cloudwatch_metric_alarms.tf
=> TM: hmpps-oem: fix cert expiry alarm

terraform/environments/ccms-ebs/application_variables.json
CC-3058: dbf01 IOPS 7000 -> 24000.
=> CC-3058: dbf01 IOPS 7000 -> 24000.

terraform/environments/oasys/locals_production.tf, terraform/environments/oasys/locals_test.tf, terraform/environments/oasys/main.tf
=> oasys san test

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Patching the ingestion environment in AP.
=> :wrench: Update AP Ingestion image versions

terraform/environments/corporate-staff-rostering/locals_preproduction.tf, terraform/environments/corporate-staff-rostering/locals_production.tf
- remove azure a record references
- rename preproduction cname ppiwfm-b to ppiwfm (points to -> pp-csr-db-a)
- add production cname piwfm (points to -> pd-csr-db-a)
=> remove r53 azure a records, change ppifm cname, add piwfm cname for prod

terraform/environments/tipstaff/platform_providers.tf
Bug fixed
https://github.com/integrations/terraform-provider-github/issues/2357#issuecomment-2375751262
=> Revert change to specify github provider version.

terraform/environments/hmpps-domain-services/locals_lbs.tf, terraform/environments/hmpps-domain-services/locals_security_groups.tf
- split up security groups 'cause trusted_moj_digital_staff_public will have too many rules as it's been expanded
=> fix security group due to limits

terraform/environments/delius-core/files/user_outbound_table_mapping.json
=> Do not remove the STAFF_ID column

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
New module, not sure if there is any other changes required in this repo. Replicating that as for fms, due to how similar they are
=> add new module for mdss

terraform/environments/oasys-national-reporting/locals_production.tf
- onr prod windows share (multi-az)
- add missing secrets buckets for DB's
=> add multi-az fsx share and db secrets bucket

terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_production.tf, terraform/environments/oasys/locals_production.tf, terraform/modules/baseline_presets/cloudwatch.tf, terraform/modules/baseline_presets/variables.tf
Updating cloudwatch agent config in line with MOJ security guidelines.
=> tm-867: cloudwatch-config

terraform/environments/oasys-national-reporting/locals_production.tf
- add missing iam policy for prod to get secrets from secrets manager
=> need iam policy for instance

terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/hmpps-domain-services/locals_production.tf, terraform/environments/hmpps-domain-services/locals_test.tf
=> destroy ahead of manual domain removal

terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/hmpps-domain-services/locals_production.tf, terraform/environments/hmpps-domain-services/locals_test.tf
- re-deploy nart client jumpservers
=> and put them back

terraform/environments/oasys-national-reporting/locals_test.tf
- add a record and lb for t2-onr-bods-1 back in
=> add t2 lb back in

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_iam_role/main.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_iam_role/outputs.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_iam_role/versions.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/variables.tf
Permissions added:
- lakeformation:getDataAccess
Module added to module
- share_dbs_with_roles
=> added the complained about error from yesterday's airflow logs

terraform/environments/oasys-national-reporting/locals_production.tf
=> :construction: initial commit to deploy pd-onr-bods-1 instance

terraform/environments/corporate-staff-rostering/templates/cloud_watch_windows.json
Remediating custom cloudwatch agent settings files.
=> tm-867: cloudwatch-agent-settings

terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/locals_security_groups.tf
- fix rdp security group access to allow azure gateway
=> :wrench: fix bods rdp access to allow azure gateway

terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/templates/user-data-onr-bods-pwsh.yaml.tftpl
- deploy pd-onr-bods-1 again
- change volume initialization code in template
=> deploy pd-onr-bods-1 with different volume initialization approach

terraform/environments/oasys-national-reporting/locals_production.tf
- remove pd-onr-bods-1 
drive initialization fully works now though
=> :rewind: remove pd-onr-bods-1

terraform/environments/oasys-national-reporting/locals_production.tf
=> :rocket: deploy pd-onr-bods-2

terraform/environments/cica-tariff/bastion_linux.json
Add public key for access to tariff bastion.
=> 🔐 Add new public key for bastion access

terraform/environments/analytical-platform-compute/iam-policies.tf, terraform/environments/analytical-platform-compute/iam-roles.tf, terraform/environments/analytical-platform-compute/s3-buckets.tf
- Tags things
- Adds policy and role
=> 🎟️ Add IAM policy and role for interacting with MWAA KMS and S3

terraform/modules/ip_addresses/moj.tf
On request from Network Team (Tom Lee) - increase IP range for internal global protect traffic
=> TM: extend global protect internal range

terraform/environments/corporate-staff-rostering/templates/cloud_watch_windows.json
Reverting the csr cloudwatch config to remove invalid filters.
=> tm-867: csr cloudwatch-config

terraform/environments/analytical-platform-common/iam-policies.tf
- Hopefully fixes https://github.com/moj-analytical-services/analytical-platform-airflow-python-example/actions/runs/12931251398/job/36064671126#step:9:35
=> 🛂 Add `ecr:DescribeRepositories` to ECR access role

terraform/environments/planetfm/locals_production.tf
=> TM: planetfm: increase T drive to 250 on pd-cafm-db-b

terraform/modules/baseline_presets/backups.tf
Adding vss equivalent policies.
=> TM-713: revising-backup-policies

terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Improve the database grant logic to include live feed databases and handle suffixes appropriately. This change ensures that live feed databases are granted access based on the environment configuration.
=> Enhance database grant logic for live feed databases

terraform/environments/oasys-national-reporting/locals_ec2_autoscaling_groups.tf, terraform/environments/oasys-national-reporting/locals_ec2_instances.tf, terraform/environments/oasys-national-reporting/locals_lbs.tf, terraform/environments/oasys-national-reporting/locals_security_groups.tf, terraform/environments/oasys-national-reporting/locals_test.tf
ONR T2 infra build - already applied
=> TM-864: onr: build t2 bip

terraform/environments/analytical-platform-common/ecr-repositories.tf, terraform/environments/analytical-platform-common/iam-policies.tf, terraform/environments/analytical-platform-common/iam-role.tf, terraform/environments/analytical-platform-common/kms-keys.tf, terraform/environments/analytical-platform-common/s3-buckets.tf
- Creates resources for Terraform state store
- KMS key
- S3 bucket
- IAM policy
- IAM role
- Bumps module versions
=> 🪣 Prepare Analytical Platform Terraform state store in Common account

terraform/environments/analytical-platform-common/s3-buckets.tf
=> 🛟 Add versioning to Terraform state bucket

terraform/environments/planetfm/locals_production.tf
Moving 1 instance to VSS enabled backup policy for testing.
=> tm-925: testing-vss-tag

terraform/environments/laa-stabilisation-cdc-poc/bastion_linux.json
Grant access to CDC POC Environment
=> CC-3109-CDC-POC-access

terraform/environments/analytical-platform-common/iam-role.tf
- Removes MFA requirement, we assume this with other roles
=> 🚑 Remove MFA requirements from service role

terraform/environments/oasys-national-reporting/locals_security_groups.tf, terraform/environments/oasys-national-reporting/locals_test.tf
Fix couple of typos with ONR T2 security groups
=> TM: onr: security group fixes

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf, terraform/environments/electronic-monitoring-data/imports.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf, terraform/environments/electronic-monitoring-data/modules/lakeformation_database_share/main.tf, terraform/environments/electronic-monitoring-data/share_analytical_platform.tf, terraform/environments/electronic-monitoring-data/share_data_catalogue_iam.tf
Adjust IAM role settings to accommodate the development environment by modifying resource counts and suffixes accordingly.
=> Update IAM role configurations for development environment

terraform/environments/ccms-ebs/application_variables.json
CC-3116: Added 250GB to the dbf04 volume in Production.
=> CC-3116: Added 250GB to the dbf04 volume in Production.

terraform/environments/laa-stabilisation-cdc-poc/bastion_linux.json
=> CC-3109-CWA-CDC-POC-access

terraform/environments/planetfm/locals_production.tf
Reverting backup tags post test.
=> tm-925: reverting-tag

terraform/environments/hmpps-domain-services/locals_ec2_instances.tf, terraform/environments/hmpps-domain-services/locals_preproduction.tf, terraform/environments/planetfm/locals_production.tf
Assigning IAM policy and revising tags to enable backup policies.
=> TM-925: testing-rdgw-vss

terraform/environments/observability-platform/environment-configurations.tf
- Onboards `analytical-platform-common-production`
=> 🔭 Onboard Analytical Platform's Common account

terraform/environments/hmpps-domain-services/locals_preproduction.tf
Revising backup tags to avoid duplicate backups.
=> tm-925: revising-backup-tag

terraform/environments/ppud/iam.tf, terraform/environments/ppud/lambda.tf
Update to lambda functions to use new matplotlib lambda layer.
=> Update 310125 6

terraform/environments/ppud/iam.tf, terraform/environments/ppud/lambda.tf, terraform/environments/ppud/s3.tf
Deletion of unused S3 bucket and lambda layer and update to IAM policies.
=> Update 030225 4

terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/kubernetes-cluster-role-bindings.tf, terraform/environments/analytical-platform-compute/kubernetes-cluster-roles.tf, terraform/environments/analytical-platform-compute/kubernetes-role-bindings.tf, terraform/environments/analytical-platform-compute/kubernetes-roles.tf, terraform/environments/analytical-platform-compute/kubernetes-secret-stores.tf, terraform/environments/analytical-platform-compute/kubernetes-service-accounts.tf
- Adds required permissions for Airflow repo to create External secrets
=> 🧑‍🔬 Cross account ESO

terraform/environments/laa-stabilisation-cdc-poc/bastion_linux.json
Add key to bastion host to access CDC-Poc env
=> 	modified:   bastion_linux.json

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
SSCL have requested the use of our ingestion service to onboard their data into Analytical Platform in advance of switching suppliers.
This PR onboards them to the service.
=> Onboarding SSCL SFTP Information

terraform/environments/nomis-combined-reporting/locals_production.tf
Remove testing ASGs
Add first production EC2
=> TM-944: ncr: add primary CMS

terraform/environments/nomis-combined-reporting/locals_production.tf
Add prod CMS, App, Webadmin and LB config
=> TM-944: ncr: prod build v2

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
- Is part of https://github.com/ministryofjustice/analytical-platform/issues/6650
=> 📌 Update Actions Runners

terraform/environments/nomis-combined-reporting/locals_lbs.tf, terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf
Add first prod web server, plus harmless fix typo in preprod.
=> TM-944: ncr: prod build v3

terraform/environments/analytical-platform-ingestion/dms/kms-keys.tf, terraform/environments/analytical-platform-ingestion/dms/s3.tf
Further to [this](https://github.com/ministryofjustice/modernisation-platform-environments/pull/9590) PR.
=> :wrench: Add `count` to avoid building in development

terraform/environments/panda-cyber-appsec-lab/ec2.tf
First try to allow the local vpn access for the defectdojo services.
=> Updated security group to allow VPN access

terraform/environments/analytical-platform-ingestion/dms/s3.tf
=> 🪣  Correct bucket name

terraform/environments/analytical-platform-ingestion/dms/iam-policies.tf
This PR updates the key used in the IAM policy for the destination bucket.
=> 🔑 Update IAM Policy Destination Bucket Key

terraform/environments/analytical-platform-ingestion/dms/iam-policies.tf, terraform/environments/analytical-platform-ingestion/dms/s3.tf
- Correct Key
- Remove `*` permissions
=> :wrench: Correct Key in Replication Policy Destination

terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
The EARs and SARs work has required 2 new folders to be added in CaDT. Adding these dbs to the list of dbs we share with the AP
=> Add new dbs for ears and sars

terraform/environments/electronic-monitoring-data/metric_alarms.tf
Introduce an SNS topic for monitoring the FMS land bucket count along with the necessary alarm configuration.
=> Add SNS topic and alarm configuration for FMS land bucket count

terraform/environments/oasys-national-reporting/locals_test.tf
- these were missing/deferred till we got the issue with the AWS provider out of the way
=> alarms for onr bods T2

terraform/environments/ccms-ebs/ccms-s3.tf
CC-3154: Extended 'logging_s3_policy'.
=> CC-3154: Extended 'logging_s3_policy'.

terraform/environments/digital-prison-reporting/application_variables.json
This PR creates the placeholder secrets for the calculate-release-dates DPS service.
=> DPR2-1777: Create placeholder secrets for calculate-release-dates

terraform/environments/delius-core/locals_preproduction.tf, terraform/environments/delius-core/locals_production.tf, terraform/environments/delius-core/locals_stage.tf, terraform/environments/delius-core/locals_test.tf
PR to add missing Observer terraform variables to resolve terraform pipeline errors
=> Add missing observer vars

terraform/environments/digital-prison-reporting/main.tf
- Adds a temporary Glue job to the dev environment only as part of demoing the Data Quality spike
=> DPR2-1448: Data Quality Spike job for demo

terraform/environments/analytical-platform-ingestion/environment-configuration.tf, terraform/environments/analytical-platform-ingestion/iam-policies.tf, terraform/environments/analytical-platform-ingestion/iam-roles.tf, terraform/environments/analytical-platform-ingestion/kms-keys.tf, terraform/environments/analytical-platform-ingestion/s3.tf
This PR relates to [this](https://github.com/ministryofjustice/analytical-platform/issues/5175) piece of work and is a work in progress.
Since I have attempted to make the module `datasync_opg_bucket` serve both development and production this has necessitated making changes to how this bucket is called in files I never intended on touching e.g. `datasync-locations.tf` and `datasync-tasks.tf`.
=> 🪣  DataSync Ingestion configuration

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Updates from dummy keys to actual keys.
Follows on from [this PR](https://github.com/ministryofjustice/modernisation-platform-environments/pull/9641).
=> 🔑 Update KMS Keys

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Further to [this](https://github.com/ministryofjustice/modernisation-platform-environments/pull/9658) PR. Minor correction to destination bucket name.
=> :wrench: Update Target Bucket

terraform/environments/laa-stabilisation-cdc-poc/cwa-poc2/alb.tf, terraform/environments/laa-stabilisation-cdc-poc/cwa-poc2/ec2_app_servers.tf, terraform/environments/laa-stabilisation-cdc-poc/cwa-poc2/ec2_concurrent_manager.tf, terraform/environments/laa-stabilisation-cdc-poc/cwa-poc2/ec2_database.tf, terraform/environments/laa-stabilisation-cdc-poc/cwa-poc2/efs.tf, terraform/environments/laa-stabilisation-cdc-poc/cwa-poc2/locals.tf, terraform/environments/laa-stabilisation-cdc-poc/cwa-poc2/route53.tf, terraform/environments/laa-stabilisation-cdc-poc/cwa-poc2/variables.tf, terraform/environments/laa-stabilisation-cdc-poc/main.tf
***Jira:*** [TM-990](https://dsdmoj.atlassian.net/browse/TM-990)
[TM-990]: https://dsdmoj.atlassian.net/browse/TM-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TM-990] added fixes as per requests

terraform/environments/genesys-call-centre-data/ap_airflow.tf
airflow authentication secrets manager setup
=> airflow authentication secrets manager setup

terraform/environments/hmpps-domain-services/locals_ec2_instances.tf
enable-alarms-on-hmpps-domain-services
=> TM-757: enable-alarms-on-hmpps-domain-services

terraform/environments/analytical-platform-compute/iam-policies.tf
Fixes https://github.com/ministryofjustice/analytical-platform/issues/6944
- Updates SES permissions to allow sending to all identities
See below screenshot, its working now
=> 📤 Update SES actions

terraform/environments/laa-stabilisation-cdc-poc/database.tf
Implementing keepalive solution for CWA CDC POC, added to userdata, but will be ignored unless the database is rebuilt
=> Cdc poc keepalive

terraform/environments/hmpps-domain-services/locals_security_groups.tf, terraform/environments/hmpps-domain-services/locals_test.tf
- add sg rules for RDS setup to work between jumpserver(s) i.e. NartClient machines and RDS instances
=> deploy test instances again

terraform/environments/ppud/lambda.tf
Creation of 2 cloudwatch log groups for lambda function logging with a retention period of 30 days.
=> Update 240225 2

terraform/environments/electronic-monitoring-data/s3.tf
Introduce an IAM policy document and an S3 bucket policy to grant the CADT runner access to the necessary S3 resources.
=> Add IAM policy and S3 bucket policy for CADT runner access

terraform/environments/oasys-national-reporting/locals_preproduction.tf
=> TM-992: onr: fix preprod EFS security group

terraform/environments/oasys-national-reporting/locals_preproduction.tf
=> TM-992: onr preprod web server

terraform/environments/oasys-national-reporting/locals_preproduction.tf
=> TM-992: onr fix preprod URL

.devcontainer/README.md, scripts/member-local-plan.sh
- Updates dev container README
- Updates path to script
- Updates running examples
- Updates `scripts/member-local-plan.sh` to understand components
=> 📝 Update member local planning script and dev container README

terraform/environments/analytical-platform-ingestion/data.tf, terraform/environments/analytical-platform-ingestion/datasync-tasks.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/7008
- Switches to using a populated secret 
=> 🔀 Switch to secret for DataSync includes

terraform/environments/observability-platform/environment-configurations.tf, terraform/environments/observability-platform/modules/grafana/athena-source/main.tf, terraform/environments/observability-platform/modules/grafana/athena-source/variables.tf, terraform/environments/observability-platform/modules/observability-platform/tenant-configuration/main.tf, terraform/environments/observability-platform/modules/observability-platform/tenant-configuration/variables.tf
- Add athena output location to OP configuration
=> configure athena output location

terraform/environments/cica-tariff/bastion_linux.json
Add new public key for bastion access.
=> 🔐 Add new public key for access to bastion

terraform/environments/ppud/data.tf, terraform/environments/ppud/iam.tf, terraform/environments/ppud/s3.tf
Update to bucket iam and replication policy.
=> Update 030325 12

terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf
Add oracle db connected check for the AWS nomis combined reporting databases
=> ncr: add monitoring for bip DBs

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
- Adding dev SFTP user
- Updating prod user IP
=> Adding dev OPG OCR SFTP user

terraform/environments/oasys/README.md
Amended the README.md file to add the missing bits needed for the official production release. Note this was done some time ago.
=> Adding changes to oasys README.md

terraform/environments/digital-prison-reporting/event_bus.tf, terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/modules/eventbridge/outputs.tf
Add policy to put events on new custom event bus
=> [DPR2-1715] add policy for custom event bridge

terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
adding an additional db to store testing results for dbt tests on live feed tables
=> Added "testing" db to live_feed_dbs to store testing results in this db for various live feed tables

terraform/environments/analytical-platform-ingestion/datasync-locations.tf
- Updates `server_hostname` to the new SMB host
=> 🥂 Update SMB hostname

terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_production.tf, terraform/environments/nomis/locals_test.tf
=> TM-1042: migrate to new nomis cert

terraform/environments/ccms-ebs-upgrade/ec2-oracle_ebs_conc-sg.tf
CC-3244: Allowed traffic from EBS Apps to Concurrent Tier on port 1626.
=> CC-3244: Allowed traffic from EBS Apps to Concurrent Tier on port 1626.

terraform/environments/electronic-monitoring-data/metric_alarms.tf
Adjust the threshold and unit for the metric alarm to improve monitoring accuracy.
=> Update metric alarm threshold and unit in electronic monitoring data

terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_preproduction.tf, terraform/environments/nomis/locals_production.tf, terraform/environments/nomis/locals_test.tf
remove old nomis cert. I've checked LB and everything using the new one
=> TM-1042: nomis: remove old cert

terraform/environments/electronic-monitoring-data/dms_variables.tf, terraform/environments/electronic-monitoring-data/lake_formation_cloud_platform.tf
Enhance Lake Formation setup to include tables for the test environment and enable data filtering modules for both including and excluding special records.
=> Update Lake Formation configuration for test environment and data filtering

terraform/environments/cica-tariff/locals.tf, terraform/environments/cica-tariff/tariff_ec2_app_sg.tf
Add RAS NATted IP range to Tariff SG ingress
=> 🛂 Add NAT range to security group ingress

terraform/environments/electronic-monitoring-data/metric_alarms.tf
Introduce a KMS key for encrypting metric alarms and update the associated SNS topics to utilize this key for enhanced security.
=> Add KMS key for metric alarms and update SNS topics to use it

terraform/environments/observability-platform/environment-configurations.tf
Creating observability platform configuration as part of 10% developement time
See unit tests below.
=> observability platform configuration

terraform/environments/observability-platform/environment-configurations.tf
Onboard cooker into production and enable cloudwatch
=> Obs-Plat Onboard Cooker

terraform/environments/ccms-ebs-upgrade/observability_platform.tf, terraform/environments/ccms-ebs/observability_platform.tf
Onboard Observability Platform tenant for `CCMS-EBS` and `CCMS-EBS-UPGRADE` as per https://user-guide.observability-platform.service.justice.gov.uk/getting-started/onboarding.html
=> CCMS-EBS Onboard Observability Platform

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/locals_test.tf
Backup missing in other environments. Added prod EFS.
=> TM-1064: add efs and enable efs backup

terraform/environments/oasys/README.md
This is the latest version of the PR with no additional deletes in place.
It has the comments form 9842 in there and should be acceptable.
=> Latest version of the PR

.github/workflows/generate-dependabot-file.yml
Ref ticket https://github.com/ministryofjustice/modernisation-platform/issues/8757 and based on https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/workflows/generate-dependabot-file.yml
=> Adds signed commits for generate-dependabot workflow.

terraform/environments/oasys-national-reporting/locals_production.tf
Add the first EC2 to ONR prod build
=> TM-1064: onr: add pd-onr-cms-1

terraform/environments/oasys-national-reporting/locals_production.tf
Add prod web servers + LB config
=> TM-1064: onr: add prod web servers

terraform/environments/ppud/iam.tf, terraform/environments/ppud/s3.tf
Creation of S3 bucket for cross account replication to MoJ MPC service.
=> Update 110325 2

terraform/environments/electronic-monitoring-data/locals.tf, terraform/environments/electronic-monitoring-data/transfer_server_accounts.tf
Introduce configuration for SCRAM user accounts, including SSH keys and CIDR settings, to enhance access management in the electronic monitoring environment.
=> Add SCRAM user account configuration and SSH keys

terraform/environments/electronic-monitoring-data/lake_formation.tf
Adding initial tags for testing application via dbt.
=> Create tag resources

terraform/environments/hmpps-domain-services/locals_ec2_instances.tf, terraform/environments/hmpps-domain-services/patch.tf
Revising AWS Patch Manager in hmpps-domain-services
=> TM-1056: aws-patch-manager-hmpps-domain-service-preprod

terraform/environments/observability-platform/environment-configurations.tf
After discussion with Mac and Jacob
=> CCMS Athena Removal

terraform/environments/electronic-monitoring-data/application_variables.json, terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Enhance Lake Formation admin settings by adding assume account roles to the list of administrators.
=> Update Lake Formation admin settings to include assume account roles

terraform/environments/electronic-monitoring-data/locals.tf, terraform/environments/electronic-monitoring-data/transfer_server_accounts.tf
Revise the SFTP account configuration to utilize SCRAM keys and update CIDR ranges accordingly.
=> Update SFTP account configuration for SCRAM keys and CIDR ranges

terraform/environments/electronic-monitoring-data/lake_formation.tf
Adding lf permission resources to cross role.
=> Add LF permission to EM cross account data role

terraform/environments/analytical-platform-compute/environment-configuration.tf
Adding new domains that have not replicated from database-access repo.
To do: Fix where these are created.
=> Adding new lftags

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/secrets.tf, terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/data-catalogue/values.yml.tftpl
Fixes https://github.com/ministryofjustice/analytical-platform/issues/7075
- Adds a self-hosted runner for https://github.com/ministryofjustice/data-catalogue
=> 🏃 Add self-hosted runner for Data Catalogue

terraform/environments/electronic-monitoring-data/lake_formation.tf, terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Adding LFTag permissions by creating a new policy doc, policy and role policy attachement.
=> Adding LFTag access to data IAM role

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
Refactor the IAM policy document for Airflow to improve clarity and structure. Introduce a new module for loading SCRAM alcohol monitoring data, enhancing data management capabilities.
=> Refactor IAM policy for Airflow and add SCRAM alcohol monitoring module

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_test.tf, terraform/modules/baseline/fsx.tf, terraform/modules/baseline/variables.tf, terraform/modules/fsx_windows/main.tf, terraform/modules/fsx_windows/variables.tf
Testing out FSX aliases option in both test and preprod. Applied OK to test already.
=> TM-946: add fsx aliases option

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/modules/baseline/bastion_linux.tf, terraform/modules/fsx_windows/versions.tf
Fix checkov errors
Fix bastion error
Fix ONR typo
=> TM-946: baseline terraform fixes

terraform/environments/observability-platform/environment-configurations.tf
Moving to the development grafana.
=> Cooker to development grafana

terraform/environments/nomis-combined-reporting/locals_production.tf
Add missing DR secrets so DBAs can rebuild it
=> TM: ncr: add database secrets for DR

terraform/environments/dacp/ecs.tf, terraform/environments/dacp/ecs_scaling.tf, terraform/environments/dacp/monitor-alert.tf
Refactor terraform interpolation
Add some checkov ignores
=> DACP: Add scaling for ecs (preprod test only)

terraform/environments/analytical-platform-compute/helm-charts-actions-runners.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/7259
- Adds runners (on-demand and spot) for CaDT Sandbox
=> 🏃 CaDT Sanbox Runners

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
This request adds a CGI/CPS user information and IP ranges to the production transfer services setup.
The remainder will be configured in AP.
=> Onboarding cgi to transfer services

terraform/environments/ccms-ebs-upgrade/application_variables.json, terraform/environments/ccms-ebs-upgrade/sns.tf, terraform/environments/ccms-ebs/application_variables.json, terraform/environments/ccms-ebs/ccms-sns.tf
CC-1947: Fixes for recurring deletions of topic subscriptions in CCMS.
=> CC-1947: Fixes for recurring deletions of topic subscriptions in CCMS.

terraform/environments/dacp/load_balancer.tf, terraform/environments/dacp/monitor-alert.tf, terraform/environments/dacp/rds.tf, terraform/environments/dacp/secrets.tf, terraform/environments/dacp/waf.tf
=> DACP: Fine tune ram and cpu utilisation alarms for ecs scaling

terraform/environments/ccms-ebs-upgrade/ec2-oracle_accessgate.tf, terraform/environments/ccms-ebs-upgrade/ec2-oracle_ebs_apps.tf, terraform/environments/ccms-ebs-upgrade/ec2-oracle_ebs_conc.tf, terraform/environments/ccms-ebs-upgrade/ec2-oracle_ebs_db.tf, terraform/environments/ccms-ebs-upgrade/ec2-oracle_webgate.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_accessgate.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_ebs_apps.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_ebs_db.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_webgate.tf, terraform/environments/ccms-ebs/ccms-sns.tf
CC-3320: cpu_core_count -> cpu_options.
=> CC-3320: cpu_core_count -> cpu_options.

terraform/environments/ccms-ebs/ccms-ec2-oracle_ebs_apps-nlb.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_webgate-nlb.tf
=> CC-3323: vpc -> domain.

terraform/environments/data-platform-apps-and-tools/helm-charts-system.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/7330
- Updates DPAT ingress-nginx to 4.12.1
=> 📌 Update DPAT ingress-nginx to 4.12.1

terraform/environments/hmpps-oem/locals_cloudwatch_metric_alarms.tf
HPA has been migrated so can remove this check
=> TM: hmpps: remove HPA alarm

terraform/environments/nomis/locals_security_groups.tf
Allow nomis node manager and web access from new jump servers in mod platform
=> TM-1114: nomis: allow web access from mp jump servers

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
This PR satisfies [this](https://github.com/ministryofjustice/analytical-platform/issues/7070) request. 
Adds Glenn Barber to Ingestion.
=> 🤝  Add Glenn Barber to AP Ingestion Service

terraform/environments/ccms-ebs-upgrade/ec2-oracle_accessgate.tf, terraform/environments/ccms-ebs-upgrade/ec2-oracle_ebs_apps.tf, terraform/environments/ccms-ebs-upgrade/ec2-oracle_webgate.tf, terraform/environments/ccms-ebs-upgrade/efs.tf, terraform/environments/ccms-ebs-upgrade/sandbox/ec2-oracle_ebs_apps.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_accessgate.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_ebs_apps.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_webgate.tf
=> CC-3346: Fixed AVD-AWS-0028.

terraform/environments/ccms-ebs-upgrade/ec2-oracle_ebs_apps-alb.tf, terraform/environments/ccms-ebs-upgrade/ec2-oracle_webgate-alb.tf, terraform/environments/ccms-ebs-upgrade/sandbox/ec2-oracle_ebs_apps-alb.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_ebs_apps-alb.tf, terraform/environments/ccms-ebs/ccms-ec2-oracle_webgate-alb.tf
=> CC-3346: Fixed AVD-AWS-0052.

terraform/environments/operations-engineering/iam.tf, terraform/environments/operations-engineering/kms.tf, terraform/environments/operations-engineering/s3.tf
Set up backend for tf statefile for auth0 infra
=> Add backend for auth0 infra

terraform/environments/ccms-ebs-upgrade/s3.tf, terraform/environments/ccms-ebs-upgrade/sandbox/s3.tf, terraform/environments/ccms-ebs/ccms-s3.tf
=> CC-3346: Fixed AVD-AWS-0086.

terraform/environments/ppud/iam.tf, terraform/environments/ppud/s3.tf
Creation of new S3 bucket for MPC report replication and updating of S3 bucket policy ARNs.
=> Update 070425 5

terraform/environments/nomis/locals_cloudwatch_metric_alarms.tf, terraform/modules/baseline_presets/cloudwatch_dashboards.tf, terraform/modules/baseline_presets/cloudwatch_metric_alarms.tf
Tweak iowait alarm thresholds to ensure we alarm quicker in production
=> TM-1172: improve iowait alarms

terraform/environments/analytical-platform-ingestion/modules/dms/.terraform-docs.yaml, terraform/environments/analytical-platform-ingestion/modules/dms/DB_SETUP.md, terraform/environments/analytical-platform-ingestion/modules/dms/README.md, terraform/environments/analytical-platform-ingestion/modules/dms/data_buckets.tf, terraform/environments/analytical-platform-ingestion/modules/dms/default_task_settings.json, terraform/environments/analytical-platform-ingestion/modules/dms/endpoints.tf, terraform/environments/analytical-platform-ingestion/modules/dms/examples/example-readme/main.tf, terraform/environments/analytical-platform-ingestion/modules/dms/examples/example-readme/mappings.json, terraform/environments/analytical-platform-ingestion/modules/dms/iam-roles.tf, terraform/environments/analytical-platform-ingestion/modules/dms/lambda-functions/metadata_generator/main.py, terraform/environments/analytical-platform-ingestion/modules/dms/lambda-functions/metadata_generator/requirements.txt, terraform/environments/analytical-platform-ingestion/modules/dms/lambda-functions/validation/main.py, terraform/environments/analytical-platform-ingestion/modules/dms/lambda-functions/validation/requirements.txt, terraform/environments/analytical-platform-ingestion/modules/dms/metadata_generator.tf, terraform/environments/analytical-platform-ingestion/modules/dms/replication_instance.tf, terraform/environments/analytical-platform-ingestion/modules/dms/replication_task.tf, terraform/environments/analytical-platform-ingestion/modules/dms/secrets.tf, terraform/environments/analytical-platform-ingestion/modules/dms/terraform.tf, terraform/environments/analytical-platform-ingestion/modules/dms/validation.tf, terraform/environments/analytical-platform-ingestion/modules/dms/variables.tf
At time of writing head commit on this branch was 507b364a321a53fcb80b6740a86f9ecd6a8ed75a but they are pulling with rebase so that may change
Pull request is [here](https://github.com/ministryofjustice/analytical-platform/pull/6625)
=> Commit verbatim copy of DMS module from ministryofjustice/analytical-platform repo terraform-dms-module branch

terraform/environments/digital-prison-reporting/athena_federated_queries.tf, terraform/environments/digital-prison-reporting/data.tf, terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/secrets.tf
- Sets up federated queries for ONR via Athena
- Only created in Dev and Test environments
=> ONR federated query connector and Athena data catalog

terraform/environments/ccms-ebs-upgrade/s3.tf, terraform/environments/ccms-ebs-upgrade/sandbox/s3.tf, terraform/environments/ccms-ebs/ccms-s3.tf
=> CC-3346: Fixed AVD-AWS-0091.

terraform/environments/ccms-ebs-upgrade/s3.tf, terraform/environments/ccms-ebs-upgrade/sandbox/s3.tf, terraform/environments/ccms-ebs/ccms-s3.tf
=> CC-3346: Fixed CKV_TF_1.

terraform/environments/ccms-ebs-upgrade/s3.tf, terraform/environments/ccms-ebs-upgrade/sandbox/s3.tf, terraform/environments/ccms-ebs/ccms-s3.tf
=> CC-3346: Fixed CKV_AWS_21.

terraform/environments/ccms-ebs/ccms-lambda-certificate-monitor.tf, terraform/environments/ccms-ebs/ccms-lambda-monitor-payment-load.tf, terraform/environments/ccms-ebs/ccms-lambda.tf
=> CC-3346: Fixed CKV_AWS_50.

terraform/environments/laa-stabilisation-cdc-poc/bastion_linux.json
Added Michael Keane and Jack Liggett to the SSH users
=> Added Michael Keane and Jack Liggett

terraform/environments/analytical-platform-compute/sagemaker-probation-search.tf
reverting back to the original model now testing is done.
=> revert sagemaker-probation-search.tf

terraform/environments/analytical-platform-compute/environment-configuration.tf
=> 👪 backport LFTag

terraform/environments/delius-core/modules/helpers/efs/main.tf, terraform/environments/delius-core/patch_manager.tf
Add an egress rule for efs datasync
=> Add egress rule for efs datasync

terraform/environments/analytical-platform-compute/environment-configuration.tf
- Adds `cjs_cross_dataset` and `sentence_offence`
- Alphabetises the list 👼  
=> 🏷️ Backport LFTags

terraform/environments/electronic-monitoring-data/modules/lakeformation_database_share/main.tf, terraform/environments/electronic-monitoring-data/share_analytical_platform.tf
Add data cells permissions to create-a-derived-table runner role
=> EM: add data cells filter permissions

terraform/environments/hmpps-domain-services/locals_preproduction.tf
=> revert secrets build

terraform/modules/baseline/bastion_linux.tf
Amended the module so that it will use 4.4.2 rather than 4.4.1.
It is to amend some code spotted a while ago by Dominic Robinson.
=> Change module bastion_linux.tf to 4.4.2 at the end rather than 4.4.1

terraform/environments/analytical-platform-compute/kms-keys.tf, terraform/environments/analytical-platform-compute/kubernetes-external-secrets.tf, terraform/environments/analytical-platform-compute/kubernetes-namespaces.tf, terraform/environments/analytical-platform-compute/kubernetes-secrets.tf, terraform/environments/analytical-platform-compute/random.tf, terraform/environments/analytical-platform-compute/rds.tf
Add resources for the Dashboard Service
- Namespace
- RDS
- Secrets for RDS
=> Add namespace, kubernetes-external-secret for Dashboard Service

terraform/environments/analytical-platform-common/observability.tf, terraform/environments/analytical-platform-compute/observability.tf, terraform/environments/analytical-platform-ingestion/observability.tf
- Remove defaults
- Add to ingestion
- Bump to 2.0.0
=> 🔭 Align Analytical Platform Observability

.github/workflows/analytical-platform-ingestion.yml
- Updates `.github/workflows/analytical-platform-ingestion.yml` to match `.github/workflows/analytical-platform-compute.yml` to hopefully fix https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/14623365103
=> ♻️ Update Ingestion workflow to match Compute

terraform/environments/analytical-platform-ingestion/dms/data.tf
This pull request has been created to trigger workflows after the merge of [this](https://github.com/ministryofjustice/modernisation-platform-environments/pull/10324) pull request.
=> 🎨  Format `data.tf` to trigger workflow

scripts/generate-dependabot-file.sh
Increasing :dependabot: limit as still maxing out
=> Increase Dependabot Limit

terraform/environments/delius-core/modules/delius_environment/alb_frontend.tf
Disable mobile access to delius
=> Disable mobile access

terraform/environments/nomis/locals_production.tf
Use prod-nomis-web-a instance to test nomis reporting link
=> TM-1227 - allow testing of prod AWS nomis reporting via nomis

terraform/environments/analytical-platform-compute/helm-charts-dashboard-service.tf
Deploy dashboard service to production environment
=> Attempt to deploy dashboard service in production

terraform/environments/digital-prison-reporting/athena_federated_queries.tf, terraform/environments/digital-prison-reporting/data.tf, terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/secrets.tf
- Enabled in Dev and Test
- Initially we will only have the test connectivity and credentials
=> Federated queries for nDelius

terraform/environments/nomis-combined-reporting/locals_production.tf
NART ready for the additional web servers now
=> TM-1179: ncr: add additional prod web servers

terraform/environments/ppud/lambda.tf, terraform/environments/ppud/platform_secrets.tf, terraform/environments/ppud/s3.tf
Disabling lambda code signing and replacing account ID with ssm parameter store value.
=> Update 300425 3

terraform/environments/electronic-monitoring-data/locals.tf, terraform/environments/electronic-monitoring-data/transfer_server_accounts.tf
New SFTP server for g4s to send us lcm data
=> EM: add new sftp server for lcm data

terraform/environments/nomis-combined-reporting/locals_production.tf
Web servers are built, add them to LB
=> TM-1179: ncr: add new webservers to LB

terraform/environments/ppud/s3.tf
Updates to S3 Bucket to use dynamic ARNs, enabled logging and blocked non SSL access.
=> Update 010525 5

terraform/environments/nomis-combined-reporting/locals_preproduction.tf, terraform/environments/nomis-combined-reporting/locals_production.tf, terraform/environments/nomis-combined-reporting/locals_test.tf
Fix a couple of typos and correct production message
=> TM-1229: fix nomis reporting maintenance messages

terraform/environments/nomis/locals_development.tf
=> TM-1238: nomis: build new oracle11g DB for testing in dev

terraform/environments/digital-prison-reporting/domain_builder.tf, terraform/environments/digital-prison-reporting/kms.tf, terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/main.tf, terraform/environments/digital-prison-reporting/modules/domains/ingestion-jobs/glue.tf, terraform/environments/digital-prison-reporting/modules/domains/reconciliation-job/main.tf, terraform/environments/digital-prison-reporting/modules/dynamo_tables/main.tf, terraform/environments/digital-prison-reporting/modules/dynamo_tables/versions.tf, terraform/environments/digital-prison-reporting/modules/glue_job/main.tf, terraform/environments/digital-prison-reporting/modules/lambda_trigger/main.tf, terraform/environments/digital-prison-reporting/modules/lambda_trigger/variables.tf, terraform/environments/digital-prison-reporting/modules/lambda_trigger/versions.tf, terraform/environments/digital-prison-reporting/modules/redshift/main.tf, terraform/environments/digital-prison-reporting/modules/step_function/main.tf, terraform/environments/digital-prison-reporting/policy.tf, terraform/environments/digital-prison-reporting/sg.tf
This PR tags untagged resources with the Jira number. Where the Jira number could not be determined the value DPR2-XXXX was used.
=> DPR2-1856: Tag untagged resources

terraform/environments/nomis/locals_development.tf, terraform/environments/nomis/locals_test.tf
=> TM-1238: build new 11g db in nomis test instead of dev

terraform/environments/ppud/cloudwatch_filters_groups_windows.tf
New log groups and cloudwatch metric filters for preproduction and development environments.
=> Update 060525 2

terraform/environments/electronic-monitoring-data/modules/landing_bucket/main.tf, terraform/environments/electronic-monitoring-data/s3.tf, terraform/environments/electronic-monitoring-data/secrets.tf
Adding secret and lambda function arn for dev/pp/test
=> EM Live Feeds: add implementation for lambda role arn

terraform/environments/ppud/cloudwatch_alarms_windows.tf
=> Update 070525 4

terraform/environments/nomis/locals_production.tf
Add new cert with includes additional zone for testing nomis reporting. Subsequent PR will swap over to it.
=> TM-1247: nomis: add additional cert

terraform/environments/digital-prison-reporting/policy.tf
Error in this workflow https://github.com/moj-analytical-services/create-a-derived-table/actions/runs/14881097905/job/41789204531
=> dmet-prisons: add getTables

terraform/environments/digital-prison-reporting/policy.tf
Ticket: https://github.com/moj-analytical-services/dmet-prisons/issues/318
=> dmet-prisons-318: add getdatabases

terraform/environments/nomis/locals_production.tf
Swap to the new cert - should be no impact but I'll do it at a quiet time just in case
=> TM-1247: nomis: swap prod certs

terraform/environments/ppud/cloudwatch_filters_groups_windows.tf
New Cloudwatch log group and metric filters.
=> Update 080525 2

terraform/environments/electronic-monitoring-data/share_cloud_platform.tf
Adding further config to allow crime matching api role to assume relevant modernisation platform role.
=> ACR-137 Crime Matching API Config

terraform/environments/analytical-platform-compute/src/helm/values/actions-runners/create-a-derived-table/values.yml.tftpl
- 🫣 typo on my part
applied locally
=> 🚑 Correct OneCrown IPs

terraform/environments/coat/athena.tf
Updated glue policy and iam role
=> updated glue policy and iam role

terraform/environments/nomis/locals_test.tf
=> nomis: Add 200GB to t1-nomis-db-1-b data disks

terraform/environments/digital-prison-reporting/notifications.tf
This PR configures an alert to be issued when a DMS task fails
=> DPR2-849: Alert on DMS task failure

terraform/environments/coat/athena.tf
- Updated Glue configuration
- Add Glue permissions to all members of the account
- Updated path to the data files in glue crawler configuration
- [#5336](https://github.com/ministryofjustice/operations-engineering/issues/5336
) 
---
=> Coat athena integration

terraform/environments/digital-prison-reporting/lake_formation.tf
.... now that the cross-account role is admin
I seperataly revoked these permissions on the AWS console
=> DMET-prisons: remove grant permissions

terraform/environments/digital-prison-reporting/lake_formation.tf
=> typo in `electronic`

terraform/environments/coat/athena.tf
- Updated permissions and role for glue 
- Restrict role only to glue service
- Add logging permission for glue service
-[ #5336](https://github.com/ministryofjustice/operations-engineering/issues/5336) 
---
=> updated permissions for glue service

terraform/environments/electronic-monitoring-data/share_analytical_platform_compute.tf
Adding staging databases as part of the mdss workflow.
=> Add allied mdss source to main

terraform/environments/analytical-platform-compute/environment-configuration.tf
Fixes https://github.com/moj-analytical-services/data-engineering-database-access/actions/runs/14972345161/job/42058194030
- Adds `counter_terrorism` tag
=> ⏪ Port DEDA tag

terraform/environments/coat/athena.tf
- Replaced inline policy for glue service with AWS managed one that have full permission set needed for the service to work 
- Updated athena.tf 
- [#5336](https://github.com/ministryofjustice/operations-engineering/issues/5336) 
---
=> removed inline policy and attached aws managed for glue service

terraform/environments/digital-prison-reporting/athena_federated_queries.tf, terraform/environments/digital-prison-reporting/data.tf, terraform/environments/digital-prison-reporting/lake_formation.tf, terraform/environments/digital-prison-reporting/locals.tf, terraform/environments/digital-prison-reporting/secrets.tf
- Sets up federated Athena queries for ndmis Oracle database
- We will initially only have account for Dev, Test and Pre-Prod
=> PDD-3: Federated queries for NDMIS in Dev, Test and Pre-Prod

terraform/environments/analytical-platform-compute/powerbi/ec2.tf
- We don't need to test and production during this PoC phase 
=> ⬇️ Scale down PowerBI Gateway instances in test and production

terraform/environments/cica-tariff/bastion_linux.json
Add user public keys for access to Tariff test env bastion
=> 🛂 Add public keys for Test bastion

terraform/environments/digital-prison-reporting/athena_federated_queries.tf
Previously it could not access the secret.
=> PDD-3: Fix ndmis secret access for athena federated queries.

terraform/environments/coat/s3.tf
- Hardcoded account number in policy identifiers replaced with the a terraform lookup for the root account id.
- Updated policies in https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/coat/s3.tf
- [#5357 ](https://github.com/ministryofjustice/operations-engineering/issues/5357)
=> account number replaced with account id from secret

scripts/generate-dependabot-file.sh
Increase :dependabot: PR limit as it is hitting the maximum allowed
=> :dependabot: Increase PR limit

scripts/generate-dependabot-file.sh
bumping limit again as still hitting max PR's:
=> :dependabot: Increase PR limit again

terraform/environments/sprinkler/test_module_reference.tf
Just adding some more test code that references a module in the "root" component to test out some updates I'm making to the strategy.
https://github.com/ministryofjustice/modernisation-platform/issues/9882
=> Test adding ref to module in root component

terraform/environments/sprinkler/testbed/modules/main.tf, terraform/environments/sprinkler/testbed/modules/outputs.tf, terraform/environments/sprinkler/testbed/modules/variables.tf
More test code being added to sprinkler to test updated strategy workflow to pinpoint module changes.
https://github.com/ministryofjustice/modernisation-platform/issues/9882
=> Adds a module to a component folder for testing strategy

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
Adding an airflow IAM role for GPS data
=> EM: GPS role added

terraform/environments/hmpps-domain-services/locals_production.tf
For GFSL data upload pipeline - add permissions to access secret
=> TM-1265: add secret policy to jump server

terraform/environments/ppud/s3.tf
New S3 bucket for storage of EC2 and Cloudwatch metrics.
=> Update 270525 3

terraform/environments/ppud/eventbridge.tf, terraform/environments/ppud/lambda_scripts/ppud_elb_uptime_calculate_prod.py, terraform/environments/ppud/lambda_scripts/ppud_elb_uptime_data_prod.py
New eventbridge rule and updates to lambda python scripts.
=> Update 290525 4

terraform/environments/ppud/eventbridge.tf, terraform/environments/ppud/lambda.tf, terraform/environments/ppud/lambda_scripts/ppud_elb_trt_calculate_prod.py, terraform/environments/ppud/lambda_scripts/ppud_elb_trt_data_prod.py, terraform/environments/ppud/versions.tf
New lambda function and eventbridge rules and update to python scripts.
=> Update 300525 3

terraform/environments/electronic-monitoring-data/dms_lcm_archive_local_full_task_tables_selection.json, terraform/environments/electronic-monitoring-data/dms_main.tf
Now that I've restored the backup file, this PR adds a configuration to create a DMS migration task for the LCM cloud data (2023)
- Updated dms main
- Added a task table selection json
=> ELM-3500 ingest LCM cloud - DMS task definition

terraform/environments/analytical-platform-compute/actions-runner/helm-charts-actions-runners.tf, terraform/environments/analytical-platform-compute/actions-runner/secrets.tf
- Updates Actions Runners to [2.325.0-1](https://github.com/ministryofjustice/analytical-platform-actions-runner/releases/tag/2.325.0-1)
Tested on moj-analytical-services/airflow
=> 📌 Update Actions Runners to 2.325.0-1

terraform/environments/coat/templates/coat-gh-actions-assume-role-policy.json, terraform/environments/coat/templates/coat-gh-actions-policy.json
- Updates Policy and Trusted Entities
- Updated trust policy only allows OIDC tokens from all branches
- Fixed name of bucked in s3 permissions
- [#5360 ](https://github.com/ministryofjustice/operations-engineering/issues/5360)
=> S3 upload reports

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
This PR patches the ingestion environments (dev and prod) as per the most recent releases of each image. 
This resolves [this](https://github.com/ministryofjustice/analytical-platform/issues/7842) issue.
=> 📌 Ingestion Patching - June

terraform/environments/coat/iam.tf, terraform/environments/coat/locals.tf, terraform/environments/coat/s3.tf, terraform/environments/coat/templates/coat-cross-account-assume-role-policy.json, terraform/environments/coat/templates/coat-cross-account-policy.json
https://github.com/ministryofjustice/operations-engineering/issues/5352 and https://github.com/ministryofjustice/operations-engineering/issues/5339 for allowing cross account to access buckets
=> s3 cross account role and policy added

terraform/environments/coat/s3.tf
- Updated KMS permissions as It was added in wrong bucket before 
- Moved permissions for CoatGithubActionsReportUpload from cur_s3_kms to coat_s3_kms
- [#5360 ](https://github.com/ministryofjustice/operations-engineering/issues/5360)
---
=> corrected kms permissions for gha role

terraform/environments/oasys-national-reporting/locals_preproduction.tf
=> deploy instance

terraform/environments/oasys/locals_preproduction.tf
- add secrets buckets for https://mojdt.slack.com/archives/C8NJZFNPN/p1749652427252339 request
- creates /oracle/database/BISYS42/passwords and */BIAUD42/passwords
=> add secrets buckets for oasys-preprod

terraform/environments/maat/maat-ecs.tf
Reverts ministryofjustice/modernisation-platform-environments#11058
=> Revert "Revert "LASB-4132|Update MAAT ECS to run on Latest task definition""

terraform/environments/digital-prison-reporting/policy.tf
Related to https://github.com/ministryofjustice/modernisation-platform-environments/pull/11048
This fixes an invalid permissions
=> dmet-prisons-384 - Remove invalid LF permission

terraform/environments/coat/iam.tf, terraform/environments/coat/locals.tf, terraform/environments/coat/s3.tf, terraform/environments/coat/templates/coat-cur-v2-hourly-dev-bucket-policy.json, terraform/environments/coat/templates/coat-cur-v2-hourly-prod-bucket-policy.json
https://github.com/ministryofjustice/operations-engineering/issues/5352 and https://github.com/ministryofjustice/operations-engineering/issues/5339 for allowing cross account to access buckets
=> S3 bucket policy and permissions

terraform/environments/nomis-combined-reporting/locals.tf, terraform/environments/nomis-combined-reporting/locals_development.tf, terraform/environments/nomis-combined-reporting/locals_ec2_autoscaling_groups.tf, terraform/environments/nomis-combined-reporting/locals_ec2_instances.tf, terraform/environments/nomis-combined-reporting/locals_security_groups.tf, terraform/environments/nomis-combined-reporting/main.tf
Nomis Reporting security group tidy up:
- remove bods and jumpserver as not currently in use
- utilise baseline provided SGs
- remove duplicate rules
=> TM-1320: ncr simplify sgs

terraform/environments/maatdb/modules/rds/rds.tf
Update the DB parameter for buffer overflow.
=> CC-3702-maat-db-error-in-mp

terraform/environments/nomis-data-hub/locals.tf, terraform/environments/nomis-data-hub/locals_ec2_instances.tf, terraform/environments/nomis-data-hub/locals_security_groups.tf, terraform/environments/nomis-data-hub/main.tf
Simplify SGs:
- enable + make use of baseline SGs
- remove unused code
=> TM-1320: ndh: simplify SGs

terraform/environments/analytical-platform-compute/eks-cluster.tf, terraform/environments/analytical-platform-compute/environment-configuration.tf
- Adds EKS Node Monitoring Agent
- Enables EKS Node Auto Repair for EKS Managed Node Groups
https://aws.amazon.com/about-aws/whats-new/2024/12/node-health-monitoring-auto-repair-amazon-eks/ 
=> 🔬 Add EKS Node Monitoring Agent

terraform/environments/analytical-platform-compute/dashboard-service/helm-charts-dashboard-service.tf
Release https://github.com/ministryofjustice/analytical-platform-dashboard-service/releases/tag/0.1.10
=> Deploy dashboard service v0.1.10

terraform/environments/analytical-platform-compute/dashboard-service/helm-charts-dashboard-service.tf
Deploy dashboard service 0.1.11
=> Deploy dashboard service 0.1.11

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/locals_security_groups.tf, terraform/environments/oasys-national-reporting/locals_test.tf
Add EFS SG
Add FSX rules to BODS SG
=> TM-1320: onr: security group fix

terraform/environments/corporate-staff-rostering/locals_ec2_instances.tf, terraform/environments/corporate-staff-rostering/locals_security_groups.tf
=> Rollback CSR SG change

terraform/environments/nomis/locals_preproduction.tf
For testing a production issue with TAGSAR
=> nomis: add additional preprod web server

terraform/environments/ppud/iam.tf, terraform/environments/ppud/lambda.tf
Updating IAM roles, policies & attachments for lambda, removed old roles & policies not in use.
=> Update 240625 7

terraform/environments/analytical-platform-compute/environment-configuration.tf
- Upgrades VPC CNI to [1.19.6](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.19.6)
=> 🌐 Upgrade VPC CNI

terraform/environments/electronic-monitoring-data/modules/lakeformation_database_share/main.tf
add a local so permissions are still granted to databases even if already exists
=> EM: Lakeformation module tweak

terraform/environments/corporate-staff-rostering/locals_ec2_instances.tf
No issues in the test so removing the security group from all other servers
=> TM-1376: csr: remove jumpserver SG

terraform/environments/corporate-staff-rostering/locals_security_groups.tf
Remove unused or duplicate rules from the CSR web security group
=> TM-1376: csr: update web security group

terraform/environments/planetfm/locals_production.tf
Test was successful, removing domain SG from the other EC2s.
=> TM-1376: planetfm: remove domain SG

terraform/environments/corporate-staff-rostering/locals_security_groups.tf
Remove unused and duplicate rules from the APP security group
=> TM-1376: csr: update app sg rules

terraform/environments/electronic-monitoring-data/dms_centurion_task_tables_selection.json, terraform/environments/electronic-monitoring-data/dms_main.tf
As the title suggests, this time lowercase
=> added centurion to the DMS terraform

terraform/environments/nomis/locals_development.tf
On request from syscon - for investigation into a prod SAR incident
=> nomis: add additional qa11g web server

terraform/environments/hmpps-oem/locals.tf, terraform/environments/hmpps-oem/locals_development.tf, terraform/environments/hmpps-oem/locals_preproduction.tf, terraform/environments/hmpps-oem/locals_production.tf, terraform/environments/hmpps-oem/locals_test.tf
Removed ref to nomis-combined-reporting-development. Decided to duplicate the code into each environment's locals file so this is more likely to be picked up by grep if we remove further environments.
=> TM-1355: hmpps-oem: remove ref to nomis-combined-reporting-development

terraform/environments/nomis/locals_development.tf
Remove this test instance as the tagsar issue has now been identified
=> TM-1399: nomis: remove qa11g-nomis-web-b

terraform/environments/digital-prison-reporting/policy.tf
Explicitly create service linked LF role.
=> Create service linked LF role explicitly for DPR

terraform/modules/environment/locals.tf, terraform/modules/environment/variables.tf, terraform/modules/environment/versions.tf
Fix a couple of linting errors Static Analysis spewed out in last PR
=> TM: nomis: environment module fix linting errors

terraform/environments/hmpps-domain-services/locals_test.tf
Testing a 'manual' scheduling option for the patch manager module.
=> TM-1203: testing-manual-patch-scheduling

terraform/environments/nomis-data-hub/locals_preproduction.tf, terraform/environments/nomis-data-hub/locals_production.tf, terraform/environments/nomis-data-hub/locals_security_groups.tf
Swap to new NDH SGs. Mainly to be consistent with our other apps and to remove unused private/public SGs in a subsequent PR.
=> TM-1376: ndh: swap to new SGs

terraform/environments/laa-ccms-soa/alerting.tf, terraform/environments/laa-ccms-soa/ecs_cluster.tf
Tweak alerting to CCMS-SOA:
- Disable alerts which have limited benefit
- Tighten infra alerts
- Make alert wording clearer
=> chore: laa-ccms-soa tweak alerting

terraform/environments/laa-ccms-soa/alerting.tf
Fix:
- Fixes RDS alerting dimensions
- Intervals on RDS alerting
- Remove RDS latency alerting
=> fix: raise reporting interval on rds alerts, remove latency tests

terraform/environments/digital-prison-reporting/athena_federated_queries.tf, terraform/environments/digital-prison-reporting/data.tf, terraform/environments/digital-prison-reporting/secrets.tf
Connections for ndelius, onr and oasys were set up in dev but aren't required
=> Remove ndelius, onr and oasys connections from dev

terraform/environments/analytical-platform-compute/mlflow/iam-policy.tf, terraform/environments/analytical-platform-compute/mlflow/iam-role.tf, terraform/environments/analytical-platform-compute/mlflow/kms-keys.tf, terraform/environments/analytical-platform-compute/mlflow/rds-databases.tf, terraform/environments/analytical-platform-compute/mlflow/s3-buckets.tf, terraform/environments/analytical-platform-compute/mlflow/versions.tf
This PR patches the mlflow component and is related to [this](https://github.com/orgs/ministryofjustice/projects/27/views/18?pane=issue&itemId=118387370&issue=ministryofjustice%7Canalytical-platform%7C8066) issue.
=> :wrench: Compute: MLFlow - Terraform module patching 

terraform/environments/analytical-platform-compute/network/versions.tf
This PR patches the network component and is related to [this](https://github.com/orgs/ministryofjustice/projects/27/views/18?pane=issue&itemId=118387370&issue=ministryofjustice%7Canalytical-platform%7C8066) issue.
=> :wrench: Compute - Network: Terraform Modules Patching

terraform/environments/ppud/iam.tf
=> Update 140725 4

terraform/environments/analytical-platform-compute/dashboard-service/helm-charts-dashboard-service.tf
Deploy release 0.2.0 of the dashboard service to the development environment only
=> Update dashboard service to 0.2.0 only in dev

terraform/environments/analytical-platform-compute/airflow/alb.tf, terraform/environments/analytical-platform-compute/airflow/data.tf, terraform/environments/analytical-platform-compute/airflow/iam-policies.tf, terraform/environments/analytical-platform-compute/airflow/iam-roles.tf, terraform/environments/analytical-platform-compute/airflow/iam-users.tf, terraform/environments/analytical-platform-compute/airflow/kms-keys.tf, terraform/environments/analytical-platform-compute/airflow/mwaa.tf, terraform/environments/analytical-platform-compute/airflow/s3-buckets.tf, terraform/environments/analytical-platform-compute/airflow/s3-objects.tf, terraform/environments/analytical-platform-compute/airflow/versions.tf
This PR contributes to https://github.com/ministryofjustice/analytical-platform/issues/8066
This PR updates the airflow component.
=> 🔧 Airflow: Update Terraform Modules

terraform/environments/coat/s3.tf, terraform/environments/coat/templates/moj-cur-v2-hourly-without-kms-bucket-policy.json
**AWS root account - Bucket replication with multiple buckets
[#185](https://github.com/ministryofjustice/cloud-optimisation-and-accountability/issues/185)**
=> cur-v2-bucket added without KMS

terraform/environments/analytical-platform-compute/environment-configuration.tf
- There are missing from test 
=> ☁️ Add SDP endpoints for APC test

terraform/environments/electronic-monitoring-data/locals.tf, terraform/environments/electronic-monitoring-data/transfer_server_accounts.tf
for capita transfer, add a new ip address server so they can send data from new account
=> EM: new sftp server for capita

terraform/environments/ppud/ses.tf
=> Update 220725 3

terraform/environments/ppud/iam.tf, terraform/environments/ppud/sns.tf
Moved IAM permission from SNS to Lambda.
=> Update 230725 4

terraform/environments/digital-prison-reporting/modules/glue_job/main.tf, terraform/environments/digital-prison-reporting/modules/lambdas/generic/iam.tf, terraform/environments/digital-prison-reporting/policy.tf
This PR sorts the IAM policies in reverse alphabetical order.
=> DHS-336: Sort policies in descending order

terraform/environments/ccms-ebs/application_variables.json
=> CC-3795: EBS DB /u01 300GB -> 500GB

terraform/environments/oasys-national-reporting/locals_preproduction.tf, terraform/environments/oasys-national-reporting/locals_production.tf, terraform/environments/oasys-national-reporting/locals_test.tf
=> TM-1446: ad-dc-clean-up

terraform/environments/laa-enterprise-service-bus/cclf_iam.tf, terraform/environments/laa-enterprise-service-bus/cclf_lambda.tf, terraform/environments/laa-enterprise-service-bus/ccms_iam.tf, terraform/environments/laa-enterprise-service-bus/ccms_lambda.tf, terraform/environments/laa-enterprise-service-bus/ccr_iam.tf, terraform/environments/laa-enterprise-service-bus/ccr_lambda.tf, terraform/environments/laa-enterprise-service-bus/cwa_iam.tf, terraform/environments/laa-enterprise-service-bus/cwa_lambda.tf, terraform/environments/laa-enterprise-service-bus/eventbridge.tf, terraform/environments/laa-enterprise-service-bus/locals.tf, terraform/environments/laa-enterprise-service-bus/maat_iam.tf, terraform/environments/laa-enterprise-service-bus/maat_lambda.tf, terraform/environments/laa-enterprise-service-bus/s3.tf, terraform/environments/laa-enterprise-service-bus/sns.tf, terraform/environments/laa-enterprise-service-bus/sqs.tf
[HUB-32-bucket] lambda-layer bucker deployment
=> [HUB-32-bucket] lambda-layer bucker deployment

.github/workflows/format-code.yml
=> add id-token permission

terraform/environments/coat/iam.tf
update S3 bucket permission to all S3 actions to support tfstate to write access
=> tfstate_role_update

terraform/environments/ccms-ebs/ccms-secrets.tf
CC-3797: Added a secret for credentials for authentication to EUCS Entra.
=> CC-3797: Added a secret for credentials for authentication to EUCS Entra.

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
Add a role for the full refresh dag in test
=> EM: Add role for full refresh for snow data

terraform/environments/planetfm/locals_production.tf, terraform/modules/baseline_presets/ssm-documents/Command/ec2-install-automation-tools-windows.yaml
Delete app 11.  Will rebuild from new 2022 image.
Also remove GitFallback step as this was failing and no real need to have it in the ssm doc as opposed to the ec2 user data.
=> TM-1491: planetfm: prod rebuild app 11 part1

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/8298
- Adds new SFTP user `maat-xhibit`
=> 🚚 LAA XHIBIT SFTP

terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/variables.tf, terraform/environments/electronic-monitoring-data/share_analytical_platform_compute.tf
add the staging db to lake formation for access management
=> EM: add snow staging db to lakeformation

terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/main.tf, terraform/environments/electronic-monitoring-data/modules/ap_airflow_load_data_iam_role/variables.tf, terraform/environments/electronic-monitoring-data/share_analytical_platform_compute.tf
Reverts ministryofjustice/modernisation-platform-environments#12474
=> Revert "EM: add snow staging db to lakeformation"

terraform/environments/maatdb/application_variables.json, terraform/environments/maatdb/ftp_lambda.tf, terraform/environments/maatdb/python_libs/zip_s3_objects.py
Updates the zip lambda with new runtime variables and new script version to better handle how files are added to the zip package. This follows the experience with batch transfers of large numbers of files.
=> maatdb - central print zip lambda updates.

terraform/environments/delius-core/main_development.tf, terraform/environments/delius-core/main_preproduction.tf, terraform/environments/delius-core/main_production.tf, terraform/environments/delius-core/main_test.tf, terraform/environments/delius-core/modules/components/ecs_retirement/cloudwatch.tf, terraform/environments/delius-core/modules/components/ecs_retirement/data.tf, terraform/environments/delius-core/modules/components/ecs_retirement/iam.tf, terraform/environments/delius-core/modules/components/ecs_retirement/lambda.tf, terraform/environments/delius-core/modules/components/ecs_retirement/python/task_retirement.py, terraform/environments/delius-core/modules/components/ecs_retirement/variables.tf, terraform/environments/delius-core/modules/delius_environment/lambda.tf, terraform/environments/delius-core/modules/delius_environment/variables.tf
Lambda function to notify probation-migrations-team when an ECS task is being retired
=> Tm 1281 ecs retirement lambda

terraform/environments/maatdb/python_libs/zip_s3_objects.py
This update ensures that the Lambda function sends a CloudWatch metric with value 0 when no files are found for archiving. It prevents creating or uploading empty ZIP files while still providing visibility in CloudWatch for monitoring and alerts.
=> Send CloudWatch metric when no files are archived

terraform/environments/analytical-platform-ingestion/environment-configuration.tf, terraform/environments/analytical-platform-ingestion/kms-keys.tf, terraform/environments/analytical-platform-ingestion/s3.tf
Part of https://github.com/ministryofjustice/analytical-platform/issues/8340
- Adds resources from egress replication
=> 🚚 SSCT Egress

terraform/environments/ccms-ebs/ccms-ftp-lambda.tf
this pr adds cron switch to allpay inbound lambda
=> add cron switch to allay inbound lambda

terraform/environments/oasys/locals_preproduction.tf
Testing access log integration with xsiam in preprod.
=> TM-1526: oasys: enable xsiam S3 access log integration in preprod

terraform/environments/digital-prison-reporting/application_variables.json, terraform/environments/digital-prison-reporting/policy.tf
Lakeformation setup permissions
=> DPR Lakeformation Share Permissions

terraform/environments/electronic-monitoring-data/ap_airflow_iam.tf
add arg to add load fms to. new airflow
=> EM: Migrate load fms to new airflow

terraform/environments/planetfm/locals_production.tf
Doubling this disk on Glenn's request. Ran out of space last weekend
=> TM-1540: increase planetfm S drive

terraform/environments/coat/templates/coat-cur-v2-hourly-prod-bucket-policy.json
Reverts ministryofjustice/modernisation-platform-environments#12816
=> Revert "fixed policy"

terraform/environments/coat/iam.tf, terraform/environments/coat/locals.tf, terraform/environments/coat/templates/coat-cross-account-policy.json
- Added bucket permissions to cross account policy 
- Fixed kms keys permissions
- Added read permissions from master account cur bucket
- NA
---
=> Coat data sync permissions

terraform/environments/coat/templates/coat-cur-v2-hourly-prod-bucket-policy.json
- Added Permissions to the destination bucket to allow sync command 
- 
- [#5489 ](https://github.com/ministryofjustice/operations-engineering/issues/5489)
=> added permissions to destination bucket

terraform/environments/cica-tariff/bastion_linux.json
Add public keys for production bastion access.
=> 🔐 Add public keys for bastion

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
[Add SFTP for CAFM PlanetFM Inbound data transfer #8672](https://github.com/ministryofjustice/analytical-platform/issues/8672)
=> Add glenn-barber-cafm - CIDR block tbc

terraform/environments/data-platform/dns/platform_providers.tf, terraform/environments/data-platform/dns/route53-records.tf, terraform/environments/data-platform/dns/route53-zones.tf
Part of https://github.com/ministryofjustice/data-platform/issues/16
- Creates zones in each account and delegates via production
=> 🌐 Data Platform DNS

terraform/environments/youth-justice-networking/ec2.tf
Reverts ministryofjustice/modernisation-platform-environments#12957
=> Revert "Minor syslog update"

terraform/environments/youth-justice-networking/ec2.tf
Reverts ministryofjustice/modernisation-platform-environments#12973
=> Revert "Revert "Minor syslog update""

.github/workflows/data-platform.yml, terraform/environments/data-platform/aws-s3-access-logging.tf, terraform/environments/data-platform/dns/environment-configuration.tf, terraform/environments/data-platform/dns/route53-records.tf, terraform/environments/data-platform/dns/route53-zones.tf, terraform/environments/data-platform/iac/iam-roles.tf, terraform/environments/data-platform/iac/kms-keys.tf, terraform/environments/data-platform/iac/platform_providers.tf, terraform/environments/data-platform/iac/s3-buckets.tf
Resolves https://github.com/ministryofjustice/data-platform/issues/17
- Adds Terraform state store
- Adds GitHub Actions OIDC role
- Refactors DNS component
=> 🌕 Data Platform IaC

terraform/environments/ppud/data.tf
Added most_recent = true flag to newly renewed certificates.
=> ACM_250925_2

terraform/environments/xhibit-portal/xp-secrets.tf
Create AWS Secrets Manager entry for prtg-sso sensitive data for the integration and configuration.
=> feat(xhibit-portal): PRTG-SSO secrets #476

terraform/environments/analytical-platform-ingestion/environment-configuration.tf
This PR relates to an ongoing incident in ingestion. It updates to the scan lambda which has in turn been updated to use a more up to date version of clamav.
=> :wrench: Update Scan lambda image

terraform/environments/equip/main.tf
Update security groups to allow traffic between TST02 and CTX04
=> Allow access for TST02 > CTX04

terraform/environments/ppud/cloudwatch_alarms_windows.tf, terraform/environments/ppud/cloudwatch_filters_groups_windows.tf
Update to CloudWatch Metric Filters
=> Update 031025 2

terraform/environments/xhibit-portal/lambda.tf, terraform/environments/xhibit-portal/lambda/delete_old_ami.py
Add detailed logging and dry-run mode while upgraded from python3.8 to python3.12
=> xhibit-portal: upgrade lambda for amis delete

terraform/environments/ppud/cloudwatch_alarms_windows.tf, terraform/environments/ppud/cloudwatch_filters_groups_windows.tf
Update to CloudWatch Metric Filters and Alarms
=> Update 031025 7

terraform/environments/maatdb/application_variables.json, terraform/environments/maatdb/modules/rds/rds.tf, terraform/environments/maatdb/modules/rds/variables.tf
chore: restore snapshot in pre prod
=> chore: restore snapshot in pre prod

terraform/environments/digital-prison-reporting/policy.tf
Due to error [here](https://github.com/moj-analytical-services/data-engineering-datalake-access/actions/runs/17799457990/job/50595030623)
=> dmet-prisons/dl/ add lakeformation:UpdateLFTagExpression

terraform/environments/maatdb/application_variables.json
chore: deletion protection set to false
=> chore: deletion protection set to false

terraform/environments/maatdb/application_variables.json
chore: deletion protection set to true
=> chore: deletion protection set to true

terraform/environments/xhibit-portal/bastion_linux.tf
=> xhibit-portal: upgrade bastion-linux to V4.5.0 

terraform/environments/cica-tariff/locals.tf, terraform/environments/cica-tariff/tariff_ec2_iam.tf
Tariff ec2 iam update to allow access to CICA Storage Gateway S3.
=> CDI-266 Tariff IAM update

terraform/environments/electronic-monitoring-data/s3.tf
to enable sharing an access key and secret in a secure way for ticket [ELM 3901](https://dsdmoj.atlassian.net/browse/ELM-3901) adding a generic export bucket
=> EM: Add export bucket

terraform/environments/delius-mis/locals_development.tf, terraform/environments/delius-mis/modules/mis_environment/datasync.tf, terraform/environments/delius-mis/modules/mis_environment/dfi.tf, terraform/environments/delius-mis/modules/mis_environment/dis.tf, terraform/environments/delius-mis/modules/mis_environment/templates/AutoEC2LaunchV2.yaml.tftpl, terraform/environments/delius-mis/modules/mis_environment/variables.tf
* deploy dev dis instance
* enable alarms for dis instance
* revert user-data branch to main following deployment against test branch
=> add instance and user data branch
